okta/okta-developer-docs

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
1. Added documentation for group search (Early Access feature)
2. Added documentation for the new group attributes `source` and `source` link (Early Access feature. The two new group attributes are only present in groups with type `APP_GROUP`)
- **Is this PR related to a Monolith release?** Yes, 2020.10.0
* [OKTA-325066](https://oktainc.atlassian.net/browse/OKTA-325066)
@joshreesjones-okta @daytonwilliams-okta @okta/ud-core
> Add documentation for group search and app group API enhancement

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/springboot/login-redirect.md
- Fix a incorrect sign-in url in the code block.
> fix: fix the incorrect sign-in link in the code block

- packages/@okta/vuepress-site/data/error-codes.json
- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- **What's changed?** Updating error code, event type, and oauth2 error code pages.
- **Is this PR related to a Monolith release?** 2020.10.0.
> Updating event catalog

- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/overview/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/test-scim-app/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/create-guide/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/overview/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/scim/submit.md
Adds instructions on how activate the profile sourcing feature (formerly called profile mastering) for SCIM app integrations.
Yes. 2020.10.0
* [OKTA-334475](https://oktainc.atlassian.net/browse/OKTA-334475)
> Add profile sourcing to the SCIM and Submission guides

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/enable-the-custom-domain/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/update-other-okta-settings/index.md
- packages/@okta/vuepress-site/docs/guides/email-customization/before-you-begin/index.md
- packages/@okta/vuepress-site/docs/guides/email-customization/configure-custom-email-domain/index.md
- **What's changed?** Updates per Randal Degges group review
* [OKTA-333272](https://oktainc.atlassian.net/browse/OKTA-333272)
> feedback updates

- packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- **What's changed?** adding sentence about use of Implicit
* [OKTA-332810](https://oktainc.atlassian.net/browse/OKTA-332810)
> adding sentence about use of Implicit

- packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md
- **What's changed?** Minor change per Dev Feedback
* [OKTA-332807](https://oktainc.atlassian.net/browse/OKTA-332807)
> switch around App paragraph

- packages/@okta/vuepress-site/code/angular/okta_angular_auth_js/index.md
updates https://developer.okta.com/code/angular/okta_angular_auth_js/ to have the correct code for the latest version of the okta-auth-js library.
> fixed okta-auth-js for angular section

- packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
The API method was incorrect, the example below my change is correctly using POST
No
* No associated ticket
@asong-okta @susanharper-okta
> Fix request method for clientSecret rotation

- .gitignore
- scripts/travis.sh
Deploys the site to netlify, if the branch is in origin and the NFDEPLOY text is present in the commit message
Depends on the following env vars which have been added to travis via the UI:
NETLIFY_AUTH_TOKEN
NETLIFY_SITE_ID
> Add conditional netlify build

- packages/@okta/vuepress-site/code/javascript/index.md
> chore: remove server side samples link from client side JavaScript page

- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** the IDs were not rendering correctly. Added breaks so that the IDs would appear
* [OKTA-336493](https://oktainc.atlassian.net/browse/OKTA-336493)
> fixing missing ids in URL examples

- packages/@okta/vuepress-site/docs/release-notes/2020-10-1/index.md
- **What's changed?** release notes entry for 2020.10.1
- **Is this PR related to a Monolith release?** Yes 2020.10.1
> 2020-10-1 release notes:

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/oktatookta/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-serviceapp-grantscopes/index.md
- **What's changed?** fixing broken URLs because of curly braces
> fixing broken URLs because of curly braces

- packages/@okta/vuepress-site/code/javascript/index.md
- packages/@okta/vuepress-site/docs/release-notes/2020-10-1/index.md
- **What's changed?** Release Notes 2020.10.1
- **Is this PR related to a Monolith release?** Release Notes 2020.10.1
> Release 2020.10.1

- packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
- packages/@okta/vuepress-site/code/vue/index.md
* Remove links on out of date blog post about vue.js and .net
No
* [OKTA-331911](https://oktainc.atlassian.net/browse/OKTA-331911)
> OKTA-331911: Remove out of date link on blog post

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- packages/@okta/vuepress-site/docs/reference/api/oie-policy-types/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/release-notes/2016-28/index.md
> Hw fix minor format issue

- packages/@okta/vuepress-site/docs/release-notes/2020-10-2/index.md
- **What's changed?** Adding Release Notes for 2020.10.2 release. Note has received tech, RN, Security, and Editing reviews/approvals. Awaiting preview release.
> Adding Release Note entry for this week: 2020.10.2

- packages/@okta/vuepress-site/docs/concepts/okta-data-model/index.md
- **What's changed?** changing formatting for some words in this concept piece per Jakub
> changing formatting for some words in this concept piece per Jakub

- packages/@okta/vuepress-site/code/android/index.md
- packages/@okta/vuepress-site/code/react-native/index.md
- **What's changed?** Document minSdk version for Android OIDC SDK.
* [OKTA-269879](https://oktainc.atlassian.net/browse/OKTA-269879)
> Document minSdk version for Android OIDC SDK.

- packages/@okta/vuepress-site/code/python/index.md
- **What's changed?** Add link to https://github.com/okta/okta-sdk-python to page https://developer.okta.com/code/python/
* [OKTA-338515](https://oktainc.atlassian.net/browse/OKTA-338515)
> Add link to okta-sdk-python GitHub. OKTA-338515

- packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/nodeexpress/reqautheverything.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/nodeexpress/reqauthspecific.md
* update node js snippet with expectedAudience parameter
No
* [OKTA-331543](https://oktainc.atlassian.net/browse/OKTA-331543)
> OKTA-331543: Update code snippet

- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/setup-app/index.md
- **What's changed?** PKCE flow is for Native apps and SPAs, guide should offer both application types
> PKCE flow is for Native apps and SPAs

- packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
- packages/@okta/vuepress-site/docs/concepts/policies/index.md
- packages/@okta/vuepress-site/docs/guides/configure-access-policy/limit-scopes-clients-can-access/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-rules-for-policy/index.md
- packages/@okta/vuepress-site/docs/guides/request-user-consent/troubleshooting/index.md
- packages/@okta/vuepress-site/docs/guides/session-cookie/overview/index.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/define-signout-callback/aspnetcore/addbaseuri.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/define-signout-callback/aspnetcore3/addbaseuri.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/define-signout-callback/index.md
- packages/@okta/vuepress-site/docs/reference/api-overview/index.md
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- **What's changed?** Replaced instances of the terms 'whitelist'.
* [OKTA-335876](https://oktainc.atlassian.net/browse/OKTA-335876)
* [OKTA-342457](https://oktainc.atlassian.net/browse/OKTA-342457)
> Avoid the term whitelist

- packages/@okta/vuepress-site/.vuepress/scripts/findLatestWidgetVersion.js
- tests/unit/findLatestWidgetVersion.test.js
* update version parsing function
Not sure
* None
> Check whether there are multiple published SIW versions

- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
Fix react signIn widget guide to skip flaw pending state
Fixes #1599
NO
* [OKTA-342766](https://oktainc.atlassian.net/browse/OKTA-342766)
> doc: fix react siw guide - OKTA-342766

- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/openidconnect/submit.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/saml2/submit.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/scim/submit.md
Updates descriptions for all three protocols (SAML, SCIM, OIDC) with instructions on how to configure variables and use them in ISV scenarios that use multi-tenants environments.
Yes. 2020.11.0
* [OKTA-328618.](https://oktainc.atlassian.net/browse/OKTA-328618.)
> Adds in App Instance Property support

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** IdP SAML Update
- **Is this PR related to a Monolith release?** Yes **2020.11.0**
* [OKTA-332191](https://oktainc.atlassian.net/browse/OKTA-332191)
> IdP SAML Update

- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/setup-app/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- packages/@okta/vuepress-site/docs/reference/api/users/index.md
Resolves: OKTA-342844
- **What's changed?** Add new API doc for new API.
- **Is this PR related to a Monolith release?** November 2020 major release
* [OKTA-342844](https://oktainc.atlassian.net/browse/OKTA-342844)
> DWW Add new API doc for new MyAccount API.

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/apps.json
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- **What's changed?** Added bookmark app to postman collection (it already had docs)
Add Org2Org app to docs and postman collection
* OKTA-324188
> add bookmark and Org2Org apps to postman collection

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- **What's changed?** Fix typo in inline hooks number limit
* [OKTA-343899](https://oktainc.atlassian.net/browse/OKTA-343899)
> Fix typo in inline hooks number limit

- packages/@okta/vuepress-theme-prose/components/ContentPage.vue
- tests/selenium/spec/page-content-spec.js
* apply custom scroll-to code to non-hyperlink navigation (back button)
* consolidate scrolling code in a single function
No
* [OKTA-343946](https://oktainc.atlassian.net/browse/OKTA-343946)
> OKTA-343946: back button / history is broken on developer.okta.com

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/get-access-token/index.md
- **What's changed?** fixing scope example
* [OKTA-339800](https://oktainc.atlassian.net/browse/OKTA-339800)
> fixing scope example

- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/exchange-code-token/index.md
- packages/@okta/vuepress-site/docs/guides/implement-auth-code/exchange-code-token/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/overview/index.md
- packages/@okta/vuepress-site/docs/guides/implement-password/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta/prerequisites/index.md
- packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/clone-the-certificate/index.md
- **What's changed?** Updated note after talking to Noi
* [OKTA-339103](https://oktainc.atlassian.net/browse/OKTA-339103)
> updated note per Noi

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Updating conductor.yml file on staging server
> Updating re-directs

- packages/@okta/vuepress-site/docs/release-notes/2020-11-1/index.md
- **What's changed?** There's an RN entry!
- **Is this PR related to a Monolith release?** 2020.11.1
* N/A
> RN entry for 2020.11.1

- packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-access-policies/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-authz-server/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-claims/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-rules-for-policy/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-scopes/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/overview/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md
- **What's changed?** Changes made based on QA Guide fix comments
* [OKTA-305683](https://oktainc.atlassian.net/browse/OKTA-305683)
> updating Create Auth Server

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-sign-jwt/index.md
- **What's changed?** Fixing link
> fixing link to tool

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/enable-the-custom-domain/index.md
- **What's changed?** adding note about A records and CNAME records
* [OKTA-306193](https://oktainc.atlassian.net/browse/OKTA-306193)
> adding note about A records and CNAME records

- packages/@okta/vuepress-site/docs/reference/api-overview/index.md
- **What's changed?** Changes were made to reflect devdoc style guidelines.
* [OKTA-344794](https://oktainc.atlassian.net/browse/OKTA-344794)
> Updated API overview page for style

- packages/@okta/vuepress-site/docs/reference/api/zones/index.md
- **What's changed?** style update
> style update

- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** DynamicScale Inline Hook Rate Limit content update
* [OKTA-297745](https://oktainc.atlassian.net/browse/OKTA-297745)
> DynamicScale Inline Hook Rate Limit content update

- packages/@okta/vuepress-site/docs/reference/api/templates/index.md
- **What's changed?** Template style update
> Template style update

- packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
- **What's changed?** Linked Object API style update
> linked object style update

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/configure-the-sdk/index.md
- **What's changed?** Remove unnecessary `)` from "Configure the SDK" doc
> Remove unnecessary `)` from Configure the SDK doc

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/clients/index.md
- Add the initial ASA docs, namely the Client Documentation
> Add ASA Client Documentation

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/audits/index.md
- Add the initial ASA docs, namely the Audits Documentation.
> Add ASA Audits Documentation

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/advanced-server-access.json
- packages/@okta/vuepress-site/docs/reference/api/asa/introduction/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/service-users/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- Add the initial ASA docs, namely the introduction and service users.
> Initial ASA articles, introduction + service users

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- Add the initial ASA docs, namely the introduction and service users.
> Add ASA Projects

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/groups/index.md
- Add ASA Groups Documentation
> Add ASA Groups Documentation

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/users/index.md
> Add ASA Users documentation

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/teams/index.md
* Add ASA Teams doc
This is breaking #1078 up into more manageable pieces.
> Add ASA Teams page

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/configure-the-sdk/react/config.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/handle-callback/react/handle-callback.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/react/reqautheverything.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/react/reqauthspecific.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/use-the-access-token/angular/getaccesstoken.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/angular/remotesignout.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/react/remotesignout.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-your-app/angular/localsignout.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-your-app/react/localsignout.md
- **What's changed?** Updates guide for okta-react@4.0.0 okta-angular@3.0.0 and okta-signin-widget@5.0.2 
* [OKTA-335904](https://oktainc.atlassian.net/browse/OKTA-335904)
> Update guides for angular, react, and signin widget

- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/index.md
- **What's changed?** Changed wording
> changed wording

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-authz-url/index.md
- **What's changed?** fixing weirdness with the emdash
> fixing emdashes

- packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
- **What's changed?** 'sc' value which is set when the user logs in with Smart Card to the amr object.
* [OKTA-330695](https://oktainc.atlassian.net/browse/OKTA-330695)
> The amr object is missing the 'sc' value which is set when the user logs in with Smart Card

- package.json
- packages/@okta/vuepress-theme-prose/index.js
* Adds redesign feature flag guarded by env variable at build time
* Adds build option for running w/ flag on
* [OKTA-350156](https://oktainc.atlassian.net/browse/OKTA-350156)
> Add feature flag for redesign

- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/index.md
- Fix a typo in the "Overview" section
* N/A
> Fix a typo at the top of the page

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/linkedin/appatidp.md
- Edited Step 1 for length
- Edited Step 2 with a new link (the [Instructions](https://www.linkedin.com/developers/apps) link just takes you to your apps)
- Edited Step 3 for clarity
- Edited Step 4 for clarity
- Moved Step 5 to a bulleted list for clarity
- Edited last note with a new link (see above note about Instructions link)
* N/A
> Edit LinkedIn instructions for clarity

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- Add the FIDO provider to the list of supported Factor providers
- **Is this PR related to a Monolith release?** No, it is already available and this updates the documentation
* [OKTA-349710](https://oktainc.atlassian.net/browse/OKTA-349710)
> Update Factors API with FIDO provider and FIDO WebAuthn combination

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/linkedin/appatidp.md
- Fixed incorrect use of bullets in step 4
- Adjusted link text in step 2
* N/A
> Edit Step 4 Bullets and Step 2 Link

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
- Fixes showSignInAndGetTokens typo in the SIW code page
- No
* [OKTA-351491](https://oktainc.atlassian.net/browse/OKTA-351491)
> Fixes showSignInAndGetTokens typo in the SIW code page

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/configure-the-sdk/index.md
Adds note for auth server in https://developer.okta.com/docs/guides/sign-into-spa/react/configure-the-sdk/
No
* [OKTA-340132](https://oktainc.atlassian.net/browse/OKTA-340132)
> doc: add auth server note in spa config guide - OKTA-340132

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
> adding note per conversation in Fed today

- packages/@okta/vuepress-site/docs/release-notes/2020-12-0/index.md
- **What's changed?** Additions of Monthly release notes 
- **Is this PR related to a Monolith release?** 2020.12.0
> Rn entry 2020.12.0

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Document SLO and idp_initiated_login /api/v1/apps enhancements.
2020.12 Major Release
* [OKTA-350217](https://oktainc.atlassian.net/browse/OKTA-350217)
@larsjohansen-okta @susanharper-okta
> Document SLO and idp_initiated_login /api/v1/apps enhancements.

- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** New endpoint for DynamicScale
- **Is this PR related to a Monolith release?** Yes 2020.12.0
* [OKTA-350195](https://oktainc.atlassian.net/browse/OKTA-350195)
> new endpoint for DynamicScale

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md
- **What's changed?**: Add OAuth scope documentation for Administrator Roles API
- **Is this PR related to a Monolith release?** 2020.12.0
* [OKTA-348276](https://oktainc.atlassian.net/browse/OKTA-348276)
@alifatolahi-okta @yuanxue-okta @susanharper-okta
> Add OAuth scope for Administrator Roles API

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Added refresh token rotation configuration section to Apps API reference
- **Is this PR related to a Monolith release?** Yes 2020.12.0
* [OKTA-338767](https://oktainc.atlassian.net/browse/OKTA-338767)
* @susanharper-okta @venkatviswanathan-okta
> Added refresh token rotation configuration section to Apps API reference

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/next-steps/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/overview/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/refresh-token-rotation/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/use-refresh-token/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/before-you-begin/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/use-the-access-token/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/before-you-begin/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/create-okta-application/index.md
- **What's changed?** New content in various places for refresh token rotation
- **Is this PR related to a Monolith release?** 2020.12.0
* [OKTA-342936](https://oktainc.atlassian.net/browse/OKTA-342936)
> Refresh Token Rotation

- packages/@okta/vuepress-site/.vuepress/nav/guides.js
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/activate-and-enable/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/check-credentials-against-data-store/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/check-credentials-against-data-store/nodejs/check-against-user-store.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/get-submitted-credentials/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/get-submitted-credentials/nodejs/request.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/import-users/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/import-users/nodejs/password-import-api.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/overview/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/send-response/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/send-response/nodejs/send-response.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/test-password-import-hook/index.md
- **What's changed?** Merging this branch, which contains a revised version of the Password Inline Hook Guide into one overall branch that will clearly display updates to the overall Hook Guide section.
> Bd password inline hook revision

- packages/@okta/vuepress-site/pricing/index.md
- packages/@okta/vuepress-theme-prose/components/Pricing.vue
* Updates /pricing page links to be accurate
* Fixes Vue linting issues where `key` was missing inside of `v-for` iteration
> Update pricing page links

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/use-the-access-token/index.md
Use the access token [guide](https://developer.okta.com/docs/guides/sign-into-spa/angular/use-the-access-token/) is updated with token renewal hints.
No
* [OKTA-262734](https://oktainc.atlassian.net/browse/OKTA-262734)
> OKTA-262734: use access token guide: add a note on token renewal

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Update redirections what would be used after migration 
* [OKTA-346418](https://oktainc.atlassian.net/browse/OKTA-346418)
> Add redirection for deprecated links

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/openidconnect/appatidp.md
- **What's changed?** Removed Paypal reference for OpenID Connect
* [OKTA-348974](https://oktainc.atlassian.net/browse/OKTA-348974)
> removed Paypal reference

- packages/@okta/vuepress-site/docs/guides/implement-client-creds/use-flow/index.md
- **What's changed?** added base64 encode content
* [OKTA-350877](https://oktainc.atlassian.net/browse/OKTA-350877)
> base64 encode content

- packages/@okta/vuepress-site/docs/release-notes/2020-12-1/index.md
- **What's changed?** Release 2020.12.1
- **Is this PR related to a Monolith release?** Release 2020.12.1
> Release 2020.12.1

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
> Fixing endpoint path

- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
Migrate to OIE
- interaction code grant
- SIW
- direct auth using auth-js/idx-js
* [OKTA-343530](https://oktainc.atlassian.net/browse/OKTA-343530)
> guide: migrate to OIE

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-remediation/before-you-begin/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-remediation/handle-remediation/index.md
> Fixing bugs, adding title which is missing because of lack of nav

- packages/@okta/vuepress-site/docs/release-notes/2020-12-2/index.md
- **What's changed?** 2020.12.2 Release Notes
- **Is this PR related to a Monolith release?** Yes 2020.12.2
> 2020.12.2 Release Notes

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
- **What's changed?** Added EA flag for Refresh Token Rotation for Refresh Token step in SPA guide
-
> adding EA flag to SPA doc for refresh token step

- packages/@okta/vuepress-site/docs/release-notes/2020-12-0/index.md
Revising RN entry per eng team request.
- **What's changed?** RN entry is now accurate
- **Is this PR related to a Monolith release?** Sort of
> Update 2020.12.0 RN

- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/admin-notifications/index.md
- packages/@okta/vuepress-site/docs/release-notes/2020-12-2/index.md
- **What's changed?** Release Notes 2020.12.2
- **Is this PR related to a Monolith release?** Yes 2020.12.2
> Release 2020.12.2

- packages/@okta/vuepress-site/pricing/index.md
- packages/@okta/vuepress-theme-prose/index.js
* Adds Okta ThreatInsight information to the pricing matrix
* [OKTA-354784](https://oktainc.atlassian.net/browse/OKTA-354784)
https://5fe3a9eac5d585008d073902--reverent-murdock-829d24.netlify.app/pricing/
> Adds Okta ThreatInsight to pricing matrix

- packages/@okta/vuepress-site/code/react/okta_react/index.md
Update [`okta-react` guide](https://developer.okta.com/code/react/okta_react/) for `@okta/okta-auth-js` v4.5.2 and `@okta/okta-react` v4.1.0.
- No
* [OKTA-352475](https://oktainc.atlassian.net/browse/OKTA-352475)
> Update guide 'Okta Auth JS and React' to latest lib versions

- packages/@okta/vuepress-theme-prose/assets/css/layouts/_authorizationLayout.scss
- packages/@okta/vuepress-theme-prose/index.js
- packages/@okta/vuepress-theme-prose/layouts/AuthorizationLayout.vue
* Updates AuthorizationLayout (used in /login and /signup) to update logo, logo link, and background color
* Updates input styles to show right cursor for each field
* [OKTA-355578](https://oktainc.atlassian.net/browse/OKTA-355578)
> Signup page enhancements

- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
- **What's changed?** Update guide [Okta Auth JS and React](https://developer.okta.com/code/react/okta_react_sign-in_widget/) to latest lib versions: 
```
"@okta/okta-auth-js": "^4.5.0",
"@okta/okta-react": "^4.1.0",
"@okta/okta-signin-widget": "^5.2.0"
```
Other changes:
- Use function components instead of class components
- Moved configuration to separate section
* [OKTA-352474](https://oktainc.atlassian.net/browse/OKTA-352474)
Note: I've created a sample app following the new guide, tested listed sample code.
> Update guide "Okta Sign-In Widget and React" for latest lib versions

- packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md
- **What's changed?** Update [Okta Auth SDK Guide](https://developer.okta.com/code/javascript/okta_auth_sdk/)  for `@okta/okta-auth-js 4.5.0`
* [OKTA-352477](https://oktainc.atlassian.net/browse/OKTA-352477)
> Update page "Okta Auth SDK Guide" to   @okta/okta-auth-js 4.5.0

- packages/@okta/vuepress-site/code/vue/okta_vue_sign-in_widget/index.md
- **What's changed?** Updated guide [Okta Sign-In Widget and Vue](https://developer.okta.com/code/vue/okta_vue_sign-in_widget/) for `@okta/okta-signin-widget` v5.2.0, `@okta/okta-vue` v3.0.0 and `okta-auth-js` v4.5.0
* [OKTA-352479](https://oktainc.atlassian.net/browse/OKTA-352479)
> Updated guide "Okta Sign-In Widget and Vue" for latest lib versions

- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
- **What's changed?** Fix incorrect var name in `onSuccess` function in `src/Login.js` in sample code for "Okta Sign-In Widget and React"
> Fix incorrect var name in sample code for "Okta Sign-In Widget and React"

- packages/@okta/vuepress-theme-prose/assets/css/components/_login.scss
- Add bottom padding to login form
* [OKTA-355581](https://oktainc.atlassian.net/browse/OKTA-355581)
> Add bottom padding to login form

- packages/@okta/vuepress-theme-prose/assets/css/components/_pricing.scss
- packages/@okta/vuepress-theme-prose/components/Pricing.vue
- packages/@okta/vuepress-theme-prose/index.js
* Flows the features list to a single column at mobile viewport widths
* Updates font on FAQ question to be Proxima Nova
* Ensures check icons in editions matrix do not shrink at smaller viewport widths
* [OKTA-355569](https://oktainc.atlassian.net/browse/OKTA-355569)
> Pricing page enhancements

- packages/@okta/vuepress-theme-prose/assets/css/components/_signUp.scss
- packages/@okta/vuepress-theme-prose/assets/css/layouts/_authorizationLayout.scss
- packages/@okta/vuepress-theme-prose/const/signup.const.js
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- packages/@okta/vuepress-theme-prose/util/signupValidation.service.js
* [OKTA-355579](https://oktainc.atlassian.net/browse/OKTA-355579)
* [OKTA-355582](https://oktainc.atlassian.net/browse/OKTA-355582)
> Consent section & minor singn up enhancement

- packages/@okta/vuepress-site/docs/guides/configure-access-policy/limit-scopes-clients-can-access/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/request-token-claim/index.md
- **What's changed?** Change JWT validator recommendation from jsonwebtoken.io to [token.dev](https://token.dev).
> Replace jsonwebtoken.io with token.dev

- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/token-hook/index.md
Changed 2 instances of 'webmaster@clouditude.net' to 'administrator1@clouditude.net' for inclusive language effort.
No
> Minor inclusive language change

- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
> doc: add siw version to migrate-to-oie guide

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **Update Authenticators Admin API docs to include the info and samples for the allowedFor field**
- **Is this PR related to a Monolith release? - 2021.01.0** 
* [OKTA-355288](https://oktainc.atlassian.net/browse/OKTA-355288)
> OKTA-355288 : Update Authenticators Admin API docs to include the info and samples for the allowedFor field

- packages/@okta/vuepress-site/docs/release-notes/2021-01-0/index.md
- **What's changed?** Adding the 2021.01.0 Release Notes index file to the Release Branch.
- **Is this PR related to a Monolith release?** Yes! 2021.01.0.
* n/a
> Adding 2021.01.0 Release Notes to 2021.01.0 Release Branch

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
Corrected the double left arrow in the link to 'bootstrapcdn' CDN in the HTML <head>. Changed 'var' to es6+ 'const' in the scripts.
> Correct a typo and update index.md

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** Workforce license rate limit multiplier update
* [OKTA-349527](https://oktainc.atlassian.net/browse/OKTA-349527)
Don't merge until TBD.
Top of Page
New Section
> Workforce license rate limit multiplier update

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** updated date for workflow
> updating date per Karthick

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/saml2/appidpinokta.md
- **What's changed?** Updating note to fix url typo and reference using a temporary certificate until the next step
* [OKTA-358834](https://oktainc.atlassian.net/browse/OKTA-358834)
> updating note with temporary certificate

- packages/@okta/vuepress-theme-prose/const/navbar/navbar.const.js
- **What's changed?** Updating the left-hand navigation file for new System Log events for rate limits page.
- **Is this PR related to a Monolith release?** 2021.01.0
* n/a
> Update Rate Limit nav bar

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md
Had a customer caught off-guard by this and thought it would be a good thing to add to the caveats section
> SSO OIDC caveat

- packages/@okta/vuepress-site/code/angular/okta_angular_auth_js/index.md
- packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
- packages/@okta/vuepress-site/code/react/okta_react/index.md
- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
- packages/@okta/vuepress-site/code/vue/okta_vue/index.md
- packages/@okta/vuepress-site/code/vue/okta_vue_sign-in_widget/index.md
- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/setup-app/index.md
- packages/@okta/vuepress-site/docs/guides/implement-implicit/setup-app/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/create-oauth-app/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/create-okta-application/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
- Note block quote is added to guides mentioning Okta app creation
No
* [OKTA-342950](https://oktainc.atlassian.net/browse/OKTA-342950)
> Warn users about application type mismatch

- packages/@okta/vuepress-theme-prose/components/Header.redesign.vue
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- packages/@okta/vuepress-theme-prose/package.json
- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
- packages/@okta/vuepress-theme-prose/util/attribution/cookies.js
- yarn.lock
- **What's changed?** Handles UTM/Attribution values in signup form, reuses code from marketing websites
* [OKTA-354076](https://oktainc.atlassian.net/browse/OKTA-354076)
> Handle UTM/Attribution values in signup form

- packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
- **Updated code samples for Okta Sign-In Widget and Angular** 
* [OKTA-348833](https://oktainc.atlassian.net/browse/OKTA-348833)
> Updated Okta Sign-In Widget and Angular code samples.

- packages/@okta/vuepress-site/docs/release-notes/2021-01-1/index.md
- **What's changed?**Release Notes 2021.01.1 
- **Is this PR related to a Monolith release?**Yes 2021.01.1
> Rn entry 2021.01.1

- packages/@okta/vuepress-site/code/dotnet/jwt-validation/index.md
The icon on code/dotnet/jwt-validation/ was angular. Changed to dotnet.
- **What's changed?** Updated code/dotnet/jwt-validation/ to use the dotnet icon instead of angular. 
- **Is this PR related to a Monolith release?** No. 
> Update icon on code/dotnet/jwt-validation/

- packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/jwt-with-private-key/js/createprivatekeyjwt.md
- **What's changed?** In snippet "Build a JWT With a Private Key"  need to set signing algorithm explicitly (default is HS256)
* [OKTA-262731](https://oktainc.atlassian.net/browse/OKTA-262731)
> Snippet "Build a JWT With a Private Key" - Need to set signing algo explicitly 

- packages/@okta/vuepress-site/code/vue/okta_vue/index.md
- **What's changed?** Specified used version of `@okta/okta-auth-js` (v4.5.0), removed deprecated method
* [OKTA-352480](https://oktainc.atlassian.net/browse/OKTA-352480)
> Update guide "Okta Auth JS and Vue" for `@okta/okta-auth-js` v4.5.0

- packages/@okta/vuepress-theme-prose/components/MenuItem.vue
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- **What's changed?** Add correct rel value to new _blank links
* [OKTA-360351](https://oktainc.atlassian.net/browse/OKTA-360351)
> Add correct rel value to new _blank links

- packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
- **What's changed?** adding subtypes table to rate limit sys log event page
* [OKTA-359285X](https://oktainc.atlassian.net/browse/OKTA-359285)
> Subtypes table

- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
Changed "Migrate" to "Upgrade" to OIE to be consistent with PMM messaging (requested by Jiong Liu)\
- No
> Changed "Migrate" to "Upgrade" to OIE

- packages/@okta/vuepress-site/code/library-versions/index.md
Update latest stable library versions of Java libraries.
> Update Java Library Versions to the latest

- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- **What's changed?**style review 
> style review

- packages/@okta/vuepress-site/docs/guides/enable-cors/overview/index.md
- Replace https://caniuse.com/cors table with link
- no
> Replace https://caniuse.com/cors table with link

- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
Fixing style issues
- **What's changed?** Fixed doc style issues
* N/A
> Fixing OIE Migrate style issues

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/package.json
- packages/@okta/vuepress-theme-prose/util/coveo/endpoint.js
- yarn.lock
- Update coveo to a newer version which has a working renewal callback
- Locally invalidate the token to prevent UI from flickering
* [OKTA-361551](https://oktainc.atlassian.net/browse/OKTA-361551)
> Correctly renew Coveo's access token

- packages/@okta/vuepress-theme-prose/assets/css/components/_header.scss
- Increase contrast of external link icon in header
* [OKTA-361722](https://oktainc.atlassian.net/browse/OKTA-361722)
> Increase contrast of external link icon in header

- packages/@okta/vuepress-theme-prose/assets/css/components/_signUp.scss
- Increase consent label and field's size
* [OKTA-361723](https://oktainc.atlassian.net/browse/OKTA-361723)
> Increase consent label and field's size

- packages/@okta/vuepress-theme-prose/assets/css/components/_pricing.scss
- **What's changed?** Fix pricing icon's size on firefox
* [OKTA-361792](https://oktainc.atlassian.net/browse/OKTA-361792)
> Fix pricing icon's size on firefox

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/index.md
* [OKTA-361530](https://oktainc.atlassian.net/browse/OKTA-361530)
> fix minor inconsistens in home page

- packages/@okta/vuepress-site/docs/guides/enable-cors/overview/index.md
> Fixed typo in cors support doc

- packages/@okta/vuepress-site/docs/reference/index.md
- packages/@okta/vuepress-theme-prose/const/navbar/navbar.const.js
- packages/@okta/vuepress-theme-prose/const/navbar/redesign/navbar.const.js
- **What's changed?** Changed reference overview content, made use of sidebar and page navar for reference page 
* [OKTA-351801](https://oktainc.atlassian.net/browse/OKTA-351801)
> Refactor reference page content

- packages/@okta/vuepress-theme-prose/components/Home.redesign.vue
- packages/@okta/vuepress-theme-prose/util/coveo/endpoint.js
- **What's changed?** Adjust when we hide codemirror
* [OKTA-361844](https://oktainc.atlassian.net/browse/OKTA-361844)
> Adjust when we hide codemirror

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/linkedin/appatidp.md
- **What's changed?** style edits from contributor
> linkedin edit

- packages/@okta/vuepress-site/docs/reference/index.md
- packages/@okta/vuepress-theme-prose/const/navbar/navbar.const.js
- packages/@okta/vuepress-theme-prose/const/navbar/redesign/navbar.const.js
Reverts okta/okta-developer-docs#1806
> Revert "Refactor reference page content"

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/oktatookta/appatidp.md
- Edited some of the out of date instructions
- Edited each step for clarity and readability
* N/A
> Edit instructions for clarity

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/package.json
- yarn.lock
- **What's changed?** Add robots.txt file with the proper link on vuepress sitemap 
* [OKTA-362275](https://oktainc.atlassian.net/browse/OKTA-362275)
> Create robots file

- packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
- **What's changed?** Review style for Sessions
> Review style for Sessions

- packages/@okta/vuepress-site/.vuepress/public/google5031e883b1469625.html
- packages/@okta/vuepress-site/.vuepress/public/googleb0a189bf55f71e31.html
- packages/@okta/vuepress-site/.vuepress/public/googlee48454695a007b30.html
* [OKTA-346217](https://oktainc.atlassian.net/browse/OKTA-346217)
> Adds google verification static pages

- packages/@okta/vuepress-theme-prose/components/Home.redesign.vue
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- Use relative paths
- Fix typo
- Remove unused method and action attributes from signup form (we rely on JS for this)
* [OKTA-362442](https://oktainc.atlassian.net/browse/OKTA-362442)
> Homepage's SIW tweaks

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/index.js
- Setting the `redesign` feature flag to true for our upcoming launch
- Setting production values for the signup endpoints
* [OKTA-359079](https://oktainc.atlassian.net/browse/OKTA-359079)
> [MERGE!] Sets redesign FF to true for launch

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/index.js
- packages/@okta/vuepress-theme-prose/util/coveo/endpoint.js
- Fixes two footer links
- Strip quotes from coveo_token if any
* [OKTA-362616](https://oktainc.atlassian.net/browse/OKTA-362616)
> Strip quotes from coveo_token if they are present

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
Forgot Password with E-mail Factor API Collection does not match documentation
* [OKTA-343757](https://oktainc.atlassian.net/browse/OKTA-343757)
> Forgot Password with E-mail Factor API Collection does not match documentation

- packages/@okta/vuepress-site/pricing/index.md
- bullet point “Registration as a service” was added
- "Attribute mapping and transformation" text was fixed
* [OKTA-362617](https://oktainc.atlassian.net/browse/OKTA-362617)
> fixes for text and bullets

- packages/@okta/vuepress-site/signup/index.md
* [OKTA-362690](https://oktainc.atlassian.net/browse/OKTA-362690)
> Add percentage symbol on signup page

- packages/@okta/vuepress-site/.vuepress/config.js
* [OKTA-362518](https://oktainc.atlassian.net/browse/OKTA-362518)
> Add viewport meta tag to site

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
* Completing captcha after attempted submit will re-enable submit button
* Captcha that expires will disable button
* Error message shown under captcha if it is incomplete
* Captcha siteKey is configurable by hostname
* [OKTA-362615](https://oktainc.atlassian.net/browse/OKTA-362615)
> Fixes CAPTCHA form behavior

- packages/@okta/vuepress-theme-prose/assets/css/components/_searchBar.scss
- packages/@okta/vuepress-theme-prose/components/Search.redesign.vue
- Change Help Center link in search page
- Style search bar's wrapper to prevent flickering
* [OKTA-362623](https://oktainc.atlassian.net/browse/OKTA-362623)
* [OKTA-362625](https://oktainc.atlassian.net/browse/OKTA-362625)
https://6009b9b5d0c8770c51216e34--reverent-murdock-829d24.netlify.app
> Prevent search bar flickering and adjust Help Center link

- packages/@okta/vuepress-theme-prose/components/Footer.redesign.vue
- **What's changed?** Make sure we hide the circle on SPA route change
* [OKTA-362620](https://oktainc.atlassian.net/browse/OKTA-362620)
> Hide magenta circle in footer on route change

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
* Adds GA event for email signup success
* Event will be published to GTM on Tuesday 1/26 10am PST but we can merge and deploy to production any time before then
* [OKTA-362748](https://oktainc.atlassian.net/browse/OKTA-362748)
> Adds GA event for email signup

- packages/@okta/vuepress-theme-prose/components/FrontPageCodeMirror.vue
- packages/@okta/vuepress-theme-prose/components/Home.redesign.vue
- Adjust SIW's heading
- Add readonly mode to codemirror
* [OKTA-362657](https://oktainc.atlassian.net/browse/OKTA-362657)
> Improvements to homepage's SIW (makes it look & feel non-editable)

- packages/@okta/vuepress-theme-prose/components/Home.redesign.vue
- **What's changed?** Replace `Javascript` with `JavaScript`
* [OKTA-362688](https://oktainc.atlassian.net/browse/OKTA-362688)
> Adjust typo with Javascript

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/use-flow/index.md
- packages/@okta/vuepress-theme-prose/assets/css/components/_searchBar.scss
- packages/@okta/vuepress-theme-prose/components/Footer.redesign.vue
- packages/@okta/vuepress-theme-prose/components/FrontPageCodeMirror.vue
- packages/@okta/vuepress-theme-prose/components/Home.redesign.vue
- packages/@okta/vuepress-theme-prose/components/Search.redesign.vue
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
Bundling multiple fixes in this PR for a single deployment
> Developer Docs enhancements - 1

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- **What's changed?** Style edit System Log
> Style Edit System Log

- packages/@okta/vuepress-site/docs/guides/enable-cors/granting-cors/index.md
- **What's changed?** Removed Dev Console note
> Fixed Jira ticket, removed Dev Console note

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/react/reqautheverything.md
- **What's changed?** Small typo fix to close the `<Route>` tag in the example
* None, doc fix
> Add missing closing slash for the <Route> tag

- packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** Replace the header's login text and link
* [OKTA-362766](https://oktainc.atlassian.net/browse/OKTA-362766)
> Replace the header's login text and link

- packages/@okta/vuepress-site/conductor.yml
* [OKTA-363739](https://oktainc.atlassian.net/browse/OKTA-363739)
> Add trailing slash redirects for contact paths

- packages/@okta/vuepress-theme-prose/util/pendo.js
- **What's changed?** Use Okta Help Center's pendo key instead of Okta's key
* [OKTA-365268](https://oktainc.atlassian.net/browse/OKTA-365268)
> Use Okta Help Center's pendo key instead of Okta's key

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/package.json
- packages/@okta/vuepress-theme-prose/components/FrontPageCodeMirror.vue
- packages/@okta/vuepress-theme-prose/components/FrontPageWidget.vue
- yarn.lock
* Loads SIW from Okta CDN instead of from installed NPM module
* [OKTA-365567](https://oktainc.atlassian.net/browse/OKTA-365567)
> Uses CDN to load OktaSignIn

- packages/@okta/vuepress-theme-prose/assets/css/components/_pricing.scss
- **What's changed?** Fix pricing checkmark for all screen sizes
* [OKTA-365730](https://oktainc.atlassian.net/browse/OKTA-365730)
> Fix pricing checkmark for all screen sizes

- package.json
- yarn.lock
* [OKTA-366671](https://oktainc.atlassian.net/browse/OKTA-366671)
> Upgrades protractor to ^7

- packages/@okta/vuepress-theme-prose/enhanceApp.js
* [OKTA-365911](https://oktainc.atlassian.net/browse/OKTA-365911)
> Catch unmatched paths in router and display custom 404

- packages/@okta/vuepress-site/docs/release-notes/2021-02-0/index.md
- **What's changed?** Adding Monthly Release Notes for 2021.02.0
- **Is this PR related to a Monolith release?** Yes Release Notes 2021.02.0
> Adding new monthly RN entry

- packages/@okta/vuepress-site/docs/reference/api/org/index.md
- Adds Developer Doc Page for Org API
- 15 new endpoints are documented all under url namespace api/v1/org
- Monolith release: 2021.02.0
* [OKTA-364104](https://oktainc.atlassian.net/browse/OKTA-364104)
> Adds Org API Doc

- packages/@okta/vuepress-site/data/error-codes.json
- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- **What's changed?** Updated the auto-generated docs
- **Is this PR related to a Monolith release?** 2020.02.0
* N/A
> Updated files for 2020.02.0 release

- tests/selenium/framework/page-objects/MainPage.js
- tests/selenium/framework/page-objects/SignInPage.js
- tests/selenium/framework/page-objects/SignUpPage.js
- tests/selenium/spec/header-spec.js
- tests/selenium/spec/signin-spec.js
- tests/selenium/spec/signup-spec.js
- Adding selenium tests for verifying basic components rendering like header buttons, links, sign in and sign up flow
* [OKTA-349902](https://oktainc.atlassian.net/browse/OKTA-349902)
> OKTA-349902: Adding basic tests to validate components are rendering

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/data/error-codes.json
- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/troubleshooting/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/enable-and-verify/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/test-hook/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/create-service-app/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/overview/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/test-integration/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/update-default-provider/index.md
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/org/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-events/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-providers/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021-02-0/index.md
- **What's changed?** Adding Release Notes for 2021.02.0
- **Is this PR related to a Monolith release?** Yes Release Note 2021.02.0
> Release 2021.02.0

- packages/@okta/vuepress-site/docs/release-notes/2020-06-0/index.md
- **What's changed?** Reverting API RN entry
* [OKTA-363511](https://oktainc.atlassian.net/browse/OKTA-363511)
> Removing RN entry

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/register-app-in-okta/index.md
- packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/findcreds/index.md
- packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/overview/index.md
- packages/@okta/vuepress-site/docs/guides/implement-client-creds/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/define-allowed-scopes/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/refresh-token-rotation/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/create-okta-application/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-remediation/create-okta-application/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/create-okta-application/index.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/define-signout-callback/index.md
Updates instruction sets to use Admin Console for changes
Introduces guidance to enable Trusted Origins for SPA and Web apps
2021.02.0
* [OKTA-364357](https://oktainc.atlassian.net/browse/OKTA-364357)
> Admin Console Changes - 364257

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Moved IDP-Initiated Login object section to Models section
OKTA-364399, OKTA-368677
> moved IDP-Initiated Login object section to Models section

- packages/@okta/vuepress-theme-prose/components/FrontPageCodeMirror.vue
* [OKTA-367849](https://oktainc.atlassian.net/browse/OKTA-367849)
> Updates codemirror logo image URL

- packages/@okta/vuepress-site/docs/reference/api-overview/index.md
- **What's changed?** Updated note in IP Address section and made a fix in the sentence
* [OKTA-368604](https://oktainc.atlassian.net/browse/OKTA-368604)
> updated for Jira ticket

- packages/@okta/vuepress-theme-prose/const/navbar/navbar.const.js
Adding Org to nav bar
- **What's changed?** Forgot to add the Org API reference to the nav bar
* N/A
> Adding Org API Reference to nav bar

- packages/@okta/vuepress-site/docs/reference/api/oie-policy-types/index.md
> Adding Beta notice

- packages/@okta/vuepress-theme-prose/const/navbar/navbar.const.js
- packages/@okta/vuepress-theme-prose/const/navbar/redesign/navbar.const.js
- **What's changed?** Actually adding it to the nav bar this time
* N/A
> Modified correct file

- packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/next-steps/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/check-on-startup/android/checkfortoken.md
- **What's changed?** Update android developer docs: sign-in guides and deprecated repository links
* [OKTA-369138](https://oktainc.atlassian.net/browse/OKTA-369138)
> update android developer docs

- packages/@okta/vuepress-site/docs/guides/request-user-consent/build-the-request/index.md
- packages/@okta/vuepress-site/docs/guides/request-user-consent/overview/index.md
- packages/@okta/vuepress-site/docs/guides/request-user-consent/require-consent/index.md
- **What's changed?** Added more info around the prompt parameter
* [OKTA-370799](https://oktainc.atlassian.net/browse/OKTA-370799)
> more info around the prompt parameter

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/ios/installsdk.md
- **What's changed?** Added a note about other dependency managers on iOS
* [OKTA-369807](https://oktainc.atlassian.net/browse/OKTA-369807)
> iOS: Add a note about Carthage and SPM

- packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
- **What's changed?** Add to rate limit authentication table
- **Is this PR related to a Monolith release?** Yes Release 2021.03.0
> added table row

- packages/@okta/vuepress-site/.vuepress/public/BingSiteAuth.xml
- Added copy of https://developer.okta.com/BingSiteAuth.xml to /public/ folder
* [OKTA-370364](https://oktainc.atlassian.net/browse/OKTA-370364)
> Added bingSiteAuth xml

- packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
- **What's changed?** "Get Session" heading added to right-side navigation bar
* [OKTA-372547](https://oktainc.atlassian.net/browse/OKTA-372547)
> Added Get Session heading to right-side navigation bar

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/index.md
> Updating UI instructions

- packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
- **What's changed?** Style edit User Types
> Style edit User Types

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Release notes entry for March monthly
- **Is this PR related to a Monolith release?** yes 2021-03-0
* [OKTA-373820](https://oktainc.atlassian.net/browse/OKTA-373820)
> Rn entry 2021.03.0

- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/openidconnect/submit.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/saml2/submit.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/scim/submit.md
Updates and additions to match the new functionality coming in the ISV Portal.
2021.03.0
* [OKTA-372050](https://oktainc.atlassian.net/browse/OKTA-372050)
> Updates and additions to ISV Portal text fields

- packages/@okta/vuepress-site/docs/reference/api/org/index.md
Resolves: OKTA-372637
- Remove EA Tag for Org API Docs
- Should be released along with 2021.03.0 release
- GA PR: https://github.com/okta/okta-core/pull/50131
* [OKTA-372043](https://oktainc.atlassian.net/browse/OKTA-372043)
> Remove EA status tag in Org API Doc

- packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
- **What's changed?** Add to rate limit authentication table
- **Is this PR related to a Monolith release?** Yes Release 2021.03.0
* [OKTA-367134](https://oktainc.atlassian.net/browse/OKTA-367134)
> Add row to rate limit authentication table

- packages/@okta/vuepress-site/docs/release-notes/index.md
- packages/@okta/vuepress-theme-prose/assets/css/components/_button.scss
* [OKTA-373795](https://oktainc.atlassian.net/browse/OKTA-373795)
> add next button for release notes overview

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/index.md
- tests/selenium/spec/api-tags-spec.js
Reverts #1932 .
FYI @AndriiDovhopolov-okta.
> Revert "Deleted /docs/ page #1932"

- packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/customize-link-in-widget/index.md
- **What's changed?** Add self-service registration to page and change headings to accommodate both Okta-hosted and self-hosted widgets
* [OKTA-333065](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)
> Add self-service registration info

- packages/@okta/vuepress-site/docs/reference/token-hook/index.md
- **What's changed?** Minor typo fix on Token Inline Hook API reference (https://developer.okta.com/docs/reference/token-hook/)
* n/a
> Fixed stray bracket after link

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/adding-basic-auth/index.md
- packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- **What's changed?** Improved documentation on Basic Auth for the API Reference page (https://developer.okta.com/docs/reference/api/inline-hooks/) and for the Guide Common Hooks Setup (https://developer.okta.com/docs/guides/common-hook-set-up-steps/nodejs/adding-basic-auth/)
* [OKTA-373382](https://oktainc.atlassian.net/browse/OKTA-373382)
> OKTA-373382 Update Basic Auth content for Hooks

- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
- making it more clear why devs should choose SPA vs Web
-
no
recent trend of devs not knowing which one to pick and picking the wrong one
> SPA vs web

- packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/overview/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- **What's changed?** Adding Token lifetime content and links
* [OKTA-368946](https://oktainc.atlassian.net/browse/OKTA-368946)
> Adding Token lifetime content and links

- packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
- **What's changed?** Add content for thin/fat ID tokens
* [OKTA-371407](https://oktainc.atlassian.net/browse/OKTA-371407)
> Add Thin and Fat ID Token Content

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/register-app-in-okta/index.md
- **What's changed?** Added edited note to page
https://github.com/okta/okta-developer-docs/pull/1856
> Updates from TheFuzzard's Patch-1 branch

- packages/@okta/vuepress-site/code/python/pysaml2/index.md
- **What's changed?** Adding OpenID Connect vs SAML Note for PySAML2
* [OKTA-368668](https://oktainc.atlassian.net/browse/OKTA-368668)
> Adding OpenID Connect vs SAML Note for PySAML2

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes for 2021.03.1
- **Is this PR related to a Monolith release?** Yes Release Notes 2021.03.1
* [OKTA-375757](https://oktainc.atlassian.net/browse/OKTA-375757)
> Release 2021.03.1

- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
Fixed missing params for `useEffect` in [Okta Sign-In Widget and React](https://developer.okta.com/code/react/okta_react_sign-in_widget/)
* [OKTA-372161](https://oktainc.atlassian.net/browse/OKTA-372161)
> Fixed useEffect for "Okta Sign-In Widget and React" guide

- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/static-allowlist/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/use-static-group-allowlist-custom-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/use-static-group-allowlist-org-as/index.md
- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/exchange-code-token/index.md
- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/implement-auth-code/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/implement-implicit/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-serviceapp-grantscopes/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/get-access-token/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/define-allowed-scopes/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md
- packages/@okta/vuepress-site/docs/guides/implement-password/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/implement-saml2/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
- **What's changed?** Fixing various issues with cURL examples
* [OKTA-375127](https://oktainc.atlassian.net/browse/OKTA-375127)
> Fixing various issues with cURL examples

- packages/@okta/vuepress-site/docs/reference/api-overview/index.md
- **What's changed?** New supported API section and style update
* [OKTA-223347](https://oktainc.atlassian.net/browse/OKTA-223347)
> New supported API section and style update

- packages/@okta/vuepress-site/docs/guides/migrate-to-okta/bulk-migration-with-credentials/index.md
> Fixing malformed heading

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Release Notes 2021.03.2
- **Is this PR related to a Monolith release?** yes, Release Notes 2021.03.2
* [OKTA-377289](https://oktainc.atlassian.net/browse/OKTA-377289)
> Rn entry 2021.03.2

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/concepts/ie-intro/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Initial draft of OIE concept doc
* [OKTA-358659](https://oktainc.atlassian.net/browse/OKTA-358659)
> Initial draft of OIE concept doc

- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
- **What's changed?** Updated terminology referencing Identity engine
* [OKTA-374589](https://oktainc.atlassian.net/browse/OKTA-374589)
> updated OIE terminology

- packages/@okta/vuepress-theme-prose/assets/css/components/_sidebar.scss
- packages/@okta/vuepress-theme-prose/components/Sidebar.vue
- packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
- Fixed issue with active states
Before
https://user-images.githubusercontent.com/68992536/110104048-5690a180-7daf-11eb-8f3b-3cee819cf95d.mov
After:
https://user-images.githubusercontent.com/68992536/110104086-5f817300-7daf-11eb-9b26-c2c703c563e0.mov
* [OKTA-320822](https://oktainc.atlassian.net/browse/OKTA-320822)
> Fixed issue with active states

- packages/@okta/vuepress-theme-prose/assets/css/components/_pricing.scss
- packages/@okta/vuepress-theme-prose/components/Pricing.vue
* [OKTA-377975](https://oktainc.atlassian.net/browse/OKTA-377975)
> add pricing banner

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-sign-jwt/index.md
- **What's changed?** Changed the JWT link
* [OKTA-375829](https://oktainc.atlassian.net/browse/OKTA-375829)
> changing link

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/php/login-redirect.md
- **What's changed?** Explains Variables
- 
* [OKTA-374893](https://oktainc.atlassian.net/browse/OKTA-374893)
> Explain route and state

- packages/@okta/vuepress-site/code/android/index.md
- **What's changed?**  Fixed typo "lolipop" in code/android/index.md
> fixed typo in code/android/index.md

- packages/@okta/vuepress-site/docs/guides/build-sso-integration/specify-your-settings/openidconnect/settings.md
- packages/@okta/vuepress-site/docs/guides/oin-oidc-guide/protocol-level-requirements/index.md
Add SPA app using Authorization Code with PKCE to the allowed list of applications
No
* [OKTA-375131](https://oktainc.atlassian.net/browse/OKTA-375131)
> Update OIN Guide - allow SPA using PKCE

- packages/@okta/vuepress-site/live-widget/index.md
- packages/@okta/vuepress-theme-prose/assets/css/components/_liveWidget.scss
- packages/@okta/vuepress-theme-prose/components/LiveWidgetJSCodeMirror.vue
- packages/@okta/vuepress-theme-prose/components/LiveWidgetOktaWidget.vue
- packages/@okta/vuepress-theme-prose/package.json
- yarn.lock
- **What's changed?**  Fixes for leftovers comments
> Fixes for live widget pr

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-publicprivate-keypair/index.md
- **What's changed?** Added tool for PEM to JWT conversion
* [OKTA-375829](https://oktainc.atlassian.net/browse/OKTA-375829)
> Added tool for PEM to JWT conversion

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
API Release Notes 
2021.03.3
* [OKTA-380221](https://oktainc.atlassian.net/browse/OKTA-380221)
> API Release Note for 2021.03.3

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-sign-jwt/index.md
- **What's changed?** adding exp in the example and bullet list
* [OKTA-374860](https://oktainc.atlassian.net/browse/OKTA-374860)
> adding exp in the example and bullet list

- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
- **What's changed?**  Update *Register your app* topic, specifically the CLI/Website instructions for *Tell Okta about the app*
* [OKTA-378784](https://oktainc.atlassian.net/browse/OKTA-378784)
> Update Register your app topic for OKTA-378784

- packages/@okta/vuepress-site/signup/index.md
* [OKTA-378547](https://oktainc.atlassian.net/browse/OKTA-378547)
> update bullet points

- packages/@okta/vuepress-theme-prose/components/Home.vue
* [OKTA-378904](https://oktainc.atlassian.net/browse/OKTA-378904)
> Update home page text

- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
- **What's changed?** Update redirect URIs after a conversion with Nathan Griffin, where he was working with a confused developer.
> Update redirect URIs to match Okta samples

- packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/configure-packages/android/installoktaauthsdk.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/android/installsdk.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/sign-in-page/android/signin.md
- packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/configure-packages/android/installsdk.md
- Updated android docs
* [OKTA-375729](https://oktainc.atlassian.net/browse/OKTA-375729)
> Updates outdated android docs

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/org.json
- packages/@okta/vuepress-site/docs/reference/api/org/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
Resolves: OKTA-379252
-Adds postman collection to org API
* [OKTA-379252](https://oktainc.atlassian.net/browse/OKTA-379252)
> Adds postman collection to org API

- packages/@okta/vuepress-theme-prose/components/TermsAndConditionsDialog.vue
* [OKTA-383054](https://oktainc.atlassian.net/browse/OKTA-383054)
>  Add state obj parameter

- packages/@okta/vuepress-site/docs/concepts/ie-intro/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-remediation/before-you-begin/index.md
- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/oie-policy-types/index.md
- **What's changed?** Adding IE and Limited GA flags to IE docs
* [OKTA-380746](https://oktainc.atlassian.net/browse/OKTA-380746)
> adding flags

- packages/@okta/vuepress-theme-prose/assets/css/components/_signUp.scss
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
* [OKTA-381303](https://oktainc.atlassian.net/browse/OKTA-381303)
> Make "I agree" field optional, add line breaker

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/signup/oie.md
- packages/@okta/vuepress-theme-prose/assets/css/components/_signUp.scss
- packages/@okta/vuepress-theme-prose/assets/css/layouts/_authorizationLayout.scss
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- yarn.lock
- **Is this PR related to a Monolith release?**  no
* [OKTA-378095](https://oktainc.atlassian.net/browse/OKTA-378095)
> Adds OIE signup

- packages/@okta/vuepress-site/pricing/index.md
- packages/@okta/vuepress-theme-prose/components/Pricing.vue
- yarn.lock
* [OKTA-383733](https://oktainc.atlassian.net/browse/OKTA-383733)
> Updates pricing advanced plan

- packages/@okta/vuepress-site/index.md
* [OKTA-384510](https://oktainc.atlassian.net/browse/OKTA-384510)
> Changes homepage compliance text

- packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md
- **What's changed?** Updated rotation schedule note per Warren and Jon
* [OKTA-383651](https://oktainc.atlassian.net/browse/OKTA-383651)
> updated note

- packages/@okta/vuepress-theme-prose/assets/css/components/_code.scss
- packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
* [OKTA-373048](https://oktainc.atlassian.net/browse/OKTA-373048)
https://606cfa89a666b51405c5d125--reverent-murdock-829d24.netlify.app/docs/guides/request-user-consent/require-consent/
> Fix css position for copy button

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** Adding whitespace character `&#160;` to the ends of lines with terminal curly braces to make the URLs render correctly. Hopefully this is only temporary.
* [OKTA-384590](https://oktainc.atlassian.net/browse/OKTA-384590)
> Adding whitespace character to make urls render correctly

- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/dynamic-allowlist-custom-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/dynamic-allowlist-org-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/overview/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/add-groups-claim-custom-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/add-groups-claim-org-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/overview/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/add-custom-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/create-app-profile-attribute/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/overview/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/overview/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/use-static-group-allowlist-custom-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/use-static-group-allowlist-org-as/index.md
- **What's changed?** Add groups claims steps for Custom Authorization Server  and did some general clean-up and clarification of the four guides
* [OKTA-383551](https://oktainc.atlassian.net/browse/OKTA-383551)
> custom claims and groups claims updates

- packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
- **What's changed?** Fix the aggregation values in rate limit doc page.
- **Is this PR related to a Monolith release?** No. It's a bug fix, can be merged at any time
* [OKTA-385804](https://oktainc.atlassian.net/browse/OKTA-385804)
> Fix aggregation values in rate limit doc page

- packages/@okta/vuepress-site/docs/reference/api/threat-insight/index.md
- **What's changed?** Update index.md to highlight free trial users need to request full TI enablement if needed.
* [OKTA-374756](https://oktainc.atlassian.net/browse/OKTA-374756)
> Update index.md to highlight free trial users need to request full TI enablement if needed.

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** 2021.04.0 PF bug
- **Is this PR related to a Monolith release?** Yes
* [OKTA-373689](https://oktainc.atlassian.net/browse/OKTA-373689)
> PF for 2021.04.0

- packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
- **What's changed?** Fix for error with autoscroll - I had PR where I forgot to rename variable and autoscroll got broken, here is a quick fix
> Restoring autoscrolling in sidebar

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes for April weekly release (2021.04.1)
- 
- **Is this PR related to a Monolith release?** Yes, 2021.04.1
* [OKTA-387034](https://oktainc.atlassian.net/browse/OKTA-387034)
> Rn entry 2021.04.1

- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
Guide missing the new required prop for the security component
- **What's changed?** The guide is missing the new required prop for the security component added in the v5 of @okta/okta-react
> Update guide for v5 of @okta/okta-react

- packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
- packages/@okta/vuepress-theme-prose/components/TermsAndConditionsDialog.vue
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- **What's changed?**  Fixed label naming from Country to Country/Region in Sign Up page
* [OKTA-386001](https://oktainc.atlassian.net/browse/OKTA-386001)
> Fixed Country label in Sign Up page

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/package.json
- yarn.lock
* [OKTA-259667](https://oktainc.atlassian.net/browse/OKTA-259667)
> Update markdown-it-attrs library to fix issue with curly brackets

- packages/@okta/vuepress-site/3rd_party_notices/Web_App_Client_JS/index.md
- packages/@okta/vuepress-site/docs/reference/api-overview/index.md
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/domains/index.md
- packages/@okta/vuepress-site/docs/reference/api/factor-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- packages/@okta/vuepress-site/docs/reference/api/features/index.md
- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- packages/@okta/vuepress-site/docs/reference/api/oie-policy-types/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- yarn.lock
- **What's changed?** Replaced RFC 5988 with RFC 8288
* [OKTA-385312](https://oktainc.atlassian.net/browse/OKTA-385312)
> Replaced RFC 5988 with RFC 8288

- packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/angular/remotesignout.md
- **What's changed?** Fixed compile error.
> Fix code example

- packages/@okta/vuepress-site/pricing/index.md
* [OKTA-388752](https://oktainc.atlassian.net/browse/OKTA-388752)
> change email support address for pricing page

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Previewfix
- **Is this PR related to a Monolith release?** Yes
* [OKTA-381601](https://oktainc.atlassian.net/browse/OKTA-381601)
> Remove RN entry because of PF

- packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
- **What's changed?**  IdP Discovery section is updated with a note.
* [OKTA-354752](https://oktainc.atlassian.net/browse/OKTA-354752)
> add a note on IdP Discovery feature limitation

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
Resolves: OKTA-388384
New Content-Type parameter added to allos omission of parts of certain User API responses that are expensive to compute for some configurations.
- **Is this PR related to a Monolith release?** 2021.04.2
* [OKTA-388384](https://oktainc.atlassian.net/browse/OKTA-388384)
> DWW Document new Content-Type parameter for get/list user APIs

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Add release notes for 2021.04.2
- **Is this PR related to a Monolith release?** Yes, 2021.04.2
* [OKTA-388827](https://oktainc.atlassian.net/browse/OKTA-388827)
> Rn entry 2021.04.2

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Release notes and content for 2021.04.2
- **Is this PR related to a Monolith release?** Yes, 2021.04.2
* [OKTA-388827](https://oktainc.atlassian.net/browse/OKTA-388827)
> Release 2021.04.2

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** SIW release links in the April 2021 release notes
> Link SIW release updates to specific release versions in RN

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- Add Multi IdP support description brought together with OIE
* [OKTA-385366](https://oktainc.atlassian.net/browse/OKTA-385366)
> Update IDP Discovery Policy with Multi IDP support

- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/scim/submit.md
Add in new text for SCIM submissions - allowing Group membership updates to be batched in smaller PATCH operations.
Yes. 2021.05.0
* [OKTA-379544](https://oktainc.atlassian.net/browse/OKTA-379544)
* [OKTA-391398](https://oktainc.atlassian.net/browse/OKTA-391398)
> Update SCIM submission guide

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding monthly 2021.05.0 release note entries.
- **Is this PR related to a Monolith release?** Yes, 2021.05.0
* [OKTA-391217](https://oktainc.atlassian.net/browse/OKTA-391217)
> Rn entry 2021.05.0

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
Resolves: OKTA-373744
- API doc updates for group profiles feature. 
- Merge targeting 2021.05.0 according to @nghadge-okta 
* [OKTA-373744](https://oktainc.atlassian.net/browse/OKTA-373744)
> DWW Document group profiles

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** add /login/token/redirect to DynamicScale and Workforce multiplier
- **Is this PR related to a Monolith release?** Yes, 2021.05.0
* [OKTA-390067](https://oktainc.atlassian.net/browse/OKTA-OKTA-390067)
> Add /login/token/redirect in DS and WF

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md
missing a couple characters in authorize url
Added a couple missing characters to authorize url so it's correct
> typo in index.md

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- Password Policy API doc update for callFactor in recovery settings.
- Monolith Release: ASAP
- Wanna check out how this would look? See [here](https://6093f145a05b0300c2dbe5cd--reverent-murdock-829d24.netlify.app/docs/reference/api/policy/#recovery-factors-object) (courtesy: Netlify)
* [OKTA-392164](https://oktainc.atlassian.net/browse/OKTA-392164)
> Add callFactor recovery object

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/captchas.json
- packages/@okta/vuepress-site/docs/reference/api/captchas/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
Adds Developer Doc Page for CAPTCHA APIs
5 new endpoints are documented under url namespace api/v1/captchas
3 new endpoints are documented under url namespace api/v1/org/captcha
* [OKTA-391470](https://oktainc.atlassian.net/browse/OKTA-391470)
> API Reference for captcha instance management

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Add docs for the new Okta Expression Language used in OIE
- **Is this PR related to a Monolith release?** No. This PR is ready to be merged.
* [OKTA-371557](https://oktainc.atlassian.net/browse/OKTA-371557)
@nghadge-okta @daytonwilliams-okta
> Add docs for the new Okta Expression Language used in OIE.

- packages/@okta/vuepress-site/docs/reference/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Updating the Reference left-hand navigation bar to incorporate all Hook content under one category.
* n/a
> Initial update to Reference left-hand nav for Hooks

- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
* Also adding GA tracking fields that may exist on the user's session and attaching it to the attribution data sent on signup
* [OKTA-392895](https://oktainc.atlassian.net/browse/OKTA-392895)
> Add GA tracking fields to signup attribution data

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes for 2021.05.1
- **Is this PR related to a Monolith release?** Yes Release Notes 2021.05.1
* [OKTA-393671](https://oktainc.atlassian.net/browse/OKTA-393671)
> Rn entry 2021.05.1

- packages/@okta/vuepress-site/docs/guides/build-sso-integration/before-you-begin/openidconnect/prep.md
Update the SSO integration guide for OIN to include details about OIDC SPA apps that use PKCE
No
* [OKTA-389293](https://oktainc.atlassian.net/browse/OKTA-389293)
> Update with changes on SPA PKCE apps for OIN

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/components/Footer.vue
* [OKTA-395765](https://oktainc.atlassian.net/browse/OKTA-395765)
> Removes trailing slash from footer auth0 link

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding 2021.05.2 Release Notes to Release Branch
- **Is this PR related to a Monolith release?** 2021.05.2
* [OKTA-395207](https://oktainc.atlassian.net/browse/OKTA-395207)
> Rn entry 2021.05.2

- packages/@okta/vuepress-theme-prose/assets/css/components/_apiLifecycle.scss
- packages/@okta/vuepress-theme-prose/global-components/ApiLifecycle.vue
* [OKTA-391142](https://oktainc.atlassian.net/browse/OKTA-391142)
> Add Classic Engine label

- packages/@okta/vuepress-theme-prose/assets/css/components/_homePage.scss
- packages/@okta/vuepress-theme-prose/components/Home.vue
* [OKTA-393061](https://oktainc.atlassian.net/browse/OKTA-393061)
> Reduce banner size

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes for latest weekly release; includes three bug fixes.
- **Is this PR related to a Monolith release?** 2021.05.2
* [OKTA-395207](https://oktainc.atlassian.net/browse/OKTA-395207)
> Rn entry 2021.05.2 (#2139)

- packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
- **What's changed?** Added OIE label
- **Is this PR related to a Monolith release?** Yes, related to okta/okta-core#52846
* [OKTA-396500](https://oktainc.atlassian.net/browse/OKTA-396500)
> Add OIE label

- packages/@okta/vuepress-site/docs/guides/index.md
- **What's changed?** Added a reference to Hooks, including links to example Hook implementations, on the Okta Developer Docs > Guides [Overview](https://developer.okta.com/docs/guides/) page.
* [OKTA-372713](https://oktainc.atlassian.net/browse/OKTA-372713)
> Update to Guides Overview for Hooks

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/linkedin/appatidp.md
- **What's changed?** Added new step required by LinkedIn
* [OKTA-397633](https://oktainc.atlassian.net/browse/OKTA-397633)
> adding sign in with linkdin step

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/google/appatidp.md
- **What's changed?** redirect url example added to be consistent with other idp wording
* [OKTA-397955](https://oktainc.atlassian.net/browse/OKTA-397955)
> redirect url example added to be consistent with other idp wording

- packages/@okta/vuepress-site/docs/reference/api/domains/index.md
- Fix api method in certificate example
* [OKTA-OKTA-397871](https://oktainc.atlassian.net/browse/OKTA-397871)
> Resolve OKTA-397871 fix api method in certificate example

- packages/@okta/vuepress-site/.vuepress/config.js
- Developer day link was added to Community menu in header
NOTE - not merge until May 25th
* [OKTA-395384](https://oktainc.atlassian.net/browse/OKTA-395384)
> "Developer day" link added to Header

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Release Notes entry for 2021.05.3
- **Is this PR related to a Monolith release?** Release Notes entry for 2021.05.3
* [OKTA-397590](https://oktainc.atlassian.net/browse/OKTA-397590)
> Rn entry 2021.05.3

- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/create-service-app/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/overview/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/test-integration/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/update-default-provider/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-events/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-providers/index.md
Related to OKTA-394426
- **What's changed?**  This PR makes changes to the `BETA` 3rd party risk engine APIs based on the feedback we got from the partners. 
- **Is this PR related to a Monolith release?**  2021.05.3 (Confirm)
* [OKTA-394426](https://oktainc.atlassian.net/browse/OKTA-394426)
> Update the API documentation for 3rd party risk engine

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/before-you-begin/go/create-app.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/aspnet/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/aspnetcore3/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/go/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/nodeexpress/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/php/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/springboot/configmid.md
- **What's changed?** Added custom Authorization Server Id option to SDK sample snippet. Fixed 2 broken links in the Sign users in to web app > Configure packages  pages.
* [OKTA-396302](https://oktainc.atlassian.net/browse/OKTA-396302)
> Vn-OKTA-396302-Add note about issuer to Node Express Quickstart Guide

- packages/@okta/vuepress-theme-prose/components/Pricing.vue
- **What's changed?** ![image](https://user-images.githubusercontent.com/68992536/119952661-ed7f8b00-bfa5-11eb-94a0-09ef92581df9.png)
* [OKTA-399249](https://oktainc.atlassian.net/browse/OKTA-399249)
> Text updated on custom plan in /pricing section

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- Added device condition to signon policy API in the dev doc
- Added device condition EL to EL dev doc.
* [OKTA-394380](https://oktainc.atlassian.net/browse/OKTA-394380)
* [OKTA-394104](https://oktainc.atlassian.net/browse/OKTA-394104)
@chenningzhang-okta @jakubvul @okta/device-platform @jeanettedillon-okta Please review.
> Added device condition to signon policy API in the dev doc

- packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Addition to Okta Developer Docs / Concepts: User Profiles 
* [OKTA-320481](https://oktainc.atlassian.net/browse/OKTA-320481)
> Bd okta 320481 okta user profiles

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** release notes for 2021.06.0 
- **Is this PR related to a Monolith release?** yes release notes for 2021.06.0
* [OKTA-399935](https://oktainc.atlassian.net/browse/OKTA-399935)
> Rn entry 2021.06.0

- packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/refresh-token-rotation/index.md
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- yarn.lock
- **What's changed?** removing EA flags for refresh token rotation
- **Is this PR related to a Monolith release?** Yes 2021.06.0
> removing the EA flags

- packages/@okta/vuepress-theme-prose/global-components/ErrorCodes.vue
* [OKTA-303440](https://oktainc.atlassian.net/browse/OKTA-303440)
> Add padding for error code

- packages/@okta/vuepress-theme-prose/global-components/StackSelector.vue
Fixes issue where pages with multiple snippets were repeating the same snippet since changes in https://github.com/okta/okta-developer-docs/pull/2176
* [OKTA-397896](https://oktainc.atlassian.net/browse/OKTA-397896)
> Fixes issue where snippets were being repeated

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Added docs for EL security expressions used in Policy Rules.
* [OKTA-394101](https://oktainc.atlassian.net/browse/OKTA-394101)
> Add a section for security expressions in Policy Rules.

- packages/@okta/vuepress-site/docs/guides/migrate-to-okta/prerequisites/index.md
- I noticed that this link was incorrect while reading. I am assuming that the link was meant to point to the feature reference and not the guide to migrate users using the feature, but correct me if I'm mistaken.
- Not that I know of.
> Fix Inline Password Hook link

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes for 2021.06.1
- **Is this PR related to a Monolith release?** Yes Release Notes for 2021.06.1
* [OKTA-401543](https://oktainc.atlassian.net/browse/OKTA-401543)
> Adding RN 2021.06.1

- tests/selenium/framework/page-objects/BasePage.js
* [OKTA-402200](https://oktainc.atlassian.net/browse/OKTA-402200)
> Use WebDriver wrapper directly for page refresh on Selenium tests

- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Updated RL dashboard doc with user feedback
> Rate Limit Dashboard Updates

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- packages/@okta/vuepress-theme-prose/global-components/ErrorCodes.vue
- **What's changed?** Adding Release Notes for 2021.06.1
- **Is this PR related to a Monolith release?** Yes Release Notes 2021.06.1
> Release 2021.06.1

- packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/configure-self-service-registration-policy/index.md
- **What's changed?** Update self registration
* [OKTA-367827](https://oktainc.atlassian.net/browse/OKTA-367827)
> Update Self Registration to Add Trusted Origin

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Removed the word "immediately in User API
* [OKTA-391158](https://oktainc.atlassian.net/browse/OKTA-391158)
> Removed the word "immediately" in Users API

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
- **What's changed?** Removed "Refresh token rotation EA" note. Re-arranged steps to align with updated App Integration Wizard.
* [OKTA-403132](https://oktainc.atlassian.net/browse/OKTA-403132)
> OKTA-403132 remove refresh token rotation EA and update SPA-create-app-integration instructions

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes to Release branch
- **Is this PR related to a Monolith release?** 2021.06.2
* [OKTA-403264](https://oktainc.atlassian.net/browse/OKTA-403264)
> Rn entry 2021.06.2

- packages/@okta/vuepress-site/docs/guides/submit-app/submission1-general/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/openidconnect/submit.md
Adds question on OIDC modes for ISV submissions in the OIN Manager
Yes. 2021.06.0 (released when OIN Manager updates go live)
* [OKTA-396199](https://oktainc.atlassian.net/browse/OKTA-396199)
> Add OIDC mode question (OKTA-396199)

- packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- packages/@okta/vuepress-site/docs/reference/api/iam-roles/index.md
- Split between all users and all groups
- https://oktainc.atlassian.net/browse/OKTA-390139
* [OKTA-404632](https://oktainc.atlassian.net/browse/OKTA-404632)
> changed docs to reflect split of all groups and all users

- packages/@okta/vuepress-site/code/php/index.md
Added TODO to follow up with the PHP team when they return from PTO
> Removing dead link

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Added release notes for this week's release
- **Is this PR related to a Monolith release?** 2021.06.2
* [OKTA-403264](https://oktainc.atlassian.net/browse/OKTA-403264)
> Rn entry 2021.06.2 (#2222)

- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
- **What's changed?** Updated terminology as per recent direction.
* [OKTA-399598](https://oktainc.atlassian.net/browse/OKTA-399598)
> Updated terminology for Identity Engine and direct auth

- packages/@okta/vuepress-site/.vuepress/config.js
- scripts/publish.sh
* [OKTA-253160](https://oktainc.atlassian.net/browse/OKTA-253160)
> Add robots meta tag

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-sign-jwt/index.md
- **What's changed?** Added algorithm info from Dragos PR now that he's gone
> alg addition and a link added

- packages/@okta/vuepress-site/code/oie/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Added new “Identity Engine SDKs & Samples” page inside the Languages & SDKs section.
* [OKTA-399045](https://oktainc.atlassian.net/browse/OKTA-399045)
> VN OKTA 399045 OIE SDKs and Samples page

- packages/@okta/vuepress-site/docs/concepts/ie-intro/index.md
- **What's changed?** Replaced intro with an updated one from Daniel Lu per Emeka and an OIE email thread on updates to older OIE docs
> intro update per Emeka and Daniel Lu

- packages/@okta/vuepress-site/code/react/okta_react/index.md
- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/add-signin-button/react/login-redirect.md
- update snippets with okta-auth-js@5.0.0 compatible code
* [OKTA-392445](https://oktainc.atlassian.net/browse/OKTA-392445)
> chore: use okta-react@6.0.0 in guides' snippets

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes for 2021.06.3
- **Is this PR related to a Monolith release?** Yes Release Notes 2021.06.3
* [OKTA-405180](https://oktainc.atlassian.net/browse/OKTA-405180)
> Rn entry 2021.06.3

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- Remove dup app label constraint
- **Is this PR related to a Monolith release?** : yes, 2021.06.3
* [OKTA-405368](https://oktainc.atlassian.net/browse/OKTA-405368)
Reviewers: @okta/developerdocs
> Remove dup app label constraint

- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
I added a Best Practice section to /keys as discussed 
Two things:
1. I added in the detailed best-practice advice laid out in the internal Jira comments by Jon Kraatz here:
https://oktainc.atlassian.net/browse/OKTA-381855
2. I also moved the below note from higher up in the docs to this Best Practices section:
> **Note:** Okta strongly recommends retrieving keys dynamically with the JWKS published in the discovery document.<p>
Okta also recommends caching or persisting these keys to improve performance. If you cache signing keys and automatic key rotation is enabled, be aware that verification fails when Okta rotates the keys automatically. Clients that cache keys should periodically check the JWKS for updated signing keys.
Moving that down feels...wrong in a way because it's less …
> /keys best practice

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/configlocations.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/githubinstructions.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/projectstructure.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- **What's changed?** style, grammar, punctuation, format edits
> First embedded edit

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/react/reqauthspecific.md
- Import missing Switch component
> Import missing Switch component

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- Add Domains API to left navbar menu
- Monolith release: 2021.06.4
* [OKTA-405126](https://oktainc.atlassian.net/browse/OKTA-405126)
> OKTA-405126 Add Domains API to left navbar menu

- packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
Fixes broken internal link
No
* [OKTA-406509](https://oktainc.atlassian.net/browse/OKTA-406509)
> Update SCIM reference files to fix broken link

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/gather-information/index.md
- **What's changed?** fixing lone bullet
> fixing lone bullet

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-run-sample/main/aspnet/testapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-run-sample/main/index.md
- **What's changed?** sdk run sample edits
> sdk run sample edits

- packages/@okta/vuepress-site/docs/guides/oie-embedded-overview/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-overview/main/index.md
- **What's changed?** minor edit to the embedded overview
> oie-embedded-overview edits

- packages/@okta/vuepress-site/code/oie/index.md
- **What's changed?** Updates to Identity Engine SDK landing page
* [OKTA-399045](https://oktainc.atlassian.net/browse/OKTA-399045)
> OKTA-399045 New Identity Engine SDK and Sample app page

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-run-sample/main/aspnet/testapp.md
- **What's changed?** Removing questions
> Removing questions

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/index.md
- **What's changed?** Edits for embed sdk basic signin
> Edits for embed sdk basic signin

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/aspnet/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- **What's changed?** Edits for oie-embedded-common-org-setup 
> Edits for oie-embedded-common-org-setup

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/index.md
- **What's changed?** sdk use cases signout
> sdk use cases signout

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-alternate-flows/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-run-sample/main/aspnet/testapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-run-sample/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/index.md
Updates to the org setup page and other small changes
> Updates to the org setup page and other small changes

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-overview/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/index.md
- **What's changed?** sdk use cases
> sdk use cases

- packages/@okta/vuepress-site/code/vue/okta_vue/index.md
- packages/@okta/vuepress-site/code/vue/okta_vue_sign-in_widget/index.md
Updates these pages:
- https://developer.okta.com/code/vue/okta_vue_sign-in_widget/
- https://developer.okta.com/code/vue/okta_vue/
for [`@okta/okta-vue 5`](https://github.com/okta/okta-vue/pull/56), `@okta-auth-js 5`, `Vue 3` instead of Vue 2
* [OKTA-386971](https://oktainc.atlassian.net/browse/OKTA-386971)
> Update docs for Vue to okta-vue 5, vue 3

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/oktatookta/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/openidconnect/appidpinokta.md
- **What's changed?** adding note for userinfo endpoint
* [OKTA-390451](https://oktainc.atlassian.net/browse/OKTA-390451)
> adding note for userinfo endpoint

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-alternate-flows/main/index.md
- **What's changed?** Embedded edits alternate flows
> Embedded edits alternate flows

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** OIE rate limit endpoints added
* [OKTA-406553](https://oktainc.atlassian.net/browse/OKTA-406553)*
> oie endpoints

- packages/@okta/vuepress-site/.vuepress/config.js
- scripts/publish.sh
> Use correct syntax for DEPLOY_ENV assignment

- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/add-groups-claim-custom-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/add-groups-claim-org-as/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/overview/index.md
- **What's changed?** wording around fat and thin token for clarification
* [OKTA-360306](https://oktainc.atlassian.net/browse/OKTA-360306)
> wording around fat and thin token for clarification

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** Added OIE endpoints to DS/WF
- **Is this PR related to a Monolith release?** TBD
* [OKTA-407813](https://oktainc.atlassian.net/browse/OKTA-407813)
> Add OIE Endpoints to Dynamic Scale and Workforce

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
these samples are missing the redirectUri
> Add redirecUri to samples

- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/enable-and-verify/index.md
- **What's changed?** Clarification on UI procedures to create an Event Hook in the Event Hooks Guide.
* [OKTA-333017](https://oktainc.atlassian.net/browse/OKTA-333017)
* [OKTA-333008](https://oktainc.atlassian.net/browse/OKTA-333008)
> Clarification on UI procedures to create an Event Hook 

- packages/@okta/vuepress-site/docs/reference/api/zones/index.md
- **What's changed?** Update the Zones API to add info on the default IP Network Zone, and include description on IP vs Dynamic Zones.
* [OKTA-407419](https://oktainc.atlassian.net/browse/OKTA-407419)
> Add default Zone, IP vs Dynamic Zone info in the intro of Zones API

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding release notes for 2021.06.4
- **Is this PR related to a Monolith release?** Yes, 2021.06.4
* [OKTA-406724](https://oktainc.atlassian.net/browse/OKTA-406724)
> Rn entry 2021.06.4

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
* add 2021.06.4 release note items
* update 2021.06.4 bug list
* update entries 2021.06.4
- **What's changed?** Adding 2021.06.4 resolved bug to release notes
- **Is this PR related to a Monolith release?** Yes, 2021.06.4
* [OKTA-406724](https://oktainc.atlassian.net/browse/OKTA-406724)
> Release Notes for 2021.06.4 (#2287)

- packages/@okta/vuepress-site/code/angular/okta_angular_auth_js/index.md
- packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
Pages:
- https://developer.okta.com/code/angular/okta_angular_sign-in_widget/
- https://developer.okta.com/code/angular/okta_angular_auth_js/
To support latest okta-auth-js 5.0, [okta-angular 3.2.0](https://github.com/okta/okta-angular/pull/40) Angular 12.
* [OKTA-386969](https://oktainc.atlassian.net/browse/OKTA-386969)
> Update Angular guides to latest okta-angular

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/clientsecret.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/aspnet/applicationtype.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/aspnet/newapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
Enabled several common sections in the OIE Embedded docs to become tech specific.
> Oie docs embedded update common config changes 1

- packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
- **What's changed?** Added entries to the table
- **Is this PR related to a Monolith release?** Yes 2021.07.0
* [OKTA-394607](https://oktainc.atlassian.net/browse/OKTA-394607)
> Added entries to the operation rate limit subtypes table

- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- **What's changed?** Add developer docs for unique attributes.
- **Is this PR related to a Monolith release?** Yes. 2021.07.0
* [OKTA-398999](https://oktainc.atlassian.net/browse/OKTA-398999)
@donwoods-okta @daytonwilliams-okta @okta/ud-core
> Add developer docs for unique attributes.

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- the Feature will GA to Prod, so remove the related EA flags
- **Is this PR related to a Monolith release?**  2021.7.0 
* OKTA-402796
> Remove EA flags for a GAed Feature

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Added the July monthly release notes to the Release Notes > 2021 file.
- **Is this PR related to a Monolith release?** 2021.07.0
* [OKTA-408752](https://oktainc.atlassian.net/browse/OKTA-408752)
> Adding 2021.07.0 Monthly Release Notes

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Add ticket to 2021.06.4 change log.
- **Is this PR related to a Monolith release?** Yes, 2021.06.4
* [OKTA-406724](https://oktainc.atlassian.net/browse/OKTA-406724)
> add to bug list in post 2021.06.4 release

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/configorder.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
Made the config order section tech stack specific.
> Oie docs embedded update common config changes 2

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/index.md
Moved OIE Embedded use case content to be lang specific
> Oie docs embedded swift

- packages/@okta/vuepress-site/docs/index.md
- packages/@okta/vuepress-site/docs/release-notes/index.md
- packages/@okta/vuepress-theme-prose/assets/css/components/_nutritionFacts.scss
- packages/@okta/vuepress-theme-prose/assets/css/prose.scss
- packages/@okta/vuepress-theme-prose/global-components/NutritionFacts.vue
* [OKTA-403628](https://oktainc.atlassian.net/browse/OKTA-403628)
https://60ddee956e3f68008eb03352--reverent-murdock-829d24.netlify.app/docs/release-notes/
> add nutrition global component

- packages/@okta/vuepress-site/.vuepress/scripts/yml-parse-check.js
> Fix broken reference in `yml-parse-check` script

- packages/@okta/vuepress-site/docs/reference/api/captchas/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** adding captchas to nav bar and edits
> adding captchas to nav bar and edits

- packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- packages/@okta/vuepress-site/docs/guides/implement-saml2/overview/index.md
- **What's changed?** removing EA flag for SAML Assertion 2.0 grant flow going GA
- **Is this PR related to a Monolith release?** Yes 2021.07.0
> removing EA flag for SAML Assertion 2.0 grant flow going GA

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** This needed to be part of 2021.07.0.
- **Is this PR related to a Monolith release?** Yes 2021.07.0
* [OKTA-406626](https://oktainc.atlassian.net/browse/OKTA-406626)
> adding in trexfix

- packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
- packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/captchas/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** api ref edits and adding in lga flag
- **Is this PR related to a Monolith release?** Yes Tuscany
> api ref edits and adding in lga flag

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-alternate-flows/main/nodejs/getuserprofile.md
- **What's changed?** Adding an "Alternate Flow" page for Embedded SDK 
* [OKTA-408181](https://oktainc.atlassian.net/browse/OKTA-408181)
> Adding NodeJS Alternate Flow page to Embedded-OIE Docs

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-alternate-flows/main/ios/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/ios/integrationsteps.md
1. Added userinfo code for swift. (alternate flows page)
2. Updated signout code for swift based on conversation with Mike (Lead Swift engineer)
> Oie docs embedded swift 5

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/clientsecret.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-alternate-flows/main/java/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/java/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/java/summaryofsteps.md
- **What's changed?** Final edit of Java content in the OIE embedded auth guides, and some common content (that affects Java)
* [OKTA-408182](https://oktainc.atlassian.net/browse/OKTA-408182)
> OIE embedded SDK-SIW guide for Java -  edit review

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-alternate-flows/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-common/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-limitations/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-run-sample/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-overview/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-run-sample/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-overview/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/index.md
- packages/@okta/vuepress-site/docs/reference/ie-limitations/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** OIE Limitations Doc
- **Is this PR related to a Monolith release?** Yes. Tuscany
* [OKTA-401565](https://oktainc.atlassian.net/browse/OKTA-401565)
> OIE Limitations Doc

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/ios/integrationsteps.md
Updated coming soon message in swift use cases without documentation.
> Oie docs embedded swift update coming soon 2

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/java/integrationsteps.md
- **What's changed?** Add "coming soon" blurb to outstanding uses cases for Java SDK
* [OKTA-408182](https://oktainc.atlassian.net/browse/OKTA-408182)
> Add Java SDK coming-soon blurb for oustanding uses cases

- packages/@okta/vuepress-site/docs/guides/email-customization/customize-email-templates/index.md
- **What's changed?** Add content for advanced email customization
- **Is this PR related to a Monolith release?** TBD
> Added content for advanced email customization

- packages/@okta/vuepress-site/docs/guides/email-customization/customize-email-templates/index.md
Updated the opening blurb to be more clear, and cleaned up some syntax
- Yes, 2021.07.1 (going out to prod today)
no JIRA
> Simplified some intro language for email macros guide

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Rn entry 2021.07.1
- **Is this PR related to a Monolith release?** Yes 2021.07.1
* [OKTA-410720](https://oktainc.atlassian.net/browse/OKTA-410720)
> Rn entry 2021.07.1

- packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** Release 2021.07.1
- **Is this PR related to a Monolith release?** Yes Release 2021.07.1 
* [OKTA-410720](https://oktainc.atlassian.net/browse/OKTA-410720)
> Release 2021.07.1

- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- **What's changed?** Added more detail for Downtime 
* [OKTA-365182](https://oktainc.atlassian.net/browse/OKTA-365182)
> Updated rate limit dashboard downtime info

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** adding redirect for no slash at the end per Emeka
> adding redirect for no slash at the end per Emeka

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/android/summaryofsteps.md
- **What's changed?** sign in with facebook for android
> sign in with facebook for android

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/ios/integrationsteps.md
- **What's changed?**  Added source code comments to the OIE Swift samples
> Add source code comments to the Swift samples

- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- Added Domains API to the Postman Collections list
> Added Domains API to the Postman Collections list

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding new RN entry
- **Is this PR related to a Monolith release?** Yes 2021.07.2
* [OKTA-414540](https://oktainc.atlassian.net/browse/OKTA-414540)
> Weekly Release Note 2021.07.2

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/android/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/index.md
- **What's changed?** adding Android Self-Registration Use Case
- **Is this PR related to a Monolith release?** Tuscany 
> Android Self-Registration Use Case

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/android/summaryofsteps.md
- **What's changed?** Android sign-in password/email
> Android sign-in password/email

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/android/summaryofsteps.md
- **What's changed?** Android password/phone use case
> Android password/phone use case

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/android/summaryofsteps.md
- **What's changed?** Android password recovery use case
> Android password recovery use case

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/android/integrationsteps.md
- **What's changed?** making updates to android per java update
> making updates to android per java update

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/brands.json
- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- Adds Developer Doc Page for Brands API
- 12 new endpoints are documented under url namespace `api/v1/brands`
- Monolith release: `2021.08.0`
* [OKTA-403658](https://oktainc.atlassian.net/browse/OKTA-403658)
> OKTA-403658: Adding API references for branding

- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- Update Registration Hooks Documentation for OIE
* [OKTA-404956](https://oktainc.atlassian.net/browse/OKTA-404956)
> oie changes for registration hooks

- .travis.yml
- packages/@okta/vuepress-site/.vuepress/scripts/addWorkerScript.js
- packages/@okta/vuepress-site/.vuepress/scripts/updateBuildScript.js
- scripts/helpers.sh
- scripts/travis.sh
The major change in this PR updates the VM in Travis to `large` to increase the memory available to the build process, which was hitting a memory bottleneck when building the site, leading to massive slowdown and timing out the build. This change is temporary to unblock PRs/merging.
**We need to further investigate since this change is now costing us Travis credits on every build.**
Since the OIE docs launch, we're seeing a lot more timeouts on building the site, likely due to the number of pages added:
* [OKTA-417069](https://oktainc.atlassian.net/browse/OKTA-417069)
> Increases build VM size, cleans up `.travis.yml`

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** removing EA flags from OAuth consent API operations
> removing EA flags from OAuth consent API operations

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Release notes for 2021.08.0
- **Is this PR related to a Monolith release?** Yes 2021.08.0
* [OKTA-416141](https://oktainc.atlassian.net/browse/OKTA-416141)
> Release notes for 2021.08.0

- packages/@okta/vuepress-site/code/oie/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/android/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-out/android/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/reference/api/captchas/index.md
- **What's changed?** updates per the Java SDK updates
> updates per the Java SDK updates

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/githubinstructions.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/overview/index.md
- **What's changed?** Minor typo updates to [Third-Party Risk Integration](https://developer.okta.com/docs/guides/third-party-risk-integration/overview/) page (link to Risk Providers) and to OIE Embedded Authentication guides for Node.js, [Download and Set up the SDK, Sign-In Widget, and Sample App](https://developer.okta.com/docs/guides/oie-embedded-common-download-setup-app/nodejs/main/): fixed an error in the git clone command for SDK.
* n/a
> Minor typo updates

- .travis.yml
- packages/@okta/vuepress-site/.vuepress/scripts/updateBuildScript.js
* Returns us to `medium` instances (free/included with our Travis plan)
* Updates build to use thread pool-like behavior (we actually discard and recreate threads) with a max number of pages per thread to limit memory usage
* We may want to use a real thread pool implementation library at some point to be even more efficient in the future
* [OKTA-417069](https://oktainc.atlassian.net/browse/OKTA-417069)
> Returns build configuration to use `medium` instances

- packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- **What's changed?** Add exp to Device Secret introspect endpoint in Native SSO flow
- **Is this PR related to a Monolith release?** Yes `2021.08.2`
* [OKTA-418639](https://oktainc.atlassian.net/browse/OKTA-418639)
> Add `exp` to Device Secret introspect endpoint in Native SSO flow

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
Include relevant content currently present on admin docs.
- This content is present on https://help.okta.com/oie/en-us/Content/Topics/identity-engine/oie-limitations.htm and needs to be included here as well :)
> Add "Self-Service Registration" section

- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/activate-and-enable/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/overview/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?** Added the changes to enable the registration inline hook guide for Okta Identity Engine.
* n/a
> Adding Identity Engine procedure for Registration Inline Hook Guide

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- packages/@okta/vuepress-site/docs/release-notes/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adding release notes for both Okta Identity Engine and Okta Classic for the weekly release.
- **Is this PR related to a Monolith release?** 2021.08.1
* [OKTA-417196](https://oktainc.atlassian.net/browse/OKTA-417196)
> Release 2021.08.1

- packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
- **What's changed?** "Fixed the JSON request in the "Register new client" POST example. Removed "refresh_token" from grant types because the current JSON request doesn't work." <br>
Re-created this PR from https://github.com/okta/okta-developer-docs/pull/2350 Thanks for original PR, @patrickjburke245 <br>
* n/a
> Update Dynamic Client Registration API reference

- packages/@okta/vuepress-site/docs/guides/email-customization/customize-email-templates/index.md
- Added a table and description to describe how functions can be used with Velocity
- This went live in 2021.07.1
* https://oktainc.atlassian.net/browse/OKTA-417381
> Add functions to email macros guide

- packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
- **What's changed?** Added client rate limit event type info to rate limit system log events
* [OKTA-416975](https://oktainc.atlassian.net/browse/OKTA-416975)
> Added OAuth2 client rate limit event type

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- Added favicon details for all variant definitions
- 2021.08.0 (already live)
https://oktainc.atlassian.net/browse/OKTA-420044
> Added favicon details

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Added entries for RN 2021.08.2
- **Is this PR related to a Monolith release?** Yes RN 2021.08.2
* [OKTA-419686](https://oktainc.atlassian.net/browse/OKTA-419686)
> Added RN 2021.08.2

- packages/@okta/vuepress-site/docs/concepts/hosted-vs-embedded/index.md
> Improve "Okta hosted vs Customer hosted" concept (part 2)

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-intro/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Okta Identity Engine Overview
* [OKTA-417578](https://oktainc.atlassian.net/browse/OKTA-417578)
> Okta Identity Engine Overview

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/oktatookta/appatidp.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/register-app-in-okta/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/prepare-app/index.md
- packages/@okta/vuepress-site/docs/guides/build-sso-integration/create-your-app/openidconnect/create.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/create-oauth-app/index.md
- packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/configure-oidc-native-apps/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/create-okta-application/index.md
- **What's changed?** Updated prod doc link to alias and changed page heading in the cross-ref
- **Is this PR related to a Monolith release?**No 
* [OKTA-396431](https://oktainc.atlassian.net/browse/OKTA-396431)
> Updated link and page heading in the cross-reference

- packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
- **What's changed?** Fixing a link in the Redirect Auth page.
* n/a
> Updating Social Identity Provider Settings link in Redirect Auth page

- package.json
- yarn.lock
* [OKTA-334549](https://oktainc.atlassian.net/browse/OKTA-334549)
> Upgrade mocha package

- packages/@okta/vuepress-theme-prose/components/Sidebar.vue
* [OKTA-419134](https://oktainc.atlassian.net/browse/OKTA-419134)
* [OKTA-419090](https://oktainc.atlassian.net/browse/OKTA-419090)
> Fix sidebar expanding issue and lose focus issue

- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- **What's changed?** Adding Risk Integration API collection to Postman Collection page
* n/a
> Adding Risk API collection to Postman Collection page

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Release note entry for 2021.08.3
- **Is this PR related to a Monolith release?** Yes, 2021.08.3
* [OKTA-421699](https://oktainc.atlassian.net/browse/OKTA-421699)
> Rn entry 2021.08.3

- packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md
- packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/primary-authentication/ios/primaryauth.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/configure-the-sdk/blazorwebasm/config.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/go/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/php/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/python/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/require-authentication/go/reqautheverything.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/require-authentication/go/reqauthspecific.md
- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/go/accesstoken.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** Made more URL code style updates
* [OKTA-416575](https://oktainc.atlassian.net/browse/OKTA-416575)
> URL Code Style Consistency Updates

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** I added the sample conditional expressions included in the Jira issue (note, the link to the Jira issue below is correct. I accidentally included the parent Jira issue number in the branch name). Also, I tweaked some of the formatting on the page to align with the style guide. For example, the use of sentence case in headings, the non-capitalization of common nouns.
* [OKTA-79984](https://oktainc.atlassian.net/browse/OKTA-79984)
> OKTA-417619 Updates to EL page

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Add Release Notes entries
- **Is this PR related to a Monolith release?** Yes, Release Notes 2021.09.0
* [OKTA-423533](https://oktainc.atlassian.net/browse/OKTA-423533)
> Adding RN entries

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- Add "Subscriptions" nav menu item to be visible
- Subscriptions API will be available on monolith release
- `2021.09.0` 
- [OKTA-411537](https://oktainc.atlassian.net/browse/OKTA-411537)
@alifatolahi-okta @nateyocom-okta @susanharper-okta
> Add "Subscriptions" nav menu item to Okta Core API

- packages/@okta/vuepress-site/docs/guides/submit-app/submission1-general/index.md
Changes to the OIN Manager includes a new way to add support information for customers.
Yes. 2021.09.0
* [OKTA-420487](https://oktainc.atlassian.net/browse/OKTA-420487)
> Update Support Contact info in OIN Submission Guide

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
OKTA-421213 dev docs for dynamic issuer mode
- **dev docs for dynamic issuer mode** 
- **Is this PR related to a Monolith release? Yes 2021.09.0** 
* [OKTA-421213](https://oktainc.atlassian.net/browse/OKTA-421213)
> OKTA-421213 dev docs for dynamic issuer mode

- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/scim/submit.md
Updates on Group Patch Batch Size text (OKTA-392453)
Change to UI reflected in reference guide instructions
Yes. 2021.09.0
* [OKTA-422274](https://oktainc.atlassian.net/browse/OKTA-422274)
> Updates to OIN submission guide

- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- API reference for Online Access
* [OKTA-412286](https://oktainc.atlassian.net/browse/OKTA-412286)
- Primary reviewers: @yuliu-okta @susanharper-okta 
- Secondary reviewers: @okta/federations
> API reference for Online Access

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- **What's changed?** adding limitations and note on custom sign-in page
> adding limitations and note on custom sign-in page

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- **What's changed?** adding limitations and note on custom sign-in page
> Revert "adding limitations and note on custom sign-in page"

- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
Reverts okta/okta-developer-docs#2391
> Revert "API reference for Online Access"

- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/submission1-general/index.md
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adding Release Notes for 2021.09.0
- **Is this PR related to a Monolith release?** Yes, Release Notes 2021.09.0
* [OKTA-423533](https://oktainc.atlassian.net/browse/OKTA-423533)
> Release 2021.09.0

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
Reverts okta/okta-developer-docs#2524
> Revert "Revert "adding limitations and note on custom sign-in page""

- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/go/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/go/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/java/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-basic-sign-in/nodejs/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/go/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/java/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-load/nodejs/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/go/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/go/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/java/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-cases/oie-embedded-widget-use-case-sign-in-soc-idp/nodejs/summaryofsteps.md
- **What's changed?** embedded widget use case updates
* [OKTA-421030](https://oktainc.atlassian.net/browse/OKTA-421030)
> embedded widget use case updates

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- **What's changed?** Received the wrong link yesterday
> fixing hoc link

- packages/@okta/vuepress-site/docs/guides/oie-intro/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/activate-and-enable/index.md
- packages/@okta/vuepress-site/docs/release-notes/index.md
- **What's changed?** A few straggling engine naming nits.
* [OKTA-425097](https://oktainc.atlassian.net/browse/OKTA-425097)
> OKTA-425097

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-basic-sign-in/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-pwd-recovery-mfa/ios/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-self-reg/ios/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-email/ios/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-pwd-phone/ios/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/ios/summaryofsteps.md
Updated headings for the Swift/IOS sections per the JIRA ticket
* [OKTA-423081](https://oktainc.atlassian.net/browse/OKTA-423081)
> Okta 423081 master self reg swift rework

- packages/@okta/vuepress-site/code/android/index.md
Adding a useful blog post resource Mikel (and @mraible) put together as I noticed this page was lacking in some Kotlin resources.
No
> Add useful blog guide

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/use-flow.md
- **What's changed?** Create a new PR to re-start Travis. Fixes a typo from this PR: https://github.com/okta/okta-developer-docs/pull/2471
* n/a
> Creating new PR for PR-2471

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/apple/appatidp.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/register-app-in-okta/index.md
Added required steps for a developer setting up sign-in with apple, user needs to update a configuration within the apple developer portal
- no
* https://oktainc.atlassian.net/browse/OKTA-393028
> Update to sign in with apple

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/aspnet/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/java/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/nodejs/summaryofsteps.md
- **What's changed?** Self-registration heading updates
> Self-registration heading updates

- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/scim/submit.md
Adding information to the OIN app integration submission instructions > SCIM settings, concerning Group membership PATCH operation timeouts.
No
*  [OKTA-426400](https://oktainc.atlassian.net/browse/OKTA-426400).
> fixing OKTA-426400

- packages/@okta/vuepress-theme-prose/global-components/DeveloperDayBanner.vue
- **What's changed?** Updated developer day banner to point to YouTube playlist.
* [OKTA-425628](https://oktainc.atlassian.net/browse/OKTA-425628)
> Update Developer Day banner

- packages/@okta/vuepress-site/docs/guides/email-customization/customize-email-templates/index.md
App context is now available so adding details about the 3 available app macros. This is now available in all velocity email templates to call app context from the OIE state token
- Live as of 2021.09.0
* https://oktainc.atlassian.net/browse/OKTA-250595
> App context macros

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- Add a note for `scope` size limitation while request includes `offline_access` scope
* [OKTA-423280](https://oktainc.atlassian.net/browse/OKTA-423280)
> Add note for scope size limitation while requesting offline_access

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- **What's changed?** updating wording per LARS
> updating wording per LARS

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Added redirects for some deprecated Identity Engine pages that were combined and reorganized; including other redirects from weekly analytic sheets.
Staging server is updated to confirm: https://vuepress-site.trexcloud.com/docs/
* n/a
> Updates to conductor.yaml file for redirects

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding release notes for 2021.09.2
- **Is this PR related to a Monolith release?** Yes. 2021.09.2
* [OKTA-427510](https://oktainc.atlassian.net/browse/OKTA-427510)
> Rn entry 2021.09.2

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
RESOLVES OKTA-385098
- **What's changed?** Remove audience param from v1 authn
- **Is this PR related to a Monolith release?** Yes, Release 2021.09.2, https://github.com/okta/okta-core/pull/56750
* [OKTA-385098](https://oktainc.atlassian.net/browse/OKTA-385098)
@okta/idx @iancorcoran-okta @petermiller-okta @okta/developerdocs please review
> Remove audience param from v1 authn

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** Added endpoints to the SMS and Call rate limits section
* [OKTA-428184](https://oktainc.atlassian.net/browse/OKTA-428184)
> Updates to the Rate Limit SMS Endpoint List

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
Reverts okta/okta-developer-docs#2569
> Revert "Updates to the Rate Limit SMS Endpoint List"

- packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- **What's changed?** Adding Release Notes 2021.09.3
- **Is this PR related to a Monolith release?** Yes, Release Notes 2021.09.3
* [OKTA-428572](https://oktainc.atlassian.net/browse/OKTA-428572)
> Release Note Entry 2021.09.3

- packages/@okta/vuepress-theme-prose/assets/css/components/_homePage.scss
- packages/@okta/vuepress-theme-prose/components/Home.vue
* [OKTA-428170](https://oktainc.atlassian.net/browse/OKTA-428170)
> Removes "authenticate up to 15k users" subheading on Home

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** Added verification info
* [OKTA-428184](https://oktainc.atlassian.net/browse/OKTA-428184)
> Added Verify Rate Limit Info

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- **What's changed?** Fix heading link
- **Is this PR related to a Monolith release?** Yes 2021.09.3
> Fixed OIE RN heading link

- packages/@okta/vuepress-site/docs/reference/api/risk-providers/index.md
fixed formatting for Risk Provider example
> fixed formatting for Risk Provider example

- packages/@okta/vuepress-site/code/oie/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/java/integrationsteps.md
- **What's changed?** Style edits to OIE embedded guide and fixed broken link from SDK landing page.
* [OKTA-413125](https://oktainc.atlassian.net/browse/OKTA-413125)
> OKTA-413125 Edit oie embedded content part2, fixed broken link

- packages/@okta/vuepress-site/docs/reference/index.md
Correcting from 'Advance Service Access' to 'Advance Server Access'
- Correcting from 'Advance Service Access' to 'Advance Server Access'
> Correcting ASA Title

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- **What's changed?** Release note entries for 2021.09.4
- **Is this PR related to a Monolith release?** Yes, 2021.09.4
* [OKTA-430690](https://oktainc.atlassian.net/browse/OKTA-430690)
> Release Note entries for 2021.09.4

- packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-claims/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/add-custom-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/create-app-profile-attribute/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Small tweaks to my recent EL merge to align it with the style guide.
- 
* [OKTA-433357](https://oktainc.atlassian.net/browse/OKTA-433357)
> OKTA-433357 Updates to align with style guide

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Creating PR on behalf of Ian and Gabriel. Formatting the relational operators so that they render properly.
* https://github.com/okta/okta-developer-docs/pull/2498
> Fix relational operators in EL for OIE

- packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/create-org/index.md
- **What's changed?** Updated details about org creation.
* [OKTA-430780](https://oktainc.atlassian.net/browse/OKTA-430780)
> OKTA 430780 update org creation details to reflect pricing changes

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
- Update examples for refresh token to use request body instead of query parameters 
> Update examples for refresh token to use request body instead of query parameters

- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Add 2021.10.0 release note items in API and OIE API RNs
- **Is this PR related to a Monolith release?** Yes, 2021.10.0
* [OKTA-432967](https://oktainc.atlassian.net/browse/OKTA-432967)
> Add 2021.10.0 release note items in API and OIE API RNs

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?**Added endpoints to the workforce multiplier list 
- **Is this PR related to a Monolith release?**Yes, Release 2021.10.0 
* [OKTA-433442](https://oktainc.atlassian.net/browse/OKTA-433442)
> Added endpoints to workforce multiplier list

- packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
- **What's changed?** Removed EA flag for /guides/configure-native-sso/ topic
- **Is this PR related to a Monolith release?** Yes, 2021.10.0
* [OKTA-428053](https://oktainc.atlassian.net/browse/OKTA-428053)
> Remove EA flag for Configure SSO for Native apps topic

- packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
- **What's changed?** Updated the Log per client mode info
- **Is this PR related to a Monolith release?** Yes, 2021.10.0
* [OKTA-427240](https://oktainc.atlassian.net/browse/OKTA-427240)
> Client-based rate limit mode info update

- packages/@okta/vuepress-theme-prose/components/Home.vue
> remove 15k MAU

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **What's changed?** Document updating Authenticators `PUT /api/v1/authenticators/{id}`
* [OKTA-431104](https://oktainc.atlassian.net/browse/OKTA-431104)
> Document updating Authenticators `PUT /api/v1/authenticators/{id}`

- packages/@okta/vuepress-site/docs/concepts/interaction-code/index.md
Fixed typo in interaction code graphic 
No
> Typo in interaction code graphic

- packages/@okta/vuepress-site/docs/guides/mfa/main/ga/enrollfactor.md
- packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
- packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md
- **What's changed?** Fix broken links in MFA single-page guide
> Fix broken links in MFA guide

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** redirects for external idp
* [OKTA-442255](https://oktainc.atlassian.net/browse/OKTA-442255)
> Sdh redirectfix

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding release notes for 2021.11.0
- **Is this PR related to a Monolith release?** Yes. Release notes 2021.11.0
* [OKTA-441565](https://oktainc.atlassian.net/browse/OKTA-441565)
> Rn entry 2021.11.0

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- **What's changed?** Updates to Event Hook daily limits
- **Is this PR related to a Monolith release?** 2021.11.0
* [OKTA-434532](https://oktainc.atlassian.net/browse/OKTA-434532)
> Updating Event Hook daily limit to 200K from 100K - two locations

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
Update to branding docs for contrast color auto-detection
2021.11
* [OKTA-426715](https://oktainc.atlassian.net/browse/OKTA-426715)
> OKTA-426715: Update to branding docs for contrast color auto-detection

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- **What's changed?** adding sessionToken limitation during upgrade
* [OKTA-443007](https://oktainc.atlassian.net/browse/OKTA-443007)
> sessionToken oie limitations add

- packages/@okta/vuepress-site/docs/guides/custom-error-pages/use-macros/index.md
- packages/@okta/vuepress-site/docs/guides/style-the-widget/style-okta-hosted/index.md
- **What's changed?** Adding macros related to THEME_BUILDER
- **Is this PR related to a Monolith release?** Yes. 2020.11.0
* [OKTA-440888](https://oktainc.atlassian.net/browse/OKTA-440888)
> porting over Arsalan's changes to a new PR

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/ios/addsdk.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/ios/langspecificmapguide.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/ios/minimumrequirements.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/ios/sdksforauthflows.md
- Added swift content to the *Add the Identity Engine SDK to your app" doc
* [OKTA-425729](https://oktainc.atlassian.net/browse/OKTA-425729)
> Napa docs2 add sdk to your app swift

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/index.md
- **What's changed?** adding new link to product upgrade overview
- **Is this PR related to a Monolith release?** Napa
> adding new link to product

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/customize-themes/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/main/index.md
- packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/session-and-persistent-sso/ios/enablesso.md
- **What's changed?** I previously converted https://developer.okta.com/docs/guides/create-an-api-token/main/ to a single page guide in https://github.com/okta/okta-developer-docs/pull/2635, but the redirects were not correctly implemented, and I wanted to check for any broken links. This PR fixes those.
* [OKTA-438715](https://oktainc.atlassian.net/browse/OKTA-438715)
> fixing redirects and broken links for create-an-api-token

- packages/@okta/vuepress-site/docs/guides/email-customization/customize-email-templates/index.md
- **What's changed?** Removed mention of feature flag in the Enhanced Email Macros section. Update contact support blurb.
> Remove mention of feature flag from Enhanced Email Macros

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-deprecated-methods/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-i18n/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-styling/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- **What's changed?** Added nutrition facts to SIW docs
* [OKTA-407996](https://oktainc.atlassian.net/browse/OKTA-407996)
> Added nutrition facts to SIW docs

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-deprecated-methods/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-i18n/main/index.md
- **What's changed?** Corrected code block & added guide summary above nutrition facts
> Updates to SIW docs

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** fixing redirects
- **Is this PR related to a Monolith release?** nope
* [OKTA-438747](https://oktainc.atlassian.net/browse/OKTA-438747)
> fixing redirects

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Add RN 2021.11.1 entry
- **Is this PR related to a Monolith release?** Yes, Release Note 2021.11.1
* [OKTA-443918](https://oktainc.atlassian.net/browse/OKTA-443918)
> Add Release Note 2021.11.1 entry

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/define-route.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/react/define-route.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/define-route.md
- **What's changed?** "our" to "the"
* [OKTA-445542](https://oktainc.atlassian.net/browse/OKTA-445542)
> OKTA-445542 Changing "our" to "the"

- packages/@okta/vuepress-site/code/library-versions/index.md
- packages/@okta/vuepress-site/code/nodejs/index.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/next-steps/nodeexpress/samples.md
- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/nodejs/accesstoken.md
- **What's changed?**  jwt-verifier-js GH links updated
* [OKTA-415301](https://oktainc.atlassian.net/browse/OKTA-415301)
> chore: update jwt-verifier-js links

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/schemas.json
- packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
Resolves: OKTA-435191
- Log Streaming and Log Streaming Schemas APIs dev docs
- **Is this PR related to a Monolith release?** Yes, 2021.11.01
* [OKTA-435191](https://oktainc.atlassian.net/browse/OKTA-435191)
> OKTA-435191: Log Streaming API dev docs

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/apple/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/facebook/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/google/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/linkedin/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/microsoft/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/idpaccount.md
- **What's changed?** fixing duplicate period
> removing period from snippet

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/java/addsdk.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-planning-embedded-upgrades/index.md
- **What's changed?** Add link to Interaction Code grant type guide from the Napa overview and planning guides.
> Add Interaction Code grant type link to the Napa docs

- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
- **What's changed?** fixing overview to fit with nut facts
> fixing overview to fit with nut facts

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/ios/addsdk.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth-vs-oie.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/auth.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/mfaauth.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/pswrvy.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/aspnet/signout.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth-vs-oie.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/auth.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/mfaauth.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/pswrvy.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/sample.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/signout.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/ios/upgrade.md
- Implemented upgrade/mapping guide for Swift
- Tweaks to upgrade/mapping guide for .Net (including feedback from Indranil)
- Deploy link: https://618beede6524ed5053d6c7eb--reverent-murdock-829d24.netlify.app/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/ios/main/
* [OKTA-425737](https://oktainc.atlassian.net/browse/OKTA-425737)
* [OKTA-445046](https://oktainc.atlassian.net/browse/OKTA-445046)
> Napa docs2 upgrade sdk ios swift

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- **What's changed?** Updated to include Brian's comments
> Minor Fixes to RN 2021.11.1

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
OKTA-445342 - Enhance device developer docs to include/exclude attribute
Note section -
- **What's changed?**  Enhance device developer docs to include/exclude attribute
* [OKTA-445342](https://oktainc.atlassian.net/browse/OKTA-445342)
> OKTA-445342 - Enhance device developer docs to include/exclude attribute

- packages/@okta/vuepress-site/docs/reference/api/asa/introduction/index.md
- **What's changed?** Updated ASA rate limiting section
* [OKTA-446295](https://oktainc.atlassian.net/browse/OKTA-446295)
> Updated rate limiting section

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-api-sdk-to-oie-sdk/main/android/pswrvy.md
- **What's changed?** minor change to trigger build
- **Is this PR related to a Monolith release?** Napa
> minor change to trigger build

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** tweaks
* N/A
> TBS Custom URL

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Add 2021.11.2 release note entries
- **Is this PR related to a Monolith release?** Yes, 2021.11.2
* [OKTA-445807](https://oktainc.atlassian.net/browse/OKTA-445807)
> 2021.11.2 release note entries

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
- packages/@okta/vuepress-site/docs/guides/session-cookie/index.md
- packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
- **What's changed?** multi to single for session cookie
* [OKTA-438744](https://oktainc.atlassian.net/browse/OKTA-438744)
> multi to single for session cookie

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-deprecated-methods/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-i18n/main/index.md
- **What's changed?** Small fixes to my Napa docs.
* [OKTA-447602](https://oktainc.atlassian.net/browse/OKTA-447602)
> OKTA-447602 fixes issues with TBS Napa docs

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-out/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/java/integrationsteps.md
- **What's changed?** Remove links to specific lines in the IDX Java SDK (GitHub). The Java IDX SDK was refactored, so the links to specific lines in the file are not appropriate anymore.
* [OKTA-447672](https://oktainc.atlassian.net/browse/OKTA-447672)
> OKTA-447672 Remove links to specific lines in the Java IDX SDK

- .github/PULL_REQUEST_TEMPLATE.md
- packages/@okta/vuepress-site/docs/guides/quickstart/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/admin-notifications/index.md
- **What's changed?** URL for the subscription of a User with a specific type
> Fix URL for user subscriptions

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
- packages/@okta/vuepress-site/docs/guides/session-cookie/index.md
- packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
- **What's changed?** Session Cookie multi to single
* [OKTA-438744](https://oktainc.atlassian.net/browse/OKTA-438744)
> Session Cookie multi to single

- packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
The configure-signon-policy had a sample code n/a in the nut facts. I've removed it as per latest guidelines.
> Updating nut facts for configure-signon-policy

- packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
This guide is nicely-converted to single page, but there was a Sample code n/a in the nut facts, which we'd agreed to remove as per the latest guidelines. This PR fixes that.
> Update nut fact in request-user-consent guide

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/main/index.md
- **What's changed?** https://github.com/okta/okta-developer-docs/pull/2801 updated https://developer.okta.com/docs/guides/sign-into-mobile-app/android/main/ so that it has working redirects and better nut facts. This PR builds on that, to update stack selectors and nut fact sample code to the latest guidelines we agreed on.
> updating nut facts sample code and stack selectors to agreed guidelines

- packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/nodeexpress/reqautheverything.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/nodeexpress/reqauthspecific.md
- **What's changed?** Update the Express API quickstart guide to updated sdk usages and better match code samples so devs have a better experience getting going.
- **Is this PR related to a Monolith release?** No, I don't think so
* No Jira ticket yet.
> update code example to remove extra curly brace

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding release notes for 2021.11.3
- **Is this PR related to a Monolith release?** Yes. 2021.11.3
* [OKTA-448198](https://oktainc.atlassian.net/browse/OKTA-448198)
> RN entry 2021.11.3

- packages/@okta/vuepress-site/docs/reference/api/threat-insight/index.md
- **What's changed?** Update ThreatInsight configuration api with standardized ISO timestamps
- **Is this PR related to a Monolith release?** 2021.11.3
* [OKTA-445365](https://oktainc.atlassian.net/browse/OKTA-445365)
> Update ThreatInsight configuration api with standardized ISO timestamps

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
adding data migration scenario for end user dashboard variant
* [OKTA-449713](https://oktainc.atlassian.net/browse/OKTA-449713)
> OKTA-449713: adding data migration scenario for end user dashboard variant

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/nodeexpress/configmid.md
Without appBaseUrl the example code is not working.
> Added appBaseUrl for NodeJS-Express initial config

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/nodeexpress/configmid.md
- **What's changed?** Added a missing config prop to Express quickstart guide so a developer successfully creates an authenticated app.
* No Jira ticket created (yet).
> update the express instruction to include missing config property

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/config.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/define-route.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/getuserinfo.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/handle-callback.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/login-redirect.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/reqauthspecific.md
- **What's changed?** Update the Vue quickstart guide to use Vue 3, updated sdk usages, and better match code samples so devs have a better experience getting going.
- **Is this PR related to a Monolith release?** No, I don't think so
* No Jira ticket yet
> update vue quickstart instructions

- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Release Notes entry 2021.12.0
- **Is this PR related to a Monolith release?** Release Notes entry 2021.12.0
* [OKTA-451228](https://oktainc.atlassian.net/browse/OKTA-451228)
> Rn entry 2021.12.0

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- Added steps for EA release of "Custom Domains with Okta-Managed Certificates"
https://user-images.githubusercontent.com/49454026/144483935-129ef17e-5a96-4f7c-8aed-02c57703e729.mov
- 2021.12.0 Self-Service EA for both Classic and OIE
* https://oktainc.atlassian.net/browse/OKTA-443472
* https://oktainc.atlassian.net/browse/OKTA-447974
> okta-managed certs guide

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/schemas.json
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
Resolves: OKTA-439999
- Adding a Log Streaming Schemas API endpoint to list all schemas visible to org
- Update as per Azhar: 2021.12.0
* [OKTA-439999](https://oktainc.atlassian.net/browse/OKTA-439999)
> OKTA-439999: List Log Streaming Schemas

- packages/@okta/vuepress-site/docs/reference/api/org/index.md
- **What's changed?** deprecating org logo API
- **Is this PR related to a Monolith release?** 2021.12.0
* [OKTA-432207](https://oktainc.atlassian.net/browse/OKTA-432207)
> OKTA-432207: deprecating org logo API

- packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
- **What's changed?** Updated concurrent rate limit per client
* [OKTA-452049](https://oktainc.atlassian.net/browse/OKTA-452049)
> Updated maximum concurrent rate limit per client

- packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** update config.js file to add /oie-upgrade-mfa-enroll-policy/ to hidden Google list
* [OKTA-431926](https://oktainc.atlassian.net/browse/OKTA-431926)
> Update hidden Google list for /oie-upgrade-mfa-enroll-policy/ 

- packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
- **What's changed?** Fixing em dashes and two stray StackSelector tags that were incorrect
> fixes while I was there

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
On Authenticators API page (https://developer.okta.com/docs/reference/api/authenticators-admin/) replace `HIGH_RISK_ALWAYS` with `HIGH_RISK_ONLY`
* [OKTA-444823](https://oktainc.atlassian.net/browse/OKTA-444823)
> Change `HIGH_RISK_ALWAYS` -> `HIGH_RISK_ONLY`

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
- **What's changed?** @janethu-okta noticed that the redirects were not implemented correctly for https://developer.okta.com/docs/guides/mfa/ga/main/. This PR aims to fix that. While I was there, I also took the time to fix the stack selectors and nut facts to the latest agreed guidelines.
- Redirects tested on staging, 12/3/21. Redirects work as expected.
> fixing redirects for the mfa guide

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/android/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/ios/configlocations.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/ios/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/ios/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/ios/softwarerequirements.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/redirecturi.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-limitations/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md
- **What's changed?** Implemented edit suggestions from Chris in OKTA-452180. Changed StackSelector to StackSnippet element in /oie-embedded-common-download-setup-app/main/index.md and /oie-embedded-common-refresh-tokens/main/index.md
* [OKTA-452180](https://oktainc.atlassian.net/browse/OKTA-452180)
> OKTA-452180 further Tuscany edits

- packages/@okta/vuepress-site/docs/concepts/monitor/index.md
- packages/@okta/vuepress-site/docs/guides/identity-providers/index.md
- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-planning-embedded-upgrades/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/github/noemail.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- packages/@okta/vuepress-site/docs/reference/api/features/index.md
- packages/@okta/vuepress-site/docs/reference/api/threat-insight/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?** Updating a selection of hard-coded references to help.okta.com with appropriate aliases.
* [OKTA-452755](https://oktainc.atlassian.net/browse/OKTA-452755)
> Updating references to hoc with aliases

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/android/runsdkapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/android/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/aspnet/runsdkapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/aspnet/runwidgetapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/aspnet/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/go/runsdkapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/go/runwidgetapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/go/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/ios/runsdkapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/ios/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runsdkapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runwidgetapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/nodejs/runsdkapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/nodejs/runwidgetapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/nodejs/samplecode.md
- **What's changed?** Update nutrition facts for /oie-common-org-setup/ and /oie-embedded-common-run-samples/ pages, as well as fixing some stack selector links.
* [OKTA-452179](https://oktainc.atlassian.net/browse/OKTA-452179)
> OKTA-452179 Tuscany nut facts cleanup for org-setup/ and run-samples/ pages

- packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md
- packages/@okta/vuepress-site/docs/concepts/saml/faqs/index.md
- packages/@okta/vuepress-site/docs/concepts/scim/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
- **What's changed?** Reviewed and updated a selection of cross-references to ensure accuracy.
* [OKTA-430421](https://oktainc.atlassian.net/browse/OKTA-430421)
> OKTA-430421 - Review and update selection of cross-references

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
- **What's changed?** Fix one broken link on Implement OAuth for Okta Guide
* n/a
> Fix one broken link on Implement OAuth for Okta Guide

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Add release note entry for 2021.12.1
- **Is this PR related to a Monolith release?** Yes, 2021.12.1
* [OKTA-452953](https://oktainc.atlassian.net/browse/OKTA-452953)
> Add 2021.12.1 release note entry

- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
QR code support is added back to device flow docs.
- **Is this PR related to a Monolith release?**  2021.12.1
* [OKTA-453140](https://oktainc.atlassian.net/browse/OKTA-453140)
> QR code support is added back to device flow docs.

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/android/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/ios/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/samplecode.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/android/refreshusingthesdk.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/aspnet/introspectendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/aspnet/refreshendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/aspnet/refreshusingthesdk.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/go/introspectendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/go/refreshendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/go/refreshusingthesdk.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/ios/refreshusingthesdk.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/java/introspectendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/java/refreshendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/java/refreshusingthesdk.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/nodeexpress/introspectendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/nodeexpress/refreshendpointrequest.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-refresh-tokens/main/nodeexpress/refreshusingthesdk.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-limitations/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/main/android/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/main/java/integrationsteps.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Clean up nutrition facts for: "Download and set up the SDK, Sign-In Widget, and sample app", "Refresh the access and ID tokens". Update title for "Limitations" doc.
* [OKTA-452179](https://oktainc.atlassian.net/browse/OKTA-452179)
> OKTA-452179 cleanup nutrition facts for Tuscany

- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding Release Notes for 2021.12.1
- **Is this PR related to a Monolith release?** Yes, 2021.12.1
* [OKTA-452953](https://oktainc.atlassian.net/browse/OKTA-452953)
> Release Notes for 2021.12.1

- packages/@okta/vuepress-site/docs/guides/index.md
- **What's changed?** Updates to Guides overview to clean up merge conflict
* n/a
> Updated Guides overview page

- packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
- **What's changed?** Added a column for Inline Hook values that are required for the `amr` object, which differ from other requests.
* [OKTA-434916](https://oktainc.atlassian.net/browse/OKTA-434916)
> OKTA-434916 Updates to Sessions API amr object table

- packages/@okta/vuepress-site/docs/guides/index.md
- **What's changed?** TEST - Updating two links on Guide Overview
* n/a
> Staging Test - Branch 1

- packages/@okta/vuepress-site/docs/guides/index.md
> Added changes to first two links and last two links

- packages/@okta/vuepress-site/docs/guides/index.md
- **What's changed?** TEST - merging to staging with multiple conflicts
* n/a
> Updating the same links to create multiple merge conflicts

- packages/@okta/vuepress-site/docs/guides/customize-themes/index.md
- **What's changed?** Added nut facts to page
> Added nut facts

- packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md
- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- **What's changed?** Added nut facts to Device Authorization Grant and Native SSO
> Added nutrition facts

- packages/@okta/vuepress-site/docs/guides/submit-app/main/saml2/submit.md
- **What's changed?** Add SLO app instance properties as per OKTA-455770
- **Is this PR related to a Monolith release?** Yes, 2022.01.0
- https://61c410e71a1060306db6d448--reverent-murdock-829d24.netlify.app/docs/guides/submit-app/saml2/main/#protocol-specific-settings
* [OKTA-455770](https://oktainc.atlassian.net/browse/OKTA-455770)
> OKTA-455770 Add AIPS to OIN SAML SLO questions

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adding new 2022 release notes for first monthly, including new left-hand nav categories.
- **Is this PR related to a Monolith release?** 2022.01.0
* [OKTA-456601](https://oktainc.atlassian.net/browse/OKTA-456601)
> Release Notes for 2022.01.0 monthly release

- packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
- packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md
- packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/main/index.md
- packages/@okta/vuepress-site/docs/guides/find-your-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/main/index.md
- packages/@okta/vuepress-site/docs/guides/saml-tracer/main/index.md
- packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/main/index.md
- packages/@okta/vuepress-site/docs/guides/sharing-cert/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/main/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- packages/@okta/vuepress-site/docs/guides/updating-saml-cert/main/index.md
- **What's changed?** Review nutritional facts in Basics section of the Guides
* [OKTA-456109](https://oktainc.atlassian.net/browse/OKTA-456109)
> Review nutritional facts in Guides > Basics

- packages/@okta/vuepress-site/docs/guides/event-hook-ngrok/main/nodejs/sample-app.md
- **What's changed?** Fixing a Hook Guide missing HTML tag in code sample
* n/a
> Added missing html tag for Event Hooks with ngrok Guide

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
- packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/blazorwebasm/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/react/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/vue/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/aspnet/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/aspnetcore3/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/go/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/nodeexpress/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/php/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/python/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/springboot/samplecode.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
* [OKTA-456111](https://oktainc.atlassian.net/browse/OKTA-456111)
> Reviewed Nutrition Facts in Sign Users In section

- packages/@okta/vuepress-site/docs/guides/social-login/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- **What's changed?** Fixed typo.
- **Is this PR related to a Monolith release?** Nope. Nein. Non.
* N/A
> Fixes typo in social IdP page description

- packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
- packages/@okta/vuepress-site/docs/guides/revoke-tokens/main/index.md
- packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
- packages/@okta/vuepress-site/docs/guides/validate-id-tokens/main/index.md
- **What's changed?** Reviewed nutrition facts in Authorization section
* [OKTA-456161](https://oktainc.atlassian.net/browse/OKTA-456161)
> Reviewed nutrition facts for Authorization section in Guides

- packages/@okta/vuepress-site/docs/guides/mfa/main/index.md
- **What's changed?** There was a typo, and the intro paragraph was in heading format rather than body text. This change fixes those.
> Fixing typo and intro para

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adds release notes for 2022.01.1
- **Is this PR related to a Monolith release?** Yes, 2022.01.1
* [OKTA-458445](https://oktainc.atlassian.net/browse/OKTA-458445)
> TBS - 2022.01.1 merge notes into release branch

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-sms-messaging/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/android/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/angular/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/aspnet/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/aspnetcore3/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/ios/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/nodeexpress/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/react-native/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/react/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/springboot/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/vue/samplecode.md
- **What's changed?** Review nutrition facts
* [OKTA-457722](https://oktainc.atlassian.net/browse/OKTA-457722)
> Reviewed nutrition facts in Brand and Customize section of Guides

- packages/@okta/vuepress-site/code/dotnet/aspnet/index.md
- packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/sign-in-method.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/sign-in-method.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/sign-in-method.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/sign-in-method.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/sign-in-method.md
- **What's changed?** Fixes a typo found in several places — ODIC to OIDC
* [OKTA-459376](https://oktainc.atlassian.net/browse/OKTA-459376)
> fix typo ODIC

- packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Fix some erroneous public permission names.
Also, fix a typo in some of the JSON request examples.
* [OKTA-451288](https://oktainc.atlassian.net/browse/OKTA-451288)
> Correct the userprofile permission name

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
For the Administrator Roles API, correct some invalid JSON in the request body and an inaccurate response body.
- **Is this PR related to a Monolith release?** **No**
* [OKTA-456827](https://oktainc.atlassian.net/browse/OKTA-456827)
> Fix response of Admin Roles Add More Resources operation

- packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta-prerequisites/main/index.md
- **What's changed?** Reviewed nutrition facts
* [OKTA-457724](https://oktainc.atlassian.net/browse/OKTA-457724)
> Reviewed nutrition facts in Guides > Deploy to Production

- packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- **What's changed?** Update OAuth to support refresh tokens for SPAs
* [OKTA-456460](https://oktainc.atlassian.net/browse/OKTA-456460)
> OKTA-456460 Update OAuth to support refresh tokens for SPAs

- packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
Resolves: OKTA-459553
- Fixing json payloads in example curl commands
* [OKTA-459553](https://oktainc.atlassian.net/browse/OKTA-459553)
> OKTA-459553: Fixing example curl payloads

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Removed a reference to radius and replaced RADIUS VPN with LDAP API 
See https://oktainc.atlassian.net/browse/OKTA-435837 for more details.
- **What's changed?**  Removed references to RADIUS
* https://oktainc.atlassian.net/browse/OKTA-435837
> Removed references to RADIUS

- packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md
- **What's changed?** Add multi-tenant solution link to Okta organization > multi-org section
* [OKTA-461282](https://oktainc.atlassian.net/browse/OKTA-461282)
> OKTA-461282 Add multi-tenant link to Okta multi-org

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- Updating Postman collection to add `SSWS` in the auth scheme for Devices API in Authorization header
- **Is this PR related to a Monolith release?** - NO
* [OKTA-456537](https://oktainc.atlassian.net/browse/OKTA-456537)
> Fixing API header token auth scheme

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- **What's changed?** Fix org sign-up page to go to OIE page
* [OKTA-460712](https://oktainc.atlassian.net/browse/OKTA-460712)
> Fix links to go to OIE sign-up page

- packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-ngrok/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/githubinstructions.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/android/integrationsteps.md
- **What's changed?** Fix invalid languages
> Fix invalid languages as reported by VuePress

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/main/index.md
> removing EA flags for refresh token rotation that went GA in May 20221

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** -- For Forgot password API, 'Any enrolled MFA factor' option is supported for IDX Pipeline 
- **Is this PR related to a Monolith release?**  - OKTA-452933 (In production release 2022.01.0) 
* [OKTA-453950](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)
> Updated forgot password api to add support for Any enrolled MFA 453950

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Fixes typo in a new note in Users API docs. Also converts h's to sentence case (but not Okta objects).
* N/A
> TBS Fixes typo in Users API

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **Is this PR related to a Monolith release?** Yes. 2022.01.2
* [OKTA-460422](https://oktainc.atlassian.net/browse/OKTA-460422)
> Rn entry 2022.01.2

- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- **What's changed?** Added roles that can access RL dashboard
* [OKTA-464358](https://oktainc.atlassian.net/browse/OKTA-464358)
> Added roles that can access RL dashboard

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release Notes for 2022.01.2
- **Is this PR related to a Monolith release?** Yes. 2022.01.2
* [OKTA-460422](https://oktainc.atlassian.net/browse/OKTA-460422)
> Release 2022.01.2

- packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
- packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/android/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/ios/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/main/index.md
- packages/@okta/vuepress-theme-prose/global-components/EmbeddedBrowserWarning.vue
- **What's changed?** I've added a global component that inserts a warning note against using embeddedbrowsers/webviews for authentication, and used this component in a few places where it would be prudent to display that note.
* [OKTA-462331](https://oktainc.atlassian.net/browse/OKTA-462331)
> add in warnings against using web views/embedded browsers
