packages/@okta/migrate-from-jekyll/index.js
packages/@okta/vuepress-site/conductor.yml

Adds correct spacing for conductor file.

Update conductor spacing

---

packages/@okta/vuepress-site/.vuepress/config.js
packages/@okta/vuepress-theme-default/layouts/Layout.vue
packages/@okta/vuepress-theme-default/layouts/Quickstart.vue
packages/@okta/vuepress-theme-default/layouts/SectionIndex.vue

Updates the headers to show the anchor link on hover.

Updates the header links

---

packages/@okta/vuepress-theme-default/layouts/Layout.vue
packages/@okta/vuepress-theme-default/layouts/Quickstart.vue
packages/@okta/vuepress-theme-default/layouts/SectionIndex.vue

Removes outbound icon link

---

packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md
packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
packages/@okta/vuepress-site/conductor.yml
packages/@okta/vuepress-site/quickstart-fragments/java/generic-implicit/index.md
packages/@okta/vuepress-site/quickstart-fragments/java/spring-auth-code/index.md
packages/@okta/vuepress-site/quickstart-fragments/java/spring-implicit/index.md
packages/@okta/vuepress-site/quickstart-fragments/okta-sign-in-page/default-example/index.md
packages/@okta/vuepress-site/quickstart-fragments/widget/default-example/index.md
packages/@okta/vuepress-theme-default/global-components/ApiOperation.vue

Triage from Migration

---

packages/@okta/vuepress-site/test_page/index.md
packages/@okta/vuepress-theme-default/components/TableOfContents.vue

- Fixes a table that was malformed in test_page
- expands ToC when on mobile

Ghost inspector fixes

---

packages/@okta/vuepress-site/.vuepress/enhanceApp.js

see github.com/vuejs/vuepress/issues/1173

Removes patch for un-loaded components

---

packages/@okta/vuepress-site/authentication-guide/generic-oidc/index.md

notes didn't have the correct formatting.

fix note style

---

packages/@okta/vuepress-site/docs/api/resources/oidc/index.md

note on browser redirect for logout and authorize endpoints
https://oktainc.atlassian.net/browse/OKTA-202702

note on browser redirect for logout and authorize endpoints

---

packages/@okta/vuepress-site/reference/okta_expression_language/index.md

Added pre-column for rows that have only examples and output in order to fix the layout of the table and not overlap with the sidebar menu.

Okta Expression Language - String Functions layout fix

---

packages/@okta/vuepress-site/docs/api/resources/oauth-clients/index.md
packages/@okta/vuepress-site/docs/api/resources/policy/index.md

This fixes the reported broken tables.   
Additional work on tables needs to be done.  See #71

Fixes reported broken tables

---

packages/@okta/vuepress-site/docs/api/getting_started/design_principles/index.md
packages/@okta/vuepress-site/docs/api/resources/sessions/index.md
packages/@okta/vuepress-site/docs/api/resources/users/index.md
packages/@okta/vuepress-theme-default/global-components/SupportsCors.vue

Update old Liquid tag api_cors

---

packages/@okta/vuepress-theme-default/global-components/EventTypes.vue

Trying to solve an issue reported in #78 
This is working locally fine as well as on netlify.
The only thing that I notice is that the console.log causes a slow-down

Remove a console.log

---

packages/@okta/vuepress-site/conductor.yml

Adds server side redirects

---

packages/@okta/vuepress-plugin-my-okta/clientRootMixin.js

This plugin was causing issues due to how it was swapping out content on the page.
Doing so was breaking how some of the vuepress functionality was working.
As a side-effect, we no longer have to disable this plugin for anything but developer.okta.com
This is an attempt to resolve the issue #78

Updates my_okta plugin

---

.travis.yml

* The configuration for slack notifications was using the old config for okta.github.io, which wouldn't work
* Created a new integration on slack and updated the config here

Updates slack notifications configuration

---

packages/@okta/vuepress-plugin-my-okta/clientRootMixin.js

This is an attempt to fix the issue that was reported about event_types page search not working
The issue was caused by the content replacement of my-okta domain swapping
See: #78

Update my okta fix event types

---

packages/@okta/vuepress-site/docs/api/resources/factor_admin/index.md

After testing locally it looks better inline.

Visual fix

---

packages/@okta/vuepress-site/standards/SAML/setting_up_a_saml_application_in_okta/index.md

Fixes broken image link

---

packages/@okta/vuepress-site/.vuepress/config.js
packages/@okta/vuepress-site/.vuepress/enhanceApp.js

Prevent Preloading of all pages

---

packages/@okta/vuepress-plugin-my-okta/clientRootMixin.js

doesn't replace the last slash of the domain swap

---

packages/@okta/vuepress-site/docs/change-log/2019-03-2/index.md
packages/@okta/vuepress-site/docs/change-log/2019-03-3/index.md

Adding missing RN entry, also fixing typo

---

packages/@okta/vuepress-site/.vuepress/config.js
packages/@okta/vuepress-site/.vuepress/nav/codePages.js
packages/@okta/vuepress-site/.vuepress/nav/main.js
packages/@okta/vuepress-theme-default/components/Sidebar.vue

Moves sidebar defs into config files.
resolves #69

Change default sidebar to config file

---

packages/@okta/vuepress-site/conductor.yml

Attempting to set-up a redirect 
from: https://developer.okta.com/docs/how-to/set-up-auth-server
to: https://developer.okta.com/authentication-guide/implementing-authentication/set-up-authz-server/

Attempting to add redirect

---

packages/@okta/vuepress-site/docs/api/getting_started/rate-limits/index.md

Resolves: OKTA-213882
@okta/eng-perf

Fixed the discrepancies in rate limits of shared buckets

---

.github/PULL_REQUEST_TEMPLATE.md

Creating PR template

---

packages/@okta/vuepress-plugin-active-header-links/clientRootMixin.js
packages/@okta/vuepress-theme-default/layouts/Layout.vue

- Updates the offset-top for active header links as well as anchor links to mimic what was happening
resolves #122

Updates the values for the header links

---

packages/@okta/vuepress-theme-default/layouts/Layout.vue

updates query selector to ignore quickstart links

---

packages/@okta/vuepress-site/.vuepress/config.js
packages/@okta/vuepress-theme-default/components/Code.vue
packages/@okta/vuepress-theme-default/components/EditLink.vue
packages/@okta/vuepress-theme-default/components/Page.vue

- Adds edit link to Page and Code component
* resolves #91

Adds edit page link

---

packages/@okta/vuepress-theme-default/components/StackSelector.vue
packages/@okta/vuepress-theme-default/layouts/Guides.vue

fix(guides): Fixes scrolling issue on StackSelector tab change

---

packages/@okta/vuepress-site/code/library-versions/index.md

Update node SDK versions on libraries page

---

packages/@okta/vuepress-theme-default/global-components/EventTypes.vue

Adds better searching for event types
Searches all properties of the object now 
Adds history pushstate for the query as well.
Resolves #162

Event type search and query param

---

packages/@okta/vuepress-site/docs/api/resources/authn/index.md

- **What's changed?** Fixing bad Support link, bad Users link, and changing Help link to use alias.
* I'm faster than Jira

Fixing bad links

---

packages/@okta/vuepress-theme-default/global-components/FrameworkIconBlock.vue
packages/@okta/vuepress-theme-default/util/frameworks.js

Fixes the listed titles for NET Core; fixes the omission of React Native on the Featured Guides; fixes the missing NodeJS Icon; updates the list of titles for all currently supported icons.
Guides WIP

fix(guides): Updates framework icon options

---

packages/@okta/vuepress-site/docs/api/resources/authn/index.md

- **What's changed?** Added explanation related to resend push notification endpoint. Push notification response contains resend URL in case of timeout/rejection but explanation is missing currently.
* [OKTA-213500](https://oktainc.atlassian.net/browse/OKTA-213500)

Added explanation for resend push notification endpoint

---

packages/@okta/vuepress-site/docs/api/resources/policy/index.md

- **What's changed?**  Majority of the links that exist in the Policy API docs do not work. This PR fixes the anchors to use the correct element ids.
* [OKTA-219223](https://oktainc.atlassian.net/browse/OKTA-219223)

fix links in the policy API docs

---

packages/@okta/vuepress-site/use_cases/inline_hooks/token_hook/token_hook/index.md

Closes https://github.com/okta/okta-developer-docs/pull/182

Fix token inline hooks instructions

---

packages/@okta/vuepress-site/.vuepress/config.js

- **What's changed?**  Updates header links for Support and removes domain from others.
resolves #185

Updated header links

---

packages/@okta/vuepress-site/docs/api/resources/authn/index.md

- **Update the API doc to mention that If an API token is not provided, the deviceToken will be ignored.
** 
- **Is this PR related to a Monolith release? NO**
* [OKTA-211233](https://oktainc.atlassian.net/browse/OKTA-211233)

OKTA-211233 : Update doc related to deviceToken and API token

---

packages/@okta/vuepress-site/use_cases/event_hooks/index.md

- Conceptual overview of Event Hooks.
- Event Hooks functionality is  currently targeted for EA release in 2019.04.0.
* [OKTA-209169](https://oktainc.atlassian.net/browse/OKTA-209169)

Event Hooks Overview

---

packages/@okta/vuepress-site/docs/change-log/2019-04-0/index.md

change log for april monthly

---

packages/@okta/vuepress-site/use_cases/event_hooks/index.md

Conceptual overview of Event Hooks.
Event Hooks functionality is currently targeted for EA release in 2019.04.0.
Resolves:
OKTA-209169

Mk okta 209169 event hooks concept

---

packages/@okta/vuepress-site/reference/error_codes/index.md

Not sure where else this might present itself but the LDAPi references it in response to a failed attempt to connect using password concatenated with OTP
- **What's changed?** Adds an entry for Error code E0000068 - This error code is encountered when an incorrect passcode/answer is provided during an authentication request.
I encountered this error message with the LDAP Interface.  I am not sure where else it might present itself.
No open JIRA or GH Ticket, it resolves itself #188 i can open an issue on this project if required but it seems superfluous.

Add entry for E0000068

---

packages/@okta/vuepress-site/code/dotnet/okta-oauth-aspnet-codeflow/index.md
packages/@okta/vuepress-site/code/dotnet/okta-oauth-spa-authjs-osw/index.md
packages/@okta/vuepress-site/code/dotnet/okta-oidc-spa-osw-aspnet/index.md
packages/@okta/vuepress-site/conductor.yml
packages/@okta/vuepress-site/test_page/index.md

- **What's changed?** Removes files that are handled by conductor.yml  The redirects that were happening with the `github_url` frontmatter were not carried over to VuePress.
* [OKTA-218303](https://oktainc.atlassian.net/browse/OKTA-218303)

Cleans up some un-necessary code/dotnet files

---

packages/@okta/vuepress-site/guides/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/before-you-begin/index.md
packages/@okta/vuepress-theme-default/components/GuidesNavigation.vue
packages/@okta/vuepress-theme-default/components/GuidesOverview.vue

- **What's changed?** 100% less lorem ipsum on the guides overview page, and other fixes to match the mocks
* Things that annoyed Nate
* https://oktainc.atlassian.net/browse/OKTA-219919

Small wording fixes

---

packages/@okta/vuepress-theme-default/assets/css/okta/pages/guides.scss

* Forces guides nav width to be consistent (it occasionally changed when stackselector choice changed
* No
* [OKTA-218633](https://oktainc.atlassian.net/browse/OKTA-218633)

Guides nav width

---

packages/@okta/vuepress-site/code/ios/index.md

Link to the new samples repo for iOS

Update iOS sample application link

---

packages/@okta/vuepress-site/quickstart-fragments/dotnet/aspnet4-auth-code/index.md

Fixed a typo in .NET quickstart.
No
* [OKTA-218187](https://oktainc.atlassian.net/browse/OKTA-218187)

Fix typo in .NET quickstart.

---

packages/@okta/vuepress-site/code/android/index.md

This needs to point to our new sample application repo

Update link to android samples

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** adds redirect and removes duplicate
* OKTA-221187

Adds redirect for /standards/OAuth/

---

packages/@okta/vuepress-site/conductor.yml

Trying to force Conductor to work

Okta 221187

---

packages/@okta/vuepress-site/docs/api/getting_started/rate-limits/index.md

- **What's changed?** Updating url to be /api/v1/authn/factors/{factorIdOrFactorType}/verify instead of /api/v1/authn/factors/{factorId}/verify
* [OKTA-221134](https://oktainc.atlassian.net/browse/OKTA-221134)

update url to /api/v1/authn/factors/{factorIdOrFactorType}/verify

---

packages/@okta/vuepress-site/reference/scim/index.md

deleted the other tags and references to the Beta for the other Group Push methods:
* GET
* PUT
* PATCH
* DELETE

delete Beta tags and references for other methods

---

packages/@okta/vuepress-site/authentication-guide/implementing-authentication/auth-code-pkce/index.md
packages/@okta/vuepress-site/code/ios/index.md
packages/@okta/vuepress-site/code/library-versions/index.md
packages/@okta/vuepress-site/docs/change-log/2018-14/index.md
packages/@okta/vuepress-site/use_cases/api_access_management/index.md

Updating the links for our new libs, plus some copy edits

Update new iOS lib URLs

---

packages/@okta/vuepress-site/guides/sign-into-mobile-app/before-you-begin/android/create-app.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/check-for-tokens/android/checkfortoken.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/check-for-tokens/index.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/configure-packages/android/configuremid.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/configure-packages/android/installsdk.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/configure-the-callback/android/configurescheme.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/get-user-info/android/getinfo.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-in-page/android/signin.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/use-access-token/android/usetoken.md

Add Android specific content
* [OKTA-216989](https://oktainc.atlassian.net/browse/OKTA-216989)

Add Andoid specific content

---

packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/inline-hooks.json
packages/@okta/vuepress-site/docs/api/resources/inline-hooks/index.md
packages/@okta/vuepress-site/reference/postman_collections/index.md

Removed the method property from the channel config in the request body of inline hooks.
Resolves: OKTA-221543
- **Removed the method property from the channel config in the request body of inline hooks.**
* [OKTA-221543](https://oktainc.atlassian.net/browse/OKTA-221543)

Removed the method property from the channel config in the request body

---

packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/event-hooks.json
packages/@okta/vuepress-site/docs/api/getting_started/rate-limits/index.md
packages/@okta/vuepress-site/reference/postman_collections/index.md

Resolves: OKTA-216896
- **Adding a postman collection for event hooks.**
->
* [OKTA-216896](https://oktainc.atlassian.net/browse/OKTA-216896)

Adding a postman collection for event hooks.

---

packages/@okta/vuepress-site/.vuepress/nav/main.js
packages/@okta/vuepress-site/docs/api/resources/event-hooks/index.md
packages/@okta/vuepress-site/docs/api/resources/inline-hooks/index.md

- This change is intended for monolith release 2019.04.1
- Add Event Hooks API Management Doc
- Fix some issues in Inline Hooks API Management Doc, such as adding missing lifecycle operations
* [OKTA-219029](https://oktainc.atlassian.net/browse/OKTA-219029)

Add Event Hooks API Doc

---

packages/@okta/vuepress-site/standards/SAML/setting_up_a_saml_application_in_okta/index.md

Removing extra period

---

packages/@okta/vuepress-site/.vuepress/nav/main.js
packages/@okta/vuepress-site/use_cases/event_hooks/index.md

- **What's changed?** Minor fixes to the Event Hooks documentation, as listed in the Jira item.
* [OKTA-221895](https://oktainc.atlassian.net/browse/OKTA-221895)

Event Hooks doc minor fixes

---

packages/@okta/vuepress-site/guides/sign-into-web-app/configure-packages/aspnet/configmid.md
packages/@okta/vuepress-site/guides/sign-into-web-app/configure-packages/aspnetcore/configmid.md
packages/@okta/vuepress-site/guides/sign-into-web-app/get-user-info/aspnet/getuserinfo.md
packages/@okta/vuepress-site/guides/sign-into-web-app/get-user-info/aspnetcore/getuserinfo.md
packages/@okta/vuepress-site/guides/sign-into-web-app/redirect-to-sign-in/aspnet/login-redirect.md
packages/@okta/vuepress-site/guides/sign-into-web-app/redirect-to-sign-in/aspnetcore/login-redirect.md
packages/@okta/vuepress-site/guides/sign-into-web-app/require-authentication/aspnet/reqauthspecific.md
packages/@okta/vuepress-site/guides/sign-into-web-app/require-authentication/aspnetcore/reqautheverything.md
packages/@okta/vuepress-site/guides/sign-into-web-app/require-authentication/aspnetcore/reqauthspecific.md

* Update all .NET examples and make sure all code samples start with ```csharp.
* Expand getuserinfo.md to show examples of accessing claims in both controllers and views.
No

Polish for .NET Web guides

---

README.md
package.json

Moving authoring info to wiki, and adding links

---

README.md
package.json
packages/@okta/vuepress-site/docs/api/resources/authn/index.md

Update `guides` with latest `master` once again. No guides content was harmed in the making of this PR.

Update guides with master (part tres)

---

packages/@okta/vuepress-site/docs/api/resources/apps/index.md
packages/@okta/vuepress-site/docs/api/resources/users/index.md

- **What's changed?** Removing docs for retracted Beta 
* N/A

Removing doc for retracted beta

---

packages/@okta/vuepress-site/documentation/index.md

Fixing bad link

---

packages/@okta/vuepress-site/authentication-guide/tokens/validating-access-tokens/index.md

Fix broken links and improve text

---

packages/@okta/vuepress-site/docs/change-log/2019-04-2/index.md

- **What's changed?** Adding change log entry for 2019.04.2
- **Is this PR related to a Monolith release?** Yes, 2019.04.2

Change log entry for 2019.04.2

---

packages/@okta/vuepress-site/docs/change-log/2019-04-2/index.md

- **What's changed?** Removing trailing slash from link

Fixing broken link

---

packages/@okta/vuepress-site/reference/okta_expression_language/index.md

fix table format

---

packages/@okta/vuepress-site/guides/sign-into-spa/configure-the-sdk/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/create-okta-application/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/define-callback/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/handle-callback/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/next-steps/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/require-authentication/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/use-the-access-token/index.md
packages/@okta/vuepress-site/guides/sign-into-web-app/configure-packages/index.md
packages/@okta/vuepress-site/guides/sign-into-web-app/create-okta-application/index.md
packages/@okta/vuepress-site/guides/sign-into-web-app/define-callback/aspnet/define-route.md
packages/@okta/vuepress-site/guides/sign-into-web-app/define-callback/aspnetcore/define-route.md
packages/@okta/vuepress-site/guides/sign-into-web-app/define-callback/springboot/define-route.md
packages/@okta/vuepress-site/guides/sign-into-web-app/get-user-info/index.md
packages/@okta/vuepress-site/guides/sign-into-web-app/next-steps/index.md
packages/@okta/vuepress-site/guides/sign-into-web-app/redirect-to-sign-in/aspnet/login-redirect.md
packages/@okta/vuepress-site/guides/sign-into-web-app/redirect-to-sign-in/aspnetcore/login-redirect.md
packages/@okta/vuepress-site/guides/sign-into-web-app/redirect-to-sign-in/springboot/login-redirect.md

Removes some links that don't work right now (replaced with TODOs). We can fix these after OKTA-224075. Having these is not blocking for publishing MVP.

Fix guide links

---

packages/@okta/vuepress-site/code/library-versions/index.md
packages/@okta/vuepress-site/docs/api/resources/users/index.md
packages/@okta/vuepress-site/reference/okta_expression_language/index.md

Update guides from master

---

package.json
packages/@okta/vuepress-site/guides/sign-into-mobile-app/before-you-begin/iOS/create-app.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/check-for-tokens/iOS/checkfortoken.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/configure-packages/iOS/configuremid.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/configure-packages/iOS/installsdk.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/get-user-info/iOS/getinfo.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/next-steps/iOS/samples.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-in-page/iOS/signin.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/use-access-token/iOS/usetoken.md

Added sign-in guide for iOS OIDC SDK
* [OKTA-216988](https://oktainc.atlassian.net/browse/OKTA-216988)

OKTA-216988-Sign-users-in guide content for iOS

---

package.json
packages/@okta/vuepress-site/guides/sign-into-mobile-app/index.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-out-page/android/signout.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-out-page/iOS/signout.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-out-page/index.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-out-page/reactnative/signout.md

Android sign-out guide.
Added a section sign-out-page. Not sure if we want to put this with sign-in-page.
* [OKTA-220642](https://oktainc.atlassian.net/browse/OKTA-220642)

Android sign-out guide

---

packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-out-page/iOS/signout.md

* [OKTA-220641](https://oktainc.atlassian.net/browse/OKTA-220641)

OKTA-220641-Sign-out guide content for iOS

---

packages/@okta/vuepress-site/docs/change-log/2019-05-0/index.md

- **What's changed?** Adding entry for 2019.05.0
- **Is this PR related to a Monolith release?** Yes, 2019.05.0

Adding entry for 2019.05.0

---

packages/@okta/vuepress-site/code/php/simplesamlphp/index.md

SAML guidance link has been moved and the existing link is broken. 
New link should be: https://www.okta.com/integrate/documentation/single-sign-on/
No
* no JIRA, manually found and fixed this issue.

Fix broken link to "SAML Guidance"

---

packages/@okta/vuepress-site/conductor.yml
packages/@okta/vuepress-site/docs/api/resources/event-hooks/index.md

- **What's changed?** Adding python redirect and link to event hooks postman collection

Feedback fixes

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Just trying to get the redirect working...

Specifying index dot html

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Redirecting `/change-log/` to `/release-notes/`

Adding redirect

---

packages/@okta/vuepress-site/conductor.yml

Trying two more redirect strategies

---

packages/@okta/vuepress-site/conductor.yml

Trying to get redirect working

---

tests/selenium/framework/page-objects/TableOfContentsPage.js
tests/selenium/framework/shared/util.js
tests/selenium/spec/table-of-contents-spec.js

- Add hash link scroll test
* [OKTA-218834](https://oktainc.atlassian.net/browse/OKTA-218834)

add hash link scroll test

---

packages/@okta/vuepress-site/docs/api/resources/inline-hooks/index.md

- **What's changed?** Fixed a typo.

Fixing typo

---

packages/@okta/vuepress-site/authentication-guide/implementing-authentication/auth-code/index.md
packages/@okta/vuepress-site/authentication-guide/implementing-authentication/password/index.md

- **fixing link label and link to correct location (Client Authentication Methods)?** 

fixing link label and link to correct location

---

packages/@okta/vuepress-site/authentication-guide/implementing-authentication/auth-code/index.md
packages/@okta/vuepress-site/authentication-guide/implementing-authentication/password/index.md

- **adding back in slash for link going to client authentication method section** 

adding back in slash

---

packages/@okta/vuepress-site/docs/release-notes/2019-05-0/index.md
packages/@okta/vuepress-site/docs/release-notes/2019-05-1/index.md

- **What's changed?** It's the release notes entry for the 2019.05.1 release.
- **Is this PR related to a Monolith release?** Yes! That's the whole point!
* N/A

Rn entry 2019.05.1 (#346)

---

packages/@okta/vuepress-site/docs/api/resources/oidc/index.md

- **Linking client authentication method section to new add app examples** 
* N/A

linking client authentication method to new add app examples

---

packages/@okta/vuepress-site/docs/api/resources/idps/index.md

- **Fixed the broken link for the Add SAML IdP?** 
* [OKTA-227233](https://oktainc.atlassian.net/browse/OKTA-227233)

broken link to add saml idp

---

packages/@okta/vuepress-site/docs/release-notes/2019-05-1/index.md

- **What's changed?** Adding missing RN item
- **Is this PR related to a Monolith release?** Definitely

Adding new RN item

---

packages/@okta/vuepress-site/docs/api/resources/oidc/index.md

- **What's changed?** Clarifying description of Okta Org VS Custom AuthZ server.
* [OKTA-210980](https://oktainc.atlassian.net/browse/OKTA-210980)

Updating descriptions of two different kinds of AuthZ servers

---

packages/@okta/vuepress-site/guides/sign-into-mobile-app/sign-in-page/iOS/signin.md

- Fixes 'swfit' to 'swift' in markdown formatting
- No
- No associated JIRA/issue

fix(guides): Corrects typo in markdown formatting

---

packages/@okta/vuepress-site/code/android/index.md
packages/@okta/vuepress-site/use_cases/api_access_management/index.md
packages/@okta/vuepress-site/use_cases/authentication/index.md
packages/@okta/vuepress-site/use_cases/event_hooks/index.md
packages/@okta/vuepress-site/use_cases/events-api-migration/index.md
packages/@okta/vuepress-site/use_cases/inline_hooks/index.md
packages/@okta/vuepress-site/use_cases/mfa/index.md
packages/@okta/vuepress-site/use_cases/relationships/index.md

Better meta descriptions for SEO

---

packages/@okta/vuepress-site/docs/api/resources/oidc/index.md

- **What's changed?** The wording could be clearer

Tweaking wording

---

packages/@okta/vuepress-site/.vuepress/scripts/build-guides-info.js

- Adds section & guide info to page title
- No
* [OKTA-221733](https://oktainc.atlassian.net/browse/OKTA-221733)

feat(guides): Adds section & guide info to page title

---

packages/@okta/vuepress-site/.vuepress/scripts/build.sh
packages/@okta/vuepress-site/.vuepress/scripts/strip-guide-parts-from-sitemap.js
packages/@okta/vuepress-site/package.json
yarn.lock

- Removes guides fragments from sitemap
- No
* [OKTA-223585](https://oktainc.atlassian.net/browse/OKTA-223585)

fix(guides): Removes guides fragments from sitemap

---

packages/@okta/vuepress-site/docs/api/resources/oidc/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/add-signin-button/angular/login-redirect.md
packages/@okta/vuepress-site/guides/sign-into-spa/configure-the-sdk/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/create-okta-application/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/define-callback/angular/define-route.md
packages/@okta/vuepress-site/guides/sign-into-spa/define-callback/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/handle-callback/angular/handle-callback.md
packages/@okta/vuepress-site/guides/sign-into-spa/handle-callback/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/require-authentication/angular/reqauthspecific.md
packages/@okta/vuepress-site/guides/sign-into-spa/use-the-access-token/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/use-the-access-token/react/getaccesstoken.md
packages/@okta/vuepress-site/guides/sign-into-spa/user-info/angular/getuserinfo.md

* Changes to angular guide after completing [OKTA-220639](https://oktainc.atlassian.net/browse/OKTA-220639)

Updates to the angular guide

---

packages/@okta/vuepress-site/.vuepress/scripts/build-guides-info.js
packages/@okta/vuepress-theme-default/layouts/Guides.vue

- Allows a guide w/o a StackSelector
- Adds no-specified framework in url for SSR
- No
* [OKTA-225381](https://oktainc.atlassian.net/browse/OKTA-225381)
* [OKTA-227332](https://oktainc.atlassian.net/browse/OKTA-227332)

fix(guides): Allows guides w/o frameworks

---

packages/@okta/vuepress-site/docs/release-notes/2019-05-2/index.md

- **Release Notes 2019-05-2** 
* N/A

Adding new rn entry

---

packages/@okta/vuepress-site/docs/api/resources/oidc/index.md

- **Reworded a sentence, added a missing closing paren?** 
* [OKTA-159469](https://oktainc.atlassian.net/browse/OKTA-159469)

edit and typo

---

packages/@okta/vuepress-site/authentication-guide/social-login/google/index.md

Update step num during google social login setup
No

Update step num during google social login setup

---

packages/@okta/vuepress-site/docs/release-notes/2019-05-2/index.md

- **Release Notes 2019-05-2** 
* N/A

Release 2019.05.2

---

packages/@okta/vuepress-site/use_cases/mfa/index.md

- **What's changed?** Title captures it perfectly.

Removing outdated video and dead tweet

---

packages/@okta/vuepress-site/guides/protect-your-api/configure-packages/index.md
packages/@okta/vuepress-site/guides/sign-into-mobile-app/configure-packages/index.md
packages/@okta/vuepress-site/guides/sign-into-spa/configure-the-sdk/index.md
packages/@okta/vuepress-site/guides/sign-into-web-app/configure-packages/index.md

- **Updated the Org Domain line in multiple guides to reference the **Org URL** to help users find it** 
* N/A

updating the Org Domain line in multiple guides

---

packages/@okta/vuepress-site/guides/custom-url-domain/enable-the-custom-domain/index.md
packages/@okta/vuepress-site/guides/custom-url-domain/gather-information/index.md
packages/@okta/vuepress-site/guides/custom-url-domain/overview/index.md
packages/@okta/vuepress-site/guides/custom-url-domain/update-other-okta-settings/index.md

- **Updates to doc from Wils review** 
* N/A

Wils review comments addressed

---

packages/@okta/vuepress-site/docs/api/resources/oidc/index.md

Added a note to /keys and /.well-known endpoints that the data returned is eventually consistent.
Details for the product change: https://oktainc.atlassian.net/browse/OKTA-228562
- **Is this PR related to a Monolith release?** 2019.05.03
* [OKTA-229355](https://oktainc.atlassian.net/browse/OKTA-229355)

Added a note to /keys and /.well-known endpoints that the data returned is eventually consistent

---

packages/@okta/vuepress-site/docs/release-notes/2019-05-3/index.md

- **What's changed?** Adding release notes entry for this release.
- **Is this PR related to a Monolith release?** Yes, 2019.05.3

Release notes entry for 2019.05.3

---

packages/@okta/vuepress-site/docs/api/resources/zones/index.md

Reverts okta/okta-developer-docs#374

Added Dynamic Zone Support to api doc (Reverted)

---

packages/@okta/vuepress-site/docs/release-notes/2019-05-3/index.md
packages/@okta/vuepress-site/use_cases/inline_hooks/token_hook/token_hook/index.md

- **What's changed?** Weekly site update for the release.
- **Is this PR related to a Monolith release?** Yes, 2019.05.3

Weekly Docs Release 2019.05.3

---

packages/@okta/vuepress-site/conductor.yml

Trying to figure out how our redirects work. Also fixing a typo in an existing redirect.

Testing redirect

---

packages/@okta/vuepress-site/conductor.yml

Reverts okta/okta-developer-docs#391

Revert "Testing redirect"

---

packages/@okta/vuepress-site/conductor.yml

Redirect test

---

packages/@okta/vuepress-site/conductor.yml

Testing redirects contd

---

packages/@okta/vuepress-site/conductor.yml

Redirect test7

---

packages/@okta/vuepress-site/conductor.yml

Finalizing redirects. These should work.

---

packages/@okta/vuepress-site/docs/release-notes/2019-05-3/index.md

- **What's changed?** Adding preview fix to release notes for 2019.05.3 for issue with authorization with PKCE flow.
- **Is this PR related to a Monolith release?** Yes, 2019.05.3

Adding preview fix to release notes

---

packages/@okta/vuepress-site/guides/sign-into-spa/add-signin-button/vue/login-redirect.md
packages/@okta/vuepress-site/guides/sign-into-spa/before-you-begin/vue/create-app.md
packages/@okta/vuepress-site/guides/sign-into-spa/configure-the-sdk/vue/config.md
packages/@okta/vuepress-site/guides/sign-into-spa/define-callback/vue/define-route.md
packages/@okta/vuepress-site/guides/sign-into-spa/handle-callback/vue/handle-callback.md
packages/@okta/vuepress-site/guides/sign-into-spa/install-sdk/vue/installsdk.md
packages/@okta/vuepress-site/guides/sign-into-spa/next-steps/vue/samples.md
packages/@okta/vuepress-site/guides/sign-into-spa/require-authentication/vue/reqautheverything.md
packages/@okta/vuepress-site/guides/sign-into-spa/require-authentication/vue/reqauthspecific.md
packages/@okta/vuepress-site/guides/sign-into-spa/use-the-access-token/react/getaccesstoken.md
packages/@okta/vuepress-site/guides/sign-into-spa/use-the-access-token/vue/getaccesstoken.md
packages/@okta/vuepress-site/guides/sign-into-spa/user-info/vue/getuserinfo.md

- Adds Vue content for sign-into-spa guide
- No
* [OKTA-221193](https://oktainc.atlassian.net/browse/OKTA-221193)

feat[guides] Adds Vue content for sign-into-spa guide

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Adding redirects for two reported 404s

Adding redirects

---

packages/@okta/vuepress-site/docs/api/resources/idps/index.md

- **Fixed Links to Protocol Object and Property Object** 
* [OKTA-218059](https://oktainc.atlassian.net/browse/OKTA-218059)

fixed links

---

packages/@okta/vuepress-site/docs/release-notes/2019-06-0/index.md

- **What's changed?** RN entry for 2019.06.0 release
- **Is this PR related to a Monolith release?** Mos _def_

Adding entry for 2019.06.0

---

packages/@okta/vuepress-site/docs/api/resources/apps/index.md

- **What's changed?** Document risk for unassignment API
- **Is this PR related to a Monolith release?** 2019.06.0
* [OKTA-230648](https://oktainc.atlassian.net/browse/OKTA-230648)

Document risk for unassignment API

---

packages/@okta/vuepress-site/docs/release-notes/2017-23/index.md

Just a tiny change to poke Bacon.

Just a minor change

---

packages/@okta/vuepress-site/conductor.yml

Modifying redirect in conductor to get (hopefully) get it working.

Adding index dot html

---

packages/@okta/vuepress-site/conductor.yml

More redirect fixes

---

packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md
packages/@okta/vuepress-site/docs/guides/add-saml-idp/create-authz-url/index.md
packages/@okta/vuepress-site/docs/guides/custom-error-pages/index.md
packages/@okta/vuepress-site/docs/guides/custom-error-pages/use-macros/index.md
packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/overview/index.md
packages/@okta/vuepress-site/docs/guides/custom-url-domain/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md
packages/@okta/vuepress-site/docs/guides/federate-with-oidc/overview/index.md
packages/@okta/vuepress-site/docs/guides/federate-with-oidc/test-authz-url/index.md
packages/@okta/vuepress-site/docs/guides/find-your-domain/overview/index.md
packages/@okta/vuepress-site/docs/guides/implement-client-creds/use-flow/index.md

- **Fixes to broken links in guides section** 

link fixes

---

packages/@okta/vuepress-site/conductor.yml

Fixed indent

---

packages/@okta/vuepress-site/conductor.yml

Testing redirect fix. Will apply more generally if it works.

Trying to fix event-types redirect

---

packages/@okta/vuepress-site/conductor.yml

Adding version of all redirects created during migration without `/index.html`.

Adding all redirects, but without slash index html

---

packages/@okta/vuepress-site/.vuepress/scripts/yml-parse-check.js
packages/@okta/vuepress-site/package.json
packages/@okta/vuepress-theme-default/layouts/Guides.vue

- Adds a minimal check-to-confirm-conductor.yml-parses to prevent silent publish failures
- No

Br hat conductor yaml parse check

---

packages/@okta/vuepress-site/conductor.yml
packages/@okta/vuepress-theme-default/layouts/Guides.vue

- Adds redirects for guides pages that migrated from `/guides/*` to `/docs/guides/*`
- No

great migration of redirects

---

packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md

Fixing URL

---

packages/@okta/vuepress-site/docs/guides/protect-your-api/before-you-begin/springboot/create-app.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-cors/springboot/configcors.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-packages/springboot/independ.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/springboot/reqauthspecific.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/before-you-begin/springboot/create-app.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/index.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/springboot/addconfigpkg.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/springboot/configmid.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/define-callback/springboot/define-route.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/get-user-info/index.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/get-user-info/springboot/getuserinfo.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/springboot/login-redirect.md

Incorporating feedback from user feedback

Tweaking the Spring Boot sign in guide

---

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md

Rebased and squashed #409 post-migration

Improve expression language func reference

---

packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/send-test-request/index.md

Fix broken note

---

packages/@okta/vuepress-site/docs/guides/sign-into-spa/define-callback/index.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/define-callback/index.md

Fix broken links

---

packages/@okta/vuepress-site/docs/guides/sign-in-with-facebook/configure-idp/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-google/configure-idp/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-linkedin/configure-idp/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-microsoft/configure-idp/index.md

- Fixes inconsistencies in Social Login setup guide + specify where to configure an Identity Provider in the Developer Console and Classic UI.
* [OKTA-232350](https://oktainc.atlassian.net/browse/OKTA-232350)

Fixes inconsistencies in Social Login setup guides

---

packages/@okta/vuepress-site/docs/guides/custom-error-pages/customization-examples/index.md

- **Minor indentation issue that I forgot to correct earlier** 

code indentation issue

---

packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/use-macros-and-request-context/index.md

- **making macro pages the same in hosted sign in as it is in error pages** 

making macro pages the same in hosted sign in as it is in error pages

---

packages/@okta/vuepress-site/conductor.yml

- **Fixing redirect** 
* [OKTA-233028](https://oktainc.atlassian.net/browse/OKTA-233028)

redirect fix

---

packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md

Fixing missing letter "s" under Request Example for the following calls:
Activate Event Hook
Deactivate Event Hook
Delete Event Hook
Uppercase letter for: Channel Object, Config Object, AuthScheme Object, Events Object.
- **Is this PR related to a Monolith release?**:
No
* [OKTA-230097](https://oktainc.atlassian.net/browse/OKTA-230097)

Fixing typos

---

packages/@okta/vuepress-site/conductor.yml

- **adding blank line** 
* [OKTA-233028](https://oktainc.atlassian.net/browse/OKTA-233028)

adding blank line

---

packages/@okta/vuepress-site/conductor.yml

- Adds redirect carefully and maintaining the trailing newline
- No

fix(redirects): Adds oin-promotion redirect

---

packages/@okta/vuepress-site/.vuepress/nav/main.js

- **What's changed?** Adding an entry for the Event Hooks page to the Concepts TOC in the sidebar.

Adding Event Hooks to Concepts TOC

---

packages/@okta/vuepress-site/conductor.yml
packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/use-macros-and-request-context/index.md

- Adds redirect 
- No
* [OKTA-233028](https://oktainc.atlassian.net/browse/OKTA-233028)

Merge Redirects in staging to master

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- **Fixing anchor for Issue #477** 
* Issue #477

fixing anchor for Issue #477

---

packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/react/remotesignout.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-your-app/react/localsignout.md

Documents how to sign out of a React app.
* [OKTA-221202](https://oktainc.atlassian.net/browse/OKTA-221202)

Sign out (React)

---

packages/@okta/vuepress-site/docs/guides/custom-url-domain/update-other-okta-settings/index.md

- **Added information on updating application endpoints** 
* [OKTA-215471](https://oktainc.atlassian.net/browse/OKTA-215471)

added updating application endpoints

---

packages/@okta/vuepress-site/.vuepress/nav/main.js
packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md

- **new okta org concept guide** 
* [OKTA-220675](https://oktainc.atlassian.net/browse/OKTA-220675)

new okta org concept guide

---

packages/@okta/vuepress-site/docs/reference/api-overview/index.md

Removing redundant phrase
- **What's changed?** Removing redundant phrase.

Removing a redundant phrase in API Overview page

---

packages/@okta/vuepress-site/docs/reference/token-hook/index.md

- **What's changed?** Updated wording of intro paragraph to cover possibility of changing existing claims.

Updating intro wording

---

packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md

- **Fixed the GET API CRUD tag** 
* [OKTA-234539](https://oktainc.atlassian.net/browse/OKTA-234539)

fixed api crud tag

---

packages/@okta/vuepress-site/docs/release-notes/2019-06-3/index.md

- **What's changed?** Creating release notes entry.
- **Is this PR related to a Monolith release?** Yes, 2019.06.3

Creating release notes entry for 2019.06.3

---

packages/@okta/vuepress-site/docs/reference/token-hook/index.md

- **adding and modifying claims in objects and arrays** 
- **Is this PR related to a Monolith release?** Yes - release-2019.06.3
* [OKTA-233091](https://oktainc.atlassian.net/browse/OKTA-233091

adding and modifying claims in objects and arrays

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Adding redirect for factor administration page.
* [OKTA-234226](https://oktainc.atlassian.net/browse/OKTA-234226)

Adding redirect for Factor Administration page

---

packages/@okta/vuepress-site/docs/reference/token-hook/index.md
packages/@okta/vuepress-site/docs/release-notes/2019-06-3/index.md

- **What's changed?** Docs update for weekly release.
- **Is this PR related to a Monolith release?** Yes, 2019.06.3

Release 2019.06.3

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Fixing previously-added entry for factor administration page. Was missing the index.html at the end of the 'from:' statement.
* [OKTA-234226](https://oktainc.atlassian.net/browse/OKTA-234226)

Fixing previously added entry for factor administration.

---

packages/@okta/vuepress-site/code/python/pysaml2/index.md

- **fixing wrong link in pysaml2 doc** 
* [OKTA-235266](https://oktainc.atlassian.net/browse/OKTA-235266)

fixing wrong link in pysaml2 doc

---

packages/@okta/vuepress-site/code/library-versions/index.md

Update the Android SDK library versions.

Update android sdk library version

---

packages/@okta/vuepress-site/docs/release-notes/2019-06-3/index.md

subject verb agreement

---

packages/@okta/vuepress-site/docs/release-notes/2019-06-3/index.md

- **What's changed?** Adding item.
- **Is this PR related to a Monolith release?** Yes, 2019.06.3

Adding item retroactively to 2019.06.3 release notes

---

packages/@okta/vuepress-site/docs/guides/sign-in-with-linkedin/setup-app/index.md
packages/@okta/vuepress-site/docs/release-notes/2019-07-0/index.md

- **What's changed?** Adding RN entry for 2019.07.0 release, and removing notice about LinkedIn IDP creation being disabled.
- **Is this PR related to a Monolith release?** 100%

RN entry created

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Trying to get root-level redirects to work

Trying to get redirects working

---

packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/android/configuremid.md
packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/android/installsdk.md
packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/create-okta-application/index.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/android/remotesignout.md

Android mobile sign out guide.
Updated mobile sign in to fit with sign out.
* [OKTA-237211](https://oktainc.atlassian.net/browse/OKTA-237211)

Android mobile signout

---

packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md

- **What's changed?** add link to protect your apis guide and some other minor style tweaks
* [OKTA-210924](https://oktainc.atlassian.net/browse/OKTA-210924)

add link to protect your apis guide and some other minor style tweaks

---

packages/@okta/vuepress-site/docs/reference/scim/index.md

- **What's changed?** Updated page so that it is consistent with our normal API reference doc. This also fixes the misrendering headlines and broken nav links.
* #292

Updated SCIM Reference headings

---

packages/@okta/vuepress-site/code/react/okta_react/index.md

fix login button
- **What's changed?** fix login/logout buttons
* https://devforum.okta.com/t/okta-react-sample-does-not-work/2836/3

fix login/logout button

---

packages/@okta/vuepress-plugin-my-okta/clientRootMixin.js
packages/@okta/vuepress-theme-default/assets/css/okta.scss
packages/@okta/vuepress-theme-default/assets/css/okta/components/Tooltip.scss

- Adds title tooltip to {yourOktaDomain} before replacing
- Adds different title tooltip to {yourOktaDomain} after replacing
- adds polling to ensure replacement happens regardless of race conditions
- No
* [OKTA-222796](https://oktainc.atlassian.net/browse/OKTA-222796)

 feat: Adds abbr[title] to {yourOktaDomains}

---

packages/@okta/vuepress-site/docs/reference/api/factors/index.md

Overhaul the factors API reference page.
- **Is this PR related to a Monolith release?**  
NO
* [OKTA-227479](https://oktainc.atlassian.net/browse/OKTA-227479)

Overhaul the factors API reference page

---

packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md

- **What's changed?** Linking to new Event Hook setup guide from the Event Hooks concept page. Also, changing capitalization of mentions of the term Event Hooks.
* [OKTA-231340X](https://oktainc.atlassian.net/browse/OKTA-231340)

Links between event hook content

---

packages/@okta/vuepress-site/docs/guides/implement-password/overview/index.md

- **What's changed?** Clarifying guidance around when to use Resource Owner Password flow.

Clarifying recommendation

---

packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md

Removed an extra each in a statement.

Updated "Event Hooks" okta documentation

---

packages/@okta/vuepress-site/docs/guides/byo-saml/overview/index.md
packages/@okta/vuepress-site/docs/guides/index.md

**What's changed?** 
- modified Overview guide page URLs to point out to the new locations
- added BYO SAML guide under Guides in order to be displayed in the sidebar
**Is this PR related to a Monolith release?**
No

BYO SAML guide update

---

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
packages/@okta/vuepress-site/docs/reference/import-hook/index.md
packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
packages/@okta/vuepress-site/docs/reference/token-hook/index.md

- **What's changed?** Changing all mentions of the term 'Inline Hooks' to be capitalized.

Capitalizing the term Inline Hooks

---

packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md
packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md

- **What's changed?** Added more detail and emphasis to the requirements for a valid URI for an external service endpoint.
* [OKTA-238468](https://oktainc.atlassian.net/browse/OKTA-238468)

Adding info on valid URIs for external service endpoints

---

packages/@okta/vuepress-site/quickstart-fragments/nodejs/express-implicit/index.md
packages/@okta/vuepress-site/quickstart-fragments/nodejs/generic-implicit/index.md

- **What's changed?** NodeJS frameworks have been updated to include the audience when verifying the JWT token, in order to provide a clear and better code example.

Update for NodeJS quickguide to include audience for JWT verification

---

packages/@okta/vuepress-site/docs/release-notes/2019-07-0/index.md

- **What's changed?** Added hotfixed item.
- **Is this PR related to a Monolith release?** Yes, but to an old one.

Adding hotfixed item to entry

---

package.json
scripts/updateSeDrivers.sh
tests/selenium/conf.js
yarn.lock

Updates yarn.lock 

---

packages/@okta/vuepress-site/code/library-versions/index.md

Seems the date was in year 2010, thinking it would more logically be 2020

Date for PowerShell

---

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md

- **What's changed?** Minor style edit.

Inline Hooks - minor style edit

---

packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/mappings.json
packages/@okta/vuepress-site/docs/reference/api/mappings/index.md
packages/@okta/vuepress-site/docs/reference/postman-collections/index.md

- Adding documentation for the Public Mapping API endpoints: list Mappings, get Mapping, partial update Mapping. 
- Targeted for monolith release: 2019.08.0
* [OKTA-236299](https://oktainc.atlassian.net/browse/OKTA-236299)
@colinwang-okta @donwoods-okta @jakubvul-okta @okta/ud-core

documenting new Mappings API endpoints

---

packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/inline-hooks.json
packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
packages/@okta/vuepress-site/docs/reference/postman-collections/index.md

Resolves OKTA-240360: Inline Hooks postman collection missing list inline hooks by type
1. Adding new request Get InlineHooks By Type to the inline hooks postman collection.
2. Updating the postman collection link in the index.md
* [OKTA-240360](https://oktainc.atlassian.net/browse/OKTA-240360)
- @motikagan-okta @alexandrazhang-okta

Resolves OKTA-240360: Inline Hooks postman collection missing list inlineHooks by type

---

packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/jwt-with-private-key/js/createprivatekeyjwt.md
packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/jwt-with-shared-key/js/createclientsecretjwt.md

- Adds JS samples to building JWT guide
- No
* [OKTA-226946](https://oktainc.atlassian.net/browse/OKTA-226946)

feat(guides): Adds js code to building jwt guide

---

packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/configure-packages/android/installsdk.md
packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/retrieve-refresh-token/android/challenge.md
packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/retrieve-refresh-token/android/getnewaccesstoken.md
packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/store-tokens/android/storerefreshtoken.md

Android biometrics guide: Device authentication for private key access.
* [OKTA-231745](https://oktainc.atlassian.net/browse/OKTA-231745)

android biometrics guide

---

packages/@okta/vuepress-site/docs/release-notes/2019-08-0/index.md

- **What's changed?** Release Notes entry for 2019-08-0
- **Is this PR related to a Monolith release?** Yes 2019-08-0

Rn entry 2019.08.0

---

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md

- **What's changed?** Removing EA banner from Inline Hooks concepts page and management API reference page
- **Is this PR related to a Monolith release?** Yes, 2019.08.0, but targeting master for this pull request, because too late for inclusion in release branch.

Removing EA banner from Inline Hooks pages

---

packages/@okta/vuepress-theme-default/util/frameworks.js

- **What's changed?** Supports #589, with human-formatted provider names that will appear in the Stack Selector. 

Add IdP names as frameworks for guides

---

packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md

- **What's changed?** Adding an example of GET inlineHooks with type query parameter.

Adding example of GET /inlineHooks with type query parameter

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md

- **Is this PR related to a Monolith release?**  no - the monolith code has been released
* [OKTA-234459](https://oktainc.atlassian.net/browse/OKTA-234459)

Clear current user sessions API doc

---

packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
packages/@okta/vuepress-site/docs/guides/byo-saml/upload-the-certificate/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/add-list-of-groups/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/configure-custom-claim/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/create-groups-claim/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/get-group-ids/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/send-test-request/index.md

- **What's changed?** Typos and so on that I found while looking for other things in the docs 
N/A

typos and so on that I found while looking for other things in the docs

---

README.md
packages/@okta/vuepress-site/.vuepress/nav/codePages.js
packages/@okta/vuepress-site/code/python/index.md
packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
packages/@okta/vuepress-site/docs/guides/byo-saml/upload-the-certificate/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/add-list-of-groups/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/configure-custom-claim/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/create-groups-claim/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/get-group-ids/index.md
packages/@okta/vuepress-site/docs/guides/create-token-with-groups-claim/send-test-request/index.md
packages/@okta/vuepress-site/docs/index.md
packages/@okta/vuepress-site/docs/release-notes/2019-08-1/index.md
packages/@okta/vuepress-theme-default/assets/css/okta/pages/docsIndex.scss

- **What's changed?** Exactly what the title says.
- **Is this PR related to a Monolith release?** Definitely.

Rn entry 2019.08.1

---

packages/@okta/vuepress-site/docs/release-notes/2019-08-1/index.md

- **What's changed?** Dev doc update for 2019.08.1. Just an RN entry this week.
- **Is this PR related to a Monolith release?** Definitely.
* N/A

Doc Release for 2019.08.1

---

packages/@okta/vuepress-site/docs/reference/api/groups/index.md

**What's changed?** 
- added note that the request to /api/v1/groups/{{groupId}} is supported only server side as confirmed by @AshishVaidya-okta on OKTA-226281
- corrected minor grammar in List Groups note
**Is this PR related to a Monolith release?**
No

Get Group notification update

---

packages/@okta/vuepress-site/docs/guides/sign-in-with-facebook/add-redirect-uri/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-facebook/complete-authz-url/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-facebook/configure-idp/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-facebook/register-oidc-app/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-facebook/using-facebook-login/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-google/complete-authz-url/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-google/register-oidc-app/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-linkedin/register-oidc-app/index.md
packages/@okta/vuepress-site/docs/guides/sign-in-with-microsoft/register-oidc-app/index.md

- **What's changed?** Added reference to Authorization Code grant type also working and added Implicit step to Google guide, and a few style clean up items

Venkat edits to Social Login guides

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** More explanation around id token/thin token
* [OKTA-228423](https://oktainc.atlassian.net/browse/OKTA-228423)

more explanation around id token/thin token

---

README.md

- **What's changed?** Added a note in the prerequisite section
NA

updated the README.md file with a note about installation type

---

packages/@okta/vuepress-site/conductor.yml

* [OKTA-235356](https://oktainc.atlassian.net/browse/OKTA-235356)

testing SAML and Facebook

---

packages/@okta/vuepress-site/docs/concepts/events-api-migration/index.md

- **What's changed?** a couple of minor typos I came across while scanning the page for style issues

typo fixes

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Fixing top 404s for this week.

Fixing 404s

---

packages/@okta/vuepress-site/.vuepress/scripts/yml-parse-check.js
packages/@okta/vuepress-site/conductor.yml
packages/@okta/vuepress-site/package.json

- Adds checks for known conductor.yml issues
- No
* [OKTA-234098](https://oktainc.atlassian.net/browse/OKTA-234098)

ci: Adds check for known conductor.yml issues

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Fixing redirect for old Tokens API page.
* N/A

Fixing redirect

---

packages/@okta/vuepress-site/.vuepress/config.js

- **What's changed?** Adds community toolkit to footer
* resolves #564

Updates footer to add community toolkit link

---

packages/@okta/vuepress-site/docs/guides/sign-users-out/define-signout-callback/android/addbaseuri.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/define-signout-callback/index.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/define-signout-callback/ios/addbaseuri.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/android/remotesignout.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/ios/remotesignout.md

- **What's changed?** Moved callback info from one section, to the correct section for iOS and Android
* [OKTA-246743](https://oktainc.atlassian.net/browse/OKTA-246743)

callback update for ios and android

---

packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/nodeexpress/addconfigpkg.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/nodeexpress/configmid.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/define-callback/nodeexpress/define-route.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/get-user-info/nodeexpress/getuserinfo.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/nodeexpress/login-redirect.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/require-authentication/nodeexpress/reqautheverything.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/require-authentication/nodeexpress/reqauthspecific.md

- **What's changed?** edited new content for style and punctuation

edited new content for style and punctuation

---

packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md

- **What's changed?** Adding link to step-by-step guide for registering an Event Hook; adding more explanation of the authorization header; correcting the nesting of sections within the  page.
* [OKTA-240528](https://oktainc.atlassian.net/browse/OKTA-240528)

Clarify authorization header

---

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md

Fixing anchor link
- **What's changed?** Updating anchor link

Update Rate Limits

---

packages/@okta/vuepress-site/code/angular/index.md
packages/@okta/vuepress-site/code/javascript/index.md
packages/@okta/vuepress-site/code/react/index.md
packages/@okta/vuepress-site/code/react/okta_react/index.md
packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
packages/@okta/vuepress-site/code/vue/index.md
packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md
packages/@okta/vuepress-site/docs/concepts/auth-overview/index.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/configure-the-sdk/index.md
packages/@okta/vuepress-site/quickstart-fragments/angular/default-example/index.md
packages/@okta/vuepress-site/quickstart-fragments/react/default-example/index.md
packages/@okta/vuepress-site/quickstart-fragments/vue/default-example/index.md

PKCE flow is released for React, Angular, Vue. This is the preferred flow for SPA applications.
React, Angular, and VUE OIDC libraries now use a common, normalized configuration format. Updating documentation to reflect this.
* [OKTA-239801](https://oktainc.atlassian.net/browse/OKTA-239801

PKCE is preferred flow for SPA apps (angular, vue, react)

---

packages/@okta/vuepress-site/code/angular/okta_angular_auth_js/index.md
packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
packages/@okta/vuepress-site/code/react/okta_react/index.md
packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/create-okta-application/index.md
packages/@okta/vuepress-site/quickstart-fragments/react/default-example/index.md
packages/@okta/vuepress-site/quickstart-fragments/widget/default-example/index.md

* [OKTA-239801](https://oktainc.atlassian.net/browse/OKTA-239801)

Updates 'code' sections with PKCE config. Updates 'sign-in-widget' to 3.2

---

packages/@okta/vuepress-site/docs/guides/saml-application-setup/add-general-info/index.md

- **What's changed?** Forgot to update the wording for add general info when I changed the title

changed wording for add general info

---

packages/@okta/vuepress-site/code/ios/index.md

Update ios doc with new metadata
No
* [OKTA-228174](https://oktainc.atlassian.net/browse/OKTA-228174)

Update ios index.md

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-0/index.md

- **What's changed?** Adding release notes entry for 2019.09.0.
- **Is this PR related to a Monolith release?** Yes, 2019.09.0

Creating release notes entry.

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-0/index.md

- **What's changed?** Fixed anchor link.
- **Is this PR related to a Monolith release?** Yes, 2019.09.0.

Fixing missed anchor link mistake.

---

packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md

- **What's changed?** Needed to hyphenate and introduce abbreviation correctly for style

fixing JIT

---

packages/@okta/vuepress-site/code/angular/index.md
packages/@okta/vuepress-site/code/dotnet/aspnet/index.md
packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
packages/@okta/vuepress-site/code/go/index.md
packages/@okta/vuepress-site/code/ios/index.md
packages/@okta/vuepress-site/code/java/index.md
packages/@okta/vuepress-site/code/javascript/index.md
packages/@okta/vuepress-site/code/nodejs/index.md
packages/@okta/vuepress-site/code/php/index.md
packages/@okta/vuepress-site/code/react/index.md
packages/@okta/vuepress-site/code/rest/index.md
packages/@okta/vuepress-site/code/vue/index.md

Added metadata updated titles for code homepages on developer.okta.com
No
* [OKTA-228174](https://oktainc.atlassian.net/browse/OKTA-228174)

Add metadata, update titles for d.o.c code homepages

---

packages/@okta/vuepress-site/code/android/index.md
packages/@okta/vuepress-site/code/python/index.md
packages/@okta/vuepress-site/code/react-native/index.md
packages/@okta/vuepress-site/docs/concepts/auth-overview/index.md
packages/@okta/vuepress-site/docs/concepts/social-login/index.md

Updates to topic titles, headers, meta data added
No
* [OKTA-228174](https://oktainc.atlassian.net/browse/OKTA-228174)

Meta Tags for Developer Docs - PR#2

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-0/index.md

- **What's changed?** Removed item ENG_REJECT_BAD_OAUTH_CLIENTS_AND_WARN_FOR_ACTIVE_CLIENTS.
- **Is this PR related to a Monolith release?** Yes, 2019.09.0

Removing item for hotfix

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-0/index.md

- **What's changed?** Added link from release notes item about SAML Inline Hook to the doc page for it.
- **Is this PR related to a Monolith release?** Yes, 2019.09.0

Link from release notes item to SAML Assertion Inline Hook page

---

packages/@okta/vuepress-site/docs/concepts/auth-overview/index.md
packages/@okta/vuepress-site/docs/concepts/authentication/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/before-you-begin/index.md
packages/@okta/vuepress-site/docs/guides/mfa/prerequisites/index.md
packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/index.md
packages/@okta/vuepress-site/docs/reference/api-overview/index.md
packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
packages/@okta/vuepress-site/docs/reference/api/roles/index.md
packages/@okta/vuepress-site/docs/reference/error-codes/index.md
packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
packages/@okta/vuepress-site/docs/reference/scim/index.md
packages/@okta/vuepress-site/docs/reference/webfinger/index.md

Added meta data to several topics.
Cleaned up the text on the OAuth intro guide.
No
* [OKTA-228174](https://oktainc.atlassian.net/browse/OKTA-228174)

Metadata & text clean up

---

packages/@okta/vuepress-site/docs/reference/api/apps/index.md

updated `targetUrl` parameter in request sample to `targetURL`
no
* [OKTA-221084](https://oktainc.atlassian.net/browse/OKTA-221084)

update targetUrl ---> targetURL

---

packages/@okta/vuepress-site/code/java/spring/index.md
packages/@okta/vuepress-site/code/python/index.md
packages/@okta/vuepress-site/docs/concepts/authentication/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/before-you-begin/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/index.md
packages/@okta/vuepress-site/docs/guides/mfa/index.md
packages/@okta/vuepress-site/docs/guides/mfa/prerequisites/index.md
packages/@okta/vuepress-site/docs/guides/set-up-event-hook/index.md
packages/@okta/vuepress-site/docs/guides/validate-access-tokens/index.md
packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/index.md
packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
packages/@okta/vuepress-site/docs/reference/webfinger/index.md

Updated title, added metadata
No
* [OKTA-288174](https://oktainc.atlassian.net/browse/OKTA-288174)

Updates to topic metadata - 2019.09.10

---

.travis.yml
scripts/updateSeDrivers.sh

- Using xenial dist in travis 
- Update to use chromedriver 77
- Nope
* [OKTA-248964](https://oktainc.atlassian.net/browse/OKTA-248964)

Using xenial dist for travis

---

packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md

- **What's changed?** Fixed a typo.

Correcting typo

---

packages/@okta/vuepress-site/docs/concepts/authentication/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/index.md
packages/@okta/vuepress-site/docs/reference/webfinger/index.md

Updates from review comments - capitalization.
No
* [OKTA-288174](https://oktainc.atlassian.net/browse/OKTA-288174)

Check in changes from review comments

---

packages/@okta/vuepress-site/docs/concepts/authentication/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/before-you-begin/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/index.md

Minor fixes to files in the staging branch

Metadata updates & typo

---

packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md

Updates Angular SIW code example to use latest production CSS.
* [OKTA-247577](https://oktainc.atlassian.net/browse/OKTA-247577)

Angular SIW code example (Use latest CSS)

---

packages/@okta/vuepress-plugin-active-header-links/package.json
packages/@okta/vuepress-site/package.json
packages/@okta/vuepress-theme-default/assets/css/legacy/master.css
packages/@okta/vuepress-theme-default/assets/css/okta/components/BlogPost.scss
packages/@okta/vuepress-theme-default/assets/css/okta/components/Hero.scss
packages/@okta/vuepress-theme-default/package.json
yarn.lock

- **What's changed?** This updates the VuePress core to 1.1.0, taking it out of an alpha version
* [OKTA-226213](https://oktainc.atlassian.net/browse/OKTA-226213)

Updates VuePress core to 1.1.0

---

packages/@okta/vuepress-plugin-active-header-links/package.json
packages/@okta/vuepress-site/package.json
packages/@okta/vuepress-theme-default/assets/css/legacy/master.css
packages/@okta/vuepress-theme-default/assets/css/okta/components/BlogPost.scss
packages/@okta/vuepress-theme-default/assets/css/okta/components/Hero.scss
packages/@okta/vuepress-theme-default/package.json
yarn.lock

- **What's changed?** This updates the VuePress core to 1.1.0, taking it out of an alpha version
* [OKTA-226213](https://oktainc.atlassian.net/browse/OKTA-226213)

Update VuePress to 1.1.0

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-2/index.md

- **What's changed?** Release Notes entry for 2019.09.2
- **Is this PR related to a Monolith release?** Yes Release Notes entry for 2019.09.2

Rn entry 2019.09.2

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-2/index.md

* Release notes entry 2019.09.2
- **What's changed?** Release Notes entry for 2019.09.2
- **Is this PR related to a Monolith release?** Definitely.

Rn entry 2019.09.2 (#674)

---

packages/@okta/vuepress-site/docs/reference/api/features/index.md

fix typo index.md

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Redirect

Adding new redirect and modifying existing ones

---

packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md

- **What's changed?** Fixing link that refers to old anchor to go to new page.
* N/A

Fixing link

---

packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/overview/index.md

- **What's changed?** found a typo in a URL

fixing url typo

---

README.md

- **What's changed?** Adding note about how to fork betterer. 

Updating instructions

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-3/index1.md

- **What's changed?** Release Notes entry from 2019.09.3
- **Is this PR related to a Monolith release?** Yes, Release 2019.09.3

Rn entry 2019.09.3

---

packages/@okta/vuepress-site/docs/reference/api/authn/index.md

- **What's changed?** Removing excerpt from the authn api reference frontmatter.
- **Is this PR related to a Monolith release?** Negative.

Removing excerpt

---

packages/@okta/vuepress-site/code/javascript/okta_auth_sdk/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md
packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
packages/@okta/vuepress-site/docs/release-notes/2017-23/index.md

* [OKTA-213059](https://oktainc.atlassian.net/browse/OKTA-213059)

Fixing non-alias links to ProdHelp

---

packages/@okta/vuepress-theme-default/util/frameworks.js

- **What's changed?** Fixing “React Native” so that the React logo appears in the stack selector

fixing react-native

---

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/oktatookta/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/openidconnect/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/saml2/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-an-app-at-idp/saml2/appatidp.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-authz-url/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/register-app-in-okta/index.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/use-idp-to-sign-in/index.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/primary-authentication/android/primaryauth.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/primary-authentication/index.md
packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/overview/index.md
packages/@okta/vuepress-site/docs/guides/byo-saml/overview/index.md
packages/@okta/vuepress-site/docs/guides/byo-saml/publish-the-csr/index.md
packages/@okta/vuepress-site/docs/guides/byo-saml/sign-the-csr/index.md
packages/@okta/vuepress-site/docs/guides/byo-saml/update-the-key-credential/index.md
packages/@okta/vuepress-site/docs/guides/byo-saml/upload-the-certificate/index.md

- **What's changed?** Fixing a few obvious typos that I found

various typos found while reviewing guides for style inconsistencies

---

packages/@okta/vuepress-site/docs/guides/create-an-api-token/create-the-token/index.md
packages/@okta/vuepress-site/docs/guides/create-an-api-token/index.md
packages/@okta/vuepress-site/docs/guides/create-an-api-token/overview/index.md
packages/@okta/vuepress-site/docs/guides/create-an-api-token/token-expiration-deactivation/index.md

- **What's changed?** Updating this content to match guide formatting

updated guide to match guide format

---

packages/@okta/vuepress-site/docs/release-notes/2019-09-4/index.md

- **What's changed?** RN entry for 2019.09.4
- **Is this PR related to a Monolith release?** Definitely

Rn entry 2019.09.4

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- Update dev docs to reflect scope name constraints.
* [OKTA-212397](https://oktainc.atlassian.net/browse/OKTA-212397)
@jakubvul

Update scope description with validation requirements

---

packages/@okta/vuepress-site/docs/reference/api/apps/index.md
packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md

- **What's changed?** Adding a request example for creating a service app with a JWKS to the Dynamic Client Registration content and fixing an issue in /apps

updating API Ref docs for OAuth for Okta APIs guide

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

According to the post on the OKTA forum below, this is no longer
the actual behavior of the logout endpoint. 
https://devforum.okta.com/t/oidc-web-application-okta-logout-issue/2705/2

Remove phrasing around handling expired id tokens

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md

List users by "search" - table formatting
List Users Request Parameters description change
NO
* [OKTA-253843](https://oktainc.atlassian.net/browse/OKTA-253843)

List Users Request Parameters description change

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md

List users by "search" - table formatting
List users by "search" - table formatting
- **Is this PR related to a Monolith release?**  
No
* [OKTA-253843](https://oktainc.atlassian.net/browse/OKTA-253843)

List users by "search" - table formatting

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** Adding additional error condition per user feedback
* [OKTA-253647](https://oktainc.atlassian.net/browse/OKTA-253647)

adding additional error condition per user feedback

---

packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md
packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md

- **What's changed?** Adding Preview and Production org content to the concept guide
* [OKTA-246773](https://oktainc.atlassian.net/browse/OKTA-246773)

adding preview and prod org info

---

packages/@okta/vuepress-site/docs/reference/api/factor-profiles/index.md

Try a more condensed approach to the feature documentation
* [OKTA-249978](https://oktainc.atlassian.net/browse/OKTA-249978)

Try a more condensed approach to the feature documentation

---

packages/@okta/vuepress-site/docs/reference/api/factor-profiles/index.md

Fixup documentation of adoption feature
Fixup documentation of Password and Email factor profile settings
Fixup documentation of feature links object
* [OKTA-245765](https://oktainc.atlassian.net/browse/OKTA-245765)

Improve documentation of adoption feature

---

packages/@okta/vuepress-site/docs/reference/api/factor-profiles/index.md

Document the Recovery Factor Profile Feature
* [OKTA-249978](https://oktainc.atlassian.net/browse/OKTA-249978)

Document the Recovery Factor Profile Feature

---

packages/@okta/vuepress-site/docs/reference/api/factor-profiles/index.md

Update factor profiles API doc to cover Email factor features
* [OKTA-249978](https://oktainc.atlassian.net/browse/OKTA-249978)

Update factor profiles API doc to cover Email factor features

---

packages/@okta/vuepress-site/docs/reference/api/factor-profiles/index.md

Added example Json for Factor Profile
Re-format password factor features sections to be consistent with other features
Fix a couple typos

Add example Json for Factor Profile

---

packages/@okta/vuepress-site/docs/reference/api/features/index.md

- **What's changed?** It's all the title. It's _very_ descriptive.
* A nagging sense of annoyance with myself.

Ordering properties and params in alpha order

---

packages/@okta/vuepress-site/docs/release-notes/2019-10-1/index.md

- **What's changed?** release notes entry for release-2109.10.1
- **Is this PR related to a Monolith release?** Yes. Release notes entry for release-2109.10.1

release-2019.10.1

---

packages/@okta/vuepress-site/docs/reference/api/factor-profiles/index.md

Add some curl \ json examples for common operations

Add Curl\Json examples

---

packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md

- **What's changed?** Formatting changes

format issues

---

packages/@okta/vuepress-site/docs/concepts/authentication/index.md

- **What's changed?** Added missing comma to "find out more" text below "OAuth 2.0, OpenID Connect, and Social Login".
* N/A

Added missing comma

---

packages/@okta/vuepress-site/docs/concepts/oin-scim/index.md
packages/@okta/vuepress-site/docs/guides/oin-build-provisioning-integration/submit-for-review/index.md
packages/@okta/vuepress-site/docs/guides/oin-build-provisioning-integration/test-scim-server/index.md

Corrected the links to standard/SCIM/SCIMFiles path

Fix relative linking in SCIM topics

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md

1. Explain why `search` results should not be used in critical flows.
2. Reword terminology as per https://devforum.okta.com/t/search-vs-filter/1172
Borrowing wording from @tomabbott-okta 
No

Remove references to "replicated" store

---

packages/@okta/vuepress-site/conductor.yml

Sdh okta255842 saml cert

---

packages/@okta/vuepress-site/docs/concepts/index.md
packages/@okta/vuepress-site/docs/index.md

- Removes icon from cards
- Adds more link to the concepts page on `/docs/reference/`

Add more links and remove card icon

---

packages/@okta/vuepress-site/.vuepress/nav/main.js
packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Added a redirect, updated one that wasn't working, and added the Features API to the left-side nav.
* [OKTA-105070](https://oktainc.atlassian.net/browse/OKTA-105070)

Jv misc fixes

---

package.json
scripts/update-se-drivers.sh
scripts/updateSeDrivers.sh

Apply latest updateSeDrivers.sh script

---

packages/@okta/vuepress-theme-default/assets/css/okta/base/variables.scss
packages/@okta/vuepress-theme-default/assets/css/okta/components/PageContent.scss

- **What's changed?** Adding support for PATCH to our API operations plugin.
- **Is this PR related to a Monolith release?** Kinda sorta but not really. #742 needs this.
Non-real example (first real example is in #742)

Adding PATCH API operation method

---

packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md

- **What's changed?** Changing name of page in metadata, so that it shows up properly in Google; correcting typo in excerpt metadata.

Changing name of Inline Hooks Management API page in metadata

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Fixing byo-saml redirects

Creating redirects

---

packages/@okta/vuepress-site/code/rest/index.md

- **What's changed?** Removed double curly braces around "userId".

Fix curly braces

---

packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md

- **What's changed?** Updating metadata in Event Hooks Management API page to differentiate it from Event Hooks concepts page and be consistent with Inline Hooks Management API page.

Updating metadata in Event Hooks Management API

---

packages/@okta/vuepress-site/docs/release-notes/2019-10-2/index.md

- **What's changed?** Creating weekly release notes entry.
- **Is this PR related to a Monolith release?** Yes, 2019.10.2

Creating release notes entry for 2019.10.2

---

packages/@okta/vuepress-site/docs/guides/oin-build-provisioning-integration/faqs/index.md
packages/@okta/vuepress-site/docs/guides/oin-build-provisioning-integration/review-scim-docs/index.md
packages/@okta/vuepress-site/docs/guides/oin-build-provisioning-integration/submit-for-review/index.md
packages/@okta/vuepress-site/docs/guides/oin-build-provisioning-integration/test-scim-server/index.md
packages/@okta/vuepress-site/docs/guides/oin-build-sso-integration/partner/index.md

Clean up external and cross-ref links that Travis missed

Clean Up Linking

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** making info a note and changing wording
* [OKTA-159462](https://oktainc.atlassian.net/browse/OKTA-159462)

making info a note and changing wording

---

packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/overview/index.md

Fix a typo

---

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md

- **What's changed?** This makes the final `{id}` show up in the rendered HTML.

Temporary fix to make the terminal variable show up

---

packages/@okta/vuepress-site/docs/release-notes/2019-11-0/index.md

- **What's changed?** Release Notes Entry for 2019.11.0
- **Is this PR related to a Monolith release?** Yes. Release Notes Entry for 2019.11.0

Rn entry 2019.11.0

---

packages/@okta/vuepress-site/docs/concepts/saml/index.md
packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/test-scim-server/index.md
packages/@okta/vuepress-site/docs/guides/build-sso-integration/integrate/index.md
packages/@okta/vuepress-site/docs/guides/index.md
packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
packages/@okta/vuepress-site/docs/reference/token-hook/index.md

- **What's changed?** GA SAML and Token Inline Hook
- **Is this PR related to a Monolith release?** 2019.11.0
* [OKTA-244855](https://oktainc.atlassian.net/browse/OKTA-244855)
* [OKTA-244856](https://oktainc.atlassian.net/browse/OKTA-244856)

GA SAML and Token Inline Hook

---

packages/@okta/vuepress-site/docs/reference/api/apps/index.md
packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md

- **What's changed?** Adding request_object_signing_alg property info
* [OKTA-254606](https://oktainc.atlassian.net/browse/OKTA-254606)

adding property info

---

packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-access-policies/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-authz-server/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-claims/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-rules-for-policy/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/create-scopes/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/overview/index.md
packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md
packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** Updating create an auth server content per cust feedback
* [OKTA-260282](https://oktainc.atlassian.net/browse/OKTA-260282)

Updating create an auth server content

---

packages/@okta/vuepress-site/docs/guides/build-sso-integration/index.md
packages/@okta/vuepress-site/docs/guides/build-sso-integration/overview/index.md

Updates to doc title to correct capitalization

---

packages/@okta/vuepress-site/.vuepress/nav/main.js
packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md

- **What's changed?** update to releases page
* [OKTA-217330](https://oktainc.atlassian.net/browse/OKTA-217330)

update to releases page

---

packages/@okta/vuepress-site/docs/reference/api/authn/index.md

- **What's changed?** Added CORS badges for MFA operations under Authentication API
* OKTA-260800

CORS badge for MFA operations under Authn API

---

packages/@okta/vuepress-site/docs/release-notes/2019-11-1/index.md

- **What's changed?** RN Entry for 2019.11.1
- **Is this PR related to a Monolith release?** Yup
* N/A

Rn entry 2019.11.1

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** typo and clarification

typo and clarification

---

packages/@okta/vuepress-site/docs/reference/api/authn/index.md

- **What's changed?** Document the factorType challenge type for WebAuthn; also clean up some references to factorId during verification
- **Is this PR related to a Monolith release?** It's related to an already-deployed monolith release: 2019.11.0 (but has no dependency)
* [OKTA-260985](https://oktainc.atlassian.net/browse/OKTA-260985)

Document factorType verification for WebAuthn

---

packages/@okta/vuepress-site/docs/reference/api/factors/index.md

- **What's changed?** Adding an example of YubiKey factor verification
* [OKTA-214290](https://oktainc.atlassian.net/browse/OKTA-214290)
- @okta/enterpriseauth-team @okta/developerdocs

add YubiKey factor verification example

---

packages/@okta/vuepress-site/docs/release-notes/2019-11-2/index.md

- **What's changed?** Release notes entry.
- **Is this PR related to a Monolith release?** Yes, 2019.11.2.

Adding Release Notes Entry

---

packages/@okta/vuepress-site/docs/guides/oauth-for-okta/overview/index.md

- **What's changed?** fixed feature flag name in overview

fixing feature flag name

---

packages/@okta/vuepress-site/quickstart-fragments/android/default-example/index.md

Quick start is referencing old SDK.
This updates it to use the latest.

Update Android quickstart

---

packages/@okta/vuepress-site/docs/concepts/scim/index.md

Link pointer to the SCIM on-prem provisioning document on support.okta.com
NO
* [OKTA-149003](https://oktainc.atlassian.net/browse/OKTA-149003)

Corrected SCIM link

---

packages/@okta/vuepress-site/docs/concepts/saml/index.md

Fixes typo

---

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md

fix minor error, it's not `user.username`, it's `user.login`

fix minor error

---

packages/@okta/vuepress-theme-prose/assets/css/components/_apiLifecycle.scss
packages/@okta/vuepress-theme-prose/assets/css/components/_apiOperation.scss
packages/@okta/vuepress-theme-prose/assets/css/prose.scss
packages/@okta/vuepress-theme-prose/global-components/ApiLifecycle.vue
packages/@okta/vuepress-theme-prose/global-components/ApiOperation.vue

Prose add global components

---

packages/@okta/vuepress-site/docs/release-notes/2019-11-3/index.md

- **What's changed?** release notes 2019.11.3
- **Is this PR related to a Monolith release?** Yes 2019.11.3

Rn entry 2019.11.3

---

packages/@okta/vuepress-site/docs/release-notes/2019-11-3/index.md

- **What's changed?** Release Notes 2019.11.3 
- **Is this PR related to a Monolith release?** 2019.11.3

Release 2019.11.3

---

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/google/appidpinokta.md

- **What's changed?** Removing mention of what to do if Google doesn't support email scope, since they do support it.

Tweak to Google IdP Guide

---

packages/@okta/vuepress-site/docs/reference/api/index.md
packages/@okta/vuepress-theme-prose/assets/css/components/_apiOperation.scss
packages/@okta/vuepress-theme-prose/assets/css/components/_code.scss
packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
packages/@okta/vuepress-theme-prose/assets/css/components/_pageTitle.scss
packages/@okta/vuepress-theme-prose/assets/css/components/_sidebar.scss
packages/@okta/vuepress-theme-prose/assets/css/components/_table.scss
packages/@okta/vuepress-theme-prose/assets/css/layouts/_layout.scss
packages/@okta/vuepress-theme-prose/assets/css/prose.scss
packages/@okta/vuepress-theme-prose/components/Sidebar.vue
packages/@okta/vuepress-theme-prose/global-components/ApiOperation.vue
packages/@okta/vuepress-theme-prose/layouts/Layout.vue

Prose tree nav

---

packages/@okta/vuepress-plugin-active-header-links/package.json
packages/@okta/vuepress-site/package.json
yarn.lock

Update VuePress to 1.2.0

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Fixing broken redirects
* [OKTA-265827](https://oktainc.atlassian.net/browse/OKTA-265827)

fixing broken redirects

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** Updated the Response Example
* [OKTA-198405](https://oktainc.atlassian.net/browse/OKTA-198405)

request example update

---

packages/@okta/vuepress-site/code/angular/okta_angular_auth_js/index.md

- Angular walkthrough was non-functional and out of date. Fixed and updated to work with latest version of Angular and AuthJS.
* [OKTA-266118](https://oktainc.atlassian.net/browse/OKTA-266118)

angular + authjs: fix/update quickstart walkthrough

---

packages/@okta/vuepress-site/docs/release-notes/2019-12-1/index.md

- **What's changed?** Added release note for 2019.12.1
* [OKTA-262950](https://oktainc.atlassian.net/browse/OKTA-262950)

Rn entry 2019.12.1

---

packages/@okta/vuepress-site/books/api-security/authz/attribute-based/index.md

Fixed typo

---

packages/@okta/vuepress-site/docs/release-notes/2019-12-1/index.md

- **What's changed?** Adding release note for 2019.12.1
* [OKTA-262950](https://oktainc.atlassian.net/browse/OKTA-262950)

Release note for 2019.12.1

---

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
packages/@okta/vuepress-site/docs/reference/token-hook/index.md

- **What's changed?** token inline hook troubleshooting section and a few minor additions
* [OKTA-241664](https://oktainc.atlassian.net/browse/OKTA-241664)

token inline hook troubleshooting section and a few minor additions

---

packages/@okta/vuepress-site/.vuepress/config.js

- **What's changed?** Add banner through GTM and move Heap to GTM

Add banner through GTM and move Heap to GTM

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/create-oauth-app/index.md

minor typo

---

packages/@okta/vuepress-site/data/event-types.json
packages/@okta/vuepress-site/docs/release-notes/2020-01-0/index.md

- **What's changed?** Not much, actually.
- **Is this PR related to a Monolith release?** Definitely.

Doc Release 2020.01.0

---

packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md

- **What's changed?** Added a bullet per the JIRA and removed one caveat per the fix announced in the December Release Notes
* [OKTA-268721](https://oktainc.atlassian.net/browse/OKTA-268721)

caveat update and removal of one caveat that has been fixed

---

packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md

- **What's changed?** had the wrong base URL

fixing alias

---

packages/@okta/vuepress-site/docs/reference/api/apps/index.md

- **What's changed?** updated examples and added content to table
* [OKTA-165547](https://oktainc.atlassian.net/browse/OKTA-165547)

updated examples and added content to table

---

packages/@okta/vuepress-site/code/android/index.md
packages/@okta/vuepress-site/code/angular/index.md
packages/@okta/vuepress-site/code/dotnet/aspnet/index.md
packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
packages/@okta/vuepress-site/code/dotnet/index.md
packages/@okta/vuepress-site/code/go/index.md
packages/@okta/vuepress-site/code/ios/index.md
packages/@okta/vuepress-site/code/java/index.md
packages/@okta/vuepress-site/code/javascript/index.md
packages/@okta/vuepress-site/code/nodejs/index.md
packages/@okta/vuepress-site/code/php/index.md
packages/@okta/vuepress-site/code/python/index.md
packages/@okta/vuepress-site/code/react-native/index.md
packages/@okta/vuepress-site/code/react/index.md
packages/@okta/vuepress-site/code/vue/index.md

- **What's changed?** Code page titles are now less inaccurate.
* N/A

Revising code page titles

---

packages/@okta/vuepress-site/data/event-types.json

- **What's changed?** Removing events with "since" values of `null`, which was breaking the filtering.
* N/A

Fixing event catalog search

---

packages/@okta/vuepress-site/.vuepress/config.js

- **What's changed?** Removes test_page from sitemap
* [OKTA-254799](https://oktainc.atlassian.net/browse/OKTA-254799)

Exclude test_page from sitemap

---

packages/@okta/vuepress-site/docs/reference/api/apps/index.md

- **What's changed?** Making fragments consistently have no periods and then some other minor things I found along the way

fragment cleanup

---

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/before-you-begin/index.md

- **What's changed?** adding the term inbound federation for better search results
* [OKTA-270144](https://oktainc.atlassian.net/browse/OKTA-270144)

adding the term inbound federation for better search results

---

scripts/setup.sh

Update bacon node version

---

packages/@okta/vuepress-site/docs/release-notes/2020-01-2/index.md

- **What's changed?** Added RN entry.
- **Is this PR related to a Monolith release?** 2020.01.2

Creating Release Notes Entry for 2020.01.2

---

packages/@okta/vuepress-site/quickstart/index.md
packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
packages/@okta/vuepress-theme-prose/assets/css/components/_quickstart.scss
packages/@okta/vuepress-theme-prose/assets/css/prose.scss
packages/@okta/vuepress-theme-prose/components/OnThisPage.vue
packages/@okta/vuepress-theme-prose/components/Quickstart.vue
packages/@okta/vuepress-theme-prose/global-components/DomainAdminWarning.vue
packages/@okta/vuepress-theme-prose/layouts/Layout.vue

- **What's changed?** Adds the quickstarts back into site with prose layout

Add quickstarts back in

---

packages/@okta/vuepress-site/docs/reference/api/roles/index.md

- **What's changed?** add EA doc for third party admin in roles api
- **Is this PR related to a Monolith release?** no, it's already in EA in prod
* [OKTA-275648](https://oktainc.atlassian.net/browse/OKTA-275648)

add EA doc for third party admin in roles api

---

packages/@okta/vuepress-site/.vuepress/nav/reference.js
packages/@okta/vuepress-theme-prose/assets/css/components/_sidebar.scss
packages/@okta/vuepress-theme-prose/components/Sidebar.vue
packages/@okta/vuepress-theme-prose/components/SidebarItem.vue

Prose resource nav file

---

scripts/update-se-drivers.sh

- Updates CI data to include Chrome 80 build info
- No
- Travis build issue

adds travis update for Chrome 80

---

packages/@okta/vuepress-site/docs/reference/api/idps/index.md

- **What's changed?** Added note about Okta currently only supporting rsa-based certs
* [OKTA-272742](https://oktainc.atlassian.net/browse/OKTA-272742)

note about rsa certs

---

packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md

Added info on using PUT vs PATCH for user and group updates through the SCIM protocol
No
* [OKTA-236274](https://oktainc.atlassian.net/browse/OKTA-236274)

Update SCIM FAQ

---

scripts/update-se-drivers.sh

Update chrome driver

---

packages/@okta/vuepress-site/docs/concepts/api-access-management/index.md

- **What's changed?** Addressing customer feedback
* [OKTA-276603](https://oktainc.atlassian.net/browse/OKTA-276603)

first draft of update to item

---

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
packages/@okta/vuepress-site/docs/reference/api/users/index.md
packages/@okta/vuepress-site/docs/reference/password-hook/index.md

- **What's changed?** Minor edits.

Minor edits to Password Inline Hook content

---

packages/@okta/vuepress-site/docs/reference/api/apps/index.md

- **What's changed?** Updating headings per sentence style and table sorting

headings and table sort

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- **What's changed?** Updating headings, tables, and fragments

auth serv headings and tables and fragments

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md
packages/@okta/vuepress-site/docs/reference/password-hook/index.md

- **What's changed?** Doc fixes for the articles treating Password Import inline Hook functionality.

Doc fixes for Password Import Inline Hook

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md

Fix typo in oauth for okta doc

---

packages/@okta/vuepress-site/docs/reference/password-hook/index.md

- **What's changed?** Minor style edits.

Minor style edits to Password Import Hook

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md

- **What's changed?** Adjusted api example for Create User with Password Import Inline Hook to auto-activate user with no email.

Doc fix for password inline hook user creation

---

packages/@okta/vuepress-site/docs/reference/webfinger/index.md

- **What's changed?** Corrected accept header from application/json to application/jrd+json
* [OKTA-248566](https://oktainc.atlassian.net/browse/OKTA-248566)

correcting accept header for webfinger request

---

packages/@okta/vuepress-site/docs/release-notes/2020-02-1/index.md

- **What's changed?** Doc update for weekly release. Added 3 bug fix blurbs.
- **Is this PR related to a Monolith release?** Yes, 2020.02.1
* N/A

Rn entry 2020.02.1

---

packages/@okta/vuepress-theme-prose/assets/css/components/_top-bar.scss

[Prose]: Top Bar Nav styles

---

packages/@okta/vuepress-site/.vuepress/nav/codePages.js

[Prose]: Add title for Languages to sidebar

---

packages/@okta/vuepress-site/quickstart/index.md
packages/@okta/vuepress-theme-prose/assets/css/components/_quickstart.scss
packages/@okta/vuepress-theme-prose/components/Breadcrumb.vue
packages/@okta/vuepress-theme-prose/components/Quickstart.vue

- Removed Left Hand Nav
- Changed style of code selector
- Updated padding above code selector box
- Added Quickstart to breadcrumb
- Made (skip to server) link work
Design approved by @alexdahl-okta

Update quickstart page design

---

packages/@okta/vuepress-theme-prose/util/frameworks.js

Add missing values in framework.js.
No
#983

Add missing values in prose frameworks.js.

---

packages/@okta/vuepress-site/.vuepress/config.js
packages/@okta/vuepress-theme-prose/enhanceApp.js
packages/@okta/vuepress-theme-prose/package.json
yarn.lock

- **What's changed?** Adds browser-update to D.O.C. for old versions.
You can test by adding `#test-bu` to any URL

Adds browser-update.org code

---

packages/@okta/vuepress-site/docs/reference/webfinger/index.md

- **What's changed?** Typo fixed.

Typo fix on Webfinger page

---

packages/@okta/vuepress-site/docs/release-notes/index.md

- **What's changed?** Adds release notes page title

Add release notes page header

---

packages/@okta/vuepress-site/docs/reference/api/roles/index.md

- **What's changed?** Target clarifications added and style updates

target info and style updates

---

packages/@okta/vuepress-site/docs/reference/api/roles/index.md

- **What's changed?** Missed a couple

missing caps

---

packages/@okta/vuepress-site/docs/release-notes/2020-02-2/index.md

- **What's changed?** We are informing the public about some bugs that we fixed in this release.
- **Is this PR related to a Monolith release?** 💯 
* N/A

Release 2020.02.2

---

packages/@okta/vuepress-site/.vuepress/config.js
packages/@okta/vuepress-site/.vuepress/scripts/addWorkerScript.js

* Prevent Pre-fetch
* Update Prefetch worker logic
* Add comment on worker change

Prevent Pre-fetch (#1014)

---

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md

- **What's changed?** adding missing quote
* [OKTA-280851](https://oktainc.atlassian.net/browse/OKTA-280851)

adding missing quote

---

packages/@okta/vuepress-site/docs/guides/sharing-cert/overview/index.md
packages/@okta/vuepress-site/docs/reference/api/apps/index.md

- **What's changed?** Fixing some improperly-ported links
* N/A

Fixing broken links

---

packages/@okta/vuepress-site/docs/guides/sign-into-spa/add-signin-button/react/login-redirect.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/configure-the-sdk/react/config.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/define-callback/react/define-route.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/handle-callback/react/handle-callback.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/react/reqautheverything.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/react/reqauthspecific.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/use-the-access-token/react/getaccesstoken.md
packages/@okta/vuepress-site/docs/guides/sign-into-spa/user-info/react/getuserinfo.md

- Updates sign-into-spa guide for the new v2 of our okta-react SDK
- No
* [OKTA-281986](https://oktainc.atlassian.net/browse/OKTA-281986)

Updates sign-into-spa for okta-react v2.x

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md

- Fixes a bad link from within sections of the "Create an OAuth 2.0 app in Okta" guide. (existing link would resolve to guides page instead of section)
- No
- a flaw in the universe

Fixes bad link

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-0/index.md

- **What's changed?** 2020.03.0 Release Notes
- **Is this PR related to a Monolith release?** Yes 2020.03.0

Rn entry 2020.03.0

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- **What's changed?** Document new request parameters for paginating List Authorizaton Servers operation
- **Is this PR related to a Monolith release?** 2020.03.0
* [OKTA-278771](https://oktainc.atlassian.net/browse/OKTA-278771)

Update Authorization Servers API docs

---

packages/@okta/vuepress-site/docs/reference/api/roles/index.md

- **What's changed?** Removing list of roles and inserting link to table just below. Adding EA to new admin role in the table

EA flag for new role

---

packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
packages/@okta/vuepress-site/docs/guides/refresh-tokens/index.md
packages/@okta/vuepress-site/docs/guides/refresh-tokens/overview/index.md
packages/@okta/vuepress-site/docs/guides/refresh-tokens/use-refresh-token/index.md

- **What's changed?** Renaming header, adding cross ref, and some other clean up
* [OKTA-281041](https://oktainc.atlassian.net/browse/OKTA-281041)

renaming header, adding cross ref, and some other clean up

---

packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/react/remotesignout.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-your-app/react/localsignout.md

- updates sign-out guide for okta-react 2.x
- includes examples for both function-based components and class-based components
- No
* [OKTA-232099](https://oktainc.atlassian.net/browse/OKTA-232099)

updates sign-out guide for okta-react 2.x

---

packages/@okta/vuepress-site/docs/reference/password-hook/index.md

- **What's changed?** Fixed a typo.

Typo fix in Password Hook page

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-1/index.md

- **What's changed?** Adding release notes entry.
- **Is this PR related to a Monolith release?** Yes, 2020.03.1

Release notes entry

---

packages/@okta/vuepress-site/code/react/okta_react/index.md

- Updates the /code/react/okta_react examples to cover okta-react 2.x
- Also gives both function-based component and class-based component examples
- No
* [OKTA-272787](https://oktainc.atlassian.net/browse/OKTA-272787)

updates code/okta_react/ examples for the okta-react 2.x

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-1/index.md

- **What's changed?** Docs update for weekly release. Currently, the only content change is the new release notes entry.
- **Is this PR related to a Monolith release?** Yes, 2020.03.1.

Release 2020.03.1

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-0/index.md

- **What's changed?** adding in vuln 
- **Is this PR related to a Monolith release?** yes 2020.03.0

adding vuln to RNs

---

packages/@okta/vuepress-site/quickstart-fragments/react/default-example/index.md

- Updates react quickstart for okta-react 2.x (hook only, as it is quickstart)
- No
* [OKTA-283155](https://oktainc.atlassian.net/browse/OKTA-283155)

Updates react quickstart for okta-react 2.x

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- **What's changed?** Clarify a parameter as being a body parameter
N/A

Clarify key rotation "use" param is body param

---

packages/@okta/vuepress-site/docs/guides/build-sso-integration/before-you-begin/index.md

Corrected an instance of "Open ID Connect" to the proper name "OpenID Connect"
No

Minor fix - "Open ID" to "OpenID"

---

packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/go/accesstoken.md
packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/index.md
packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/java/accesstoken.md
packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/nodejs/accesstoken.md
packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/php/accesstoken.md
packages/@okta/vuepress-theme-prose/util/frameworks.js

- Adds StackSelector to the validate-access-token guide
- Populates the NodeJS version of that stack selector
- No
* [OKTA-271033](https://oktainc.atlassian.net/browse/OKTA-271033)

Adds stackselector + js for validate-access-token guide

---

packages/@okta/vuepress-site/docs/reference/api/factors/index.md

- **What's changed?** Adding missing factor types
* N/A

Adding missing Factor type values

---

packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md

- **What's changed?** updating headings, fragments, sorting tables

event hook heading, table sort, fragment updates

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-1/index.md

- **What's changed?** removing a blurb
- **Is this PR related to a Monolith release?** 2020.03.1

remove RN blurb

---

packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test-old.json
packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test.json

Removing a contradictory test that was causing ISV issues.
No
* [OKTA-279453](https://oktainc.atlassian.net/browse/OKTA-279453)

Remove conflicting SCIM test

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md

- **What's changed?** Updated the response that Forgot Password operation returns in relationship with the new flow for password recovery.

Forgot Password response example update

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-2/index.md

- **What's changed?** Release Notes for 2020.03.2
- **Is this PR related to a Monolith release?** yes 2020.03.2

Rn entry 2020.03.2

---

packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md

- **What's changed?** Updated access token sentence
* [OKTA-284679](https://oktainc.atlassian.net/browse/OKTA-284679)

sentence tweak

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-2/index.md
packages/@okta/vuepress-site/docs/release-notes/index.md

- **What's changed?** Release notes 2020.03.2
- **Is this PR related to a Monolith release?** Yes 2020.03.2

Release 2020.03.2

---

packages/@okta/vuepress-site/docs/reference/api/factors/index.md

- **What's changed?** (see title)
* [OKTA-284600](https://oktainc.atlassian.net/browse/OKTA-284600)

Fixing anchor links

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- Authorization Server Object updated to show that audiences is an array

Update Authorization Server Docs

---

packages/@okta/vuepress-site/docs/reference/api-overview/index.md
packages/@okta/vuepress-site/docs/reference/api/authn/index.md
packages/@okta/vuepress-site/docs/release-notes/2020-03-1/index.md

- **What's changed?** made updates to coincide with the device behavior updates being made
- **Is this PR related to a Monolith release?** Yes 2020.03.2 
* [OKTA-283357](https://oktainc.atlassian.net/browse/OKTA-283357)

first draft WIP device behavior updates

---

packages/@okta/vuepress-site/docs/reference/api/features/index.md

bug in the docs fixed
* [OKTA--284494](https://oktainc.atlassian.net/browse/OKTA--284494)

Update feature stage to have state and not status

---

packages/@okta/vuepress-site/quickstart-fragments/widget/default-example/index.md

- cleaned up sign-in widget quickstart examples
- No
* [OKTA-278489](https://oktainc.atlassian.net/browse/OKTA-278489)

cleans up siw quickstart

---

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-authz-url/index.md
packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/get-access-token-using-service-app/index.md
packages/@okta/vuepress-site/docs/guides/submit-app/prepare-for-submission/index.md

Jv fixing links

---

packages/@okta/vuepress-site/docs/reference/api/factor-admin/index.md

- **What's changed?** Updated headings, fragments, and table sort

next header, fragment, table update

---

packages/@okta/vuepress-site/docs/guides/custom-url-domain/enable-the-custom-domain/index.md
packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md

- **What's changed?** Adding explicit caveat that custom domain must be a subdomain.
* [OKTA-285821](https://oktainc.atlassian.net/browse/OKTA-285821)

Jv adding customurl caveat

---

packages/@okta/vuepress-site/docs/release-notes/2020-03-2/index.md

- **What's changed?** adding additional blurb now that Prod deployment is complete
- **Is this PR related to a Monolith release?** yes 2020.03.2

adding in RN blurb now that prod has deployed

---

packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md

- **What's changed?**  Fix typo

Typo on type, "channelType" -> "string"

---

packages/@okta/vuepress-site/docs/reference/api/templates/index.md

- **What's changed?** Translations is an object, not an array.
* [OKTA-286133](https://oktainc.atlassian.net/browse/OKTA-286133)

Correcting table

---

packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md

- **What's changed?** Add a missing paramater
* N/A

Fix: Add `primary.name` param to table for get linked values

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md

- **What's changed?** Added requirement to have users with appropriate administrative permissions in Okta when using OAuth for Okta API feature

Requirement for users with administrative permissions for OAuth for Okta API feature

---

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/azure/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/facebook/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/google/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/linkedin/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/microsoft/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/oktatookta/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/openidconnect/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/saml2/appidpinokta.md
packages/@okta/vuepress-site/docs/guides/add-an-external-idp/create-authz-url/index.md

- **What's changed?** switched colon with emdash for item descriptions

colon to emdash

---

packages/@okta/vuepress-site/docs/guides/find-your-domain/overview/index.md

- **What's changed?** Customer Feedback making sure they know to be in the Dev Console when looking for their ORG URL
* [OKTA-287540](https://oktainc.atlassian.net/browse/OKTA-287540)

note for dev cons

---

packages/@okta/vuepress-site/docs/guides/find-your-domain/overview/index.md

- **What's changed?** noticed mistake in note

fixing wording in note:

---

scripts/update-se-drivers.sh

Adds support for chrome 81 tests

---

packages/@okta/vuepress-site/docs/release-notes/2020-04-0/index.md

RN entry for 2020.04.0

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/overview/index.md
packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md

- **What's changed?** Removing EA flag

removing EA

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js

moved location of mfa and session cookie guide as it was not in alphabetical order
no

move location of mfa and session cookie guide.

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md

Reverts okta/okta-developer-docs#1104

Revert "OKTA-286819: Add Sessions API scopes to implement oauth for okta guide"

---

packages/@okta/vuepress-site/docs/reference/api/features/index.md

- **What's changed?** features api headings, fragments, table sort

features api headings, fragments, table sort

---

packages/@okta/vuepress-theme-prose/util/frameworks.js

Fix missing icons for `go`, `java` and `php` in `/docs/guides/validate-access-tokens/go/overview/`
**Screenshot**
* [OKTA-284215](https://oktainc.atlassian.net/browse/OKTA-284215)

fix: missing icons for go java php

---

packages/@okta/vuepress-site/docs/reference/api/users/index.md

- **What's changed?** Trying to make the description of the salt property clearer.

Clarification for salt property of hashed password object

---

packages/@okta/vuepress-theme-prose/components/OnThisPage.vue

waiting for dom to render before sizing component or scrolling
no

waiting for dom to render before sizing component or scrolling.

---

packages/@okta/vuepress-site/docs/release-notes/2020-04-1/index.md

- **What's changed?** Added RN entry.
- **Is this PR related to a Monolith release?** 2020.04.1

Adding RN Entry for 2020.04.1

---

packages/@okta/vuepress-site/docs/reference/api/idps/index.md

- **What's changed?** fixed wording for issuerMode

issuerMode wording fix

---

packages/@okta/vuepress-site/docs/release-notes/2020-04-1/index.md

- **What's changed?** Docs update for weekly release.
- **Is this PR related to a Monolith release?** 2020.04.1

Release 2020.04.1

---

packages/@okta/vuepress-site/data/event-types.json

- **What's changed?** Event Catalog updates since 2019.03.1
- **Is this PR related to a Monolith release?** It should have been
* N/A

Updated event catalog

---

packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md

- **Is this PR related to a Monolith release?** Nyet
* N/A

Removing next section link

---

packages/@okta/vuepress-site/docs/concepts/saml/faqs/index.md
packages/@okta/vuepress-site/docs/concepts/saml/index.md
packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
packages/@okta/vuepress-site/docs/concepts/scim/index.md

Added link from SCIM guide to SSO guide.
Links to concept topics from the Guides
Added in pointers to FAQs in the concept topics
Updates to fix title positioning issues on concept & FAQ topics
* [OKTA-290055](https://oktainc.atlassian.net/browse/OKTA-290055)

Updates to internal links - SSO & SCIM guides

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/overview/index.md

- **What's changed?** adding org auth server note to overview page
* [OKTA-293687](https://oktainc.atlassian.net/browse/OKTA-293687)

adding org auth server note to overview page

---

packages/@okta/vuepress-site/docs/reference/api-overview/index.md

- **What's changed?** removing EA flag

removing EA flag

---

packages/@okta/vuepress-site/docs/reference/api/idps/index.md

Added description to the existing IdP API for PIV/Smart Card. 
- **Is this PR related to a Monolith release?**: No
* [OKTA-267855](https://oktainc.atlassian.net/browse/OKTA-267855)
Reviewers: @srinivasanagandla-okta @jakubvul-okta 
Optional reviewers: @okta/hybridaccess-team

Add documentation for CRUD API for Smart Card IDP

---

packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/before-you-begin/react-native/sample.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/configure-packages/react-native/installoktaauthsdk.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/handle-authentication-responses/react-native/handle-responses.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/next-steps/react-native/samples.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/primary-authentication/react-native/primaryauth.md

Add React Native code sample to guide under path `/docs/guides/build-custom-ui-mobile/react-native/before-you-begin/`
* [OKTA-233817](https://oktainc.atlassian.net/browse/OKTA-233817)

feat: add react-native code to guide - OKTA-233817

---

packages/@okta/vuepress-site/docs/release-notes/2020-05-0/index.md

- **What's changed?** Monthly release notes entry
- **Is this PR related to a Monolith release?** Yes 2020.05.0

Adding new release notes entry

---

packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/go/accesstoken.md

- **What's changed?** Add a more detailed guide for validating access token for Golang
* [OKTA-279312](https://oktainc.atlassian.net/browse/OKTA-279312)

Update validate_access_token guide for Golang

---

packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/php/accesstoken.md

- **What's changed?** Add a more detailed guide for validating access token for
* [OKTA-280079](https://oktainc.atlassian.net/browse/OKTA-280079)

Update validate_access_token guide for PHP

---

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md

Doc changes for clarifying DynamicScale for Delegated Authentication
No
* [OKTA-295781](https://oktainc.atlassian.net/browse/OKTA-295781)

Doc changes for clarifying DynamicScale for Delegated Authentication

---

packages/@okta/vuepress-site/docs/reference/token-hook/index.md

- **What's changed?** Added groups as reserved access token claim for Token Inline Hook

Added groups as reserved access token claim for Token Inline Hook

---

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md

Reverts okta/okta-developer-docs#1162

Revert "expression language update"

---

packages/@okta/vuepress-site/conductor.yml

#637  Description:
- **What's changed?** Adding redirect.

Adding redirect.

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Testing redirect.

Mk broken link redirect saml guide

---

packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/create-app-profile-attribute/index.md
packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/index.md

- **What's changed?** adding steps to create app profile attribute and access via custom claims
* [OKTA-296446](https://oktainc.atlassian.net/browse/OKTA-296446)

create app profile attribute and access via custom claims

---

packages/@okta/vuepress-site/docs/release-notes/2020-05-1/index.md

- **Is this PR related to a Monolith release?** 💯 
* N/A

RN entry for 2020.05.1

---

packages/@okta/vuepress-site/docs/reference/api/mappings/index.md

- **What's changed?** Updating headings, fragments, tables for style

Updating headings, fragments, tables for style

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- **What's changed?** additional style items found for auth servers

additional style items found for auth servers

---

packages/@okta/vuepress-site/docs/reference/api/factors/index.md

- **What's changed?** Factors api heading, fragments, table style updates

Factors api heading, fragments, table style updates

---

scripts/update-se-drivers.sh

- updates chrome version for tests
- No
* Allows Travis tests to pass

Adds support for chromedriver 83

---

packages/@okta/vuepress-site/docs/release-notes/2020-05-2/index.md

- **What's changed?** Rn entry 2020.05.2

Rn entry 2020.05.2

---

packages/@okta/vuepress-site/docs/reference/error-codes/index.md

- **What's changed?** error code style edits

error code style edits

---

package.json

- **What's changed?** Three bash scripts have been consolidated into one by someone who had no idea what they were doing.
* N/A

Merging doc update bash scripts

---

packages/@okta/vuepress-theme-prose/assets/css/components/_frameworkIconBlock.scss
packages/@okta/vuepress-theme-prose/global-components/FrameworkIconBlock.vue

fix icon in featured guide component.
**before** :
**after**:
no
* [OKTA-297137](https://oktainc.atlassian.net/browse/OKTA-297137)

Fix for saml, oidc icon issue in prose layout

---

packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/java/accesstoken.md

- **What's changed?** 2020.05.2 release notes
- **Is this PR related to a Monolith release?** Yes 2020.05.2

Release 2020.05.2

---

packages/@okta/vuepress-site/docs/guides/sharing-cert/update-target-app-with-kid/index.md

- **What's changed?** Removed unnecessary button on last page of guide
* [OKTA-299601](https://oktainc.atlassian.net/browse/OKTA-299601)

removed button

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

Addresses feedback from devforum - https://devforum.okta.com/t/documentation-for-introspect-endpoint/9450
No

Updates note about public clients calling /introspect endpoint

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** Removed stray quotes
* [OKTA-299712](https://oktainc.atlassian.net/browse/OKTA-299712)

removing quotes

---

packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md

This adds a FAQ item describing which parts of the SCIM protocol specification aren't yet supported by Okta's SCIM implementation.
No
* [OKTA-251207](https://oktainc.atlassian.net/browse/OKTA-251207)

SCIM Guide: update FAQ

---

packages/@okta/vuepress-site/.vuepress/nav/reference.js

- **What's changed?** adding Social IdP Settings to Reference left nav

adding in social IdP settings

---

packages/@okta/vuepress-site/docs/reference/api/authn/index.md

- Gave AuthN's SMS and Voice Call send-challenge a section on resend.  Text is copied from enroll resend, slightly reworded for challenge.
- Added a note about rate limit and switching providers to AuthN's SMS and Voice Call resend sections.  Note is coped from factors API.
* [OKTA-299320](https://oktainc.atlassian.net/browse/OKTA-299320)

OKTA-299320 : Adds note on sms and voice challenge resend

---

packages/@okta/vuepress-site/docs/concepts/saml/faqs/index.md
packages/@okta/vuepress-site/docs/guides/build-sso-integration/create-your-app/saml2/create.md

* Update FAQ with description of what SCIM spec elements we don't support
This adds a FAQ item describing which parts of the SCIM protocol specification aren't yet supported by Okta's SCIM implementation.
Resolves [OKTA-251207](https://oktainc.atlassian.net/browse/OKTA-251207)
* Fix user => User in SCIM API
Missed one when implementing the changes that Suasan requested as part of the SCIM guide updates last week.
* Update V2 GET Groups Example
Update the example to indicate that the return should not be NULL but rather a valid group ID and display name.
* Fixes links to AIW topics in SSO guide.
Also confirmed that all instances of app vs integration are precise.
Resolves OKTA-297178
* Update create.md
Review note from @susanharper-okta
- **Is this PR related to a …

Update SSO Guide (#1208)

---

packages/@okta/vuepress-site/docs/reference/api/idps/index.md

- **What's changed?** While using this reference for something else, found a couple of nits 

minor tweaks

---

packages/@okta/vuepress-site/docs/guides/protect-your-api/before-you-begin/go/create-app.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-cors/go/configcors.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-packages/go/configmid.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-packages/go/independ.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/next-steps/go/samples.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/go/reqautheverything.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/go/reqauthspecific.md

- **What's changed?** Adds content for the protect your api guide for Golang
* [OKTA-186467](https://oktainc.atlassian.net/browse/OKTA-186467)

Add content for 'protect your api' guides for go

---

packages/@okta/vuepress-site/docs/release-notes/2020-06-0/index.md

- **What's changed?** RN entry.
- **Is this PR related to a Monolith release?** 2020.06.0

Creating release notes entry

---

packages/@okta/vuepress-site/docs/reference/password-hook/index.md

- **What's changed?** Fix a typo for the hook type and add clarity to the command type
- **Is this PR related to a release of the Okta service?** No
@motikagan-okta FYI

Fix typo in Password Import hook type

---

packages/@okta/vuepress-site/data/error-codes.json
packages/@okta/vuepress-site/data/event-types.json
packages/@okta/vuepress-site/data/oauth2-error-codes.json
packages/@okta/vuepress-site/docs/reference/api/authn/index.md
packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
packages/@okta/vuepress-site/docs/release-notes/2020-06-0/index.md

- **What's changed?** Weekly docs release.
- **Is this PR related to a Monolith release?** 2020.06.0

Release 2020.06.0

---

packages/@okta/vuepress-site/code/react/index.md

- Adds a link
- No
* [OKTA-301427](https://oktainc.atlassian.net/browse/OKTA-301427)

adds a link to the react SIW quickstart on the react quickstart page

---

packages/@okta/vuepress-site/docs/release-notes/2020-06-1/index.md

- **What's changed?** Release notes entry for 2020.06.1
n/a

Adding new rn entry (#1238)

---

packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md

- **What's changed?** Fix example request at https://developer.okta.com/docs/reference/api/linked-objects/#request-example-2 from POST to GET.
* [OKTA-304705](https://oktainc.atlassian.net/browse/OKTA-304705)

OKTA-304705: Fix request example for get linked object definition by name api

---

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md

Explain how to obtain the name of an application for accessing app and app user attributes in EL.
Correct some examples to use valid names.
Fix tiny typo in initial text.
- Explain how to obtain the name of an application for accessing app and app user attributes in EL.
- Correct some examples to use valid names.
- Fix tiny typo in initial text.
- This is existing functionality in production.
* [OKTA-218806](https://oktainc.atlassian.net/browse/OKTA-218806)

Update examples of app and org attributes in EL

---

packages/@okta/vuepress-site/docs/guides/enable-cors/granting-cors/index.md
packages/@okta/vuepress-site/docs/guides/enable-cors/testing/index.md
packages/@okta/vuepress-theme-prose/global-components/CorsTest.vue

- **What's changed?** Implement the old cors test.  
Styling is, and always has been pretty bad.  We should update this .
* [OKTA-285858](https://oktainc.atlassian.net/browse/OKTA-285858)

Re-add CorsTest Component and enable in guide

---

packages/@okta/vuepress-site/docs/reference/password-hook/index.md

- **What's changed?** Added a note consistent with the SAML inline hook to indicate that only one hook is allowed.

Update Password Import Inline Hook limit

---

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md

- **What's changed?** Added metadata rate limit cache explanation
* [OKTA-301148](https://oktainc.atlassian.net/browse/OKTA-301148)
Primary Reviewer: @yuliu-okta 
Other Reviewers: @okta/developerdocs 
Before:
After:

Added metadata rate limit cache explanation

---

packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/findcreds/index.md
packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/index.md
packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/overview/index.md

- **What's changed?** style edit for guide
* [OKTA-304632

style edit

---

packages/@okta/vuepress-site/docs/guides/find-your-domain/findorg/index.md
packages/@okta/vuepress-site/docs/guides/find-your-domain/index.md
packages/@okta/vuepress-site/docs/guides/find-your-domain/overview/index.md

- **What's changed?** style edit and added link to Okta Org concept piece
* [OKTA-304629](https://oktainc.atlassian.net/browse/OKTA-304629)

tweaks for guide

---

packages/@okta/vuepress-site/docs/guides/build-sso-integration/before-you-begin/openidconnect/prep.md
packages/@okta/vuepress-site/docs/guides/build-sso-integration/specify-your-settings/openidconnect/settings.md

Clarify the Single Logout operations for OIDC and SAML in the SSO guide.
No
* [OKTA-272673](https://oktainc.atlassian.net/browse/OKTA-2726730)

Update logout URI info

---

packages/@okta/vuepress-site/.vuepress/nav/reference.js

- **What's changed?** Adding a link to the reference page about the Password Import Inline Hook to the left-side nav sidebar.

Adding Password Hook to Sidebar Links

---

packages/@okta/vuepress-site/docs/guides/revoke-tokens/index.md
packages/@okta/vuepress-site/docs/guides/revoke-tokens/overview/index.md
packages/@okta/vuepress-site/docs/guides/revoke-tokens/removeusersess/index.md
packages/@okta/vuepress-site/docs/guides/revoke-tokens/revokeatrt/index.md

- **What's changed?** Added request examples, style edit, authorization server clarification, split out into guide style
* [OKTA-304794](https://oktainc.atlassian.net/browse/OKTA-304794)

Revoke token guide updates

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- **What's changed?** clarify baseURL for AS

clarify baseURL for AS

---

packages/@okta/vuepress-site/docs/guides/sign-into-web-app/before-you-begin/php/create-app.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/php/addconfigpkg.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/php/configmid.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/define-callback/php/define-route.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/get-user-info/php/getuserinfo.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/next-steps/php/samples.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/php/login-redirect.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/require-authentication/php/allowanon.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/require-authentication/php/reqautheverything.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/require-authentication/php/reqauthspecific.md

- **What's changed?** Add guide for PHP Sign Users In to Webapp
* [OKTA-264629](https://oktainc.atlassian.net/browse/OKTA-264629)

Add sign users in guide for PHP

---

packages/@okta/vuepress-site/docs/guides/protect-your-api/before-you-begin/php/create-app.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-cors/php/configcors.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-packages/php/configmid.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/configure-packages/php/independ.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/next-steps/php/samples.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/php/reqautheverything.md
packages/@okta/vuepress-site/docs/guides/protect-your-api/require-authentication/php/reqauthspecific.md

- **What's changed?** Adds the guide for Protecting your API in PHP.
* [OKTA-264711](https://oktainc.atlassian.net/browse/OKTA-264711)

Add protect your api guide for PHP

---

packages/@okta/vuepress-site/code/android/index.md
packages/@okta/vuepress-site/code/angular/index.md
packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
packages/@okta/vuepress-site/code/dotnet/aspnet/index.md
packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
packages/@okta/vuepress-site/code/dotnet/jwt-validation/index.md
packages/@okta/vuepress-site/code/ios/index.md
packages/@okta/vuepress-site/code/java/spring/index.md
packages/@okta/vuepress-site/code/javascript/index.md
packages/@okta/vuepress-site/code/nodejs/index.md
packages/@okta/vuepress-site/code/php/index.md
packages/@okta/vuepress-site/code/react-native/index.md
packages/@okta/vuepress-site/code/react/index.md
packages/@okta/vuepress-site/code/react/okta_react/index.md
packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
packages/@okta/vuepress-site/code/vue/index.md
tests/selenium/spec/code-layout-spec.js

Update code pages to remove reference to quickstarts

---

packages/@okta/vuepress-site/code/android/index.md
packages/@okta/vuepress-site/code/angular/index.md
packages/@okta/vuepress-site/code/angular/okta_angular_auth_js/index.md

Missed a few pages

---

packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/ios/configuremid.md

Add logoutRedirectUri key into Okta.plist example
* [OKTA-308496](https://oktainc.atlassian.net/browse/OKTA-308496)

OKTA-308496 - QA Guide: Sign users in to your mobile app (iOS)

---

packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md

- **What's changed?** Added "API" suffix to title of the Authorization Servers page.

add API suffix to Authorization Servers title

---

packages/@okta/vuepress-site/code/library-versions/index.md

Update .NET library versions.
Preview:
No
* [OKTA-286698](https://oktainc.atlassian.net/browse/OKTA-286698)

Update .NET content.

---

packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/aspnet/configmid.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/aspnetcore/configmid.md
packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/aspnetcore3/configmid.md

Add details of how to change the AuthorizationServerId property when using different Authorization Server in ASP.NET Web App guides.
No
* [OKTA-280564](https://oktainc.atlassian.net/browse/OKTA-280564)

Update ASP.NET Web App guides

---

packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/overview/index.md
packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/sign-the-csr/index.md

- **What's changed?** In the guide on signing SAML certificates, adding some more content, suggested by Brian, on signing the CSR using popular CAs.
* [OKTA-309083](https://oktainc.atlassian.net/browse/OKTA-309083)

Adding more specific info on signing CSR using 3rd-party CA for SAML certs

---

packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/sign-the-csr/index.md
packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/update-the-key-credential/index.md

- **What's changed?** added caution formatting and updated wording

added caution per cwu

---

packages/@okta/vuepress-site/docs/reference/api/idps/index.md
packages/@okta/vuepress-site/docs/reference/postman-collections/index.md

- **What's changed?** Apple IdP API
- **Is this PR related to a Monolith release?** 2020.07.0
* [OKTA-309869](https://oktainc.atlassian.net/browse/OKTA-309869)

Apple IdP API

---

packages/@okta/vuepress-site/docs/guides/sharing-cert/generate-new-credential/index.md
packages/@okta/vuepress-site/docs/guides/sharing-cert/index.md
packages/@okta/vuepress-site/docs/guides/sharing-cert/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/sharing-cert/overview/index.md
packages/@okta/vuepress-site/docs/guides/sharing-cert/share-kid-with-target-app/index.md
packages/@okta/vuepress-site/docs/guides/sharing-cert/update-source-app-with-cert/index.md
packages/@okta/vuepress-site/docs/guides/sharing-cert/update-target-app-with-kid/index.md
packages/@okta/vuepress-site/docs/reference/api/apps/index.md

- **What's changed?** Made the QA item changes to the guide
* [OKTA-302598](https://oktainc.atlassian.net/browse/OKTA-302598)

updates to guide

---

packages/@okta/vuepress-site/docs/release-notes/2020-07-0/index.md

- **What's changed?** release notes entries
- **Is this PR related to a Monolith release?** yes, 2020.07.0

Rn entry 2020.07.0

---

packages/@okta/vuepress-site/docs/guides/submit-app/submission1-general/index.md

Changes to logo size and resolution guidance.
Yes. 2020.07.0
* [OKTA-296270](https://oktainc.atlassian.net/browse/OKTA-296270)

Updates logo size limits. 

---

packages/@okta/vuepress-site/docs/reference/api/factors/index.md

- Add API documentation for YubiKey OTP Seed Upload and Get
- **Is this PR related to a Monolith release?** Yes, 2020.07.0
* [OKTA-304377](https://oktainc.atlassian.net/browse/OKTA-304377)

Adding YubiKey seed upload and get API endpoints doc

---

packages/@okta/vuepress-site/docs/reference/registration-hook/index.md

- **What's changed?** Fixing a link to h.o.c. and using an alias.

Fixing a broken link to h.o.c.

---

packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md

- **What's changed?** Bad links are now good links.
- **Is this PR related to a Monolith release?** No. Merge this ASAP.
* N/A

Fixing some 404s

---

packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md

- **What's changed?** updated scope info for state and nonce for the authorize endpoint

state and nonce are required for the authorize endpoint

---

packages/@okta/vuepress-site/code/php/simplesamlphp/index.md

- **What's changed?** Updates and fixes some typos
* [OKTA-288580](https://oktainc.atlassian.net/browse/OKTA-288580)

Update text and typos

---

packages/@okta/vuepress-site/docs/guides/sign-into-web-app/define-callback/springboot/define-route.md

Fix wording on spring "define-callback" page

---

packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/springboot/login-redirect.md

This reads a little funny to me, so it may need a little wordsmithing

Add note that Spring automatically handles the login redirect

---

packages/@okta/vuepress-site/.vuepress/config.js
packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md

- updates the /code/javascript/okta_sign-in_widget/ to reflect v4 of the widget (mainly that pkce is now the default)
- No
* [OKTA-307997](https://oktainc.atlassian.net/browse/OKTA-307997)

Updates base widget code guide to v4 of widget

---

packages/@okta/vuepress-site/code/library-versions/index.md

- Updates versions and retirements for JS SDKs
- Changed any past retiring dates to "retired"
- updates link to okta-vue to new repo
- No
* [OKTA-316533](https://oktainc.atlassian.net/browse/OKTA-316533)

Updates versions and retirements for JS SDKs

---

packages/@okta/vuepress-site/.vuepress/nav/codePages.js
packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/index.md
packages/@okta/vuepress-theme-prose/components/Sidebar.vue
packages/@okta/vuepress-theme-prose/components/SidebarItem.vue

Support tree navigation in `/docs/guides` sidebar based on provided nav config. 
https://recordit.co/auWmJ4f1iU
* [OKTA-311410](https://oktainc.atlassian.net/browse/OKTA-311410)

feat: tree nav bar for guides - OKTA-311410

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/index.md
packages/@okta/vuepress-site/docs/guides/build-sso-integration/index.md
packages/@okta/vuepress-site/docs/guides/build-sso-integration/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/submit-app/index.md

Updates the guides to remove the OIN prefixes from the titles.
Also correct the order of the "Sign your users out" guide in the new navigation.
No
* [OKTA316889](https://oktainc.atlassian.net/browse/OKTA-316889)

Remove OIN prefixes

---

packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md

- Updates the code/react SIW page to reflect the changes in okta-react 2.x and 3.x
- No
* [OKTA-313093](https://oktainc.atlassian.net/browse/OKTA-313093)

Updates code/react siw docs for v3.x

---

packages/@okta/vuepress-site/docs/release-notes/2020-07-2/index.md

- **What's changed?** Added release notes entry for 2020.07.2
n/a

Rn entry 2020.07.2 (#1323)

---

packages/@okta/vuepress-site/docs/reference/api/apps/index.md

there is no `displayName`, it seems to work against `label` (but please verify)

Update to Apps API reference

---

packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/static-whitelist/index.md
packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md

- **What's changed?** added the Google note to two additional pages
* [OKTA-297301](https://oktainc.atlassian.net/browse/OKTA-297301)

adding note to additional page

---

packages/@okta/vuepress-site/docs/release-notes/2020-08-0/index.md

- **What's changed?** Release Notes Entry for 2020.08.0
- **Is this PR related to a Monolith release?** yes 2020.08.0

Rn entry 2020.08.0

---

packages/@okta/vuepress-site/code/library-versions/index.md

Update entry for the .NET management SDK and the .NET Authn SDK in the library versions table.
No
* [OKTA-313038](https://oktainc.atlassian.net/browse/OKTA-313038)

Update entry for .NET SDKs in the library versions table.

---

scripts/publish.sh

OKTA-307115
Fixing issues in CI.
* [OKTA-307115](https://oktainc.atlassian.net/browse/OKTA-307115)

ci: Fix publish scripts

---

scripts/publish.sh

OKTA-307115
Fix conductor payload to fix broken deployment
* [OKTA-307115](https://oktainc.atlassian.net/browse/OKTA-307115)

ci: Update payload to conductor to fix deployment

---

packages/@okta/vuepress-site/code/library-versions/index.md
packages/@okta/vuepress-site/code/react-native/index.md
packages/@okta/vuepress-site/quickstart-fragments/react-native/default-example/index.md

Update react-native repo URLs to point to the new one.
* [OKTA-311322](https://oktainc.atlassian.net/browse/OKTA-311322)

doc: update react-native repo urls

---

packages/@okta/vuepress-site/docs/guides/validate-access-tokens/overview/java/accesstoken.md

- Add a note about replacing package version in the validate-access-tokens java guide 
- No
- some dev confusion

Add a note about replacing package version

---

packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md

Fixes bug in Angular SIW guide
* [OKTA-301464](https://oktainc.atlassian.net/browse/OKTA-301464)

fix: bug in angular siw guide - OKTA-301464

---

packages/@okta/vuepress-site/code/dotnet/aspnet/index.md
packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md

Fixed broken link to the .NET Core SDK, added clarifying descriptions for all GitHub links, and included the new Okta Xamarin SDK at the bottom of the Other .NET Libraries section.
Broken and missing links

Fix links to all .NET libraries

---

packages/@okta/vuepress-site/code/java/index.md

Adds Java docs links and links to Authn, JWT verifier, and hooks SDKs

Update /code/java to include other Java projects

---

packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/sessions.json
packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
packages/@okta/vuepress-site/docs/reference/postman-collections/index.md

- Remove deprecated method from Session API Postman collection
* [OKTA-319730](https://oktainc.atlassian.net/browse/OKTA-319730)

OKTA-319730 Remove deprecated method from Session API Postman collection

---

packages/@okta/vuepress-site/docs/guides/custom-hosted-signin/edit-the-sign-in-page/index.md

The term backdoor should not be used

Use the term "backup" for the custom sign-in page

---

packages/@okta/vuepress-theme-prose/global-components/RequireClassicUI.vue

To use this tag add `<RequireClassicUI/>` at the top of the page.
Write a message for this pull request. The first block
of text is the title and the rest is the description.

Create vue component to mark page as needing the "classic ui"

---

packages/@okta/vuepress-site/.vuepress/nav/concepts.js
packages/@okta/vuepress-site/docs/concepts/how-okta-works/index.md

- **What's changed?** How Okta works concept
* [OKTA-320475](https://oktainc.atlassian.net/browse/OKTA-320475)

How Okta works concept

---

packages/@okta/vuepress-site/docs/guides/custom-url-domain/enable-the-custom-domain/index.md
packages/@okta/vuepress-site/docs/guides/custom-url-domain/gather-information/index.md
packages/@okta/vuepress-site/docs/guides/custom-url-domain/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md
packages/@okta/vuepress-site/docs/guides/custom-url-domain/update-other-okta-settings/index.md

- **What's changed?** Update of existing custom URL domain doc for CDG
* [OKTA-320487](https://oktainc.atlassian.net/browse/OKTA-320487)

Update of existing custom URL domain doc for CDG

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/configure-access-policy/configure-token-lifetime-per-client/index.md
packages/@okta/vuepress-site/docs/guides/configure-access-policy/index.md
packages/@okta/vuepress-site/docs/guides/configure-access-policy/limit-scopes-clients-can-access/index.md
packages/@okta/vuepress-site/docs/guides/configure-access-policy/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/configure-access-policy/overview/index.md
packages/@okta/vuepress-site/docs/guides/index.md

- **What's changed?** new configure access policy guide
* [OKTA-320463](https://oktainc.atlassian.net/browse/OKTA-320463)

new configure access policy guide

---

packages/@okta/vuepress-site/.vuepress/nav/concepts.js
packages/@okta/vuepress-site/docs/concepts/policies/index.md

- **What's changed?** new policies concept for CDG
* [OKTA-320484](https://oktainc.atlassian.net/browse/OKTA-320484)

new policies concept for CDG

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/index.md
packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/before-you-begin/index.md
packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/configure-self-service-registration-policy/index.md
packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/customize-link-in-widget/index.md
packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/disable-security-image/index.md
packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/index.md
packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/overview/index.md

- **What's changed?** New content for self-service registration
* [OKTA-320459](https://oktainc.atlassian.net/browse/OKTA-320459)

self-service registration

---

packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/add-custom-claim/index.md

- **What's changed?** Fixed a typo in sample ID Token.
* [OKTA-325924](https://oktainc.atlassian.net/browse/OKTA-325924)

fix typo in in custom claims sample body

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Fixed some redirects
* N/A

Jv fix redirect

---

packages/@okta/vuepress-site/conductor.yml

Trying one more way

---

packages/@okta/vuepress-site/conductor.yml

- **What's changed?** Trying to fix broken links

broken links

---

packages/@okta/vuepress-site/docs/concepts/how-okta-works/index.md

- **What's changed?** Fixing the heading size

fixing heading size

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/before-you-begin/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/prompt-factor-group/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/prompt-factor-outside-us/index.md
packages/@okta/vuepress-site/docs/guides/index.md

- **What's changed?** Configure Sign-On Policies guide
* [OKTA-320461](https://oktainc.atlassian.net/browse/OKTA-320461)

signon policy config guide

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/before-you-begin/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/prompt-factor-group/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/prompt-factor-outside-us/index.md
packages/@okta/vuepress-site/docs/guides/index.md

- **What's changed?** had to create a new branch
Original approved PR: https://github.com/okta/okta-developer-docs/pull/1400
* [OKTA-320461](https://oktainc.atlassian.net/browse/OKTA-320461)

new signon policy branch

---

packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/before-you-begin/android/sample.md
packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/configure-packages/android/installoktaauthsdk.md

Update android custom sign-in instructions to be same as updated [README](https://github.com/okta/okta-oidc-android#Sign-in-with-your-own-UI)

Update android custom-sign-in

---

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md

Changed `3x to 1000x` to `5x to 1000x`.
Changed `e.g. One App, Enterprise or IT Products` to `One App or Enterprise`
No
* [OKTA-326593](https://oktainc.atlassian.net/browse/OKTA-326593)

Remove 3x DS multiplier and IT products for DynamicScale from public facing dev docs

---

packages/@okta/vuepress-site/docs/reference/api/sessions/index.md

- Update the Developer Docs for /api/v1/sessions to clearly indicate the api does not support direct authentication
- This PR is not related to a monolith release
* [OKTA-323411](https://oktainc.atlassian.net/browse/OKTA-323411)

OKTA-323411

---

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/create-oauth-app/index.md
packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/request-access-token/index.md

Postman handles the authorization code exchange as well as PKCE so it's just as easy to use for this guide.

do not recommend Implicit for testing

---

packages/@okta/vuepress-site/docs/concepts/authentication/index.md
packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/overview/index.md
packages/@okta/vuepress-site/docs/guides/implement-auth-code/overview/index.md
packages/@okta/vuepress-site/docs/guides/session-cookie/overview/index.md
packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
packages/@okta/vuepress-site/docs/reference/api/users/index.md

- **What's changed?** Adding a note regarding the third-party cookie blocking issue to the pages that document affected functionality. The note links to the knowledge base article.
* [OKTA-326008](https://oktainc.atlassian.net/browse/OKTA-326008)

Adding notes on third-part cookie issue

---

packages/@okta/vuepress-site/docs/guides/style-the-widget/style-self-hosted/index.md

- **What's changed?** Added link to CSS Styling video tutorial and Live widget.
- **Is this PR related to a Monolith release?** CDG-V1
* [OKTA-320669](https://oktainc.atlassian.net/browse/OKTA-320669)

Added link to video tutorial and Live Widget

---

packages/@okta/vuepress-site/docs/release-notes/2020-09-1/index.md

Release Notes for 2020.09.1
Yes, 2020.09.1

 Approved by security

---

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md

- Added documentation for secret length minimums to use shared secret JWT HS Algorithms
- PR related to Nimbus Library Upgrade (scheduled for production in October)
* [OKTA-312145](https://oktainc.atlassian.net/browse/OKTA-312145)

Added documentation for secret length minimums to use shared secret JWT HS Algorithms

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/.vuepress/scripts/build-guides-info.js
packages/@okta/vuepress-site/docs/guides/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/add-user/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/create-org/cli/create-org.md
packages/@okta/vuepress-site/docs/guides/quickstart/create-org/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/create-org/website/create-org.md
packages/@okta/vuepress-site/docs/guides/quickstart/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
packages/@okta/vuepress-site/docs/guides/quickstart/register-app/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
packages/@okta/vuepress-site/docs/guides/quickstart/sign-in/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/try-api/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/try-api/java/try-api.md
packages/@okta/vuepress-site/docs/guides/quickstart/using-console/index.md

- **What's changed?** QuickStart guide for a developer new to Okta to create an org and add authentication to their app. 
* [OKTA-320468](https://oktainc.atlassian.net/browse/OKTA-320468)
* [OKTA-320469](https://oktainc.atlassian.net/browse/OKTA-320469)
* [OKTA-320470](https://oktainc.atlassian.net/browse/OKTA-320470)
* [OKTA-320471](https://oktainc.atlassian.net/browse/OKTA-320471)
* [OKTA-320472](https://oktainc.atlassian.net/browse/OKTA-320472)
* [OKTA-320473](https://oktainc.atlassian.net/browse/OKTA-320473)
* [OKTA-320474](https://oktainc.atlassian.net/browse/OKTA-320474)

CDG QuickStart 

---

packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/android/installsdk.md
packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/configure-packages/android/installsdk.md

* [OKTA-330023](https://oktainc.atlassian.net/browse/OKTA-330023)

Fix 404 link for android setup

---

packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md

This PR resolves the Python HTTP server docs that have been confusing everyone.

Fixing Python instructions

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/index.md
packages/@okta/vuepress-site/docs/guides/production-deployment/deployment-checklist/index.md
packages/@okta/vuepress-site/docs/guides/production-deployment/index.md

- **What's changed?** Updating Nav Pane and Fixing Links

Updating Nav Pane and Fixing Links

---

packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
packages/@okta/vuepress-site/docs/guides/quickstart/try-api/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/using-console/index.md

- **What's changed?** Changed the recommended redirect URI in the steps for registering an app using the website; also, a minor change at the end of the guide, so it ends less abruptly.

QuickStart: Change recommended redirect URI for consistency

---

packages/@okta/vuepress-site/docs/concepts/how-okta-works/index.md
packages/@okta/vuepress-site/docs/guides/configure-access-policy/next-steps/index.md
packages/@okta/vuepress-site/docs/guides/configure-access-policy/overview/index.md
packages/@okta/vuepress-site/docs/guides/configure-signon-policy/before-you-begin/index.md
packages/@okta/vuepress-site/docs/guides/email-customization/next-steps/index.md

- **What's changed?** added some links to new content and fixed a couple issues

adding links

---

packages/@okta/vuepress-site/.vuepress/nav/guides.js
packages/@okta/vuepress-site/docs/guides/index.md
packages/@okta/vuepress-site/docs/guides/migrate-to-okta/bulk-migration-with-credentials/index.md
packages/@okta/vuepress-site/docs/guides/migrate-to-okta/index.md
packages/@okta/vuepress-site/docs/guides/migrate-to-okta/migrate-users-password-hooks/index.md
packages/@okta/vuepress-site/docs/guides/migrate-to-okta/prerequisites/index.md

- migration guide
* [OKTA-320480](https://oktainc.atlassian.net/browse/OKTA-320480)
* [OKTA-320478](https://oktainc.atlassian.net/browse/OKTA-320478)
* [OKTA-320479](https://oktainc.atlassian.net/browse/OKTA-320479)

Added migration docs

---

packages/@okta/vuepress-site/docs/reference/api/system-log/index.md

- **What's changed?** Inclusive language update for SIP team
* [OKTA-326896](https://oktainc.atlassian.net/browse/OKTA-326896)
- @okta/developerdocs 
- @mpatnode

Inclusive language update for SIP team

---

packages/@okta/vuepress-site/docs/release-notes/2020-09-3/index.md

API Release notes docs for 2020.09.3
Yes. 2020.09.3
* [OKTA-323343](https://oktainc.atlassian.net/browse/OKTA-323343)

API Release Notes - 2020.09.3

---

packages/@okta/vuepress-site/docs/concepts/policies/index.md

- **What's changed?** Fixed typo

Fixing Typo on Policies concept page

---

packages/@okta/vuepress-site/docs/guides/enable-cors/overview/index.md
packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/create-oauth-app/index.md
packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md

- **What's changed?** CORS and O4O changes
* [OKTA-332192](https://oktainc.atlassian.net/browse/OKTA-332192)

CORS and O4O changes

---

packages/@okta/vuepress-site/docs/guides/validate-id-tokens/overview/index.md

- **What's changed?** removing node.js
* [OKTA-325989](https://oktainc.atlassian.net/browse/OKTA-325989)

removing node.js

---

packages/@okta/vuepress-site/docs/reference/api/system-log/index.md

* [OKTA-320869](https://oktainc.atlassian.net/browse/OKTA-320869)

update "Self Link Response Header" doc to make headers case lowercase

---

packages/@okta/vuepress-site/docs/reference/api/idps/index.md

- **What's changed?** SAML updates to IDPS page
* [OKTA-332191](https://oktainc.atlassian.net/browse/OKTA-332191)

SAML updates to IDPS page

---

packages/@okta/vuepress-theme-prose/assets/css/components/_top-bar.scss

- Fast-fix for https://github.com/okta/okta-developer-docs/issues/1493

Fixed issue with hover and closing dropdown 

---

packages/@okta/vuepress-site/docs/guides/quickstart/add-user/index.md
packages/@okta/vuepress-site/docs/guides/quickstart/create-org/index.md

Minor typos and formatting updates to Quick Start Guide: 
https://developer.okta.com/docs/guides/quickstart/website/add-user/
- **What's changed?** Removed an extra period; cleaned up step 3.
* n/a

Fixing minor typos and formatting in Quick Start Guide.

---

packages/@okta/vuepress-site/.vuepress/nav/codePages.js

- Fixed config to show subsections correctly
Before: 
After:
Need to mention: there is some issues with active states of links. Will be fixed in connected issue 
*[OKTA-320822](https://oktainc.atlassian.net/browse/OKTA-320822)
* [OKTA-320797](https://oktainc.atlassian.net/browse/OKTA-320797)

Additional levels in Languages and SDK 

---

packages/@okta/vuepress-site/docs/release-notes/2020-09-4/index.md
packages/@okta/vuepress-theme-prose/assets/css/components/_top-bar.scss

API Release Notes content for the 2020.09.4 release
Yes. 2020.09.4
* [OKTA-252750](https://oktainc.atlassian.net/browse/OKTA-252750)
* [OKTA-325187](https://oktainc.atlassian.net/browse/OKTA-325187)
* [OKTA-331828](https://oktainc.atlassian.net/browse/OKTA-331828)
* [OKTA-333063](https://oktainc.atlassian.net/browse/OKTA-333063)

Publish Release 2020.09.4

---

packages/@okta/vuepress-site/docs/reference/api/policy/index.md

- **What's changed?** No Content is 204, not 200.

Fixing http code

---

packages/@okta/vuepress-site/docs/guides/index.md

- **What's changed?** New Guides overview page 
* [OKTA-331499](https://oktainc.atlassian.net/browse/OKTA-331499)

new overview page

---

packages/@okta/vuepress-site/docs/guides/index.md

- **What's changed?** period not comma, thanks Brian!

period not comma

---

packages/@okta/vuepress-site/docs/reference/api/idps/index.md

Reverts okta/okta-developer-docs#1483
This is part of 2020.10.0.

Revert "SAML updates to IDPS page"

---

packages/@okta/vuepress-site/docs/guides/custom-url-domain/overview/index.md

- **What's changed?** Adding caveat per Bryant Ng
* [OKTA-332009](https://oktainc.atlassian.net/browse/OKTA-332009)

adding caveat per Bryant

---

packages/@okta/vuepress-site/docs/reference/api/factors/index.md

- **What's changed?** Add more details about factor profiles so there is less developer confusion when trying to enroll the Custom HOTP factor.
* [OKTA-333624](https://oktainc.atlassian.net/browse/OKTA-333624)

Add more info about factor profiles for Custom HOTP

---

packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/nodeexpress/remotesignout.md
packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-your-app/springboot/localsignout.md
yarn.lock

- Fix the code snippet that `Form` tag is not closed.
- `yarn.lock` got updated itself when I run `yarn install`.
- https://oktainc.atlassian.net/browse/OKTA-335034

fix: close tag form

---

packages/@okta/vuepress-theme-prose/components/Sidebar.vue
packages/@okta/vuepress-theme-prose/components/SidebarItem.vue

A copy of https://github.com/okta/okta-developer-docs/pull/1517 (w/ merge conflicts fixed)
No
* [OKTA-320822](https://oktainc.atlassian.net/browse/OKTA-320822)

Fixed active states for nav bar [#1517 clone]
