okta/okta-developer-docs

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add release note entries 
- **Is this PR related to a Monolith release?** Yes, Release 2022.02.0
* [OKTA-464427](https://oktainc.atlassian.net/browse/OKTA-464427)
> Adding new RN entries

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **Api docs for client credentials management** 
- **Is this PR related to a Monolith release? Yes**  2022.02.0
* [OKTA-461540](https://oktainc.atlassian.net/browse/OKTA-461540)
* [OKTA-461541](https://oktainc.atlassian.net/browse/OKTA-461541)
> OKTA-461540 OKTA-461541 api docs for client creds management

- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Add link to SIW upgrade page
* [OKTA-463289](https://oktainc.atlassian.net/browse/OKTA-463289)
> Add link to SIW upgrade page

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Update to `navbar.const.js` file to address issue.
* [OKTA-453977](https://oktainc.atlassian.net/browse/OKTA-453977)
> OKTA-453977 - Left-hand navigation fix for redirect vs embedded concept page

- packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
- **What's changed?** Added burst rate limit system log event info
* [OKTA-467168](https://oktainc.atlassian.net/browse/OKTA-467168)
> Add BRL system log event info

- packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md
- **What's changed?** removed brackets from bullet item
> removing brackets

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/nut-facts-samplecode.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/nutrition.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/nut-facts-samplecode.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/nutrition.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/nutrition.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/nutrition.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/index.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/nut-facts-samplecode.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/nutrition.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/nutrition.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/nutrition.md
- **What's changed?** Add nutrition.md snippets to Implement authorization by grant type docs to customize the stack-selector options and to add OIE org link for Interaction Code.
https://620175d8a3c5e5490a000aeb--reverent-murdock-829d24.netlify.app/docs/guides/implement-grant-type/authcode/main/
* [OKTA-460712](https://oktainc.atlassian.net/browse/OKTA-460712)
> OKTA-460712 Update Implement grant type docs to accommodate new stack-selector and OIE org link

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Merging release note branch into release branch
- **Is this PR related to a Monolith release?** 2022.02.1
* [OKTA-467165](https://oktainc.atlassian.net/browse/OKTA-467165)
> Rn entry 2022.02.1

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Addition of weekly release notes for February 9, 2022
- **Is this PR related to a Monolith release?** 2022.02.1
* [OKTA-467165](https://oktainc.atlassian.net/browse/OKTA-467165)
> Add weekly release notes for 2022.02.1

- packages/@okta/vuepress-theme-prose/assets/css/layouts/_authorizationLayout.scss
- **What's changed?** Adjust flex-direction of auth0--banner on smaller devices
* [OKTA-470408](https://oktainc.atlassian.net/browse/OKTA-470408)
***Large***
***Small***
> Change flex-direction of auth0-banner on smaller devices

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- **What's changed?** Test
- **Is this PR related to a Monolith release?** Test
* Test
> bd-staging-test-adding-url-in-common-hooks

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- **What's changed?** Test 2
- **Is this PR related to a Monolith release?** Test 2
* Test 2
> Test 2 to Staging

- package.json
- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- yarn.lock
- Fixes chunk load error on re-build
* [3.Docs loading error, Occasional breakage of links](https://trello.com/c/icsPAzaJ/4-3docs-loading-error-occasional-breakage-of-links)
> Docs loading error, Occasional breakage of links

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- **What's changed?** Test 3
- **Is this PR related to a Monolith release?** Test 3
* Test
> Testing on staging

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- **What's changed?** Test 4
- **Is this PR related to a Monolith release?**Test 4
* Test 4
> Testing on staging 4

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- **What's changed?** test 5
- **Is this PR related to a Monolith release?** test 5
* test 5
> Staging test 

- package.json
- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- yarn.lock
- **What's changed?** Fixes chunk load on re-build (FYI: @ulyanash merged your original PR into staging for testing. All good to go!
- **Is this PR related to a Monolith release?** n/
* [OKTA-440925](https://oktainc.atlassian.net/browse/OKTA-440925)
> OKTA-440925 Fixing site loading error

- packages/@okta/vuepress-site/docs/reference/api/asa/attributes/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/audits/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/clients/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/entitlements/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/service-users/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/teams/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/users/index.md
- **What's changed?** Updating minor spacing issues for ASA API reference pages
* n/a
> Updating minor spacing issues for ASA API reference pages

- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
- **What's changed?** Fix typo in **Test your Okta SCIM integration > Review test results** section.
* [OKTA-471556](https://oktainc.atlassian.net/browse/OKTA-471556)
> Fix typo in Test your Okta SCIM integration

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Update subdomain caveat in Custom URL guide.
* N/A - request from dev
> TBS Update subdomain caveat in Custom URL guide

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- **What's changed?** Removed the snippet reference in the title for the IdP pages since snippets do not render on the right-nav.
* [OKTA-467429](https://oktainc.atlassian.net/browse/OKTA-467429)
> OKTA-467429 - Fix title for social/external IdPs pages

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** updated names in navbar
> navbar update

- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/createproject.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/getuserinfo.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/reqauthspecific.md
- **What's changed?** Fix typos and use quotes consistently in code.
> Improve the React SPA Quickstart

- packages/@okta/vuepress-site/code/javascript/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-overview/main/index.md
- **What's changed?** Minor fixes from review spreadsheet to Sign users in / Overview and Code / JavaScript page
* n/a
> Minor fixes from sheet review - Sign users in and JavaScript code pages

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/nodejs/runsdkapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/nodejs/runwidgetapp.md
- packages/@okta/vuepress-site/docs/guides/sign-in-overview/main/index.md
> Minox fixes to the documentation

- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-theme-prose/global-components/ClassicDocOieVersionNotAvailable.vue
- **What's changed?** Fixing a global note component and one incorrect xref 
* n/a
> Updating global Note component used by 8 docs

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/aspnetcore3/samplecode.md
- **What's changed?** Update .NET 3 API repo link to reflect new quickstart and replace old link
> Update repo link to reflect new quickstart

- packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
- packages/@okta/vuepress-site/code/dotnet/blazor/index.md
- packages/@okta/vuepress-site/docs/guides/oie-intro/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/loginredirect.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/php/createproject.md
- **What's changed?** Some fast follow fixes for a few minor nits that were pointed out to me soon after launch. Keep em coming!
> minor source and link fixes

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
- API docs update for jwks_uri 
- **Is this PR related to a Monolith release?** Yes, 2022.03.0
* [OKTA-466754](https://oktainc.atlassian.net/browse/OKTA-466754)
> OKTA-466754 API docs update for jwks_uri

- packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- packages/@okta/vuepress-site/docs/reference/api/admin-notifications/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- Remove Early Access tags related to custom admin roles since we are GAing
- **Is this PR related to a Monolith release?** 2022.03.0
* [OKTA-465426](https://oktainc.atlassian.net/browse/OKTA-465426)
@alifatolahi-okta @vasishtajayanti-okta
> Remove Early Access Tags for Custom Admin Roles

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** /app and /policy updates for shareable app policy feature release
- **Is this PR related to a Monolith release?** 2022.03.0
* [OKTA-440176](https://oktainc.atlassian.net/browse/OKTA-440176)
> Add dev-docs around Shared app sign on policies

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- **What's changed?** Add description for **Enabled signed request** checkbox for generic OIDC IdP
- **Is this PR related to a Monolith release?** Yes, 2022.03.0
* [OKTA-472876](https://oktainc.atlassian.net/browse/OKTA-472876)
> OKTA-472876 Document signed request object support for generic OIDC IdP

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding release notes for 2022.03.1
- **Is this PR related to a Monolith release?** Yes. 2022.03.1
* [OKTA-476330](https://oktainc.atlassian.net/browse/OKTA-476330)
> RN entry 2022.03.1

- packages/@okta/vuepress-site/docs/guides/social-login/main/amazon/ea-icon.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/github/ea-icon.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/gitlab/ea-icon.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/paypal/ea-icon.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/salesforce/ea-icon.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/yahoo/ea-icon.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/yahoojp/ea-icon.md
- **What's changed?** Remove EA and FF info from social Idp guides. Remove stack snippet from title.
- **Is this PR related to a Monolith release?** Yes, 2022.03.0 Production
(Do not publish until release deployed to Production org)
* [OKTA-472549](https://oktainc.atlassian.net/browse/OKTA-472549)
> OKTA-472549 Remove EA and FF info from social Idp guides

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-ngrok/main/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
- **What's changed?** Review of all Hook guides to standardize on [nutrition facts](https://oktawiki.atlassian.net/wiki/spaces/DOC/pages/2399470775/Nutrition+facts+in+developer+docs)
* [OKTA-454773](https://oktainc.atlassian.net/browse/OKTA-454773)
> Updates to Hook guides standardizing nutrition facts

- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
- **What's changed?** ensure THAT fixes and fixing links that were linking to the section the link was in by mistake
> couple things I stumbled upon

- packages/@okta/vuepress-site/docs/reference/api/org/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
Adds email bounces remove list API
One new endpoint under /api/v1/org/email
Monolith release: 2022.03.0
* [OKTA-476326](https://oktainc.atlassian.net/browse/OKTA-476326)
> Adds email bounces remove list API

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- Adds API doc for myaccount phone `/challenge` and `/verify` endpoints
- **Is this PR related to a Monolith release? Yes. 2022.05.0
* [OKTA-460268](https://oktainc.atlassian.net/browse/OKTA-460268)
> Added API doc for myaccount phone /challenge and /verify endpoints

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/addconfigpkg.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/defineroute.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/getuserinfo.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/loginredirect.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/reqautheverything.md
- **What's changed?** The Go web app implementation is improved with some best practices
@chrisdavidmills after discussing with Aaron, I decided to update this as the current code was having some minor best practice issues
> Fix go OAuth implementation

- packages/@okta/vuepress-site/docs/concepts/saml/faqs/index.md
- packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
- packages/@okta/vuepress-theme-prose/components/Footer.vue
- packages/@okta/vuepress-theme-prose/global-components/ClassicDocOieVersionNotAvailable.vue
- **What's changed?** Sabin from dev support requested that we remove all mention of the developers@okta email address, reason being that every email creates a new support case and it is not very sustainable for our dev support team to handle the load. This PR points customers to our forum instead.
> removing developers@okta email from site

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add release note entries for 2022.03.2
* [OKTA-478460](https://oktainc.atlassian.net/browse/OKTA-478460)
> OKTA-478460 Add release note entries for 2022.03.2

- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release notes for 2022.03.2
- **Is this PR related to a Monolith release?** Yes, 2022.03.2
* [OKTA-478460](https://oktainc.atlassian.net/browse/OKTA-478460)
> OKTA-478460 Release Notes for  2022.03.2

- packages/@okta/vuepress-theme-prose/components/ThemeModeToggle.vue
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- packages/@okta/vuepress-theme-prose/util/coveo/endpoint.js
- packages/@okta/vuepress-theme-prose/util/localStorage.js
- **What's changed?** Verify that localStorage exists before querying it
* [OKTA-480338](https://oktainc.atlassian.net/browse/OKTA-480338)
> Prevent localStorage errors by verifying its existence

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- packages/@okta/vuepress-theme-prose/layouts/AuthorizationLayout.vue
- packages/@okta/vuepress-theme-prose/util/geoLocation.js
- tests/cypress/integration/signup_spec.js
- **What's changed?** Add region-lock to sign-up form (RU and BY)
* [OKTA-480603](https://oktainc.atlassian.net/browse/OKTA-480603)
> [Enhanced] Add region-lock to sign-up form

- packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
- **What's changed?** Andrea from dev sup requested that we add this note, as customers frequently run into this issue and it results in a significant number of support tickets. I ended up adding a bit more general context near the top, with the note underneath, as it could potentially affect any of the scenarios covered in the body of the guide.
* [OKTA-477991](https://oktainc.atlassian.net/browse/OKTA-477991)
> adding note about ignoring sessionToken

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Adds a note about CAA records and the need to add Let's Encrypt to the issuers list.
* [OKTA-481276](https://oktainc.atlassian.net/browse/OKTA-481276)
> TBS OKTA-481276 Add notes about CAA and lets encrypt

- packages/@okta/vuepress-site/docs/guides/oin-oidc-overview/main/index.md
- **What's changed?** Add unsupported refresh token note in OIN-OIDC overview
* [OKTA-447956](https://oktainc.atlassian.net/browse/OKTA-447956)
> OKTA-447956 Add unsupported refresh token note in OIN-OIDC overview

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release notes for 2022.03.3
- **Is this PR related to a Monolith release?** Release notes for 2022.03.3
* [OKTA-480492](https://oktainc.atlassian.net/browse/OKTA-480492)
> Rn entry 2022.03.3

- packages/@okta/vuepress-theme-prose/components/Home.vue
- packages/@okta/vuepress-theme-prose/global-components/AnnouncementBanner.vue
- **What's changed?** Replace OIE banner with LAPSUSS banner
* [OKTA-482162](https://oktainc.atlassian.net/browse/OKTA-482162)
> Replace OIE banner with LAPSUSS banner

- packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- **What's changed?** Updated syslog docs to include introduced `transaction.detail.requestApiTokenId` info
- **Is this PR related to a Monolith release?** 2022.02.1
* [OKTA-465398](https://oktainc.atlassian.net/browse/OKTA-465398)
> update syslog docs to include transaction.detail.requestApiTokenId info

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Document known performance limitation for scoped admins using list users endpoints.
* [OKTA-482887](https://oktainc.atlassian.net/browse/OKTA-482887)
@nghadge-okta @donwoods-okta @okta/ud-core
> Document known performance limitation for scoped admins using list users endpoints.

- packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
- **What's changed?** Update description for OIN submission test account.
* [OKTA-449814](https://oktainc.atlassian.net/browse/OKTA-449814)
2022-Mar-29: https://62430c50c921a90763fea782--reverent-murdock-829d24.netlify.app/docs/guides/submit-app/openidconnect/main/#test-account
> OKTA-449814 Update description for OIN app test account

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding release notes for 2022.04.0
- **Is this PR related to a Monolith release?** Yes. 2022.04.0
* [OKTA-482754](https://oktainc.atlassian.net/browse/OKTA-482754)
> Release notes entry 2022.04.0

- packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- **What's changed?** Remove EA flag for "Secure API connections between orgs with OAuth 2.0" multi-org guide
- **Is this PR related to a Monolith release?** Yes, 2022.04.0
* [OKTA-461728](https://oktainc.atlassian.net/browse/OKTA-461728)
> OKTA-461728 Remove EA flag for mutli-org guide

- packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md
- packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/intro.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/intro.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/intro.md
- **What's changed?** updated existing docs to reflect upcoming 2 factor default for password factor only uses cases 
- **Is this PR related to a Monolith release?** Yes 2022.04.0
* [OKTA-477375](https://oktainc.atlassian.net/browse/OKTA-477375)
> doc updates for 2 factor default

- packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- Adding Splunk Cloud Log Streaming dev docs for EA
- **Is this PR related to a Monolith release?** Yes, 2022.04.0 
⚠️ Release notes for log streaming is handled by Data Analytics team
* [OKTA-449821](https://oktainc.atlassian.net/browse/OKTA-449821)
> OKTA-449821: Splunk cloud log streaming dev docs

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/reference/csi-delauth-hook/index.md
Authentication inline hook.
This developer doc is for the Beta release of Custom Source Integration actions and it covers the following 3 actions:
1. JIT new user
2. Delegated authenticate
3. Fetch/reload profile for a user
Because this is for a Beta release, the navigation section is not updated.
@brianduffield-okta as primary reviewer.
Resolves: OKTA-479331
- **What's changed?** This is the developer doc for the Beta version of Custom Source Integration Delegated Authentication Inline Hook.
- **Is this PR related to a Monolith release?** No. This is still pre-beta. (I believe this is for April monthly 2022.04.0)
* [OKTA-479331](https://oktainc.atlassian.net/browse/OKTA-479331)
> OKTA-479331: Developer doc for Custom Source Integration Delegated

- packages/@okta/vuepress-site/docs/reference/api/asa/introduction/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/service-users/index.md
- **What's changed?** The ASA Product link alias changed last September. We need to update the ASA Product link alias's base URL to the new format. 
* [OKTA-484207](https://oktainc.atlassian.net/browse/OKTA-484207)
> OKTA-484207 Update ASA Product base url aliases

- packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/index.md
- packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/nodeexpress/relatedusecases.md
- packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/index.md
- packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md
- packages/@okta/vuepress-site/docs/guides/device-context/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/index.md
Small changes to several OIE by default 1 branch
> Small changes to several OIE by default 1 branch

- packages/@okta/vuepress-site/docs/guides/advanced-use-case-overview/index.md
- packages/@okta/vuepress-site/docs/guides/advanced-use-case-overview/main/aspnet/customsspr.md
- packages/@okta/vuepress-site/docs/guides/advanced-use-case-overview/main/aspnet/devicecontext.md
- packages/@okta/vuepress-site/docs/guides/advanced-use-case-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/advanced-use-case-overview/main/nodeexpress/customsspr.md
- packages/@okta/vuepress-site/docs/guides/advanced-use-case-overview/main/nodeexpress/devicecontext.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
Add advanced use case overview
* https://oktainc.atlassian.net/browse/OKTA-468899
> Add advanced use case overview

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/main/nodejs/integrationsteps.md
Link email use cases to okta email guide
> Link email use cases to okta email guide

- packages/@okta/vuepress-site/docs/guides/authenticators-overview/main/index.md
- **What's changed?** Added new overview page for authenticators guide section
* [OKTA-459221](https://oktainc.atlassian.net/browse/OKTA-459221)
View at https://62473a70c30f455fd325bcd4--reverent-murdock-829d24.netlify.app/docs/guides/authenticators-overview/main/
> [OKTA-459221] Authenticators contextual landing page

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Fix broken redirects
* n/a
> Update conductor.yml for broken redirects

- packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** Made improvements based on Brian's review
Netlify: https://624b2b4bcaef8b09a49687ba--reverent-murdock-829d24.netlify.app
> Telephony Inline Hook updates

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Reviewing updates to Conductor file
* n/a
> Updates to conductor file for staging

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Merging Release Note drafts into Release branch
* [OKTA-484856](https://oktainc.atlassian.net/browse/OKTA-484586)
> Rn entry 2022.04.1

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Updates to conductor.yml file to address some missing and broken redirects
* n/a
> Updates to redirect file

- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/next-steps.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/next-steps.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/see-also.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/next-steps.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/see-also.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/next-steps.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/see-also.md
- **What's changed?** Update OIE embedded auth guide Next steps section with authentication policy and clean up links
* [OKTA-484928](https://oktainc.atlassian.net/browse/OKTA-484928)
> Update OIE embedded auth guide Next steps section with authentication policy and clean up links

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
- packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- **What's changed?** Remove mentions of live widget.
- https://624f4f7e177a390b95d1a447--reverent-murdock-829d24.netlify.app/docs/guides/custom-widget/main/
* [OKTA-461539](https://oktainc.atlassian.net/browse/OKTA-461539)
> OKTA-461539 Remove mentions of live widget

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Updates a link in the last monthly RNs.
- **Is this PR related to a Monolith release?** no.
* N/A
> TBS Updates a link in last monthly RNs

- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/adddependency.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/gettingatoken.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/initializingsdksession.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/loadingaconfiguration.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/processresponse.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/signinerror.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/android/signingout.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/adddependency.md
- packages/@okta/vuepress-site/docs/guides/mobile-idx-sdk-overview/main/ios/processresponse.md
> update android docs for IDX

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
- packages/@okta/vuepress-site/docs/reference/api/mappings/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- packages/@okta/vuepress-site/docs/release-notes/2017/index.md
- packages/@okta/vuepress-site/docs/release-notes/2018/index.md
- **What's changed?** removing the in front of Okta Expression Language and some other odds and ends
* [OKTA-488837](https://oktainc.atlassian.net/browse/OKTA-488837)
> removing the in front of Okta Expression Language

- packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
Link pointed to previous version of the SCIM guide
No
> Update OIN guide to fix borked link

- packages/@okta/vuepress-site/package.json
- yarn.lock
- **What's changed?** Upgrade webpack to 4.46.0
* [OKTA-481884](https://oktainc.atlassian.net/browse/OKTA-481884)
> Upgrade webpack to 4.46.0

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- **What's changed?** Andrea S reported two issues with https://developer.okta.com/docs/guides/implement-oauth-for-okta-serviceapp/main/#generate-the-jwk-in-the-admin-console, which have resulted in support tickets being filed:
- The "Generate the JWK in the Admin Console" feature is EA, but it doesn't seem obvious enough that you need to contact support to activate it
- The examples on how to do this using the apps API have been removed, which is something that customers still want to do.
This PR aims to fix those issues.
> clarify ea status and add api jwk example

- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- this UI was updated the the Branding GA last Nov 2021, so the instructions have been incorrect since then
-
- none
* none
> UI updates

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Update redirect file with the entries from: /docs/guides/add-an-external-idp/apple/configure-idp-in-okta/ and from: /docs/guides/add-an-external-idp/-/configure-idp-in-okta
* [OKTA-489393](https://oktainc.atlassian.net/browse/OKTA-489393)
> OKTA-489393 Fix broken link from Admin Console > Configure Apple IdP settings page

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- **What's changed?** adding back in the generate jwk using api step
* [OKTA-489431](https://oktainc.atlassian.net/browse/OKTA-489431)
Netlify Link:
https://62588c64c3fcad1e44420da6--reverent-murdock-829d24.netlify.app/docs/guides/implement-oauth-for-okta-serviceapp/main/
> adding back in the generate jwk using api step

- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/customize-themes/index.md
- **What's changed?** Removes paths that refer to **Settings** > **Customization**, etc.
* [OKTA-453254](https://oktainc.atlassian.net/browse/OKTA-453254)
> TBS OKTA-453254 Updates UI references in styling guides

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Adds a note that clarifies that certain profile attributes don't work with SAML 2.0 apps.
* [OKTA-321605](https://oktainc.atlassian.net/browse/OKTA-321605)
> TBS OKTA-321605 Adds note re SAML 2.0 apps

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Add 2022.04.3 release note entry
- **Is this PR related to a Monolith release?** Yes, 2022.04.3
* [OKTA-488284](https://oktainc.atlassian.net/browse/OKTA-488284)
> Add 2022.04.3 release note entry

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- Updating the response body and providing samples for the `/idp/myaccount/phones/{id}/challenge` endpoint
* [OKTA-485374](https://oktainc.atlassian.net/browse/OKTA-485374)
> Updating response sections for phones /challenge endpoint

- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Release note updates for 2022.04.3
- **Is this PR related to a Monolith release?** Yes, 2022.04.3
* [OKTA-488284](https://oktainc.atlassian.net/browse/OKTA-488284)
> Release Notes for 2022.04.3

- packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
- **What's changed?** Removed some passive writing from the [Objects in the request from Okta ](https://developer.okta.com/docs/reference/saml-hook/#objects-in-the-request-from-okta)section.
- **Is this PR related to a Monolith release?** negative
* n/a
> Minor text update to SAML Hook reference

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/python/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/python/loginredirect.md
- App State and Nonce were being incorrectly used by the code and were not necessary here.
- Added PKCE
- Added CORS
- No
> Fix usage of NONCE and APP STATE and add PKCE

- package.json
- yarn.lock
- Add yarn resolution for async through cypress
- Upgrade cypress to latest
* [OKTA-489820](https://oktainc.atlassian.net/browse/OKTA-489820)
> Add yarn resolution for async through cypress

- packages/@okta/vuepress-theme-prose/components/Home.vue
- **What's changed?** Update incident message
* [OKTA-492930](https://oktainc.atlassian.net/browse/OKTA-492930)
> Update incident message

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
- **What's changed?** https://developer.okta.com/docs/guides/protect-your-api/aspnetcore3/main/ gives confusing/incorrect information about custom authz servers being required to protect API endpoints. This PR aims to fix that
* [OKTA-491008](https://oktainc.atlassian.net/browse/OKTA-491008)
> Clear up confusion about authz server requirements

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Fix typo in App Names section tempalte_sps -> template_sps
- **What's changed?** Fix typo in App Names section tempalte_sps
- **Is this PR related to a Monolith release?** Unsure
> Fix typo in App Names section tempalte_sps

- packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
Remove ref object from User Types API response; Reorder user type properties in sample response objects.
* [OKTA-494043](https://oktainc.atlassian.net/browse/OKTA-494043)
@donwoods-okta @daytonwilliams-okta @okta/ud-core
> Remove ref object from User Types API response.

- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
- **What's changed?** Fix 3 broken links in "Customize tokens returned from Okta with a static allow list" guide
* [OKTA-492205](https://oktainc.atlassian.net/browse/OKTA-492205)
> OKTA-492205 - Fix broken links in Customize tokens returned from Okta with a static allow list

- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- This PR makes changes to Trusted Origins API reference doc for iframe embedding feature
- **Is this PR related to a Monolith release?** Yes. 2022.05.0.
* [OKTA-OKTA-477592](https://oktainc.atlassian.net/browse/OKTA-OKTA-477592)
> Trusted Origins API doc changes for iframe embedding feature

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Addition of API and OIE API Release Notes for monthly release
- **Is this PR related to a Monolith release?** 2022.05.0
* [OKTA-491497](https://oktainc.atlassian.net/browse/OKTA-491497])
> Release Notes for 2022.05.0 Release

- packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- **What's changed?** Revisions to [Client-based rate limits](https://developer.okta.com/docs/reference/rl-clientbased/) based on new settings for Okta Identity Engine.
- **Is this PR related to a Monolith release?** 2022.05.0
* [OKTA-488590](https://oktainc.atlassian.net/browse/OKTA-480590)
> Updates to client-based rate limiting

- packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
- **What's changed?** Replace "mastering" with "sourcing" in External IdP concept
* [OKTA-488968](https://oktainc.atlassian.net/browse/OKTA-488968)
> Inclusive Language fix: replace mastering with sourcing for IdP concept

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/smartcard/index.md
- packages/@okta/vuepress-site/docs/guides/identity-providers/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- packages/@okta/vuepress-theme-prose/util/frameworks.js
- **What's changed?** Add Smart Card IdP to the "Add an Identity Provider" section
- https://626c447b9549d4009c027b48--reverent-murdock-829d24.netlify.app/docs/guides/add-an-external-idp/smartcard/
* [OKTA-490569](https://oktainc.atlassian.net/browse/OKTA-490569)
> OKTA-490569 add smart card idp

- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/settings.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/github/noemail.md
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- yarn.lock
- **What's changed?** API and OIE API Release notes for monthly release, as well as developer doc updates.
- **Is this PR related to a Monolith release?** 2022.05.0
* [OKTA-491497](https://oktainc.atlassian.net/browse/OKTA-491497)
> Release 2022.05.0 Updates

- packages/@okta/vuepress-site/docs/concepts/scim/index.md
- **What's changed?** Fixes non-inclusive language in SCIM concept doc.
* [OKTA-488972](https://oktainc.atlassian.net/browse/OKTA-488972)
> TBS OKTA-488972 Updates language in SCIM concept doc

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** Replace Whitelist, mastering, mastered, master from descriptions in IDPS API
* [OKTA-488942](https://oktainc.atlassian.net/browse/OKTA-488942)
> Inclusive Language fix: replace Whitelist, mastering, mastered, master from descriptions for IdPs API

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
1. address the remaining comments on the my account developer doc for profile endpoints.
2. add error response across the documentation to make the endpoints consistent
3. some minor wording fixes. 
N/A
* [OKTA-496101](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)
> OKTA-496101 [fixit] myaccount api developer documentation fix.

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/myaccount.json
- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- **What's changed?** Add postman collection for MyAccount APIs
- **Is this PR related to a Monolith release?** Yes. 2022.05.1
* [OKTA-495857](https://oktainc.atlassian.net/browse/OKTA-495857)
> el-okta-495857 MyAccount postman collection

- packages/@okta/vuepress-site/docs/guides/oie-intro/index.md
- **What's changed?** Removing the OIE email address from the OIE Overview guide: https://developer.okta.com/docs/guides/oie-intro/#identity-engine-versus-classic-documentation-approach
* [OKTA-496417](https://oktainc.atlassian.net/browse/OKTA-496417)
> OKTA-496417 Removing OIE email

- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- packages/@okta/vuepress-theme-prose/util/geoLocation.js
- **What's changed?** Only fetch geoLocation if not cached or expired
* [OKTA-496932](https://oktainc.atlassian.net/browse/OKTA-496932)
***Deploy:*** https://627a92f2c506a745ecd14721--reverent-murdock-829d24.netlify.app
> Only fetch geoLocation if not cached or expired

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding release notes for 2022.05.1
- **Is this PR related to a Monolith release?** Yes. Release notes 2022.05.1
* [OKTA-496016](https://oktainc.atlassian.net/browse/OKTA-496016)
> Rn entry 2022.05.1

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- **What's changed?**  Added docs related email template settings
- **Is this PR related to a Monolith release?** 2022.05.1 CF
* [OKTA-491325)](https://oktainc.atlassian.net/browse/OKTA-491325)
> OKTA-491325: Added documentation to get and update customizable template settings

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/setup-app.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/setup-app.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/setup-app.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/setup-app.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/setup-app.md
- **What's changed?** PKCE has been separated out from client auth and is now it's own additional verification option
Netlify link: https://627af1fce5cf5110d5e80171--reverent-murdock-829d24.netlify.app/docs/guides/implement-grant-type/authcode/main/#set-up-your-app
* [OKTA-488725](https://oktainc.atlassian.net/browse/OKTA-488725)
> PKCE and Client Auth UI changes

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/index.md
- packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Describes a few use cases that integrate with MyAccount API to config user-scoped acct mgmt.
- **Is this PR related to a Monolith release?** Yes. 2022.05.1
https://627bcd95a58e4c023673e9a3--reverent-murdock-829d24.netlify.app/docs/guides/configure-user-scoped-account-management/main/
* [OKTA-446974](https://oktainc.atlassian.net/browse/OKTA-446974)
> TBS User-Scoped account management guide

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Updated the intros of both Classic and Identity Engine expression language guides to clarify when to use each doc.
* [OKTA-496363](https://oktainc.atlassian.net/browse/OKTA-496363)
> OKTA-496363 Updates to EL Guides

- packages/@okta/vuepress-site/docs/guides/oin-oidc-overview/main/index.md
- **What's changed?** Fix OIN OIDC primer overview bad link: [doc] link that goes to developer.okta.com/docs
> Fix OIN OIDC primer overview bad link

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Removes blurb from "classic" API RNs. Updates blurb in OIE RNs.
- **Is this PR related to a Monolith release?** No (2022.05.1 retroactively)
* [OKTA-499742](https://oktainc.atlassian.net/browse/OKTA-499742)
> TBS Update MyAccount API RN blurbs

- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add bug in 2022.05.1 API RN 
- **Is this PR related to a Monolith release?** Yes, 2022.05.1 (backporting RN item)
* [OKTA-499552](https://oktainc.atlassian.net/browse/OKTA-499552)
> OKTA-499552 Add bug in API RN for 2022.05.1

- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add hot fix release note item to 2022.05.2
- **Is this PR related to a Monolith release?** Yes, 2022.05.2
* [OKTA-497885](https://oktainc.atlassian.net/browse/OKTA-497885)
> Release notes for 2022.05.2 

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release notes 2022.05.3
- **Is this PR related to a Monolith release?** Yes 2022.05.3
* [OKTA-499047](https://oktainc.atlassian.net/browse/OKTA-499047)
> release notes entry 2022.05.3

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- **What's changed?** Adding note about 401 response to response body in `Add a phone` and `Challenge phone`
- **Is this PR related to a Monolith release?** `2022.05.3`
* [OKTA-499104](https://oktainc.atlassian.net/browse/OKTA-499104)
> MyAccount API - Updating response body for 'Add a phone' and 'Challenge phone' to include 401 response

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** found a typo and fixed another thing in the note
> sdh-typoinidps

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
Adding additional property descriptions to the [Authenticator Object](https://developer.okta.com/docs/reference/api/authenticators-admin/#authenticator-object).
- **What's changed?** Documenting required properties for the Duo [Authenticator Object](https://developer.okta.com/docs/reference/api/authenticators-admin/#authenticator-object).
- **Is this PR related to a Monolith release?** Not related to a specific monolith release; backfilling documentation for a public accessible properties related to a Duo Authenticator object.
* [OKTA-478768](https://oktainc.atlassian.net/browse/OKTA-478768)
```
PUT /api/v1/authenticators/{authenticatorId}
{
"id": "{authenticatorId}",
"name": "Duo Security",
"provider": {
"type": "DUO",
"configuration": {
"host": "{duoHost}.duosecurity.com", …
```
> Required properties for the Duo Authenticator Object.

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** Updates the **Single User/Group/App** heading of the [DynamicScale rate limits](https://developer.okta.com/docs/reference/rl-dynamic-scale/) page. 
*n/a
> Update to DynamicScale rate limits

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- **What's changed?** Update Next step section in legacy external IdP guides to match social IdP guides
https://629a613a82a45308af617530--reverent-murdock-829d24.netlify.app/docs/guides/add-an-external-idp/facebook/main/
* [OKTA-503875](https://oktainc.atlassian.net/browse/OKTA-503875)
> OKTA-503875 Update Next step section in legacy external IdP guides

- packages/@okta/vuepress-site/docs/concepts/multi-tenancy/index.md
- **What's changed?** Fixed one typo in [Multi-tenant solutions](https://developer.okta.com/docs/concepts/multi-tenancy/#org) guide; original fix is stuck from merging in PR3390
* [PR#3390](https://github.com/okta/okta-developer-docs/pull/3390)
> Fix typo in Multi-tenant solutions concept

- packages/@okta/vuepress-site/docs/concepts/policies/index.md
- packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
- **What's changed?** updates to the Policy Concept (bringing in the more overview policy info from the Global Session Policy/Authentication Policy configuration guide), formatting the concept better, added in Jeff's authentication pipeline section
Netlify link: https://629fb10bd8ea5014f1ca897e--reverent-murdock-829d24.netlify.app/docs/concepts/policies/
* [OKTA-436795](https://oktainc.atlassian.net/browse/OKTA-436795)
> Updates to the Policy Concept

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** Add Authentication Settings section with Filter option for SAML and OIDC IdP
- **Is this PR related to a Monolith release?** Yes, 2022.06.0
* [OKTA-500903](https://oktainc.atlassian.net/browse/OKTA-500903)
> OKTA-500903 Add Authentication Settings section with Filter option

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/apple/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/facebook/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/google/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/linkedin/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/microsoft/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- **What's changed?** added step for selecting public key/private key
- **Is this PR related to a Monolith release?** Yes 2022.06.0
NETLIFY link: https://628ff9090444810e3d67b083--reverent-murdock-829d24.netlify.app/docs/guides/add-an-external-idp/openidconnect/main/#enterprise-identity-providers
* [OKTA-488734](https://oktainc.atlassian.net/browse/OKTA-488734)
> updates per new public key options for IdPs

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- Dynamic IdP routing documentation update.
- **Is this PR related to a Monolith release?** Yes. 2022.06.0 
* [OKTA-498146](https://oktainc.atlassian.net/browse/OKTA-498146)
Release:  2022.06.0
> Dynamic IdP routing documentation update

- packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- **What's changed?** Delegated Flows (resources and permissions) is publicly available for early access
- **Is this PR related to a Monolith release?** *Tentatively 2022.06.0*
* [OKTA-490974](https://oktainc.atlassian.net/browse/OKTA-490974)
> API doc updates for Delegated Flows

- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/apple/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/facebook/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/google/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/linkedin/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/microsoft/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release notes for monthly 2022.06.0
- **Is this PR related to a Monolith release?** Yes, 2022.06.0
* [OKTA-501552](https://oktainc.atlassian.net/browse/OKTA-501552)
> Release Notes for 2022.06.0

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Update RN bug OKTA-485242 (clarify RN blurb)
- **Is this PR related to a Monolith release?** Yes, 2022.06.0
> Update RN bug OKTA-485242

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
- **What's changed?** Removal of EA flag for telephony inline hook
- **Is this PR related to a Monolith release?** Yes 2022. 06.0
* [OKTA-491573](https://oktainc.atlassian.net/browse/OKTA-491573)
> removing the EA flags for telephony inline hook

- packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** removing reference to enable EA flag in UI
- **Is this PR related to a Monolith release?** Yes. 2022.06.0
> removing FF reference from guide

- packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** Adding note about using AWS Lambda as external service
* [OKTA-505883](https://oktainc.atlassian.net/browse/OKTA-505883)
> adding AWS note

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
Updated users/me endpoint docs to reflect the verification policy for emails
- Updated users/me endpoint docs to reflect the verification policy for emails
* [OKTA-506375](https://oktainc.atlassian.net/browse/OKTA-506375)
> Update users/me endpoint docs

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/reference/api/myaccount-migration/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- **What's changed?** Adds a one-pager migration guide that isn't included in the left nav, and won't be included in Google search results/search results.
* https://62a76dc7fc141c007eb8d74b--reverent-murdock-829d24.netlify.app/docs/reference/api/myaccount-migration/
* [OKTA-499554](https://oktainc.atlassian.net/browse/OKTA-499554)
* [BUSAPPS-67531](https://oktainc.atlassian.net/browse/BUSAPPS-67531)
> TBS MyAccount API migration guide

- packages/@okta/vuepress-site/docs/reference/api/myaccount-migration/index.md
- **What's changed?** small fix
n/a
> TBS fixes a mistake

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding release notes for 2022.06.1
- **Is this PR related to a Monolith release?** Yes. 2022.06.1
* [OKTA-505802](https://oktainc.atlassian.net/browse/OKTA-505802)
> RN entry 2022.06.1

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add post release vuln ticket. This PR is to be merged after all Prod cells are deployed.
- **Is this PR related to a Monolith release?** Yes, 2022.06.0
* [OKTA-501552](https://oktainc.atlassian.net/browse/OKTA-501552)
> Addendum for release 2022.06.0

- packages/@okta/vuepress-site/code/angular/index.md
- **What's changed?** Update link to [Sign in to your SPA with Auth JS]
* [OKTA-296483](https://oktainc.atlassian.net/browse/OKTA-296483)
> OKTA-296483 Add link to [Sign in to your SPA with Auth JS]

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- **What's changed?** Fixes small typo
* [OKTA-504407](https://oktainc.atlassian.net/browse/OKTA-504407)
> TBS Fixes typo in Brands API guide

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- packages/@okta/vuepress-site/docs/reference/user-query/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Current draft of new User query options reference
* [OKTA-488588](https://oktainc.atlassian.net/browse/OKTA-488588)
> OKTA-488588 - New User query guide draft

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding API and OIE API Release Notes for the weekly release
- **Is this PR related to a Monolith release?** 2022.06.2
* [OKTA-507791](https://oktainc.atlassian.net/browse/OKTA-507791)
> Release Notes for 2022.06.2

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release branch contains one dev doc update and the addition of weekly API and OIE API Release Notes.
- **Is this PR related to a Monolith release?** 2022.06.2
* [OKTA-507791](https://oktainc.atlassian.net/browse/OKTA-507791)
> Release 2022.06.2

- packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount-migration/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- **What's changed?** Updates broken links in MyAccount API docs.
* N/A
> TBS - Updates broken/incorrect links in MyAccount API docs

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add RN entries for 2022.06.3
- **Is this PR related to a Monolith release?** Yes, 2022.06.3
* [OKTA-509605](https://oktainc.atlassian.net/browse/OKTA-509605)
> OKTA-509605 - Add 2022.06.3 RN entries

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
this request has a trailing comma which is an invalid json format
- **Is this PR related to a Monolith release?**no
*none, slack convo escalated by customer issue
> fixed invalid json request

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add release notes for 2022.06.3
- **Is this PR related to a Monolith release?** Yes, 2022.06.3
* [OKTA-509605](https://oktainc.atlassian.net/browse/OKTA-509605)
> Release Notes for 2022.06.3

- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
- **What's changed?** Replace mastered with sourced for inclusive language initiative.
* [OKTA-505037](https://oktainc.atlassian.net/browse/OKTA-505037)
> OKTA-505037 Remove non-inclusive language in Custom token group claims

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Added Get Current User request using `Cookie` header (instead of SSWS `Authorization` header). Added user detail notes for both Get current user requests.
* [OKTA-328813](https://oktainc.atlassian.net/browse/OKTA-328813)
> OKTA-328813 - Add get current user request with Cookie and notes

- packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
- packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- **What's changed?** Added small updates to the Rate Limits overview and the Create an API Token pages of developer.okta.com on the feature configurable rate limits by API Token.
- **Is this PR related to a Monolith release?** 2022.07.0
* [OKTA-506935](https://oktainc.atlassian.net/browse/OKTA-506935)
> OKTA-506935 Configurable Rate Limits by API Token

- packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- **What's changed?** EA flag removal in Role Assignment Concept
- **Is this PR related to a Monolith release?** Yes. 2022.07.0
* [OKTA-503417](https://oktainc.atlassian.net/browse/OKTA-503417)
> EA flag removal in Role Assignment Concept

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** July monthly release notes
- **Is this PR related to a Monolith release?** Yes. 2022.07.0
* [OKTA-511348](https://oktainc.atlassian.net/browse/OKTA-511348)
> Rn entry 2022.07.0

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/addconfigpkg.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/checkfortoken.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/createproject.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/definecallback.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/getuserinfo.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/opensignin.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/redirectvalues.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/refresh.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/testapp.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/usetoken.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/index.md
Related to #3424
Latest Preview Build: 7/8 5PM Eastern
https://62c89674bfb048005cbca58e--reverent-murdock-829d24.netlify.app
Update https://developer.okta.com/docs/guides/sign-into-mobile-app-redirect/android/main/ from https://github.com/okta/okta-oidc-android to https://github.com/okta/okta-mobile-kotlin in preparation of the okta-mobile-kotlin 1.0 release.
No
* [OKTA-508890](https://oktainc.atlassian.net/browse/OKTA-508890)
> OKTA-508890 Update the android browser redirect guide to okta-mobile-kotlin.

- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?** Updates to existing sample responses.
https://62c87ff69a72465aef8ccdba--reverent-murdock-829d24.netlify.app/docs/reference/registration-hook/
[OKTA-510621](https://oktainc.atlassian.net/browse/OKTA-510621)
> TBS Updates Inline Registration Hook response samples

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
- **What's changed?** Updated the API Security > [Implement OAuth for Okta guide](https://developer.okta.com/docs/guides/implement-oauth-for-okta/main/) with revised procedures using the Admin Console and Postman to run this basic tutorial. Additionally, updated the following table: [Scopes and supported endpoints](https://developer.okta.com/docs/guides/implement-oauth-for-okta/main/#scopes-and-supported-endpoints) to include the latest available scopes visible in the Admin Console for both Classic and OIE; added the OIE tag to highlight scopes only available for OIE.
* [OKTA-452468](https://oktainc.atlassian.net/browse/OKTA-452468)
> OKTA-452468 Update procedures and scope table in Implement OAuth guide

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Adding a note to point admins to how to map an app to a policy
* [OKTA-497435](https://oktainc.atlassian.net/browse/OKTA-497435)
> adding note with link

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/authenticators.json
- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
1. Added dev docs for create authenticator API at https://developer.okta.com/docs/reference/api/authenticators-admin/
2. Document custom app authenticator as one of the supported authenticators.
3. Added create authenticator API to the postman collection.
- **Is this PR related to a Monolith release?** Monthly Release 2022.08.0 CF
- **Netlify Link:**
https://62d5e232195e54009f39a695--reverent-murdock-829d24.netlify.app/docs/reference/api/authenticators-admin/
* OKTA-478768, OKTA-505841
> Create authenticator API and custom app authenticator

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding release notes for 2022.07.2
- **Is this PR related to a Monolith release?** Yes. 2022.07.2
* [OKTA-515377](https://oktainc.atlassian.net/browse/OKTA-515377)
> RN entry 2022.07.2

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** link update for library upgrade
- **Is this PR related to a Monolith release?** 2022.07.2
* [[OKTA-XXXXXX](https://oktainc.atlassian.net/browse/OKTA-XXXXXX)](https://oktainc.atlassian.net/browse/OKTA-498506)
* https://github.com/okta/okta-core/pull/65491
> upgrading velocity apache to 2.3

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- added a table to describe optional branding variables, this will be linked to from the new branding code editors UI
- no, this can be published ASAP
* https://oktainc.atlassian.net/browse/OKTA-516952
> using branding variables

- packages/@okta/vuepress-site/code/android/index.md
- packages/@okta/vuepress-site/code/angular/index.md
- packages/@okta/vuepress-site/code/dotnet/aspnet/index.md
- packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
- packages/@okta/vuepress-site/code/dotnet/blazor/index.md
- packages/@okta/vuepress-site/code/go/index.md
- packages/@okta/vuepress-site/code/ios/index.md
- packages/@okta/vuepress-site/code/java/index.md
- packages/@okta/vuepress-site/code/java/spring/index.md
- packages/@okta/vuepress-site/code/javascript/index.md
- packages/@okta/vuepress-site/code/nodejs/index.md
- packages/@okta/vuepress-site/code/php/index.md
- packages/@okta/vuepress-site/code/python/index.md
- packages/@okta/vuepress-site/code/react-native/index.md
- packages/@okta/vuepress-site/code/react/index.md
- packages/@okta/vuepress-site/code/vue/index.md
- packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/index.md
- packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/index.md
- packages/@okta/vuepress-site/docs/reference/import-hook/index.md
- packages/@okta/vuepress-site/docs/reference/password-hook/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
- packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
- packages/@okta/vuepress-site/docs/reference/token-hook/index.md
- **What's changed?** There are a few landing pages that don't work very well with the new system of auto-generating landing pages (with sub-page links and descriptions) that forms part of the new tree nav we are launching soon. This PR makes some small updates to those pages, to make them work with the system.
> making page paragraphs work better when used as auto-generated landing page descriptions

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** API and OIE API Release Note updates for the upcoming monthly release.
- **Is this PR related to a Monolith release?** 2022.08.0
* [OKTA-518646](https://oktainc.atlassian.net/browse/OKTA-518646)
> Rn entry 2022.08.0

- packages/@okta/vuepress-site/docs/concepts/multi-tenancy/index.md
- packages/@okta/vuepress-site/docs/concepts/scim/index.md
- packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/java/enrollmentqrcodeintegrationsteps.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/yahoo/appidpinokta.md
- **What's changed?** Site cleanup for fixit days. Fixed 4 broken links and 3 hard-coded URLs to hoc.
* [OKTA-519246](https://oktainc.atlassian.net/browse/OKTA-519246)
> OKTA-519246 Fixing 404s and alias updates fixit days

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** updated info on how passwords are verified
* [OKTA-518496](https://oktainc.atlassian.net/browse/OKTA-518496)
> update to password specifics

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- Added Accept header that contains myaccount api version to doc examples.
- added info section after api-version - access token assurance for write operations
* [OKTA-520206](https://oktainc.atlassian.net/browse/OKTA-520206)
> OKTA-520206 Added accept header for myaccount api version

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Adds the SSU email template to the VTL table.
- **Is this PR related to a Monolith release?** Yes. 2022.08.1
* [OKTA-521995](https://oktainc.atlassian.net/browse/OKTA-521995)
> Add template to VTL table

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- **What's changed?** Updates to Filter field content
* [OKTA-517878](https://oktainc.atlassian.net/browse/OKTA-517878)
* [OKTA-517877](https://oktainc.atlassian.net/browse/OKTA-517877)
> Updates to Filter field content

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Change name "Multifactor (MFA) Enrollment Policy" to "authenticator enrollment policy" for OIE
- **Is this PR related to a Monolith release?** TBD
Draft preview for discussion: https://62aa086ec63cd148d179bf36--reverent-murdock-829d24.netlify.app/docs/reference/api/policy/
* [OKTA-497465](https://oktainc.atlassian.net/browse/OKTA-497465)
> OKTA-497465 Change MFA enrollment policy to authenticator enrollment policy

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Add weekly release title 2022.08.1 for OIE RN (missed it in the RN PR) 
- **Is this PR related to a Monolith release?** Yes, 2022.08.1
* [OKTA-521170](https://oktainc.atlassian.net/browse/OKTA-521170)
> Add missed weekly release title 2022.08.1 for OIE RN

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Remove start-with less than three characters sample search API calls.
* [OKTA-521890](https://oktainc.atlassian.net/browse/OKTA-521890)
@joshreesjones-okta @nghadge-okta
> Remove start-with less than three characters sample search API calls.

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Adding release notes for 2022.08.2
- **Is this PR related to a Monolith release?** Yes. 2022.08.2
* [OKTA-523318](https://oktainc.atlassian.net/browse/OKTA-523318)
> RN entry 2022.08.2

- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
> A few missed updates

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Add bug after all Production cells have been deployed with 2022.08.1
- **Is this PR related to a Monolith release?** Yes, 2022.08.1 (prod)
* [OKTA-521170](https://oktainc.atlassian.net/browse/OKTA-521170)
> Post release for 2022.08.1 - add bug after all prod cells deployed

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
new query parameter for GET and LIST email templates 
- 2022.08.2
* https://oktainc.atlassian.net/browse/OKTA-497965
> add query parameters for `expand`

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/admin-roles.json
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- **What's changed?** Allow identifying by resource set ID or label in resource-sets API
* [OKTA-510673](https://oktainc.atlassian.net/browse/OKTA-510673)
> Allow identifying by resource set ID or label in resource-sets API

- packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
Add new mobile phone event limitation
* [OKTA-526539](https://oktainc.atlassian.net/browse/OKTA-526539)
https://6306492703bf300f26eec1bb--reverent-murdock-829d24.netlify.app/docs/guides/ie-limitations/main/#target-id-value-simulated-for-mobile-phone-event-types
> Add new mobile phone event limitation

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release Notes 2022.08.3 
- **Is this PR related to a Monolith release?** Yes  2022.08.3
* [OKTA-525297](https://oktainc.atlassian.net/browse/OKTA-525297)
> Release 2022.08.3

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- Updates Expression Language documentation with allowed group rules expressions.
- OKTA-387674
- @okta/ud-core
> Update Expression Language documentation with allowed group rules expressions

- packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- **What's changed?** Changes to the guide to reflect changes to the API reference doc
* [OKTA-521952](https://oktainc.atlassian.net/browse/OKTA-521952)
> Updates to MyAccount API guide

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Adds a bug blurb to release notes.
- **Is this PR related to a Monolith release?** 2022.08.3
* [OKTA-524327](https://oktainc.atlassian.net/browse/OKTA-524327)
> Adds bug blurb to 2022.08.3 OIE release notes

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding in the blurb for the vln
- **Is this PR related to a Monolith release?** Yes. 2022.08.3
* [OKTA-499602](https://oktainc.atlassian.net/browse/OKTA-499602)
> vln from last week

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- Added api documentation regarding a new OIE policy endpoint: Policy Cloning
- Updated the policy postman collection to include policy cloning
- **Related to Monolith release:** 2022.09.0
* [OKTA-522604](https://oktainc.atlassian.net/browse/OKTA-522604)
> Update docs to include Policy Cloning API

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/createidpnote.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/createidpnote.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/createidpnote.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/createidpnote.md
- **What's changed?** Add snippet structure for custom note before creating the IdP procedure. Add OIDC protocol note and link to D.O.C SAML procedure, as per request in OKTA-523424.
* [OKTA-523424](https://oktainc.atlassian.net/browse/OKTA-523424)
> OKTA-523424 Add custom note for Azure AD - OIDC protocol

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
te bugs and doc updates in Change table
- **What's changed?** Fix anchors for 2022.09.0 release notes bugs and doc updates in Change table
> Fix anchors for 2022.09.0 release notes Change table

- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/nodeexpress/allcontent.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/nodeexpress/mgmtsdklink.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/nodeexpress/sdklink.md
Password optional guides: Change email guide for Node JS
* [OKTA-502102](https://oktainc.atlassian.net/browse/OKTA-502102)
https://630687ef55f60b02e803a583--reverent-murdock-829d24.netlify.app/docs/guides/pwd-optional-change-email/nodeexpress/main/
Only review the Change email guide for Node JS.
> Password optional guides: Change email guide for Node JS

- packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md
- **What's changed?** Boo! Fixing small typo.
* n/a
> Fix small typo on SAML Inline Hook Guide

- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/aspnet/allcontent.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/aspnet/mgmtsdklink.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/aspnet/sdklink.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/react/samplecode.md
- **What's changed?** Password Optional "How to change your primary email" guide for .net developers
* [OKTA-502086](https://oktainc.atlassian.net/browse/OKTA-502086)
NETLIFY : https://631f400e864aab1c13640b65--reverent-murdock-829d24.netlify.app/docs/guides/pwd-optional-best-practices/aspnet/main/
> Password optional .net sdk "change your email" guide

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- packages/@okta/vuepress-site/docs/release-notes/2017/index.md
- packages/@okta/vuepress-site/docs/release-notes/2018/index.md
- packages/@okta/vuepress-site/docs/release-notes/2019/index.md
- **What's changed?** Update dev docs to remove non-inclusive words in Policy API, AuthN API, Users API, and past release notes. 
* [OKTA-521664](https://oktainc.atlassian.net/browse/OKTA-521664)
> OKTA-521664 Fix non-inclusive words based on August 2022 IL report

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding blurb for June
- **Is this PR related to a Monolith release?** Yes, 2022.06.0 
* [OKTA-3018830](https://oktainc.atlassian.net/browse/OKTA-3018830)
> adding RN to June

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/addconfigpkg.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/checkfortoken.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/createproject.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/opensignin.md
Latest Preview Build: Sept 13 2022 @ 23:00 GMT
https://6320fa9bb05c004885136999--reverent-murdock-829d24.netlify.app/docs/guides/sign-into-mobile-app-redirect/ios/main/
index.md
- removed use of "our" and "we"
addconfigpkg.md
- Added prose and code for adding statemtns to import the libraries
checkfortoken.md
- Added comment to explain a line
createproject.md
- Removed library imports since this code is written before the Okta libraries are added to the project.
opensignin.md
- Updated comments to make it clear that the catch handles errors from two different different source.
* [OKTA-528020](https://oktainc.atlassian.net/browse/OKTA-528020)
> Minor prose and code fixes

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-mfa-enroll-policy/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Add note in Policy API and Upgrade authenticator enrollment policy doc
- **Is this PR related to a Monolith release?** Yes, 2022.09.0
* [OKTA-527704](https://oktainc.atlassian.net/browse/OKTA-527704)
> OKTA-527704 - Add note for ENG_IDX_ENABLE_DEFAULT_MFA_POLICY_IN_AUTHENTICATOR_FORMAT

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Add doc action OIE release note item: Default authenticator enrollment policy settings format
- **Is this PR related to a Monolith release?** Yes, 2022.09.0
* [OKTA-527304](https://oktainc.atlassian.net/browse/OKTA-527304)
> Add DOC ACTION item for 2022.09.0

- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/aspnet/signinwithemail.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/aspnet/signinwithpwdandphone.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/aspnet/signupwithemail.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/index.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/nodeexpress/signinwithemail.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/react/signinwithpwdandphone.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/react/signupwithemail.md
- **What's changed?** dotnet version of password optional best practices guide.
* [OKTA-502999](https://oktainc.atlassian.net/browse/OKTA-502999)
NETLIFY : https://631f4acf2e41b526dec23b74--reverent-murdock-829d24.netlify.app/docs/guides/pwd-optional-best-practices/aspnet/main/
> Password optional best practices guide (dotnet)

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding classic and oie RNs for this weekly release. Includes one amendment to previous monthly release.
- **Is this PR related to a Monolith release?** 2022.09.1
* [OKTA-527489](https://oktainc.atlassian.net/browse/OKTA-527489)
> Release Note entry for 2022.09.1

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** Updated limit value for List group rules
* [OKTA-523935](https://oktainc.atlassian.net/browse/OKTA-523935)
> OKTA-523935 Updated limit value for List group rules

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add RN entries for 2022.09.2
- **Is this PR related to a Monolith release?** Yes, 2022.09.2
* [OKTA-532867](https://oktainc.atlassian.net/browse/OKTA-532867)
> Add RN entries for 2022.09.2

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add release note entries for 2022.09.2
- **Is this PR related to a Monolith release?** Yes, 2022.09.2
* [OKTA-532867](https://oktainc.atlassian.net/browse/OKTA-532867)
> Release Notes for 2022.09.2

- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/addconfigpkg.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/createproject.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/reqautheverything.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/reqauthspecific.md
.
For [instruction page for Angular](https://developer.okta.com/docs/guides/sign-into-spa-redirect/angular/main/):
- Use newest versions `@okta/okta-angular@6.0 @okta/okta-auth-js@7.0`
- Use `canLoad` instead of `canActivate` for lazy loaded module
- Use Angular 14
* [OKTA-530587](https://oktainc.atlassian.net/browse/OKTA-530587)
> Use @okta/okta-angular@6.0 @okta/okta-auth-js@7.0

- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
- **What's changed?** Revert back to emailing developer@okta.com for Profile Sourcing FF for SCIM integration testing. See support issue OKTA-528768
* [OKTA-528768](https://oktainc.atlassian.net/browse/OKTA-528768)
> OKTA-528768 Revert back to emailing developer@okta.com for Profile Sourcing FF

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** release notes entry for 2022.09.3
- **Is this PR related to a Monolith release?** Yes 2022.09.3
* [OKTA-534937](https://oktainc.atlassian.net/browse/OKTA-534937)
> release notes entry for 2022.09.3

- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/react/signinwithemail.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/react/signinwithpwdandphone.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-best-practices/main/react/signupwithemail.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/react/setupoktaorg.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/react/signupfornewaccount.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/react/whatyouneed.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/react/bestpractices.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-new-sign-up-email/main/react/setupoktaorg.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-overview/main/aspnet/signupwithemail.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-overview/main/react/widgetsignin.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-sign-in-email/main/react/setupoktaorg.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-sign-in-email/main/react/signupfornewaccount.md
Password optional: Fix any wrong links in password optional guides
* [OKTA-533855](https://oktainc.atlassian.net/browse/OKTA-533855)
> Password optional: Fix any wrong links in password optional guides

- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/nodeexpress/allcontent.md
Added sample code to change email guide for node js
* [OKTA-532227](https://oktainc.atlassian.net/browse/OKTA-532227)
https://633612a38b7df411a1fc7537--reverent-murdock-829d24.netlify.app/docs/guides/pwd-optional-change-email/nodeexpress/main/
> Added sample code to change email guide for node js

- packages/@okta/vuepress-theme-prose/components/Home.vue
- **What's changed?** This PR removes the previously-added integrator beta program survey banner from the homepage, as the period for running the survey is now over.
* [OKTA-532281](https://oktainc.atlassian.net/browse/OKTA-532281)
> remove integrator banner

- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- **What's changed?** Removing Okta Classic Engine note - Device auth can be used in both Classic and Identity Engine
> removing note

- packages/@okta/vuepress-site/docs/concepts/monitor/index.md
- **What's changed?** Fix typo: ThreadInsight -> ThreatInsight
> Fix typo in ThreatInsight section

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/nodejs/auth.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/nodejs/parse.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/nodejs/scope.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/nodejs/setup.md
- **What's changed?** Added the new OAuth 2 authentication options to the Inline hook concept docs as well as the common hook set up guide.
- **Is this PR related to a Monolith release?** 2022.10.0
* [OKTA-498831](https://oktainc.atlassian.net/browse/OKTA-498831)
> Updating Inline hook concept and common hook set up guide for OAuth 2 for hooks

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Add User query options guide back into References nav (under Core Okta API)
* n/a
> Add User Query options guide back into nav

- .travis.yml
- scripts/travis.sh
* [OKTA-538633](https://oktainc.atlassian.net/browse/OKTA-538633)
> Uses Node 14 in Travis CI and sets explicit semver for netlify-cli

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- **What's changed?**Update Factors API with OIE note for the Okta Verify in OIE org feature
- **Is this PR related to a Monolith release?** Yes, 2022.10.0
* [OKTA-525563](https://oktainc.atlassian.net/browse/OKTA-525563)
> OKTA-525563 Add OIE note for ENG_OKTA_VERIFY_FACTORS_API_IN_OIE

- packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- **What's changed?** New PEM format for private key jwt
- **Is this PR related to a Monolith release?** Yes 2022.10.0
* [OKTA-489371](https://oktainc.atlassian.net/browse/OKTA-489371)
> New PEM format for private key jwt

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Shortens title length in left-nav for brand and customize docs.
- **Is this PR related to a Monolith release?** nope
* [OKTA-538555](https://oktainc.atlassian.net/browse/OKTA-538555)
> TBS - Brand and customize title length

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Shortened titles within Authorization
* [OKTA-537861](https://oktainc.atlassian.net/browse/OKTA-537861)
> Shorten authorization titles

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Updated titles in API Security
* [OKTA-537863](https://oktainc.atlassian.net/browse/OKTA-537863)
> Shorten API Security titles

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Some fixes have been made to the tree nav, and the next stage is to hopefully improve the readability of the tree nav titles to an acceptable level by shortening them appropriately. This PR deals with the following four areas:
- Sign users in
- Classic archive (small number of changes)
- Concepts (very small number of changes)
- Reference (very small number of changes)
- **Preview URL** https://633d976464755e1120e74d71--reverent-murdock-829d24.netlify.app/docs/guides/ 
* [OKTA-537852](https://oktainc.atlassian.net/browse/OKTA-537852)
> shorten tree nav titles, 4 areas

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Left-nav menu titles are shortened for OIN
* [OKTA-538557](https://oktainc.atlassian.net/browse/OKTA-538557)
> OKTA-538557 Shorten left-nav labels for OIN

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** This PR shortens the tree nav titles for the "Okta Identity Engine upgrade" section of the guides.
* [OKTA-537858](https://oktainc.atlassian.net/browse/OKTA-537858)
> Shorten OIE upgrade tree nav titles

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** This PR shortens the tree nav titles for the "Deploy to production" section of the guides.
* [OKTA-537864](https://oktainc.atlassian.net/browse/OKTA-537864)
> Shorten deployment treenav titles

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/php/independ.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/php/reqautheverything.md
- **What's changed?** Updates the PHP API quickstart to the firebase/php-jwt library, since the previous one was deprecated. The sample project is already updated to match https://github.com/okta-samples/okta-php-api-quickstart
> update sample code with firebase/php-jwt library

- packages/@okta/vuepress-site/docs/reference/api/uischema/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adds reference docs for UISchema API
* [OKTA-448404](https://oktainc.atlassian.net/browse/OKTA-448404)
> UISchema API docs

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- **What's changed?** Rate limit updates for user OTP activation
- **Is this PR related to a Monolith release?** Yes, 2022.10.0-after-Prod
* [OKTA-429940](https://oktainc.atlassian.net/browse/OKTA-429940)
> OKTA-429940 Add OTP activation rate limit

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add RN item to 2022.10.0, post production deployment.
- **Is this PR related to a Monolith release?** Yes, 2022.10.0 (post-all-prod)
* [OKTA-537076](https://oktainc.atlassian.net/browse/OKTA-537076)
> OKTA-537076 Add post-production deployment RN item for 2022.10.0

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/php/independ.md
fixes code block in quickstart https://developer.okta.com/docs/guides/protect-your-api/php/main/#include-the-dependencies
> replace spaces with tabs

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Adding release notes for 2022.10.1
- **Is this PR related to a Monolith release?** 2022.10.1
* [OKTA-539403](https://oktainc.atlassian.net/browse/OKTA-539403)
> RNs for 2022.10.1

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Add user profile attribute mapping note for group functions
* [OKTA-538109](https://oktainc.atlassian.net/browse/OKTA-538109)
> OKTA-538109 Add user attribute mapping note for group functions

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Docs release branch for 2022.10.1
- **Is this PR related to a Monolith release?** 2022.10.1
* [OKTA-539403](https://oktainc.atlassian.net/browse/OKTA-539403)
> Release 2022.10.1

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
- **What's changed?** The PAT team suggested some updates to the OIE upgrade landing page. This PR implements those.
- **Preview URL** https://63492d92e22d7518b4f27e82--reverent-murdock-829d24.netlify.app/docs/guides/oie-upgrade-overview/main/
* [OKTA-541252](https://oktainc.atlassian.net/browse/OKTA-541252)
> update OIE upgrade landing page

- packages/@okta/vuepress-theme-prose/package.json
- yarn.lock
- Upgrade moment-timezone related dependencies
* [OKTA-514727](https://oktainc.atlassian.net/browse/OKTA-514727)
* [OKTA-514728](https://oktainc.atlassian.net/browse/OKTA-514728)
> Upgrade moment related dependencies

- package.json
- yarn.lock
- **What's changed?** Upgrade got
* [OKTA-527546](https://oktainc.atlassian.net/browse/OKTA-527546)
> Upgrade got dependency

- package.json
- yarn.lock
- **What's changed?** [Upgrade unset-value](https://github.com/okta/okta-developer-docs/commit/cf31f7dca21b3b23ab053aa53262ba796351e969)
* [OKTA-530621](https://oktainc.atlassian.net/browse/OKTA-530621)
> Upgrade unset-value

- package.json
- yarn.lock
- **What's changed?** Upgrade cssnano, node-forge and nth-check
* [OKTA-527546](https://oktainc.atlassian.net/browse/OKTA-527546)
> Upgrade cssnano, node-forge and nth-check

- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- **What's changed?** Update Trusted Origins API to define number of trusted origins returned with and without a limit defined
* [OKTA-542264](https://oktainc.atlassian.net/browse/OKTA-542264)
> Update Trusted Origins API to define number of trusted origins returned with and without a limit defined

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- **What's changed?** Added a note with details on max payload for hook response to this section: https://developer.okta.com/docs/concepts/inline-hooks/#the-response
* [OKTA-544181](https://oktainc.atlassian.net/browse/OKTA-544181)
> OKTA-544181 Add max payload for hooks in Concepts

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Added classic and oie release notes for this weekly release.
- **Is this PR related to a Monolith release?** 2022.10.2
* [OKTA-541264](https://oktainc.atlassian.net/browse/OKTA-541264)
> OKTA-541264 - Release note entry for 2022.10.2

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding classic and Identity Engine release notes for weekly release. Includes one doc update to Apps API
- **Is this PR related to a Monolith release?** 2022.10.2
* [OKTA-541264](https://oktainc.atlassian.net/browse/OKTA-541264)
> OKTA-541264 Weekly Release Notes - 2022.10.2

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- **What's changed?** Added the EA tag to the [Inline Hook concept](https://developer.okta.com/docs/concepts/inline-hooks/) and the [Common Hook set up steps](https://developer.okta.com/docs/guides/common-hook-set-up-steps/nodejs/main/) guide.
* [OKTA-545221](https://oktainc.atlassian.net/browse/OKTA-545221)
> OKTA-545221 - Add EA flag to concept and guide for OAuth 2.0 for Inline Hooks feature

- packages/@okta/vuepress-site/docs/reference/api/zones/index.md
- **What's changed?** Remove the EA tag on the Zones API, which has been GA for some time.
* n/a
> Remove EA feature tag on Zones API

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding release notes for 2022.11.0
- **Is this PR related to a Monolith release?** Yes. 2022.11.0
* [OKTA-545213](https://oktainc.atlassian.net/browse/OKTA-545213)
> RN entries for 2022.11.0

- packages/@okta/vuepress-site/docs/guides/step-up-authentication/main/index.md
- **What's changed?** Update to the max_age note to add Frank's change
- **Is this PR related to a Monolith release?** Yes. 2022.11.0
* [OKTA-536284](https://oktainc.atlassian.net/browse/OKTA-536284)
> update note for Franks change

- packages/@okta/vuepress-site/docs/reference/beta-only/index.md
- packages/@okta/vuepress-site/docs/reference/index.md
- packages/@okta/vuepress-theme-prose/components/Home.vue
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** This PR makes changes to the site to prepare it for the [Redocly beta launch](https://docs.google.com/document/d/1wlgkXtG_44PmjxOKGMJeSOv6AbyLap56Z1grhi2nvPw/edit#).
- **Preview URLs**:
- https://63629f1161069a317d15be35--reverent-murdock-829d24.netlify.app/
- https://63629f1161069a317d15be35--reverent-murdock-829d24.netlify.app/docs/reference/
- https://63629f1161069a317d15be35--reverent-murdock-829d24.netlify.app/docs/reference/beta-only/
* [OKTA-544763](https://oktainc.atlassian.net/browse/OKTA-544763)
* [OKTA-544759](https://oktainc.atlassian.net/browse/OKTA-544759)
* [OKTA-544762](https://oktainc.atlassian.net/browse/OKTA-544762)
> Redocly beta launch changes

- packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
- packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Remove code format from RN title and update HOC links from XaaS and API service integration guides. Fix Redocly site URL.
> Fix HOC links from XaaS and API service int guides and RN title

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** added note about not being able to change the application type after the app is created
* [OKTA-547943](https://oktainc.atlassian.net/browse/OKTA-547943)
> adding note about application type

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- **What's changed?** Removes smart card IdP content from OIE upgrade guide
* [OKTA-549371](https://oktainc.atlassian.net/browse/OKTA-549371)
> OKTA-549371 Remove smart card IdP content from OIE upgrade guide

- packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
- **What's changed?** Update API design principles to match Redocly design principle content. See https://developer.okta.com/docs/api/#design-principles.
* [OKTA-547032](https://oktainc.atlassian.net/browse/OKTA-547032)
> OKTA-547032 Update API design principles to match Redocly design principle content

- packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
- packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
- **What's changed?** Update HOC aliases for API Service Integrations and Anything-as-a-Source guide. Update XaaS Workflow description. This PR is to be merged after Nov 7 when the HOC aliases are live.
> Update HOC alias links and XaaS Workflow description

- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
Add dev doc for these APIs:
-- /api/v1/authorizationServers/${authorizationServerId}/policies/${policyId}/lifecycle/activate
-- /api/v1/authorizationServers/${authorizationServerId}/policies/${policyId}/lifecycle/deactivate
-- /api/v1/authorizationServers/${authorizationServerId}/policies/${policyId}/rules/${ruleId}/lifecycle/activate
-- /api/v1/authorizationServers/${authorizationServerId}/policies/${policyId}/rules/${ruleId}/lifecycle/deactivate
-- /api/v1/authorizationServers/${authorizationServerId}/credentials/keys/${keyId}
-- /api/v1/authorizationServers/${authorizationServerId}/policies/${policyId}/clients
No
* [OKTA-483496](https://oktainc.atlassian.net/browse/OKTA-483496)
> Add dev doc for 6 APIs under Authorization Server Section

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Add 2022.11.1 release note entries
- **Is this PR related to a Monolith release?** Yes, 2022.11.1
* [OKTA-548315](https://oktainc.atlassian.net/browse/OKTA-548315)
> OKTA-548315 Release note 2022.11.1 entries

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?**Remove webauthn from hardware protected constraint examples
* [OKTA-551775](https://oktainc.atlassian.net/browse/OKTA-551775)
> OKTA-551775 Remove webauthn from hw protected constraint

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/copyright/index.md
- packages/@okta/vuepress-theme-prose/assets/css/components/_copyright.scss
- packages/@okta/vuepress-theme-prose/assets/css/prose.scss
- packages/@okta/vuepress-theme-prose/components/Copyright.vue
- packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?** Added copyrights and trademark acknowledgments page to the site footer 
- Netlify link : https://6376476063ee3e1db1a92529--reverent-murdock-829d24.netlify.app/copyright/
* [OKTA-537533](https://oktainc.atlassian.net/browse/OKTA-537533)
> OKTA-537533 Added copyrights and trademarks page

- packages/@okta/vuepress-site/docs/concepts/iam-overview-identity-management-factors/index.md
- packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md
- packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
- packages/@okta/vuepress-site/docs/guides/archive-set-up-self-service-registration/main/index.md
- packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/nextsteps.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/nextsteps.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/nextsteps.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/nextsteps.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/nextsteps.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/set-up-self-service-registration/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/release-notes/2018/index.md
- packages/@okta/vuepress-site/docs/release-notes/2019/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
For the sake of consistency with UX and use more customer-focused language, replaced references to "custom URL domain" with "custom domain" and replaced "email custom domain" with "email addresses"
* n/a
> custom domain and email addresses

- packages/@okta/vuepress-theme-prose/assets/css/components/_copyright.scss
> Fix stylelint issues in copyright.scss

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release notes for 2022.11.1
- **Is this PR related to a Monolith release?** Yes, 2022.11.1
* [OKTA-548315](https://oktainc.atlassian.net/browse/OKTA-548315)
> OKTA-548315 Release notes for 2022.11.1

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Update expected in preview org date to Nov 30, 2022
- **Is this PR related to a Monolith release?** Yes, 2022.11.1
* [OKTA-548315](https://oktainc.atlassian.net/browse/OKTA-548315)
> OKTA-548315 Update Expected in Preview Orgs date to Nov 30, 2022

- package.json
- yarn.lock
Upgrade cypress and add qs resolution
* [OKTA-552865](https://oktainc.atlassian.net/browse/OKTA-552865)
> Upgrade cypress and add qs resolution

- packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?**footer update with terms of service changes
-
* [OKTA-555474](https://oktainc.atlassian.net/browse/OKTA-555474)
> footer update with terms of service changes

- packages/@okta/vuepress-site/docs/guides/step-up-authentication/main/index.md
- **What's changed?** adding embedded to wording
> adding embedded to wording

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **Add documentation of 'revokeSessions' parameter to appropriate APIs** 
- **Is this PR related to a Monolith release?**  2022.12.0
* [OKTA-553270](https://oktainc.atlassian.net/browse/OKTA-553270)
> Add documentation of 'revokeSessions' parameter to appropriate APIs

- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- **What's changed?** Updates to the [Rate Limit dashboard page](https://developer.okta.com/docs/reference/rl-dashboard/) to include a note on parameter matching limits.
- 
- **Is this PR related to a Monolith release?** Yes, 2022.12.0
* [OKTA-551420](https://oktainc.atlassian.net/browse/OKTA-551420)
> OKTA-551420 Rate Limits - Support for parameter search

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
…F2 hashing algo changes
- **What's changed?** Update User API developer docs to reflect PBKDF2 hashing algo changes
- **Is this PR related to a Monolith release?** Yes 2022.12.0
Hashed Password object section changes 
Request Body 
* [OKTA-553281](https://oktainc.atlassian.net/browse/OKTA-553281)
> Update User API developer docs to reflect PBKDF2 hashing algo changes

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- **What's changed?** Update to the following docs to add preview tab feature for the Token Inline Hook:
* [Token inline hook guide](https://developer.okta.com/docs/guides/token-inline-hook/nodejs/main/#test-the-token-inline-hook)
* [Common Hook set up steps](https://developer.okta.com/docs/guides/common-hook-set-up-steps/nodejs/main/#troubleshoot-hook-implementations)
* [Inline hook concept](https://developer.okta.com/docs/concepts/inline-hooks/#troubleshooting)
* [Hooks best practices](https://developer.okta.com/docs/reference/hooks-best-practices/)
- **Is this PR related to a Monolith release?** 2022.12.0
* [OKTA-550605](https://oktainc.atlassian.net/browse/OKTA-550605)
> OKTA-550605 Token hook preview feature update

- package.json
- packages/@okta/vuepress-site/package.json
- packages/@okta/vuepress-theme-prose/package.json
- yarn.lock
- cypress
- async
- chai
- markdown-it-attrs
- postcss-scss
- query-string
- recursive-readdir
- semver
- serve-handler
- stylelint
- sass
- chalk
OKTA-489377
> Bundle of patch dependency upgrades

- packages/@okta/vuepress-theme-prose/index.js
- packages/@okta/vuepress-theme-prose/package.json
- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
- packages/@okta/vuepress-theme-prose/util/coveo/endpoint.js
- yarn.lock
- Replace `moment` and `moment-timezone` with `luxon`
* [OKTA-556896](https://oktainc.atlassian.net/browse/OKTA-556896)
> Replace moment with luxon

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
-  Adding suggested information in API doc about data consistency policy and latency parameters with the query and filter string parameters that will be directed to the DRBI (replica, instead of the primary)
Resolves: OKTA-543126
- **Is this PR related to a Monolith release?** - NA
* [OKTA-543126](https://oktainc.atlassian.net/browse/OKTA-543126)
> OKTA-543126: Update List Users API spec content on developer.okta.com

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Added a note to `Arrays.*` function as per external PR request.
* [OKTA-554436](https://oktainc.atlassian.net/browse/OKTA-554436)
> OKTA-554436 Update to Expression Language overview

- packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
-Testing staging with Travis disabled
> Minimlal change to test staging

- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- Adjust signup agreement copy
* [OKTA-554575](https://oktainc.atlassian.net/browse/OKTA-554575)
> Adjust signup agreement copy

- scripts/yarn-checks.sh
- Remove commented code from yarn-checks.sh
> Remove commented code from yarn-checks.sh

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Changed release date to December 9 from the 7th, in both API and OIE API RNs
- **Is this PR related to a Monolith release?** 2022.12.0
* n/a
> Changed 2022.12.0 Preview release date

- packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
- **What's changed?** Remove broken PDF link to Fuze SCIM doc
* [OKTA-557217](https://oktainc.atlassian.net/browse/OKTA-557217)
> OKTA-557217 Remove broken PDF link to Fuze SCIM doc

- .github/workflows/build-and-checks.js.yml
Run workflow on all PRs and not just PRs targeting `master`
> Run workflow on all PRs

- packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** Removed reference to `//browser-update.org/update.min.js` in the `config.js` file.
* [OKTA-557390](https://oktainc.atlassian.net/browse/OKTA-557390)
> OKTA-557390 Commented out script that references 3rd-party scripting file

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Release Notes for 2022.12.1
- **Is this PR related to a Monolith release?** yes 2022.12.1
* [OKTA-557878](https://oktainc.atlassian.net/browse/OKTA-557878)
> Release Notes for 2022.12.1

- packages/@okta/vuepress-site/code/php/simplesamlphp/index.md
- packages/@okta/vuepress-site/docs/concepts/oie-intro/index.md
- **What's changed?** Fixed on broken link to saml doc
* [OKTA-557214](https://oktainc.atlassian.net/browse/OKTA-557214)
> OKTA-557214 FIXIT Day: fix broken link in SAML doc

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- **What's changed?** Updating the JSON response to GET Device endpoint as per PR#3788, which is blocked by previous Travis CI check.
* n/a
> Update Devices API reference as per PR3788

- packages/@okta/vuepress-theme-prose/components/Home.vue
- **What's changed?** Reproduced PR#3496 to bypass Travis check
* n/a
> Adding users to homepage as per PR3496

- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- **What's changed?** Release 2022.12.1
- **Is this PR related to a Monolith release?** Yes Release 2022.12.1
* [OKTA-557878](https://oktainc.atlassian.net/browse/OKTA-557878)
> Release 2022.12.1

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- Documented free.fr inbox known issue
-
- no
* https://oktainc.atlassian.net/browse/OKTA-542960
> free.fr known issue

- .github/workflows/netlify-preview.js.yml
Remove netlify comment and pr comment functionality
> Remove comment and pr comment functionality

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
* [OKTA-559421](https://oktainc.atlassian.net/browse/OKTA-559421)
> rn entries

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- **What's changed?**  Added parameter `vendorName` to Factors object table, and included updates to provider type objects, as per this github issue: https://github.com/okta/okta-developer-docs/issues/3805
* [OKTA-557546](https://oktainc.atlassian.net/browse/OKTA-557546)
> OKTA-557546 UpdateFactors api

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding missed blurbs
- **Is this PR related to a Monolith release?** Yes 2022.07.0
> adding in missed blurbs

- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
- **What's changed?** Added a `PUT` request example for [Update specific Group Membership](https://developer.okta.com/docs/reference/scim/scim-20/#update-specific-group-membership) section.
* [OKTA-562221](https://oktainc.atlassian.net/browse/OKTA-562221)
> OKTA-562221 Update SCIM reference docs with example

- scripts/setup.sh
- We use 14.x through github action, this is needed on bacon's promote job as well.
> Upgrade setup.sh's node version to v14.x

- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** made a tweak to a July blurb per Shaye
- **Is this PR related to a Monolith release?** 2022.07.0
> Shaye's update

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Adding release notes for the weekly
- **Is this PR related to a Monolith release?** 2022.12.3
* [OKTA-562214](https://oktainc.atlassian.net/browse/OKTA-562214)
> Weekly Release notes merge into the Release branch

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- updated bullets on CAA record to be more clear
no
* n/a
> CAA record update

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Added weekly release notes
- **Is this PR related to a Monolith release?** 2022.12.3
* [OKTA-562214](https://oktainc.atlassian.net/browse/OKTA-562214)
> Weekly Release Notes - 2022.12.3

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Added a legal disclaimer to Users API in [Activate Users](https://developer.okta.com/docs/reference/api/users/#activate-user). (Included a few formatting updates as well.)
* [OKTA-565827](https://oktainc.atlassian.net/browse/OKTA-565827)
> OKTA-565827 UD-Core - Add legal limitations to Users API

- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Release notes entries 
- **Is this PR related to a Monolith release?** Yes 2023.01.0
* [OKTA-564522](https://oktainc.atlassian.net/browse/OKTA-564522)
> Rn entry 2023.01.0

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Updated deprecated note 
- **Is this PR related to a Monolith release?** Yes 2023.01.0
* [OKTA-565418](https://oktainc.atlassian.net/browse/OKTA-565418)
> Updating note

- packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
Resolves: OKTA-549236
- **What's changed?** Updated representation of Splunk HEC token field
- **Is this PR related to a Monolith release?** Yes, 2023.01.0
* [OKTA-549236](https://oktainc.atlassian.net/browse/OKTA-549236)
> OKTA-549236: Updating dev docs to reflect hiding sensitive data in Splunk token field

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** For completeness, added the same legal disclaimer in Activate User to the Create User section (see [#3873](https://github.com/okta/okta-developer-docs/pull/3873))
* [OKTA-565827](https://oktainc.atlassian.net/browse/OKTA-565827)
> OKTA-565827 UD-Core: Added disclaimer to Create User operation

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/go/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/main/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/go/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/go/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/ios/sdksforauthflows.md
- **What's changed?** fixing references to Open ID Connect and the possessive use of Okta
> fixing OIDC references and possessive use of Okta

- packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/nodejs/sendsmsmakecall.md
- **What's changed?** Updated call example with additional line
* [OKTA-565972](https://oktainc.atlassian.net/browse/OKTA-565972)
> adding line

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release Notes for 2023.01.1
- **Is this PR related to a Monolith release?** Yes, 2023.01.1
* [OKTA-566138](https://oktainc.atlassian.net/browse/OKTA-566138)
> OKTA-566138 Release Notes for 2023.01.1

- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-connect/main/index.md
- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
- **What's changed?** This PR adds in generic wireframes and makes other improvements, as described in the Group 6 tab of the [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1rSd7rKfuTH8qa0LnpV55JHr70KRsB0IcRBYQd_l-Q_U/edit#gid=0) for this work. You can see a work description at https://oktainc.atlassian.net/browse/OKTA-521155.
- **Preview URL** TBC
* [OKTA-521169](https://oktainc.atlassian.net/browse/OKTA-521169)
> group 6 screenshot cleanup

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** style errors in TOC
> style errors in TOC

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/summaryofsteps.md
- **What's changed?** New PR with content from PR 3813 from timtoyoshima (need a successful Travis build)
> New PR with content from PR 3813 from timtoyoshima

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/getuserprofile.md
- **What's changed?** New PR with content from PR 3815 by timtoyoshima (update to embedded oie use cases)
> New PR with content from PR 3815 by timtoyoshima

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?** removed blurb per Doc Action, tweaked blurb in new location
- **Is this PR related to a Monolith release?** yes 2023.01.0 and 2023.01.1
* [OKTA-525478](https://oktainc.atlassian.net/browse/OKTA-525478)
> Removing blurb per Doc Action

- packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
- **What's changed?** Corrected the `filter` example in the [Core API](https://developer.okta.com/docs/reference/core-okta-api/#filter) section.
* n/a
> UD-Core Minor update to filter example in core api

- packages/@okta/vuepress-site/docs/reference/api/domains/index.md
- added prose around PUT for /domains to add additional clarity around the use cases for the same API call
- no code changes, just reference doc update
n/a, requested by an SE
> PUT update for /domains

- packages/@okta/vuepress-site/docs/concepts/oie-intro/index.md
- packages/@okta/vuepress-site/docs/guides/archive-overview/index.md
- packages/@okta/vuepress-site/docs/guides/archive-overview/main/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Update "Classic archive" to "Okta Classic Engine" in TOC, and remove references to "archive"
* [OKTA-570283](https://oktainc.atlassian.net/browse/OKTA-570283)
> OKTA-570283 Update Classic archive to Okta Classic Engine

- packages/@okta/vuepress-site/docs/reference/api/asa/teams/index.md
- **What's changed?** Small note to indicate that a specific endpoint processes requests asynchronously.
* [OKTA-507487](https://oktainc.atlassian.net/browse/OKTA-507487)
> Async note

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Adding Create a profile object example to App API
* [OKTA-365743](https://oktainc.atlassian.net/browse/OKTA-365743)
> Add create a profile object example

- packages/@okta/vuepress-site/docs/release-notes/index.md
- **What's changed?** Update Release Note page to link to 2023 OIE RN
> Update Release Note page to link to 2023 OIE RN

- package.json
- packages/@okta/vuepress-site/package.json
- yarn.lock
- Upgrade dependencies
* [OKTA-566577](https://oktainc.atlassian.net/browse/OKTA-566577)
> upgrade loader-utils

- packages/@okta/vuepress-site/docs/reference/rl-previous/index.md
- **What's changed?** Added a note clarifying high rate limit capacity to: [https://developer.okta.com/docs/reference/rl-previous/#high-capacity-rate-limits](https://developer.okta.com/docs/reference/rl-previous/#high-capacity-rate-limits)
* [OKTA-486319](https://oktainc.atlassian.net/browse/OKTA-486319)
> OKTA-486319 - Team Scotty - Added a note to previous rate limits page

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release Note Entries
- **Is this PR related to a Monolith release?** 2023.01.2
* [OKTA-568344](https://oktainc.atlassian.net/browse/OKTA-568344)
> Rn entry 2023.01.2

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add release note item after 2023.01.1 all prod.
- **Is this PR related to a Monolith release?** Yes, after all prod 2023.01.1
* [OKTA-566138](https://oktainc.atlassian.net/browse/OKTA-566138)
> OKTA-566138 Add post 2023.01.1 release note item

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **What's changed?** Backport Authenticator Methods endpoint based on oas3 PR 328
https://63d7e9d7162c763b6e500116--reverent-murdock-829d24.netlify.app/docs/reference/api/authenticators-admin/
* [OKTA-569292](https://oktainc.atlassian.net/browse/OKTA-569292)
> OKTA-569292 Backport Authenticator Methods endpoint

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Wording change to CSP item to match changes from prod.
- **Is this PR related to a Monolith release?** 2023.01.2
* [OKTA-568344](https://oktainc.atlassian.net/browse/OKTA-568344)
> Adjust text for OKTA-567669 (CSP)

- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- **What's changed?** remove themes guide
> STAGING - remove themes guide

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** remove space from release note comment to push redeploy 
- 
> Redeploy release notes

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- [Custom domain and email domain](https://63e29d56a43f1320e39a5dc0--reverent-murdock-829d24.netlify.app/docs/guides/custom-url-domain/main/)
- [Sign-in page](https://63e29d56a43f1320e39a5dc0--reverent-murdock-829d24.netlify.app/docs/guides/custom-widget/main/)
- [Error pages](https://63e29d56a43f1320e39a5dc0--reverent-murdock-829d24.netlify.app/docs/guides/custom-error-pages/main/)
- [Email notifications](https://63e29d56a43f1320e39a5dc0--reverent-murdock-829d24.netlify.app/docs/guides/custom-email/main/)
> Multibrand UI updates

- packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
- **What's changed?** Update API Service integration UI labels in OIN Manager based on changes from OKTA-525864 (already released on torii)
https://63e1df09f64ab91414f614d8--reverent-murdock-829d24.netlify.app/docs/guides/build-api-integration/main/#register-your-api-service-integration
* [OKTA-572232](https://oktainc.atlassian.net/browse/OKTA-572232)
> OKTA-572232 Update API Service integration UI labels in OIN Manager

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Add configuredAttributeStatements SAML property
- **Is this PR related to a Monolith release?** Yes, 2023.02.0 (updated from 2023.01.2)
* [OKTA-571620](https://oktainc.atlassian.net/browse/OKTA-571620)
> OKTA-571620 Add configuredAttributeStatements SAML property to Apps API

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** Add properties.additionalAmr property to the IdP API for Smart Card authenticator
- **Is this PR related to a Monolith release?** Yes, doc' with RN in 2023.02.0 (orig in 2023.01.1)
https://63e30e0ff6482c0c81ad33f1--reverent-murdock-829d24.netlify.app/docs/reference/api/idps/#identity-provider-properties
* [OKTA-567644](https://oktainc.atlassian.net/browse/OKTA-567644)
> OKTA-567644 API updates for X509_BASED_AUTHENTICATOR

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release note entries for 2023.02.0
- **Is this PR related to a Monolith release?** Yes, 2023.02.0
* [OKTA-574010](https://oktainc.atlassian.net/browse/OKTA-574010)
> OKTA-574010 Release note entries for 2023.02.0

- packages/@okta/vuepress-site/data/error-codes.json
- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- **What's changed?** Update event types catalogue and API errors page
- **Is this PR related to a Monolith release?** yes, 2023.02.0
* [OKTA-574010](https://oktainc.atlassian.net/browse/OKTA-574010)
> OKTA-574010 Update event types catalogue and API errors page

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- **What's changed?** Removes outdated note and provides link to updates in redocly.
> Brands API remove old note and add new

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?** Removing RN blurb
- **Is this PR related to a Monolith release?** 2023.02.0 
* [OKTA-565854](https://oktainc.atlassian.net/browse/OKTA-565854)
> removing RN

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **What's changed?** Add Smart Card authenticator example and key. Add userVerification description for WebAuthn.
* [OKTA-575752](https://oktainc.atlassian.net/browse/OKTA-575752)
> OKTA-575752 Authenticators API updates for Smart Card and WebAuthn

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** release notes entry for 2023.02.1
- **Is this PR related to a Monolith release?** yes 2023.02.1
* [OKTA-576341](https://oktainc.atlassian.net/browse/OKTA-576341)
> Rn entry 2023.02.1

- scripts/helpers.sh
- scripts/setup.sh
> update script auth

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- **What's changed?** Added a note indicating warning, burst, and violation emails are not sent for every call.
* [OKTA-552301](https://oktainc.atlassian.net/browse/OKTA-552301)
> OKTA-552301 Team Scotty: Update to rate limits dashboard

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add new homepage announcement in the 2023.02.0 dev docs release notes
- **Is this PR related to a Monolith release?** Yes, 2023.02.0 (Merge this PR after approvals and following the homepage PR merge)
> Add new homepage announcement in the 2023.02.0 dev docs release notes

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- **What's changed?** blurb added to note in authn api
* [OKTA-580251](https://oktainc.atlassian.net/browse/OKTA-580251)
> blurb added to note in authn api

- packages/@okta/vuepress-site/docs/concepts/brands/index.md
- **What's changed?** Adds links to API docs.
https://63f8d878d8c9441a7f05153f--reverent-murdock-829d24.netlify.app/docs/concepts/brands/#use-the-brands-api
* [OKTA-580212](https://oktainc.atlassian.net/browse/OKTA-580212)
> Adds API links to brands concept doc

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release notes entries.
- **Is this PR related to a Monolith release?** 2023.02.2
* [OKTA-578706](https://oktainc.atlassian.net/browse/OKTA-578706)
> Rn entry 2023.02.2

- packages/@okta/vuepress-site/docs/reference/architecture-tutorials/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-tutorials/mmod/lab-1-configure-terraform-cloud/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-tutorials/mmod/lab-4-deploy-changes-to-production/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-tutorials/mmod/lab-6-synchronize-environments-daily/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- Removed (wip) from left navbar option for Architecture Tutorials
- Fixed several invalid links in the Terraform tutorials.
> RefArch Quick Fix March 01

- packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
- I removed a curly quote in a request body and replaced it with a normal double quote
- **Is this PR related to a Monolith release?** <!-- If so, which one?
No
* Community submitted change
> Remove curly quote in example request body for  Anything as a Source Doc

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/hook-keys/index.md
- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- **What's changed?** Removing EA tags for OAuth 2.0 for inline hooks
- **Is this PR related to a Monolith release?** 2023.03.0
* [OKTA-581384](https://oktainc.atlassian.net/browse/OKTA-581384)
> Removing EA flags for OAuth for Inline Hooks GA

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- **What's changed?** Updates to Okta Event Hook rate limits on Concepts and Best Practices pages, including increate in limit as per release.
- **Is this PR related to a Monolith release?** 2023.03.0
* [OKTA-581814](https://oktainc.atlassian.net/browse/OKTA-581814)
> OKTA-581814 Update to Event Hook rate limits

- packages/@okta/vuepress-site/docs/guides/set-up-token-exchange/main/index.md
- **What's changed?** fixed a typo and made the requests more clear with better headings
* [OKTA-586154](https://oktainc.atlassian.net/browse/OKTA-586154)
> Clarity around auth code with pkce steps

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- Adding in docs for myAccount API password endpoints
* [OKTA-502543](https://oktainc.atlassian.net/browse/OKTA-502543)
> Adding myAccount Password Docs

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Updates for Bug item
- **Is this PR related to a Monolith release?** 2023.03.0
> 2023.03.0 - Bug Wording

- packages/@okta/vuepress-site/docs/guides/set-up-token-exchange/main/index.md
- **What's changed?** Update to make more browser-specific for authorize request
> updates to pkce section

- packages/@okta/vuepress-theme-prose/assets/css/layouts/_layout.scss
- **What's changed?** Updating font weight for bold format
* n/a
> Update bold font weight in layout

- packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
- **What's changed?** Added clarifications to [client-based rate limits](https://developer.okta.com/docs/reference/rl-clientbased/) page
* [OKTA-586145](https://oktainc.atlassian.net/browse/OKTA-586145)
> OKTA-586145 - Updates to Client-based rate limits

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adding release notes to release branch
- **Is this PR related to a Monolith release?** 2023.03.1
* [OKTA-586700](https://oktainc.atlassian.net/browse/OKTA-586700)
> Release Note entry for 2023.03.1

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Updated note in OIN Submission requirements: https://developer.okta.com/docs/guides/submit-app-prereq/main/#customer-configuration-document-guidelines
* n/a
> OIN - Removed SAML references in customer config doc guidelines

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/client-secret-rotation-key-mgmnt.json
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- **What's changed?** Removed expect CT header from Client Secret Rotation postman collection responses
- **Is this PR related to a Monolith release?** yes 2023.02.2
* [OKTA-579593](https://oktainc.atlassian.net/browse/OKTA-579593)
> Removed expect CT header from Client Secret Rotation postman collection responses

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- **What's changed?** added note about parameter not shared across Classic and IE
* [OKTA-568720](https://oktainc.atlassian.net/browse/OKTA-568720)
> adding deviceToken note

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Add Parmonic doc link (OIN Ops confirmed that customer approved to add the link)
* [OKTA-581819](https://oktainc.atlassian.net/browse/OKTA-581819)
> OKTA-581819 Add Parmonic doc link - approved by customer

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/reqautheverything.md
- **What's changed?** add link to Add Packages section 
* [OKTA-368657](https://oktainc.atlassian.net/browse/OKTA-368657)
> add link to Add Packages section

- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/nodejs/event-object.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/nodejs/parse-request.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/nodejs/verification.md
- **What's changed?** Prepping for event hook filtering feature updates: Fixing a few errors, which led to few structural changes, which led to some code updates, and then a final thrashing by Acrolinx.
- **Is this PR related to a Monolith release?** 2023.04.0
* [OKTA-593386](https://oktainc.atlassian.net/browse/OKTA-593386)
> OKTA-593386 - Event Hook guide updates

- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
- **What's changed?** Add note that at least one user is required before running SCIM test suite
* [OKTA-580718](https://oktainc.atlassian.net/browse/OKTA-580718)
> OKTA-580718 Add user required for SCIM test suite note

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **What's changed?** Adds a note to identify limitations with webatun for Yubikeys. The note matches content being included on HOC.
- **Is this PR related to a Monolith release?** 2023.03.03
[Link](https://641cb61bd6d2c400b59b10aa--reverent-murdock-829d24.netlify.app/docs/reference/api/authenticators-admin/#authenticator-method-settings-object)
* [OKTA-593196](https://oktainc.atlassian.net/browse/OKTA-593196)
> Added note to aaguid object

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** RN Items
- **Is this PR related to a Monolith release?** 2023.03.3
* [OKTA-592840](https://oktainc.atlassian.net/browse/OKTA-592840)
> Add Blurbs

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-plan-embedded-upgrades/main/index.md
- **What's changed?** CORS bullet item in upgrade doc
Netlify: https://64236991c26b5b0944cbe4d6--reverent-murdock-829d24.netlify.app/docs/guides/oie-upgrade-plan-embedded-upgrades/main/#update-the-embedded-sign-in-widget
* [OKTA-594449](https://oktainc.atlassian.net/browse/OKTA-594449)
> Sdh okta594449 cors

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/python/addconfigpkg.md
- **What's changed?** Need to pin the Werkzeug package to a version that works, otherwise your example is broken.
*
> Update addconfigpkg.md to pin required package

- packages/@okta/vuepress-site/docs/guides/social-login/main/apple/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/facebook/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/google/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/linkedin/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/microsoft/idpaccount.md
Removed redundant 'with' in 'Social Login' - What you need.
Remove redundant 'with' in several modules - in *Social Login* page - section *What you need*
For: 
- Apple
- Facebook
- Google
- LinkedIn
- Microsoft
> Update idpaccount.md to avoid redundant text 'with' in Social Login page

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adding release notes for 2023.04.0
- **Is this PR related to a Monolith release?** Yes. 2023.04.0
* [OKTA-595640](https://oktainc.atlassian.net/browse/OKTA-595640)
> Rn entry 2023.04.0

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/python/addconfigpkg.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/apple/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/facebook/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/google/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/linkedin/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/microsoft/idpaccount.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- **Adding a new api under Role Assignments to list all users with Role Assignments** 
- **Is this PR related to a Monolith release?** Yes, 2023.04.0 
* [OKTA-594103](https://oktainc.atlassian.net/browse/OKTA-594103)
https://user-images.githubusercontent.com/93153569/229934803-37f2d6ec-7e44-470d-9629-92f26a696583.mov
> OKTA-594103: All Admins API doc

- packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md
- packages/@okta/vuepress-site/docs/guides/oin-api-service-overview/index.md
- **What's changed?** Remove EA flag and note from API Service Integrations, and update scope link.
- **Is this PR related to a Monolith release?** Yes, 2023.04.0
* [OKTA-577514](https://oktainc.atlassian.net/browse/OKTA-577514)
> OKTA-577514 Remove EA flag and note from API Service Integrations, and update link

- packages/@okta/vuepress-site/docs/guides/dpop/main/index.md
- **What's changed?** Added note about DPoP supporting service app
- **Is this PR related to a Monolith release?** Yes 2023.04.0
> service app note

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- **What's changed?** scope parameter character length updated
- **Is this PR related to a Monolith release?** Yes 2023.04.0
* [OKTA-594259](https://oktainc.atlassian.net/browse/OKTA-594259)
> update character length

- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** Added the endpoint `/signin/*` to the Authentication endpoints available for dynamic scale.
- **Is this PR related to a Monolith release?** 2023.04.0
* [OKTA-589035](https://oktainc.atlassian.net/browse/OKTA-589035)
> OKTA-589035 - Update Dynamic Scale with new endpoint

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/python/addconfigpkg.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/apple/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/facebook/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/google/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/linkedin/idpaccount.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/microsoft/idpaccount.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Reverts okta/okta-developer-docs#4075
> Revert "OKTA-594103: All Admins API doc"

- packages/@okta/vuepress-theme-prose/components/News.vue
- **What's changed?** Update the developer content shown on homepage
Netlify link: https://642de4500a8d0d04999ef37e--reverent-murdock-829d24.netlify.app
* None
> update developer content

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **What's changed?** Slight readability changes to a note. 
[Preview Content](https://642f37282eb8b008d3db2f41--reverent-murdock-829d24.netlify.app/docs/reference/api/authenticators-admin/#authenticator-method-settings-object)
* [OKTA-598068](https://oktainc.atlassian.net/browse/OKTA-598068)
> AAGUID Note Changes

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **What's changed?** Builds off an earlier PR to adjust wording of a note for AAGUID. Content called out Yubikey specifically, but SMEs want it generalized
* [OKTA-593196](https://oktainc.atlassian.net/browse/OKTA-593196)
> Remove Yubikey Wording

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Remove the ability to select "Apps for Good" use case in the OIN prereq doc
- **Is this PR related to a Monolith release?** No (related to torii release  ~ Apr 12, 2023)
* [OKTA-595738](https://oktainc.atlassian.net/browse/OKTA-595738)
> OKTA-595738 Remove the ability to select Apps for Good in the OIN prereq doc

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
- packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
Updated "sign-on policy" in two OIE docs to "authentication policy"
* [OKTA-481537](https://oktainc.atlassian.net/browse/OKTA-481537)
> OKTA-481537 Updated classic policy names to OIE names

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release 2023.04.1
- **Is this PR related to a Monolith release?** Yes 2023.04.1
* [OKTA-597848](https://oktainc.atlassian.net/browse/OKTA-597848)
> Release 2023.04.1

- packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sessions-api/main/index.md
- **What's changed?** Adding link and additional endpoint
* [OKTA-601417](https://oktainc.atlassian.net/browse/OKTA-601417)
> adding link and acrolinx

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Update OIN logo requirements as per fixes in OIN Manager.
https://6439b05a999d573b619a8b38--reverent-murdock-829d24.netlify.app/docs/guides/submit-app-prereq/main/#logo-guidelines
* [OKTA-599935](https://oktainc.atlassian.net/browse/OKTA-599935)
> OKTA-599935 Update logo requirements in OIN Manager

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Update OIN submission requirements for Customer configuration guide: add separate ISV guide note
* [OKTA-601609](https://oktainc.atlassian.net/browse/OKTA-601609)
> OKTA-601609 Add separate ISV guide note in OIN submission requirements

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Added a description stating how sorting is performed by characters (ASCII sort order)
* [OKTA-595653](https://oktainc.atlassian.net/browse/OKTA-595653)
> Added description of sorting by ASCII characters to address OKTA-595653.

- packages/@okta/vuepress-site/docs/guides/oin-oidc-best-practices/main/index.md
- **What's changed?** Update logo requirements in the outdated OIN integration best practices guide (this doc needs to be revamped in the very near future).
* [OKTA-587064](https://oktainc.atlassian.net/browse/OKTA-587064)
> OKTA-587064 Update outdated logo requirements in OIN integration best practices

- .github/workflows/netlify-preview.js.yml
* [OKTA-568681](https://oktainc.atlassian.net/browse/OKTA-568681)
> Update to force sha

- packages/@okta/vuepress-site/docs/reference/index.md
- **What's changed?** Added a link to the Group Owner API endpoints, which only exist on the beta Redocly site.
* n/a
> References Overview update with link to Group Owners API

- packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
- **What's changed?** As per slack/jira discussions, made the following updates:
- Added request parameters for Create User Type operation, including expanded definition for `name` parameter.
- Split out Update User Type operations (PUT/POST) into two separate operations, each with explicit request parameters and examples
- Updated response examples to match requests
* [OKTA-571460](https://oktainc.atlassian.net/browse/OKTA-571460)
> OKTA-571460 Updates to User Types API

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** API and OIE API release notes for this weekly
- **Is this PR related to a Monolith release?** 2023.04.2
* [OKTA-600440](https://oktainc.atlassian.net/browse/OKTA-600440)
> OKTA-600440 Release Notes for 2023.04.2

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release notes added for weekly release.
- **Is this PR related to a Monolith release?** 2023.04.2
* [OKTA-600440](https://oktainc.atlassian.net/browse/OKTA-600440)
> Release 2023.04.2 

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adds an additional blurb for a vuln.
- **Is this PR related to a Monolith release?** 2023.03.3
* [OKTA-592840](https://oktainc.atlassian.net/browse/OKTA-592840)
> Post fixes

- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/accesstoken.md
- **What's changed?** Guide referenced the old "Developer Console". C
> Correcting "Developer Console" reference

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/use-flow.md
- packages/@okta/vuepress-site/docs/guides/set-up-token-exchange/main/index.md
- **What's changed?** Missing bracket in link and removing EA SS bullet in OnBehalf of
> typo in saml2 and bullet removal onbehalf

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add RN entries for 2023.04.3
- **Is this PR related to a Monolith release?** Yes, 2023.04.3
* [OKTA-605248](https://oktainc.atlassian.net/browse/OKTA-605248)
> OKTA-605248 Add RN entries for 2023.04.3

- packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md
- **What's changed?** Added new Event Hook filter parameters to the API
- **Is this PR related to a Monolith release?** Removed from 2023.04.0 release. Release TBD
* [OKTA-592141](https://oktainc.atlassian.net/browse/OKTA-592141)
> OKTA-592141 Updates to Event Hook Mgmt API for monthly

- packages/@okta/vuepress-site/docs/guides/event-hook-filtering/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Initial draft of a simple event hook filter example
- **Is this PR related to a Monolith release?** Removed from 2023.04.0 release. Release TBD
* [OKTA-554534](https://oktainc.atlassian.net/browse/OKTA-554534)
> OKTA-554534 Part 2 event hook filtering guide

- packages/@okta/vuepress-theme-prose/components/Hero.vue
- **What's changed?** devday banner
Netlify
https://6452d3282dfff80080d0d6ea--reverent-murdock-829d24.netlify.app
* [OKTA-6035000](https://oktainc.atlassian.net/browse/OKTA-6035000)
> devday banner

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release Notes for 2023.04.3
- **Is this PR related to a Monolith release?** Yes, 2023.04.3
* [OKTA-605248](https://oktainc.atlassian.net/browse/OKTA-605248)
> OKTA-605248 Release Notes for 2023.04.3

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-ngrok/main/index.md
- packages/@okta/vuepress-theme-prose/global-components/EventHookEANote.vue
- packages/@okta/vuepress-theme-prose/global-components/EventHookEANoteProcedure.vue
- **What's changed?** Updates made to the following docs to include content / notes on EA event hook filtering feature:
- [Event Hook Concepts](https://developer.okta.com/docs/concepts/event-hooks/) - two new sections 
- [Event Hook](https://developer.okta.com/docs/guides/event-hook-implementation/nodejs/main/)
- [Event Hooks with ngrok](https://developer.okta.com/docs/guides/event-hook-ngrok/nodejs/main/)
- [Event hooks with Hookdeck](https://developer.okta.com/docs/guides/event-hook-hookdeck/nodejs/main/)
- **Is this PR related to a Monolith release?** Removed from 2023.04.0 release. Release TBD
* [OKTA-554534](https://oktainc.atlassian.net/browse/OKTA-554534)
> OKTA-554534 Updates to dev docs for event hook filtering

- packages/@okta/vuepress-theme-prose/components/Footer.vue
- **What's changed?** Updated the footer text to remove email address.
* [OKTA-607077](https://oktainc.atlassian.net/browse/OKTA-607077)
> OKTA-607077 - Update footer

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Changes a note to direct user to open a support case.
* [OKTA-604566](https://oktainc.atlassian.net/browse/OKTA-604566)
> Custom domain docs - add link to open support case

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- **What's changed?** Adds delauth note to MyAccount API docs
* [OKTA-606119](https://oktainc.atlassian.net/browse/OKTA-606119)
> Adds delauth note to MyAccount API docs

- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- **What's changed?** removed EA note
> actually the trusted origins note

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- Adding a new PUT `/api/v1/iam/roles/${roleIdOrLabel}/permissions/${permissionType}` with EA tag
- Updating GET `/api/v1/iam/roles/${roleIdOrLabel}/permissions/${permissionType}` to indicate conditions object in the response (EA)
- Updating POST `/api/v1/iam/roles/${roleIdOrLabel}/permissions/${permissionType}` to indicatie conditions object in the request body (EA)
- Adding a conditions object description
- **Is this PR related to a Monolith release?** yes, 2023.5.0
* [OKTA-519187](https://oktainc.atlassian.net/browse/OKTA-519187)
> OKTA-519187: conditions api changes

- packages/@okta/vuepress-site/docs/concepts/brands/index.md
- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- **What's changed?** Multibrand is going GA in Preview. Removes EA content and tweaks UI flow content.
- **Is this PR related to a Monolith release?** Yes. 2023.05.0
- https://645407fea4129a0061cf8c65--reverent-murdock-829d24.netlify.app/docs/concepts/brands/#multibrand-and-resource-sets
- https://645407fea4129a0061cf8c65--reverent-murdock-829d24.netlify.app/docs/guides/oie-upgrade-sign-in-widget/main/#upgrade-process-for-a-redirect-sign-in-flow
- https://645407fea4129a0061cf8c65--reverent-murdock-829d24.netlify.app/docs/guides/custom-url-domain/main/#use-an-okta-managed-certificate
- https://645407fea4129a0061cf8c65--reverent-murdock-829d24.netlify.app/docs/guides/custom-widget/main/#use-the-code-editor
- https://645407fea4129a0061cf8c65--reverent-murdock-829d24.netlify.app/docs/guides/c …
> Multibrand GA updates

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Remove `Staged` User requirement to reflect code changes.
- **Is this PR related to a Monolith release?** 2023.05.0
* [OKTA-604521](https://oktainc.atlassian.net/browse/OKTA-604521)
> Update wording for password hooks

- packages/@okta/vuepress-site/docs/reference/api/admin-notifications/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/attributes/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/audits/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/clients/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/entitlements/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/introduction/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/service-users/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/teams/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/users/index.md
- packages/@okta/vuepress-site/docs/reference/api/captchas/index.md
- packages/@okta/vuepress-site/docs/release-notes/2020/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Removes ASA content after a successful migration to Redocly.
- **Is this PR related to a Monolith release?** 2023.05.0
* [OKTA-606516](https://oktainc.atlassian.net/browse/OKTA-606516)
> Deprecate ASA content

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-filtering/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-ngrok/main/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- packages/@okta/vuepress-theme-prose/global-components/EventHookEANote.vue
- packages/@okta/vuepress-theme-prose/global-components/EventHookEANoteProcedure.vue
- **What's changed?** Merged three branches that contain updates to Event Hook documentation for the EA release of the event hook filtering feature, including a new guide.
- **Is this PR related to a Monolith release?** `2023.05.0`
* [OKTA-509724](https://oktainc.atlassian.net/browse/OKTA-509724)
> OKTA-509724 Event hook filtering feature 2023.05.0

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** add add for a new property of Apps API: identityStoreId 
- **Is this PR related to a Monolith release?** YES 2023.05.0
* [OKTA-603693](https://oktainc.atlassian.net/browse/OKTA-603693)
> add doc for identityStoreId

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- **What's changed?** Removes request params from the new "List all Users for a Device" operation
* [OKTA-610267](https://oktainc.atlassian.net/browse/OKTA-610267)
> Devices API - remove request params from new operation

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adding release notes for 2023.05.1
- **Is this PR related to a Monolith release?** Yes. 2023.05.1
* [OKTA-609971](https://oktainc.atlassian.net/browse/OKTA-609971)
> RN entry 2023.05.1

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/mfaoob/flow-diagram.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/mfaotp/flow-diagram.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/oob/flow-diagram.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/otp/flow-diagram.md
- **What's changed?** fixing size name in div class
> fixing div class

- packages/@okta/vuepress-site/docs/guides/authenticators-overview/main/index.md
- **What's changed?** PATEAM request to add password authenticator to authenticator overview page
* [OKTA-577727](https://oktainc.atlassian.net/browse/OKTA-577727)
> adding password auth to overview page

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** release notes entry 2023.05.2
- **Is this PR related to a Monolith release?** Yes. 2023.05.2
* [OKTA-611819](https://oktainc.atlassian.net/browse/OKTA-611819)
> release notes entry 2023.05.2

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- Add `mapAMRClaims` property to /idps API
- Yes this will be in monolith version `2023.05.2`
Corresponding OAS PR - https://github.com/okta/okta-oas3/pull/428
Corresponding monolith JIRA - https://oktainc.atlassian.net/browse/OKTA-568576
Local Preview -
* [OKTA-593253](https://oktainc.atlassian.net/browse/OKTA-593253)
> add mapAMRClaims property to /idps API

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release 2023.05.2
- **Is this PR related to a Monolith release?** Yes. Release 2023.05.2
* [OKTA-611819](https://oktainc.atlassian.net/browse/OKTA-611819)
> Release 2023.05.2

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Add note and example to the customer configuration doc: Big Bang configuration warning
https://646f6b256c46a1194f80f174--reverent-murdock-829d24.netlify.app/docs/guides/submit-app-prereq/main/#configuration-steps
* [OKTA-611855](https://oktainc.atlassian.net/browse/OKTA-611855)
> OKTA-611855 - Add OIN configuration doc warning example

- packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
- **What's changed?** Added three new sections on enabling self-service password recovery; mandatory MFA; and self-service registration
* [OKTA-555487](https://oktainc.atlassian.net/browse/OKTA-555487)
> Updates to Sign-in to SPA with AuthJS

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Add `default` to Deactivate default provisioning connection endpoint
* [OKTA-614864](https://oktainc.atlassian.net/browse/OKTA-614864)
> okta-614864 Add default to Deactivate default provisioning connection

- packages/@okta/vuepress-site/code/javascript/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/main/index.md
- **What's changed?** Added a JavaScript tile to the [Quickstart page](https://developer.okta.com/docs/guides/quickstart/main/) and removed the three "coming soon" tiles; also added a linke on the [JavaScript SDK code](https://developer.okta.com/code/javascript/) reference page, as well as cleaning up some terminology.
* [OKTA-597725](https://oktainc.atlassian.net/browse/OKTA-597725)
> OKTA-597725 - Updates to quickstart guide and javascript code reference

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** removed release note item per doc action
- **Is this PR related to a Monolith release?** Yes 2023.05.2
> remove rn per doc action

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?**  Update logo dimension descriptions and implement Acrolinx suggestions.
* [OKTA-616328](https://oktainc.atlassian.net/browse/OKTA-616328)
> OKTA-616328 Update logo dimension descriptions and implement Acrolinx suggestions

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md
- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- **What's changed?** Add note about claims and policies
* [OKTA-615553](https://oktainc.atlassian.net/browse/OKTA-615553)
> Add note about claims and policies

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adds blurbs to the release branch
- **Is this PR related to a Monolith release?** 2023.05.3
* [OKTA-613800](https://oktainc.atlassian.net/browse/OKTA-613800)
> Rn entry 2023.05.3

- packages/@okta/vuepress-site/docs/concepts/brands/index.md
- **What's changed?** Adds limitation content explaining the need to use the Brands API when sending the User Activation email.
* [OKTA-617069](https://oktainc.atlassian.net/browse/OKTA-617069)
> Multibrands and User Activation email - limitations note

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- **What's changed?** As per Anna Simmons, removing EA tags on the Admin Roles API in VuePress
* n/a
> Remove EA tags for IAM admin roles

- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
- **What's changed?** Made some updates to the Okta response for the Registration Inline Hook example.
* Internal issue over slack
> Update code for Registration Inline Hook

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- **What's changed?** Updating UI content for multibrand GA prod.
- **Is this PR related to a Monolith release?** Yes. 2023.06.0
- https://6480bc0c7c8fa5124da6c5aa--reverent-murdock-829d24.netlify.app/docs/guides/custom-url-domain/main/
- https://6480bc0c7c8fa5124da6c5aa--reverent-murdock-829d24.netlify.app/docs/guides/custom-widget/main/
- https://6480bc0c7c8fa5124da6c5aa--reverent-murdock-829d24.netlify.app/docs/guides/custom-error-pages/main/
- https://6480bc0c7c8fa5124da6c5aa--reverent-murdock-829d24.netlify.app/docs/guides/custom-email/main/
* [OKTA-611526](https://oktainc.atlassian.net/browse/OKTA-611526)
> Multibrand GA Prod

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- packages/@okta/vuepress-site/docs/reference/api/push-providers/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Revert doc action for OAUTH2_CIBA and CUSTOM_PUSH_AUTHENTICATOR. See new parent FF [OKTA-580039](https://oktainc.atlassian.net/browse/OKTA-580039). 
- **Is this PR related to a Monolith release?** Yes, 2023.06.0
* [OKTA-604179](https://oktainc.atlassian.net/browse/OKTA-604179)
> OKTA-604179 Revert doc action for OAUTH2_CIBA and CUSTOM_PUSH_AUTHENTICATOR

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
to be released for the June monthly - 2023.06.0
- policy testing tool api documentation, for EA
* [OKTA-594692]
@okta/resource-insights 
https://okta.box.com/s/exb95dwciboh00dvznimzrz8oegugwon
> OKTA-594692 policy simulation api documentation

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** June Release Note draft
- **Is this PR related to a Monolith release?** 2023.06.0
* [OKTA-617748](https://oktainc.atlassian.net/browse/OKTA-617748)
> Rn entry 2023.06.0

- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
- **What's changed?** Added small miss of previous code update
* Internal issue over slack
> Added array value to response code

- packages/@okta/vuepress-site/data/error-codes.json
- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/policy-simulation/index.md
- packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/api/push-providers/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Release notes and developer documentation updates for the June Monthly release
- **Is this PR related to a Monolith release?** 2023.06.0
* [OKTA-617748](https://oktainc.atlassian.net/browse/OKTA-617748)
> OKTA-617748 Release 2023.06.0

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021-okta-identity-engine/index.md
- **What's changed?** Deprecates the Devices API docs
* [OKTA-580203](https://oktainc.atlassian.net/browse/OKTA-580203)
> Devices API - Deprecate Devices API docs

- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
- **What's changed?** Updates Glitch links.
* [OKTA-619702](https://oktainc.atlassian.net/browse/OKTA-619702)
> Update Glitch links in reg inline hook guide

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- **What's changed?** Fixes My Password request sample
* [OKTA-618037](https://oktainc.atlassian.net/browse/OKTA-618037)
> MyAccount API - Password object request sample

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Update doc to include dynamic issuer as an option
* [OKTA-549552](https://oktainc.atlassian.net/browse/OKTA-549552)
> Custom domain: update authz server task topic

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?**RN entry for 2023.06.1
- **Is this PR related to a Monolith release?** Yes, 2023.06.1
* [OKTA-619523](https://oktainc.atlassian.net/browse/OKTA-619523)
> OKTA-619523 RN entry for 2023.06.1

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** As per the ticket, updating the sentence "You can edit or delete the default rule." based on current behaviour for Classic and OIE
* [OKTA-353663](https://oktainc.atlassian.net/browse/OKTA-353663)
> OKTA-353663 - Update Policy API Default Rules

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?** Release notes for 2023.06.1
- **Is this PR related to a Monolith release?** Yes, 2023.06.1
* [OKTA-619523](https://oktainc.atlassian.net/browse/OKTA-619523)
> OKTA-619523 Release notes for 2023.06.1

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- Add signed_nonce as factor type to Factors API page.
- Is this PR related to a Monolith release?  - No, this can be merged whenever since we are just addressing a documentation gap for a feature that is already released.
* [OKTA-611365](https://oktainc.atlassian.net/browse/OKTA-611365)
> Add signed_nonce as factor type to Factors API page

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- packages/@okta/vuepress-site/docs/reference/api/features/index.md
- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/hook-keys/index.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
- packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
- packages/@okta/vuepress-site/docs/reference/api/org/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/api/push-providers/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- packages/@okta/vuepress-site/docs/reference/api/templates/index.md
- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- packages/@okta/vuepress-site/docs/reference/api/uischema/index.md
- packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- packages/@okta/vuepress-site/docs/reference/api/xaas/index.md
- packages/@okta/vuepress-theme-prose/global-components/ApiAuthMethodWarning.vue
- **What's changed?** Add API auth method note in all participating APIs - see Emeka's SCR for API service integration, 1b task in the Jira.
https://649c44c8aa8f91172ff0dd75--reverent-murdock-829d24.netlify.app/docs/reference/api/idps/
* [OKTA-603897](https://oktainc.atlassian.net/browse/OKTA-603897)
> OKTA-603897 Add API auth method note in all participating APIs

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Removed reference to Global Session Policy with respect to Okta Expression Language.
* [OKTA-623425](https://oktainc.atlassian.net/browse/OKTA-623425)
> Removed mentions of Global Session Policy to address OKTA-623425.

- packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
- **What's changed?** Various changes to telephony hooks docs
* [OKTA-618180](https://oktainc.atlassian.net/browse/OKTA-618180)
- [Telephony Inline Hooks - Reference](https://649dfc85e901933bb1f7fb6f--reverent-murdock-829d24.netlify.app/docs/reference/telephony-hook/#troubleshoot)
- [Telephony Inline Hooks - Guide](https://649dfc85e901933bb1f7fb6f--reverent-murdock-829d24.netlify.app/docs/guides/telephony-inline-hook/nodejs/main/#preview)
> Telephony Hooks Updates

- package.json
- yarn.lock
- enforcing usage of a more secure json5 package
* [OKTA-615904](https://oktainc.atlassian.net/browse/OKTA-615904)
> enforces json5 package

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Added entries for 2023.06.2 release notes.
- **Is this PR related to a Monolith release?** Yes. Release Noes 2023.06.2.
* [OKTA-621463](https://oktainc.atlassian.net/browse/OKTA-621463)
> Release Notes for 2023.06.2

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- **What's changed?** Fixed a typo in the inline hook concepts, and ran acrolinx for kicks
* n/a
> Inline Hooks - typo and acrolinx updates

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Updated formatting
- **Is this PR related to a Monolith release?** Yes. 2023.06.2.
> Rn entry 2023.06.2

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Added entries for Release Notes for 2023.06.2
- **Is this PR related to a Monolith release?** Yes. 2023.06.2
* [OKTA-621463](https://oktainc.atlassian.net/browse/OKTA-621463)
> Release Notes for 2023.06.2 (#4240)

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Added an EA tag to Access Policy simulation endpoint in the Policy API
* n/a
> Added EA info for access simulation endpoint in Policy API

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- Adding admin role API endpoints documentation for client application
- Removing Beta tags from some endpoints
- **Is this PR related to a Monolith release?** NO (already released)
* [OKTA-623285](https://oktainc.atlassian.net/browse/OKTA-623285)
> OKTA-623285: Add missing roles assignment apis for public client

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- yarn.lock
- **What's changed?** Adds a list of TLS cert requirements.
* [OKTA-351249](https://oktainc.atlassian.net/browse/OKTA-351249)
> Custom domain: add TLS cert requirements

- packages/@okta/vuepress-site/docs/reference/token-hook/index.md
- **What's changed?** Added `scp` claim to token hook reserved list
* [OKTA-623282](https://oktainc.atlassian.net/browse/OKTA-623282)
> OKTA-623282 Add scope claim to Token Inline Hook reserved list

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- **What's changed?** Added parameters for the **Get all Policies by type**, changed a few headings from **Get** to **List**, added note about **Get a Policy with Rules** is Classic only.
* [OKTA-603633](https://oktainc.atlassian.net/browse/OKTA-603633)
* [OKTA-622770](https://oktainc.atlassian.net/browse/OKTA-622770)
> OKTA-603633 Policy API Updates from external feedback

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Tweaks the language in a WebAuthn note
> Custom domain: tweak language in WebAuthn note

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** Removes EA references for this feature.
- **Is this PR related to a Monolith release?** 2023.07.0
* [OKTA-620437](https://oktainc.atlassian.net/browse/OKTA-620437)
> Remove EA References

- packages/@okta/vuepress-site/data/error-codes.json
- packages/@okta/vuepress-site/data/event-types.json
- packages/@okta/vuepress-site/data/oauth2-error-codes.json
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add release note entries for 2023.07.0
- **Is this PR related to a Monolith release?** Yes, 2023.07.0
* [OKTA-626096](https://oktainc.atlassian.net/browse/OKTA-626096)
> OKTA-626096 RN entries for 2023.07.0

- packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-overview/main/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-center/directory-coexistence/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-center/directory-coexistence/lab-ldap-server/index.md
- **What's changed?** Fixed a few hard-coded references to hoc
* n/a
> Update some hardcoded hoc links with aliases

- packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
- **What's changed?** Update to Account Linking default setting and acrolinx updates
* [OKTA-626583](https://oktainc.atlassian.net/browse/OKTA-626583)
> linking update and acrolinx fixes

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- Update the conditions api doc tags to BETA
* [OKTA-627835](https://oktainc.atlassian.net/browse/OKTA-627835)
> OKTA-627835: Change condition api docs to BETA

- packages/@okta/vuepress-site/docs/concepts/brands/index.md
- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Adds more detail about the behaviour of branded emails in a multibrand org.
* [OKTA-620177](https://oktainc.atlassian.net/browse/OKTA-620177)
> Brands: Multibrand and emails

- packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/index.md
- **What's changed?** Removes limitations content from the Custom authenticator guide.
* [OKTA-629921](https://oktainc.atlassian.net/browse/OKTA-629921)
> Custom authenticator: remove limitation content

- packages/@okta/vuepress-site/docs/concepts/brands/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Adds note about redirect URIs in SAML app settings, IdP settings, and Authorization Server settings.
* [OKTA-629975](https://oktainc.atlassian.net/browse/OKTA-629975)
> Custom domains: Add note about redirect URIs

- packages/@okta/vuepress-site/docs/guides/terraform-design-access-security/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-design-rate-limits/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-end-user-experience/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-external-authenticators/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-groups/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-user-access/main/index.md
A quick fix with formatting changes only. A local build shows no issues.
* [OKTA-631034](https://oktainc.atlassian.net/browse/OKTA-631034)
> Update code snippet indents

- packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-design-access-security/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-design-rate-limits/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-design-rate-limits/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-landing-page/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-landing-page/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-end-user-experience/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-external-authenticators/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-external-authenticators/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-groups/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-groups/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-manage-user-access/main/index.md
- packages/@okta/vuepress-site/docs/guides/terraform-overview/main/index.md
- **What's changed?** Small fixes to the Terraform docs to better integrate the content with existing topics
[OKTA-631008](https://oktainc.atlassian.net/browse/OKTA-631008)
- [Link](https://64bed58290cf1615fd8ab235--reverent-murdock-829d24.netlify.app/docs/guides/terraform-landing-page/main/)
> Various cleanup

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Removes outdated content and adds a note
* [OKTA-622761](https://oktainc.atlassian.net/browse/OKTA-622761)
> Custom domains: removes outdated content and adds a note

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add blurbs to the Release Branch
- **Is this PR related to a Monolith release?** OKTA-627754
* [OKTA-627754](https://oktainc.atlassian.net/browse/OKTA-627754)
> RN-Entry 2023.07.1

- packages/@okta/vuepress-site/docs/concepts/brands/index.md
- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Adds details about custom email addresses in multibrand orgs
- **Is this PR related to a Monolith release?** Non.
* [OKTA-631546](https://oktainc.atlassian.net/browse/OKTA-631546)
> Multibrand: adds custom email address details

- package.json
- yarn.lock
- updates package
* [OKTA-615911](https://oktainc.atlassian.net/browse/OKTA-615911)
> updates robots guard package

- packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
- **What's changed?** Added a new procedure to enable the Progressive Profiling feature with the sample app
* [OKTA-614327](https://oktainc.atlassian.net/browse/OKTA-614327)
> OKTA-614327- Progressive profiling addition to vanilla spa redirect

- package.json
- yarn.lock
- Updates uglify-js package version
* [OKTA-615908](https://oktainc.atlassian.net/browse/OKTA-615908)
> Fix uglify-js package

- package.json
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/configmid.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/configmid.md
- yarn.lock
- updates markdown-it package
* [OKTA-615910](https://oktainc.atlassian.net/browse/OKTA-615910)
> Updates markdown-it package

- package.json
- yarn.lock
- updates highlight.js package
* [OKTA-615912](https://oktainc.atlassian.net/browse/OKTA-615912)
> updates highlight.js package

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- Changing the tags on conditions apis to be EA.
* [OKTA-635653](https://oktainc.atlassian.net/browse/OKTA-635653)
> OKTA-635653: Change condition api docs tags to EA

- package.json
- yarn.lock
- updates semver package
* [OKTA-621083](https://oktainc.atlassian.net/browse/OKTA-621083)
@paulwallace-okta
> Updates semver package

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adding RN entry for August monthly
- **Is this PR related to a Monolith release?** Yes 2023.08.0
* [OKTA-634575](https://oktainc.atlassian.net/browse/OKTA-634575)
> RN entry 2023.08.0

- packages/@okta/vuepress-site/docs/reference/api/org/index.md
- Added documents for new third party admin setting endpoint for orgs
- **Is this PR related to a Monolith release?** Yes. Tentatively 2023.08.0
* [OKTA-621427](https://oktainc.atlassian.net/browse/OKTA-621427)
> Org settings API: Third-Party Admin setting endpoints

- package.json
- yarn.lock
- Updates tough-cookie package
* [OKTA-625662](https://oktainc.atlassian.net/browse/OKTA-625662)
> Updates tough-cookie package

- packages/@okta/vuepress-site/docs/reference/api/features/index.md
- **What's changed?** removing vuepress Features content
- **Is this PR related to a Monolith release?** no 
* [OKTA-638682](https://oktainc.atlassian.net/browse/OKTA-638682)
> features deprecation

- packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/index.md
- **What's changed?** Add End-User Dashboard note in the testing steps of "Build an SSO integration" (doc gap from Qualtrics feedback)
* [OKTA-622794](https://oktainc.atlassian.net/browse/OKTA-622794)
> OKTA-622794 Add End-User Dashboard URL in the testing steps

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Vuln for prod
- **Is this PR related to a Monolith release?** Yes 2023.08.0
* [OKTA-634575](https://oktainc.atlassian.net/browse/OKTA-634575)
> vuln for prod

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Release notes for 2023.08.1
- **Is this PR related to a Monolith release?** Yes - 2023.08.1
* [OKTA-637538](https://oktainc.atlassian.net/browse/OKTA-637538)
> Release notes for 2023.08.1.

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/setup-app.md
- **What's changed?** update to refresh token note
* [OKTA-635336](https://oktainc.atlassian.net/browse/OKTA-635336)
> internal feedback

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appatidp.md
- **What's changed?** adding info on org setting for amr claims mapping 
- **Is this PR related to a Monolith release?** yes 2023.08.1
**Netlify link:**
https://64da5d3eb8098702af705158--reverent-murdock-829d24.netlify.app/docs/guides/add-an-external-idp/oktatookta/main/#create-an-app-at-the-identity-provider
* [OKTA-637831](https://oktainc.atlassian.net/browse/OKTA-637831)
> doc update amr

- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
> Suppressing UTM cookie set

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Added a note to deprecated policy API to point to the new API you should use (on OAS3)
* [OKTA-627629](https://oktainc.atlassian.net/browse/OKTA-627629)
> OKTA-627629 - Add note to deprecated policy API

- packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
- **What's changed?** Remove the Personal Identity Verification section. This limitation no longer exists.
* [OKTA-640254](https://oktainc.atlassian.net/browse/OKTA-640254)
> Remove Smartcard Section

- packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
- **What's changed?** Added passwordless authentication procedure to the vanilla JS redirect guide: https://developer.okta.com/docs/guides/auth-js-redirect/main/
* [OKTA-614327](https://oktainc.atlassian.net/browse/OKTA-614327)
> OKTA-614327 Enable passwordless auth for vanilla redirect app

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
- **What's changed?** Add reference for public client app role assignment
* OKTA-627687
@vasishtajayanti-okta @dishasheth-okta @brentschaus-okta @susanharper-okta
> OKTA-627687: Add reference for public client app role assignment

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Updated Policy API constraints example.
* [OKTA-642448](https://oktainc.atlassian.net/browse/OKTA-642448)
> OKTA-642448 - Policy API example update

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Added Release Notes for 2023.08.2
- **Is this PR related to a Monolith release?** 2023.08.2
* [OKTA-639235](https://oktainc.atlassian.net/browse/OKTA-639235)
> OKTA-639235 - 2023.08.2 Release Notes (waited for Prod release)

- .circleci/config.yml
- updates CCI dependency
* [OKTA-624829](https://oktainc.atlassian.net/browse/OKTA-624829)
> updates CCI dependency

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add RN entry for 2023.08.3
- **Is this PR related to a Monolith release?** Yes, 2023.08.3
* [OKTA-641390](https://oktainc.atlassian.net/browse/OKTA-641390)
> OKTA-641390 Add RN entry for 2023.08.3

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add release notes for 2023.08.3
- **Is this PR related to a Monolith release?** Yes, 2023.08.3
* [OKTA-641390](https://oktainc.atlassian.net/browse/OKTA-641390)
> OKTA-641390 Release notes for 2023.08.3

- .circleci/config.yml
- removes patch version, to get the latest version
* [OKTA-643782](https://oktainc.atlassian.net/browse/OKTA-643782)
> Removes patch version

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Fix markdown in Provisioning tables in Apps API
* [OKTA-643873](https://oktainc.atlassian.net/browse/OKTA-643873)
> OKTA-643873 Fix markdown in Provisioning tables in Apps API

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Fix Apps API tables: Capabilities object and Password Setting object
- **Issue:**
https://64f1452f26c2221032bb7f5e--reverent-murdock-829d24.netlify.app/docs/reference/api/apps/#capabilties-object
* [OKTA-643873](https://oktainc.atlassian.net/browse/OKTA-643873)
> OKTA-643873 Fix Apps API tables: Capabilities object and Password Setting object

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
- **What's changed?** note at top on custom auth servers and api access management
* [OKTA-491008](https://oktainc.atlassian.net/browse/OKTA-491008)
> note at top on custom auth servers and api access management

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- **What's changed?** added note per backlog ticket
* [OKTA-435551](https://oktainc.atlassian.net/browse/OKTA-435551)
> adding note and acrolinx

- packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
- **What's changed?** Removed EA tag for OKTA-646135. Added comment about leaving 'What you need' in until SKUs are completed. Replaced smart quotes.
* [OKTA-646135](https://oktainc.atlassian.net/browse/OKTA-646135)
> XaaS moved from EA to GA

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- API doc for perpetual account lockout prevention
- Monolith release: Yes, 2023.09.0
* [OKTA-553106](https://oktainc.atlassian.net/browse/OKTA-553106)
@vanngo-okta @okta/mfaplatform-team
> API doc for perpetual account lockout prevention

- packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- **What's changed?** Removing note that describes admin limitations when calling MyAccount API.
- **Is this PR related to a Monolith release?** Yes. 2023.09.0
* [OKTA-645326](https://oktainc.atlassian.net/browse/OKTA-645326)
> MyAccount API: Removes notes about admin limitations

- packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
- **What's changed?** Added more detail to the [Self-Service Registration section](https://developer.okta.com/docs/guides/ie-limitations/main/#self-service-registration) of the Okta Identity Engine limitations page: 
- **Is this PR related to a Monolith release?** yes, 2023.09.0
> Updates to OIE limitations for SSR updates

- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Fixes a small issue with the RN notes
- **Is this PR related to a Monolith release?** 2023.09.0
> 2023.09.0 RN Followup

- packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/openidconnect/prep.md
- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/openidconnect/submit.md
- packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/saml2/submit.md
- **What's changed?** Add multi-tenancy to OIN requirements, as requested by OIN Ops during ISV admin discussion (Mohammad Abdullah and Tomasz Wrobel)
https://6500ef09a0b9ec0573c71512--reverent-murdock-829d24.netlify.app/docs/guides/submit-app-prereq/main/#oin-multi-tenancy
* [OKTA-638432](https://oktainc.atlassian.net/browse/OKTA-638432)
> OKTA-638432 Add OIN multi-tenancy requirement

- packages/@okta/vuepress-site/docs/reference/architecture-center/multiple-environments/lab/index.md
- Updated the pre-requisites section of the Terraform Reference Architecture section so that it no longer uses the Okta CLI and that the production org is a free trial, rather than a developer org. The production org requires Okta Workflows which developer orgs do not have and support cannot add.
- Preview link at https://65008905c1e35706e356a73f--reverent-murdock-829d24.netlify.app/docs/reference/architecture-center/multiple-environments/lab/
* [OKTA-645244](https://oktainc.atlassian.net/browse/OKTA-645244)
> okta-645244 Correct prereqs for Terraform RefArch lab

- packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
- **What's changed?** Removed the legacy event type details on the [Event Types reference](https://developer.okta.com/docs/reference/api/event-types/).
* [OKTA-648463](https://oktainc.atlassian.net/browse/OKTA-648463)
> OKTA-648463 Remove legacy event types data on Event Types reference

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** RN blurb entry
- **Is this PR related to a Monolith release?** yes. 2023.09.1
* [OKTA-647986](https://oktainc.atlassian.net/browse/OKTA-647986)
> Rn entry 2023.09.1

- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
> Changes for BOFU

- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
This reverts changes made in commit 875bc9306e061af2b00b4a1fe70966b8f2e8ed21.
> Revert "Changes for BOFU (#4398)"

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- **What's changed?** Release branch. One RN entry.
- **Is this PR related to a Monolith release?** yes. 2023.09.1
* [OKTA-647986](https://oktainc.atlassian.net/browse/OKTA-647986)
> Release 2023.09.1

- packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
- packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
- **What's changed?** Updated three guides with current profile enrollment / progressive profile enrollment UI procedures.
* [OKTA-649951](https://oktainc.atlassian.net/browse/OKTA-649951)
> OKTA-649951 Profile and progressive profile enrollment UI updates

- packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- **What's changed?** Removing incorrect reference to `Admin Dashboard`
* [OKTA-644321](https://oktainc.atlassian.net/browse/OKTA-644321)
> OKTA-644321 Minor terminology update on Rate Limits overview

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?** Release notes for 2023.09.2
- **Is this PR related to a Monolith release?** yes  2023.09.2
* [OKTA-650469](https://oktainc.atlassian.net/browse/OKTA-650469)
> release notes entries

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?** Release 2023.09.2
- **Is this PR related to a Monolith release?** yes2023.09.2
* [OKTA-650469](https://oktainc.atlassian.net/browse/OKTA-650469)
> Release 2023.09.2

- packages/@okta/vuepress-site/docs/concepts/brands/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/index.md
- packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adds the guide that describes how to use design tokens and the JS API (instead of CSS) to style the SIW.
- **Is this PR related to a Monolith release?** Yes. 2023.10.0
* [OKTA-561049](https://oktainc.atlassian.net/browse/OKTA-561049)
> Sign-In Widget (third gen) customization guide

- packages/@okta/vuepress-site/docs/reference/api/api-tokens/index.md
- packages/@okta/vuepress-site/docs/reference/api/behavior-rules/index.md
- packages/@okta/vuepress-site/docs/reference/api/device-assurance-policies/index.md
- packages/@okta/vuepress-site/docs/reference/api/email-domains/index.md
- packages/@okta/vuepress-site/docs/reference/api/principal-rate-limits/index.md
- packages/@okta/vuepress-site/docs/reference/api/rate-limit-settings/index.md
- packages/@okta/vuepress-site/docs/reference/api/sms-templates/index.md
- **What's changed?** The new placeholder topics for new APIs documented on the redocly portal contained several copy-paste errors.
* n/a
> API Reference: fix typos

- .github/workflows/netlify-preview.js.yml
- checks out the correct sha for Netlify preview build
* [OKTA-657377](https://oktainc.atlassian.net/browse/OKTA-657377)
> checks out correct sha

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- corrects link to jwt site
https://65284438e88d7063541d73bd--reverent-murdock-829d24.netlify.app/docs/guides/implement-oauth-for-okta-serviceapp/main/#grant-allowed-scopes
* [OKTA-656274](https://oktainc.atlassian.net/browse/OKTA-656274)
> Em okta 656274 fix url

- .github/workflows/netlify-preview.js.yml
- reverts to original logic with checking out and switching to PR
- replaces `hub` with `gh`, which does the same thing
* [OKTA-657377](https://oktainc.atlassian.net/browse/OKTA-657377)
> fixes pr checkout

- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- **What's changed?** Improved the description of the `origin` parameter to include supported schemes (already documented on product side)
* [OKTA-657074 ](https://oktainc.atlassian.net/browse/OKTA-657074 )
> OKTA-657074 Improve Trusted Origins API parameter description

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- Updated APIs related permission conditions to GA.
- **Is this PR related to a Monolith release?** Yes, release: 2023.10.0
* [OKTA-655334](https://oktainc.atlassian.net/browse/OKTA-655334)
> OKTA-655334: Update conditions APIs to be GA

- package.json
- yarn.lock
- moves all packages to dev dependencies
* [OKTA-654637](https://oktainc.atlassian.net/browse/OKTA-654637)
> moves packages to dev dependencies

- package.json
- yarn.lock
- updates babel parser
* [OKTA-657991](https://oktainc.atlassian.net/browse/OKTA-657991)
> update babal parser

- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
- **What's changed?** Update **Runscope API Test** format label in 2 files
* [OKTA-661169](https://oktainc.atlassian.net/browse/OKTA-661169)
> OKTA-661169 Update Runscope API Test format label

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Updating release notes for production fix
- **Is this PR related to a Monolith release?** 2023.10.1
* [OKTA-638649](https://oktainc.atlassian.net/browse/OKTA-638649)
> OKTA-638649 Update 2023.10.1 release notes for production fix

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Fix formating for link in the Okta Device Profile table.
* n/a
> Okta Expression Language Guide - Fix broken link

- packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
- **What's changed?** Add note for refresh token support for SCIM connections
* [OKTA-656373](https://oktainc.atlassian.net/browse/OKTA-656373)
> OKTA-656373 Add note for refresh token support for SCIM connections

- packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
- **What's changed?** Add 60-second timeout response in SCIM FAQ
* [OKTA-655369](https://oktainc.atlassian.net/browse/OKTA-655369)
> OKTA-655369 Add 60 second timeout response in SCIM FAQ

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Fix the example for the the `OR` conditional operator in the https://developer.okta.com/docs/reference/okta-expression-language-in-identity-engine/#constants-and-operators
* n/a
> Okta Expression Language for IE - example fix

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** Adds org creation rate limit details
* [OKTA-660579](https://oktainc.atlassian.net/browse/OKTA-660579)
> Org Creator API rate limits

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/nodejs/auth.md
- packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-ngrok/main/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook-new-draft/main/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
- packages/@okta/vuepress-theme-prose/global-components/HookBasicAuthStep.vue
- packages/@okta/vuepress-theme-prose/global-components/HookOAuthNote.vue
- **What's changed?** Updated the Basic Auth code in the glitch apps and in the Common Hook set up guide; added improved content for Event Hook guide; added xref to Basic Auth details in all the other guides.
* n/a
> Update Hook Guides with Basic Auth updates

- packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
- **What's changed?** Removing info on self-service EA
> remove self-service ea

- packages/@okta/vuepress-theme-prose/global-components/HookBasicAuthStep.vue
- **What's changed?** Replacing tabs with spaces in `.vue` script
* n/a
> Update script spacing to avoid github warnings

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** updated supported value from ASSERTION to TOKEN
* [OKTA-280112](https://oktainc.atlassian.net/browse/OKTA-280112)
> assertion to token

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- Adjust wording to highlight GUID requirements.
- Adjust note structure to make things less overwhelming
* [OKTA-656607](https://oktainc.atlassian.net/browse/OKTA-656607)
> devicetoken Length Updates

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Updated intro to reflect usage with Identity Governance.
* [OKTA-657520](https://oktainc.atlassian.net/browse/OKTA-657520)
> Updated intro based on Lisa Dumont's request in OKTA-657520.

- .github/workflows/netlify-preview-manual.js.yml
- adds a manual GH action for Netlify Previews
* [OKTA-660889](https://oktainc.atlassian.net/browse/OKTA-660889)
> Adds a manual GH action for Netlify

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** RN Entries
- **Is this PR related to a Monolith release?** 2023.10.2
* [OKTA-659328](https://oktainc.atlassian.net/browse/OKTA-659328)
> Initial blurbs

- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
- **What's changed?** added query params to Get all Scopes
* [OKTA-286383](https://oktainc.atlassian.net/browse/OKTA-286383)
> Adding query params to Get all Scopes

- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
- removes attribution (second attempt)
> Removes attribution

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?**  Release Notes for the upcoming release
- **Is this PR related to a Monolith release?** 2023.10.2
* [OKTA-659328](https://oktainc.atlassian.net/browse/OKTA-659328)
> Release 2023.10.2

- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
> revert change for now

- packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Added Universal Logout API info to the OIN integration section
Netlif:
https://654a63f187a021009c2c7c3b--reverent-murdock-829d24.netlify.app/docs/guides/oin-universal-logout-overview/#universal-logout
* [OKTA-665324](https://oktainc.atlassian.net/browse/OKTA-665324)
> Universal Logout API info

- .github/workflows/nightly-link-checker.yml
- **What's changed?** Updated github action to print to log
* n/a
> Update to nightly link checker action

- packages/@okta/vuepress-theme-prose/assets/css/components/_header.scss
- removes `overflow:hidden` style, which hides dropdown with search suggestions
- [preview link](https://654bb2f64906e97a7e4b570d--reverent-murdock-829d24.netlify.app)
* [OKTA-646743](https://oktainc.atlassian.net/browse/OKTA-646743)
> Removes overflow style

- packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
> Reverting UTM change

- packages/@okta/vuepress-site/docs/concepts/oie-intro/index.md
- **What's changed?** The CAPTCHA section in the OIE overview is out-of-date. Needs updating.
https://654e855f4389ab12820f5cb8--reverent-murdock-829d24.netlify.app/docs/concepts/oie-intro/#captcha
* [OKTA-637722](https://oktainc.atlassian.net/browse/OKTA-637722)
> CAPTCHA - Clarify content in OIE overview

- packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
- **What's changed?** Updated link to direct auth and brought score to 80
> concept link update and acrolinx

- packages/@okta/vuepress-theme-prose/global-components/HookBasicAuthStep.vue
- **What's changed?** Updates spacing in the global component `HookBasicAuthStep.vue` to avoid the GitHub action warnings
* annoying github action warnings
> Update global component spacing

- packages/@okta/vuepress-theme-prose/components/ContentPage.vue
- Initializes anchors when the document is ready
* [OKTA-668223](https://oktainc.atlassian.net/browse/OKTA-668223)
> initializes anchors on document ready

- packages/@okta/vuepress-site/docs/guides/dpop/main/index.md
- **What's changed?** removing note and changing link
* [OKTA-663887](https://oktainc.atlassian.net/browse/OKTA-663887)
> removing note and changing link
