packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
- **What's changed?** add new faq per aaron parecki
* [OKTA-668320](https://oktainc.atlassian.net/browse/OKTA-668320)
=> add faq per aaron p

packages/@okta/vuepress-theme-prose/global-components/SignUp.vue, packages/@okta/vuepress-theme-prose/util/attribution/attribution.js
=> OKTA-636651: BOFU UTM fix

falsepos.txt
- **What's changed?** Adding two Postman URLs that are being flagged as broken (both resolve)
* n/a
=> Update to falsepos.txt file

falsepos.txt
- **What's changed?** Added a URL that link checker flags as broken 
* n/a
=> Update false positive file

packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
- **What's changed?** Adding error object content to this SAML assertion inline hook section: https://developer.okta.com/docs/reference/saml-hook/#objects-in-response-you-send
* [OKTA-453644](https://oktainc.atlassian.net/browse/OKTA-453644)
=> OKTA-453644 Add SAML Hook error object content

packages/@okta/vuepress-site/docs/guides/terraform-design-rate-limits/main/index.md, packages/@okta/vuepress-site/docs/reference/rate-limits/index.md, packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md, packages/@okta/vuepress-site/docs/reference/rl-best-practices/index.md, packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md, packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md, packages/@okta/vuepress-site/docs/reference/rl-global-mgmt/index.md, packages/@okta/vuepress-site/docs/reference/rl-global-other-endpoints/index.md
- **What's changed?** Updated the best practices with existing and new info; added better cross-doc links; added link to support page on requesting temporary rate limit increases.
* [OKTA-661610 ](https://oktainc.atlassian.net/browse/OKTA-661610 )
=> OKTA-661610 Update rate limit docs

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
- **What's changed?** Fix typo and styling
=> OAuth for Okta: fix typo and styling

package.json
- **What's changed?** Adding `event-types-to-csv script to `update-docs`
* [OKTA-668110](https://oktainc.atlassian.net/browse/OKTA-668110)
=> OKTA-668110 Update to package.json

packages/@okta/vuepress-site/docs/reference/api/event-types/index.md
- **What's changed?** Adding link to new Event Types CSV file
* [OKTA-668110](https://oktainc.atlassian.net/browse/OKTA-668110)
=> OKTA-668110 Add csv download link to Event Types reference

packages/@okta/vuepress-theme-prose/components/ContentPage.vue, packages/@okta/vuepress-theme-prose/components/OnThisPage.vue, packages/@okta/vuepress-theme-prose/mixins/AnchorHistory.vue
- Updates offsets map on a window resizing.
* [OKTA-494428](https://oktainc.atlassian.net/browse/OKTA-494428)
=> Updates anchor offsets

packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- **What's changed?** Revised a sentence for clariy
* [OKTA-661160](https://oktainc.atlassian.net/browse/OKTA-661160)
=> OKTA-661160 - Minor update to RL dashboard page

packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- **What's changed?** Adds a short sentence and a link to WebAuthn resources per request.
* [OKTA-671140](https://oktainc.atlassian.net/browse/OKTA-671140)
=> Add WebAuthn Link

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- **What's changed?** Revised timeout behaviour based on bug fix ([OKTA-611871](https://oktainc.atlassian.net/browse/OKTA-611871))
- **Is this PR related to a Monolith release?** 2023.11.1
* [OKTA-603844](https://oktainc.atlassian.net/browse/OKTA-603844)
=> OKTA-603844 Updated timeout behaviour in inline hooks concept

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Add RN entries
- **Is this PR related to a Monolith release?** Yes, 2023.11.1
* [OKTA-666626](https://oktainc.atlassian.net/browse/OKTA-666626)
=> OKTA-666626 - RN entry 2023.11.1

packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md
- **What's changed?** Added a link to webauthn.me to the WebAuthn authenticators guide.
* [OKTA-670602](https://oktainc.atlassian.net/browse/OKTA-670602)
=> okta-670602 Added webauthn.me link to authenticators-web-authn guide

packages/@okta/vuepress-site/docs/guides/oie-upgrade-plan-embedded-upgrades/main/index.md
- **What's changed?** Typo and acrolinx fixes for https://developer.okta.com/docs/guides/oie-upgrade-plan-embedded-upgrades/main/
* [OKTA-671529](https://oktainc.atlassian.net/browse/OKTA-671529)
=> OKTA-671529 Typo and acrolinx fixes

package.json
- treat warnings as errors to prevent bad code from merging
* [OKTA-662383](https://oktainc.atlassian.net/browse/OKTA-662383)
=> treat warnings as errors

packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** As per this i[ssue](https://github.com/okta/okta-developer-docs/issues/2612), added an example to the Users API
* [OKTA-656585](https://oktainc.atlassian.net/browse/OKTA-656585)
=> OKTA-656585 - Add example to Users API

packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md
The initial authorization is type POST not GET
=> The initial authorization is type POST not GET

packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- **What's changed?** Fixes typo
* [OKTA-673334](https://oktainc.atlassian.net/browse/OKTA-673334)
=> OKTA-673334 - Update OAuth and OIDC Guide

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Added December release notes for Classic and OIE release notes.
- **Is this PR related to a Monolith release?** 2023.12.0
* [OKTA-672041](https://oktainc.atlassian.net/browse/OKTA-672041)
=> OKTA-672041 - Monthly release note entry

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?** Minor edit to release notes for December monthly
- **Is this PR related to a Monolith release?** 2023.12.0
* n/a
=> Minor update to release notes

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** removed blurb per doc action request
=> removing monthly blurb per doc action

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** 2023.12.1 release notes entry
- **Is this PR related to a Monolith release?** Yes 2023.12.1
* [OKTA-674198](https://oktainc.atlassian.net/browse/OKTA-674198)
=> 2023 12 1 RNs

falsepos.txt, packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/sdksteps.md, packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/sdksteps.md
- **What's changed?** Added two links to the false-positive list. No broken links.
* n/a
=> Updating False Positives list

packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
- **What's changed?** Adding missing subtype from the operations limit table: https://developer.okta.com/docs/reference/rl-system-log-events/#operation-rate-limits
* [OKTA-675383 ](https://oktainc.atlassian.net/browse/OKTA-675383 )
=> OKTA-675383 - Add missing rate limit subtype

packages/@okta/vuepress-site/docs/concepts/multi-tenancy/index.md, packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md, packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Dev orgs not supporting Org2Org app integration
- **Is this PR related to a Monolith release?** 2023.12.1 (Dec 19, 2023)
https://65809db358f3e60c4895b78d--reverent-murdock-829d24.netlify.app/docs/guides/secure-oauth-between-orgs/main/
* [OKTA-658529](https://oktainc.atlassian.net/browse/OKTA-658529)
=> OKTA-658529 dev org minus org2org

packages/@okta/vuepress-theme-prose/assets/css/components/_headerNav.scss
- **What's changed?**  Fixed header gap for medium window widths
* [OKTA-622149](https://oktainc.atlassian.net/browse/OKTA-622149)
After fix:
=> [OKTA-622149]: Fixed header gap for medium window widths

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adding release notes for 2023.12.2
- **Is this PR related to a Monolith release?** Yes. 2023.12.2
* [OKTA-677219](https://oktainc.atlassian.net/browse/OKTA-677219)
=> Rn entry 2023.12.2

packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Added info on new `group.profile.name` operators
- **Is this PR related to a Monolith release?** 2023.12.2
* [OKTA-678524](https://oktainc.atlassian.net/browse/OKTA-678524)
=> OKTA-678524 - OIE Expression Language guide updates

packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adding release notes for 2023.12.2
- **Is this PR related to a Monolith release?** Yes. 2023.12.2
* [OKTA-677219](https://oktainc.atlassian.net/browse/OKTA-677219)
=> Release 2023.12.2

packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
- **What's changed?** added content around rotating refresh tokens and what that means to refresh token lifetime and how it differs from the idle time
* [OKTA-416277](https://oktainc.atlassian.net/browse/OKTA-416277)
=> refresh token lifetime clarifications

packages/@okta/vuepress-theme-prose/global-components/ErrorCodes.vue, packages/@okta/vuepress-theme-prose/mixins/AnchorHistory.vue
- **What's changed?** Fixed anchor link in URL mismatch in error codes page
* [OKTA-483028](https://oktainc.atlassian.net/browse/OKTA-483028)
=> OKTA-483028: Fixed URL anchor mismatch for error codes page

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Adds a post-release bug. WILL MERGE AFTER RELEASE HITS ALL CELLS IN PROD.
- **Is this PR related to a Monolith release?** Yes. 2023.12.2
* [OKTA-673562](https://oktainc.atlassian.net/browse/OKTA-673562)
=> Post-release bug 2023.12.2

packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
- **What's changed?** Updating a hard-coded product reference
* n/a
=> Add alias reference to product docs

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** New files for 2024 release notes. Add release note entries for 2024.01.0
- **Is this PR related to a Monolith release?** Yes, 2024.01.0
* [OKTA-681413](https://oktainc.atlassian.net/browse/OKTA-681413)
=> OKTA-681413 Release note entries for 2024.01.0

packages/@okta/vuepress-site/copyright/index.md
- **What's changed?** Update copyright and trademark year
=> Update copyright year

packages/@okta/vuepress-theme-prose/assets/css/abstracts/_colors.scss, packages/@okta/vuepress-theme-prose/assets/css/components/_header.scss, packages/@okta/vuepress-theme-prose/assets/css/components/_search.scss
- Added back caret icon in community dropdown in light theme
- Added background for search labels in dark theme
* [OKTA-680747](https://oktainc.atlassian.net/browse/OKTA-680747)
* [OKTA-680748](https://oktainc.atlassian.net/browse/OKTA-680748)
Preview - https://65a0ef94f3c4039509f1ca4f--reverent-murdock-829d24.netlify.app
=> OKTA-680747, OKTA-680748: Fixed minor CSS issues in header and search results

packages/@okta/vuepress-theme-prose/components/ContentPage.vue, packages/@okta/vuepress-theme-prose/components/OnThisPage.vue, packages/@okta/vuepress-theme-prose/mixins/AnchorHistory.vue
- Fixed broken navigation which did not highlight the active header on scroll in the right side nav.
- Removed dynamic anchors in the URL on scroll
* [OKTA-682407](https://oktainc.atlassian.net/browse/OKTA-682407)
=> OKTA-682407: Fixed broken navigation after first load and removed dynamic anchors in URL

packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Rolls back change to ToC.
* [OKTA-680608](https://oktainc.atlassian.net/browse/OKTA-680608)
=> Revert "Update ToC"

packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
- **What's changed?** removing no longer relevant limitation
* [OKTA-683750](https://oktainc.atlassian.net/browse/OKTA-683750)
=> remove limitations bullet

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Add Blurbs for weekly release.
- **Is this PR related to a Monolith release?** 2024.01.1
* [OKTA-683548](https://oktainc.atlassian.net/browse/OKTA-683548)
=> 2024.01.1 rn-entry

packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** Added CIC link in header
* [OKTA-685808](https://oktainc.atlassian.net/browse/OKTA-685808)
Preview - https://65a7848050cedd7f59b6d370--reverent-murdock-829d24.netlify.app/
=> OKTA-685808: Added CIC link in header

packages/@okta/vuepress-site/docs/reference/api/captchas/index.md, packages/@okta/vuepress-site/docs/reference/api/devices/index.md, packages/@okta/vuepress-site/docs/reference/api/policy/index.md, packages/@okta/vuepress-site/pricing/index.md
- **What's changed?** Removing old references to dev-inquiries@okta.com
* n/a
=> Remove old email alias

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Huge, sweeping, wide spread changes for this specific weekly release.
- **Is this PR related to a Monolith release?** 2024.01.1
* [OKTA-683548](https://oktainc.atlassian.net/browse/OKTA-683548)
=> Release 2024.01.1

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Updated incorrect release note title.
- **Is this PR related to a Monolith release?** 2023.12.0 and 2024.01.0
* n/a
=> Minor update to release note titles

packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
- **What's changed?** Adding amr supported values table
netlify link: https://65aedf016530be55b118c7de--reverent-murdock-829d24.netlify.app/docs/guides/configure-amr-claims-mapping/main/#supported-amr-values-by-authenticator-type
* [OKTA-686029](https://oktainc.atlassian.net/browse/OKTA-686029)
=> Adding amr supported values table

packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- **What's changed?** Postman Collection list page: move the bottom 2 lines to the top, as per Jira request
* [OKTA-366428](https://oktainc.atlassian.net/browse/OKTA-366428)
=> OKTA-366428 Update Postman collections topic

packages/@okta/vuepress-site/docs/reference/token-hook/index.md
- **What's changed?** Added an example error code response to the Token Hook guide.
* [OKTA-672599](https://oktainc.atlassian.net/browse/OKTA-672599)
=> OKTA-672599 - Add error example to Token Hook reference

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- **What's changed?** adding request example
* [OKTA-623222](https://oktainc.atlassian.net/browse/OKTA-623222)
=> adding request example

packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** updating left nav to match guide name
* [OKTA-689613](https://oktainc.atlassian.net/browse/OKTA-689613)
=> updating left nav to match guide name

packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- **What's changed?** adding private_key_jwt as an example
* [OKTA-623222](https://oktainc.atlassian.net/browse/OKTA-623222)
=> adding private_key_jwt as an example

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Release notes for 2024.01.2
- **Is this PR related to a Monolith release?** 2024.01.2
* [OKTA-687161](https://oktainc.atlassian.net/browse/OKTA-687161)
=> Rn entry 2024.01.2

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
Reverts okta/okta-developer-docs#4620
=> Revert "Rn entry 2024.01.2"

.github/acrolinx/global-config.edn
- **What's changed?** updating global config to finalize set up
* [OKTA-654071](https://oktainc.atlassian.net/browse/OKTA-654071)
=> acrolinx update

packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md, packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md, packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md, packages/@okta/vuepress-site/docs/reference/api/policy/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Release Notes for 2024.01.2; CSP documentation
- **Is this PR related to a Monolith release?** 2024.01.2
* [OKTA-687161](https://oktainc.atlassian.net/browse/OKTA-687161)
=> Release 2024.01.2

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Added IP restriction entry to release notes
- **Is this PR related to a Monolith release?** 2024.01.2
* [OKTA-687161](https://oktainc.atlassian.net/browse/OKTA-687161)
=> Added entry to release notes.

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/go/whatyouneed.md
- **What's changed?** Fix typos in a couple of links
* n/a
=> Fix typos in two links

.github/acrolinx/global-config.edn
- **What's changed?** lowering the acrolinx score until after the release
=> lowered score until after release

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding Release notes for 2024.02.0
- **Is this PR related to a Monolith release?** yes 2024.02.0
* [OKTA-691309](https://oktainc.atlassian.net/browse/OKTA-691309)
=> Release Notes entry 2024.02.0

packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/protocol-properties.md
- **What's changed?** Add ACS URL index restriction for OIN Wizard
- **Is this PR related to a Monolith release?** Yes, 2024.02.0
* [OKTA-692553](https://oktainc.atlassian.net/browse/OKTA-692553)
=> OKTA-692553 Add ACS URL index restriction for OIN Wizard

packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/index.md, packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md, packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adds a small guide that describes how to "delete all sessions"
- **Is this PR related to a Monolith release?** Yes. 2024.02.0
* [OKTA-649888](https://oktainc.atlassian.net/browse/OKTA-649888)
=> Guide: Delete all stay signed in sessions

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Adds CAEDD locale info. Removes dated EA stuff.
- **Is this PR related to a Monolith release?** Yes. 2024.02.0
* [OKTA-685922](https://oktainc.atlassian.net/browse/OKTA-685922)
=> CAEDD locale updates

packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/aotp/nutrition.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/bmfaotp/nutrition.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/nutrition.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/nutrition.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/nutrition.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/nutrition.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
- **What's changed?** Super admin permissions note
- **Is this PR related to a Monolith release?** Yes 2024.02.0
Netlify Link:
To bullet added in "What you need" section - https://65bc06f8b9fae3077df2887e--reverent-murdock-829d24.netlify.app/docs/guides/configure-direct-auth-grants/aotp/main/
Note added in each "Set up your app" section - https://65bc06f8b9fae3077df2887e--reverent-murdock-829d24.netlify.app/docs/guides/configure-direct-auth-grants/aotp/main/#set-up-your-app
* [OKTA-690693](https://oktainc.atlassian.net/browse/OKTA-690693)
=> Super admin permissions note

packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/nodejs/request.md
- **What's changed?** Improve the usability of the [Token inline hook guide](https://developer.okta.com/docs/guides/token-inline-hook/nodejs/main/) and address a few procedural gaps. 
* [OKTA-688716](https://oktainc.atlassian.net/browse/OKTA-688716)
=> OKTA-688716 - Revise token hook guide

packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md, packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- **What's changed?** Fixes a formatting issue on pages with CSP content
* [OKTA-693456](https://oktainc.atlassian.net/browse/OKTA-693456)
=> Format error fix on CSP pages

packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
- **What's changed?** Provide instructions to obtain the appName variable for SCIM docs
https://65c16dc7af2b9b00801e5a18--reverent-murdock-829d24.netlify.app/docs/guides/scim-provisioning-integration-prepare/main/#authentication
* [OKTA-657288](https://oktainc.atlassian.net/browse/OKTA-657288)
=> OKTA-657288 Add appName note in SCIM doc

packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **Is this PR related to a Monolith release?** 2024.02.1
* [OKTA-693864](https://oktainc.atlassian.net/browse/OKTA-693864)
=> RN branch for 2024.02.1

packages/@okta/vuepress-site/docs/guides/find-your-domain/main/index.md
- **What's changed?** As per a qualtrics ticket, adding a sign-post for end-users who stumble upon the dev doc site on this page: https://developer.okta.com/docs/guides/find-your-domain/main/
* [OKTA-694229](https://oktainc.atlassian.net/browse/OKTA-694229)
=> OKTA-694229 - Add end user blurb to find your okta domain

packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adds ToC entries for OPA & ASA on Redocly.
* [OKTA-680608](https://oktainc.atlassian.net/browse/OKTA-680608)
=> Add OPA ToC

.github/acrolinx/global-config.edn
- **What's changed?** trying a new filter
=> trying a new filter

.github/acrolinx/global-config.edn, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** testing new filter
=> testing new filter

.github/acrolinx/global-config.edn
- **What's changed?** bringing the score back up
=> bringing the score back up

packages/@okta/vuepress-theme-prose/assets/css/components/_feedback.scss, packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_footer.scss
This PR addresses the issue where the feedback button was inadvertently hidden when users scrolled down to the footer in the dark mode.
https://github.com/okta/okta-developer-docs/assets/158277016/6bf49654-7439-427b-a34b-bfe7ace961cd
=> [Fix] Ensure feedback button visibility near footer in dark mode

packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md, packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
- **What's changed?** Removes mentions of session cookies as API auth.
* [OKTA-685889](https://oktainc.atlassian.net/browse/OKTA-665889)
=> Remove mentions of session cookies as API auth

packages/@okta/vuepress-site/code/dotnet/jwt-validation/index.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
- **What's changed?** Changed xref to this page on RS256: https://auth0.com/blog/rs256-vs-hs256-whats-the-difference/
* n/a
=> Replace cross-reference in .NET pages

packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
updates link to the IETF draft
=> update link to Universal Logout spec

packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Add redirect to dotnet SDK
* [OKTA-700333](https://oktainc.atlassian.net/browse/OKTA-700333)
=> Add two redirect entries to dotnet sdk

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Weekly RNs and one backport RN
- **Is this PR related to a Monolith release?** 2024.04.2
* [OKTA-697917](https://oktainc.atlassian.net/browse/OKTA-697917)
=> OKTA-697917 -Weekly release notes entry  

packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss, packages/@okta/vuepress-theme-prose/assets/css/layouts/_layout.scss, packages/@okta/vuepress-theme-prose/components/ContentPage.vue, packages/@okta/vuepress-theme-prose/components/DocsMenuItem.vue, packages/@okta/vuepress-theme-prose/components/MobileOnThisPage.vue, packages/@okta/vuepress-theme-prose/global-components/ErrorCodes.vue, packages/@okta/vuepress-theme-prose/mixins/AnchorHistory.vue
- **What's changed?** Anchor navigation
* [OKTA-691488](https://oktainc.atlassian.net/browse/OKTA-691488)
https://github.com/okta/okta-developer-docs/assets/158277016/967bf5ae-c1c1-447c-bdee-5b1c18210de1
=> [OKTA-691488] | Improve anchors and in-page navigation

packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Added two redirect entries to conductor.yaml file
* [OKTA-700333](https://oktainc.atlassian.net/browse/OKTA-700333)
=> OKTA-700333 - Add redirect

packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
- **What's changed?** Add Postman auth setup instructions in API Design Principles > authentication section
* [OKTA-695739](https://oktainc.atlassian.net/browse/OKTA-695739)
=> OKTA-695739 Add Postman instruction link to API principles page

packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md
- **What's changed?** Update login.gov IdP Authorization parameter links. Acrolinx fixes
* [OKTA-700802](https://oktainc.atlassian.net/browse/OKTA-700802)
=> OKTA-700802 Update login.gov links

packages/@okta/vuepress-theme-prose/assets/css/components/_onThisPage.scss, packages/@okta/vuepress-theme-prose/assets/css/components/_stackSelector.scss, packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_stackSelector.scss
- Fixes color of the filter text in stack selector
- Fixes size of caret in stack selector
* [OKTA-701595](https://oktainc.atlassian.net/browse/OKTA-701595)
=> [OKTA-701595] : Fixed text color and caret size in stack selector

packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
* [OKTA-686741](https://oktainc.atlassian.net/browse/OKTA-686741)
=> Custom domain updates

packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Removed EA tags for User OAuth Token Management endpoints
* [OKTA-702016](https://oktainc.atlassian.net/browse/OKTA-702016)
=> Removed Early Access flag. OKTA-702016.

packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
- Change enum options to `data.messageProfile.deliveryChannel`
- Acrolinx changes to topic
* [OKTA-702589](https://oktainc.atlassian.net/browse/OKTA-702589)
=> Update Telephony Hooks Ref 

packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** Updates Telephony Hooks Guide to better highlight this feature.
- Highlight ability to use multiple providers
- Give some possible reasons why orgs might want to do this
- General wording changes
- **Is this PR related to a Monolith release?** 2024.03.0
* [OKTA-699446](https://oktainc.atlassian.net/browse/OKTA-699446)
=> Update Telephony Hook Guide

packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Adds mappings links object.
- **Is this PR related to a Monolith release?** Yes. 2024.03.0
* [OKTA-702769](https://oktainc.atlassian.net/browse/OKTA-702769)
=> Policy API: Add mappings links object

packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/index.md, packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md, packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Add **Set up an app provisioning connection** guide
- **Is this PR related to a Monolith release?** Yes, 2024.03.0 (trex fixed)
https://65e0a60203b95517085ae428--reverent-murdock-829d24.netlify.app/docs/guides/app-provisioning-connection/main/
* [OKTA-688752](https://oktainc.atlassian.net/browse/OKTA-688752)
=> OKTA-688752 App provisioning connection with Okta APIs

packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md
- **What's changed?** Updated various parts of the feature lifecycle management concept page, improving the Acrolinx score
* [OKTA-702250](https://oktainc.atlassian.net/browse/OKTA-702250)
=> [OKTA-702250] Feature Lifecycle Management page

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Removed a repeated release note for Granular authenticator constraints.
- **Is this PR related to a Monolith release?** 2024.03.0
* n/a
=> Removed repeated Release Note for March monthly

packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** Add note about Inline Hooks API
* [OKTA-699446](https://oktainc.atlassian.net/browse/OKTA-699446)
=> Add links to API

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** broken links for REALMS 
- **Is this PR related to a Monolith release?** yes  2024.03.0
=> URL update

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Changed year for a few entries from 2024 to 2023
=> Year fix for DPop support entry

packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** Slight rollback on previous changes, URL adjustment, and note removal.
=> Telephony Guide Round 3

packages/@okta/vuepress-theme-prose/assets/css/components/_onThisPage.scss, packages/@okta/vuepress-theme-prose/assets/css/components/_stackSelector.scss, packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_content.scss, packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_onThisPage.scss, packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_stackSelector.scss
- **What's changed?** Fixed stack selector and on-this-page component's styles in dark theme
* [OKTA-701591](https://oktainc.atlassian.net/browse/OKTA-701591)
=> [OKTA-701591] Fixed stack selector styles in dark theme

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Add blurbs for this release.
- **Is this PR related to a Monolith release?** 2024.03.1
* [OKTA-704859](https://oktainc.atlassian.net/browse/OKTA-704859)
=> Rn-entry-2024.03.1

packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Update property ordering in PUT /apps API note
* [OKTA-703301](https://oktainc.atlassian.net/browse/OKTA-703301)
=> OKTA-703301 Update property ordering in PUT apps API note

.github/acrolinx/global-config.edn
- **What's changed?** changing the regular expression for the filter to include more folders not to be scanned
=> tweaking the filter for baseline

packages/@okta/vuepress-theme-prose/assets/css/components/_header.scss
- **What's changed?** Fixed search bar's visibility in mobile view/smaller screens
* [OKTA-705749](https://oktainc.atlassian.net/browse/OKTA-705749)
=> [OKTA-705749]: Fixed search bar in mobile view

packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/nutrition.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/overview.md, packages/@okta/vuepress-site/docs/guides/oie-upgrade-sessions-api/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md, packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md, packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** We have a new, up-to-date topic in the H.O.C. on the subject of third-party cookies. We should point to it.
- 
https://65f8be82e17d882dd107ce06--reverent-murdock-829d24.netlify.app/docs/guides/implement-grant-type/authcodepkce/main/
* [OKTA-708179](https://oktainc.atlassian.net/browse/OKTA-708179)
=> Third-party cookies: update link in D.O.C.

packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/index.md, packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- **What's changed?** Add references to source/target org terminology to align with other Org2Org documentation.
* [OKTA-698520](https://oktainc.atlassian.net/browse/OKTA-698520)
=> OKTA-698520 Add target and source terms to OAuth 2.0 Org2Org

packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md
- **What's changed?**  Updated to add info about GA features released in preview. Also upped acrolinx score
- **Is this PR related to a Monolith release?**  Nope!
* [OKTA-707143](https://oktainc.atlassian.net/browse/OKTA-707143)
=> [OKTA-707143] Release Lifecycle update

packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  Straight quote fix, nav bar fix, and added H1 back in. Continuation of PR#4731
* [OKTA-707143](https://oktainc.atlassian.net/browse/OKTA-707143)
=> [OKTA-707143] Part 2, additional fixes

packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Update to dnssec note
=> Update to DNSSec note

.github/acrolinx/repositories.edn
- **What's changed?** manually running a baseline
=> baseline run

packages/@okta/vuepress-theme-prose/components/ContentPage.vue, packages/@okta/vuepress-theme-prose/components/OnThisPage.vue, packages/@okta/vuepress-theme-prose/layouts/Layout.vue, packages/@okta/vuepress-theme-prose/mixins/AnchorHistory.vue, tests/cypress/integration/table_of_contents.js
- **What's changed?** Remove caching and use binary search to get active anchors
* [OKTA-701959](https://oktainc.atlassian.net/browse/OKTA-701959)
=> OKTA-701959 | [Dev Docs] issues with navigation on big pages

packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Updates DNSSec note
=> Custom domain: DNSSec note update

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** 2024.03.2 RN entries
- **Is this PR related to a Monolith release?** Yes, 2024.03.2
* [OKTA-707879](https://oktainc.atlassian.net/browse/OKTA-707879)
=> OKTA-707879 2024.03.2 RN entries

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** API release notes for 2024.03.2
- **Is this PR related to a Monolith release?** Yes, 2024.03.2
* [OKTA-707879](https://oktainc.atlassian.net/browse/OKTA-707879)
=> OKTA-707879 2024.03.2 release notes

packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/overview.md
- **What's changed?**note about client credentials and org/custom auth servers 
* [OKTA-659261](https://oktainc.atlassian.net/browse/OKTA-659261)
=> note about client credentials and org/custom auth servers

packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss, packages/@okta/vuepress-theme-prose/components/MobileOnThisPage.vue
- **What's changed?**  Mobile view: Update scroll to position on input change
* [OKTA-712146](https://oktainc.atlassian.net/browse/OKTA-712146)
=> OKTA-712146 | Mobile view: Clicking on 'On this Page' dropdown links doesn't update the hash url

packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
- **What's changed?** Changes `okta.preview.com` to `oktapreview.com`
=> Okta Aerial: small fix

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Add post 2024.03.2 prod deploy rn item
- **Is this PR related to a Monolith release?** Yes, 2024.03.2 Prod
* [OKTA-707879](https://oktainc.atlassian.net/browse/OKTA-707879)
=> OKTA-707879 Post 2024.03.2 prod deploy RN

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding release notes for 2024.04.0
- **Is this PR related to a Monolith release?** 2024.04.0
* [OKTA-713906](https://oktainc.atlassian.net/browse/OKTA-713906)
=> RN entries for 2024.04.0

packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
- **What's changed?** Provisioning connection guide updates with OAuth2 API access
- **Is this PR related to a Monolith release?** Yes, 2024.04.0
https://66032a6faa38178c2e76f57f--reverent-murdock-829d24.netlify.app/docs/guides/app-provisioning-connection/main/
* [OKTA-705616](https://oktainc.atlassian.net/browse/OKTA-705616)
=> OKTA-705616 Provisioning connection guide updates with OAuth2 API access

packages/@okta/vuepress-site/docs/reference/rest/index.md
- **What's changed?** Noted that multiple scopes must be separated by spaces.
* [OKTA-715495](https://oktainc.atlassian.net/browse/OKTA-715495)
=> Specify that multiple scopes must be separated by spaces.

packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
- **What's changed?** Fixing a broken link in the Vue script that points to the new ITP Event Types page: https://developer.okta.com/docs/reference/api/itp-et/
* Thanks, Van!
=> Fix broken link

packages/@okta/vuepress-site/docs/reference/rest/index.md
- **What's changed?** Moved note to proper section.
* [OKTA-715495](https://oktainc.atlassian.net/browse/OKTA-715495)
=> Moved to proper section.

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Updated release note to point to a developer topic.
* [OKTA-715993](https://oktainc.atlassian.net/browse/OKTA-715993)
=> Updated link to developer topic.

packages/@okta/vuepress-site/archive/php/protect-your-api/index.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
- **What's changed?** Discovered a couple of localhost URLs on the site
*
=> Fix two local URLs

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Add SSF API links to 2024.04.0 release notes
- **Is this PR related to a Monolith release?** Yes, 2024.04.0
https://661080af914aad61bf89c6d0--reverent-murdock-829d24.netlify.app/docs/release-notes/2024-okta-identity-engine/#identity-threat-protection-with-okta-ai-is-ea-in-preview
=> Add ITP SSF API links to 2024.04.0 release notes

packages/@okta/vuepress-site/conductor.yml
- **What's changed?** A couple of IGA API endpoint urls have changed and there was a request for a redirect
* n/a
=> Add two redirects to conductor.yaml file

packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Adds a note about Okta-managed certificates and network zones.
=> Custom domains: add network zones note

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Adding lone bug to the release branch
- **Is this PR related to a Monolith release?** 2023.04.1
* [OKTA-715726](https://oktainc.atlassian.net/browse/OKTA-715726)
=> Add release note entry to release branch

packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
- **What's changed?** pointing to hoc for create an API token content
Netlify:
https://66185489a3d77a3723bd0eb4--reverent-murdock-829d24.netlify.app/docs/guides/create-an-api-token/main/#create-the-token
* [OKTA-716504](https://oktainc.atlassian.net/browse/OKTA-716504)
=> pointing to hoc for create an API token content

packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
- **What's changed?** org2org and amr claims mapping update
Netlify
https://6619962abceb8933d41430ca--reverent-murdock-829d24.netlify.app/docs/guides/configure-amr-claims-mapping/main/#use-an-existing-org2org-app
* [OKTA-714692](https://oktainc.atlassian.net/browse/OKTA-714692)
=> org2org and amr claims mapping update

packages/@okta/vuepress-site/docs/concepts/policies/index.md
- **What's changed?** Removed a sentence that stated polices can have unlimited rules; fixed a couple of typos.
* [OKTA-720167](https://oktainc.atlassian.net/browse/OKTA-720167)
=> Policies Concept - Update to number of rules

packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Removing some redirects that didn't work
* n/a
=> Clean up conductor

packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Addressing some missing properties, incorrect values, and enhancing examples for the ERP and CAE polices.
* [OKTA-718253 ](https://oktainc.atlassian.net/browse/OKTA-718253 )
=> OKTA-718253 - Fixes to ERP and CAE Policy Types in Policy API

packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md, packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md, packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md, packages/@okta/vuepress-theme-prose/global-components/HookBasicAuthValuesNote.vue, packages/@okta/vuepress-theme-prose/global-components/HookCommonSetupNote.vue
- **What's changed?** Added two single-source global components for single sourcing in the hook docs; see-alsos updated with all hook guides; minor procedure updates in the Registration Hook to remove ambiguity
* [OKTA-689678 ](https://oktainc.atlassian.net/browse/OKTA-689678 )
=> OKTA-689678 - Hook doc set updates

packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?**  
- Remove the link from the top menu.
- Update the link at the footer to point to this page: https://developer.auth0.com/
* [OKTA-720279](https://oktainc.atlassian.net/browse/OKTA-720279)
=> OKTA-720279 | Update links to CIC on developer.okta.com

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Add no SPA app support in OIN Wizard
- https://662920d5fa4fae0700e8ccc6--reverent-murdock-829d24.netlify.app/docs/guides/submit-app-prereq/main/#oin-limitations
- https://662920d5fa4fae0700e8ccc6--reverent-murdock-829d24.netlify.app/docs/guides/submit-oin-app/openidconnect/main/#overview
- 
* [OKTA-721763](https://oktainc.atlassian.net/browse/OKTA-721763)
=> OKTA-721763 Add no SPA app support in OIN Wizard

packages/@okta/vuepress-site/docs/guides/archive-set-up-self-service-registration/main/index.md
- **What's changed?** Update notes about availability of feature on Classic. Update details about password policy.
* [OKTA-650540](https://oktainc.atlassian.net/browse/OKTA-650540)
* [OKTA-721801](https://oktainc.atlassian.net/browse/OKTA-721801)
=> SSR guide (archived) - Small updates

packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
- **What's changed?** Update to OIE overview page for PATEAM
Netlify link: https://66283d50ddf59b2c8a278775--reverent-murdock-829d24.netlify.app/docs/guides/oie-upgrade-overview/main/
* [OKTA-704690](https://oktainc.atlassian.net/browse/OKTA-704690)
=> Update to OIE overview page for PATEAM

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Those darn release notes.
- **Is this PR related to a Monolith release?** 2024.04.3
[Preview](https://663287df4bcbfd2226a85a53--reverent-murdock-829d24.netlify.app/docs/release-notes/2024/)
* [OKTA-720645](https://oktainc.atlassian.net/browse/OKTA-720645)
=> Release 2024.04.3 - The "It's Gonna Be May" Release

packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Updates DNSSEC note
=> Update DNSSEC note

packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
- **What's changed?** Fixes a broken link.
=> SIW (Gen3) - fix broken link

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Release notes for May 2024 release
- **Is this PR related to a Monolith release?** 2024.05.0
* [OKTA-725292](https://oktainc.atlassian.net/browse/OKTA-725292)
=> Rn entry 2024.05.0 - IDDD review

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Post-release fix
- **Is this PR related to a Monolith release?** 2024.04.3
* [OKTA-712504](https://oktainc.atlassian.net/browse/OKTA-712504)
=> Add post-release fix

packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md
- **What's changed?** Updates to UI procedure and minor formatting
* [OKTA-724379](https://oktainc.atlassian.net/browse/OKTA-724379)
=> OKTA-724379 - Minor updates to WebAuthn integration guides

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Release notes for 2024.05.1
- **Is this PR related to a Monolith release?**   2024.05.1
* [OKTA-726566](https://oktainc.atlassian.net/browse/OKTA-726566)
=> Release notes entries for 2024.05.1 release

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Release update for 2024.05.1
- **Is this PR related to a Monolith release?**  2024.05.1
* [OKTA-726563](https://oktainc.atlassian.net/browse/OKTA-726563)
=> [OKTA-726563] 2024.05.1 release

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  update to expression language examples
* [OKTA-408401](https://oktainc.atlassian.net/browse/OKTA-408401)
https://664692a71ee1d0285500dcfb--reverent-murdock-829d24.netlify.app/docs/reference/okta-expression-language/#array-functions
=> [OKTA-408401] OEL update

packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- **What's changed?** updates to device auth
Preview Link:
https://6647ae5a1ee1d0224700da9f--reverent-murdock-829d24.netlify.app/docs/guides/device-authorization-grant/main/
* [OKTA-727783](https://oktainc.atlassian.net/browse/OKTA-727783)
=> updates to device auth

packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test.json
- **What's changed?** Update Okta-SCIM-20-SPEC-Test.json with error and response handling
https://6647d12ea3827c0ddfc91059--reverent-murdock-829d24.netlify.app/docs/guides/scim-provisioning-integration-prepare/main/#set-up-runscope
* [OKTA-728721](https://oktainc.atlassian.net/browse/OKTA-728721)
=> OKTA-728721 Update SCIM 2.0 test plan with error and response handling

packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md, packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
- **What's changed?** Add group exists operation to SCIM protocol
https://664797f19e6c500cf3b16aff--reverent-murdock-829d24.netlify.app/docs/reference/scim/scim-20/#retrieve-groups
* [OKTA-520454](https://oktainc.atlassian.net/browse/OKTA-520454)
* [OKTA-518815](https://oktainc.atlassian.net/browse/OKTA-518815)
=> OKTA-520454 Add group exists operation to SCIM protocol

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- **What's changed?** Added a bullet to the RL Overview page: https://developer.okta.com/docs/reference/rate-limits/#api-rate-limit-categories-and-cumulative-rate-limits regarding preview/production rate limits (i.e. no difference)
* [OKTA-731746](https://oktainc.atlassian.net/browse/OKTA-731746)
=> OKTA-731746 - RL overview clarification

packages/@okta/vuepress-theme-prose/assets/css/components/_menuItem.scss
- **What's changed?** Fixes community dropdown that was not interactive at all.
* [OKTA-729624](https://oktainc.atlassian.net/browse/OKTA-729624)
=> [OKTA-729624]: Fixed community dropdown

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Fix broken link to Parmonic OIN OIDC configuration. Thanks to @brianduffield-okta broken-link checker.
=> Fix Parmonic broken link

packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-20-SPEC-Test.json
- **What's changed?** Update SCIM 2 test file to fix error in GET /Users schemas property
* [OKTA-728721](https://oktainc.atlassian.net/browse/OKTA-728721)
=> OKTA-728721 Update SCIM 2 test file

.circleci/config.yml
- The latest netlify-cli package fails to install, switching to working version.
* [OKTA-732699](https://oktainc.atlassian.net/browse/OKTA-732699)
=> Uses working netlify-cli

packages/@okta/vuepress-theme-prose/util/coveo/endpoint.js
- **What's changed?** Fixed semgrep warning appearing on PRs.
* [OKTA-728335](https://oktainc.atlassian.net/browse/OKTA-728335)
=> [OKTA-728335]: Fix semgrep warning

packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md
- **What's changed?**  Fixed link, broken section, and some capitalization
* [OKTA-730760](https://oktainc.atlassian.net/browse/OKTA-730760)
=> [OKTA-730760] Content issues in guide

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Revert the Parmonic doc link - they have a redirect now
=> Update Parmonic doc link

packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Add note for the AIP name format allowed
* [OKTA-730160](https://oktainc.atlassian.net/browse/OKTA-730160)
=> OKTA-730160 - AIP variable name format

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- **What's changed?** As per PM's feedback, revised bullet as follows: `"If you purchased dynamic scale or other rate limit increases for your org, these updates only apply to production orgs unless otherwise specified."`
* [OKTA-731746](https://oktainc.atlassian.net/browse/OKTA-731746)
=> OKTA-731746 - Minor update to RL overview

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Removed item per a revert of a fix in OPS ticket.
- **Is this PR related to a Monolith release?**  no
* [OKTA-734890](https://oktainc.atlassian.net/browse/OKTA-734890)
=> [OKTA-734890] Remove item in Release Notes

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Adds table of default supported languages with BCP 47 format.
* [OKTA-735376](https://oktainc.atlassian.net/browse/OKTA-735376)
=> Custom email guide: add table of supported languages

.github/acrolinx/repositories.edn
- **What's changed?** Running baseline
=> baseline push

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Release Notes for 2024.06.0 monthly
- **Is this PR related to a Monolith release?**  2024.06.0
* [OKTA-726568](https://oktainc.atlassian.net/browse/OKTA-726568)
=> Rn entry release 2024.06.0

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Editing to reflect changes to the Customizations API content.
=> Custom email guide: edit to language for extra locales

packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** Fix typo and repeated bullet
* [OKTA-728754](https://oktainc.atlassian.net/browse/OKTA-728754)
=> OKTA-728754 - Telephony Hook - Fix typo and remove duplicate bullet

packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?**  Append source querystring to the survey URL
* [OKTA-733733](https://oktainc.atlassian.net/browse/OKTA-733733)
=> OKTA-733733 | Capture source URL for dev.okta IMP survey in banner

.wokeignore, packages/@okta/vuepress-site/books/api-security/sanitizing/reject-bad/index.md, packages/@okta/vuepress-site/books/api-security/sanitizing/sanitize-inputs/index.md
- **What's changed?** Replaced a few non-inclusive terms with inclusive ones
* [OKTA-735570](https://oktainc.atlassian.net/browse/OKTA-735570)
=> [OKTA-735570]: Replaced non inclusive terms in a few files

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Re-added links to API
- **Is this PR related to a Monolith release?**  2024.06.0 (post redocly build)
* [OKTA-726568](https://oktainc.atlassian.net/browse/OKTA-726568)
=> Redocly link add

.github/CODEOWNERS
- **What's changed?** adding Paul to strict file list
=> adding Paul

.github/acrolinx/global-config.edn
- **What's changed?** lowering score for fixitdays
=> lowering score for fixitdays

packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/basic-sign-in.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/create-app-integration.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/download-sample.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/basic-sign-in.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/create-app-integration.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/download-sample.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/create-app-integration.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/sign-in-form.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/download-sample.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/load-app.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/run-sample.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/load-app.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/run-sample.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/useaccesstoken.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/configmid.md
- **What's changed?**  First pass at placeholder updates
=> FIXIT DAY [OKTA-729831] - placeholder update

packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md, packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/configlocations.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/configlocations.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/configlocations.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/softwarerequirements.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/configlocations.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/react/configlocations.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runsdkapp.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-run-samples/main/java/runwidgetapp.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/emailtemplate.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/spring-boot/configmid.md
- **What's changed?**  More placeholders
- **Is this PR related to a Monolith release?**  None
=> Placeholder updates part 2

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/afterappidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md, packages/@okta/vuepress-site/docs/guides/configure-access-policy/main/index.md, packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md, packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md, packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md, packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md, packages/@okta/vuepress-site/docs/guides/find-your-app-credentials/main/index.md, packages/@okta/vuepress-site/docs/guides/find-your-domain/main/index.md, packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md, packages/@okta/vuepress-site/docs/guides/single-logout/main/index.md, packages/@okta/vuepress-site/docs/guides/single-logout/main/openidconnect/getrequest.md, packages/@okta/vuepress-site/docs/guides/single-logout/main/saml2/getrequest.md, packages/@okta/vuepress-site/docs/guides/single-logout/main/saml2/putrequest.md, packages/@okta/vuepress-site/docs/guides/single-logout/main/saml2/response.md, packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- **What's changed?**  Placeholder fixes
=> Placeholders pt 4

packages/@okta/vuepress-site/docs/guides/device-context/main/aspnet/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/device-context/main/nodeexpress/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/sdk.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/emailtemplate.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/sdk.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/java/siw.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/emailtemplate.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/sdk.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/nodeexpress/proxymodelsampleappactivationtokenlink.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/aspnet/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-basic-sign-in/main/aspnet/configureyourapp.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-sign-in-soc-idp/main/go/integrationsteps.md, packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/android/addsdk.md, packages/@okta/vuepress-site/docs/guides/oie-upgrade-add-sdk-to-your-app/main/java/addsdk.md
- **What's changed?**  More placeholders!
=> [OKTA-729831] placeholders pt 3

packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
- **What's changed?** Minor updates to this guide: https://developer.okta.com/docs/guides/auth-js-redirect/main/ including updating auth.js version and adding full code for ease of implementation.
* [OKTA-736503](https://oktainc.atlassian.net/browse/OKTA-736503)
=> OKTA-736503 - Minor updates to vanilla spa app

packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- **What's changed?** clarity update for oauth oidc concept
=> clarity update for oauth oidc concept

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md, packages/@okta/vuepress-site/docs/guides/custom-sms-messaging/main/index.md, packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- **What's changed?** Removes the placeholder `$` symbol from Brand and Customize guides.
=> Fix-It Days: Placeholders 1 (Brent)

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Add password-only auth policy users testing with OIN Submission Tester
https://preview-4865--reverent-murdock-829d24.netlify.app/docs/guides/submit-oin-app/openidconnect/main/#generate-instances-for-testing
* [OKTA-736323](https://oktainc.atlassian.net/browse/OKTA-736323)
=> OKTA-736323 Add password-only auth policy to OIN tester

packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md
- **What's changed?** placeholder removal for auth servers
=> placeholder removal for auth servers

packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
- **What's changed?** Replaces `$` placeholder in the Manage users section
=> Fix-It Days: Placeholders 2 (Brent)

packages/@okta/vuepress-site/docs/guides/archive-auth-js/main/index.md, packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/angular/guide.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/react/guide.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/vue/guide.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/angular/guide.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/react/guide.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-embedded-widget/main/vue/guide.md, packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/android/primaryauth.md, packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/ios/primaryauth.md, packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/react-native/installoktaauthsdk.md, packages/@okta/vuepress-site/docs/guides/mfa/main/ga/activatefactor.md, packages/@okta/vuepress-site/docs/guides/mfa/main/ga/enrollfactor.md, packages/@okta/vuepress-site/docs/guides/mfa/main/ga/verifyfactor.md, packages/@okta/vuepress-site/docs/guides/mfa/main/sms/activatefactor.md, packages/@okta/vuepress-site/docs/guides/mfa/main/sms/enrollfactor.md, packages/@okta/vuepress-site/docs/guides/mfa/main/sms/verifyfactor.md, packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/android/configfile.md, packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/ios/enablesso.md, packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/main/index.md, packages/@okta/vuepress-site/docs/guides/updating-saml-cert/main/index.md
- **What's changed?**  Updated placeholders in Classic
- **Is this PR related to a Monolith release?**  Nawww
=> Placeholders in Classic

packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- **What's changed?** clarity and $ removal for refresh tokens
=> clarity and $ removal for refresh tokens

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
- **What's changed?** oauth for okta clarity and $
=> oauth for okta clarity and $

packages/@okta/vuepress-site/docs/guides/protect-your-api/main/aspnetcore3/configureapi.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/aspnetcore3/createproject.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/go/configureapi.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/nodeexpress/configureapi.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/python/configureapi.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/configureapi.md
- **What's changed?** Fix-it-day Placeholder updates for API security > protect-your-api
=> Fit-it-day placeholder updates API Security > protect-your-api (Van)

packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- **What's changed?** Removes the offending `$` from the Role Assignment concept doc
- **Is this PR related to a Monolith release?** Nope. Nein.
=> Fix-It Days: Placeholders 3 (Brent)

packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md, packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md, packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- **What's changed?** Updated the Inline Hook concept and Event Hook concept, as well as the Common hook set up steps guide. Will save the rest for tomorrow.
=> Fix-it-day placeholder updates hook concepts

packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Release notes updates for placeholders
=> aj-okta729831-placeholder-10

packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/java/deployment.md, packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/javascript/deployment.md, packages/@okta/vuepress-site/docs/guides/deploy-your-app/main/reactnative/deployment.md, packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md, packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
- **What's changed?** Fit-it-day placeholder ($) update for Deploy to Production
=> Fit-it-day placeholder update for Deploy to Production (Van)

packages/@okta/vuepress-site/docs/reference/rest/index.md
- **What's changed?** Placeholder updates for test with Postman
=> Fit-it-day placeholder updates for test with Postman (Van)

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** doc action removal
- **Is this PR related to a Monolith release?** Yes 2024.06.0
[OKTA-727346](https://oktainc.atlassian.net/browse/OKTA-727346)
=> doc action removal

packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Added a note to OEL docs, minor placeholder fix
=> Placeholders 

packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md, packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md, packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/nodejs/password-import-api.md, packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
- **What's changed?**  More placeholders
=> Hooks guides placeholder updates

packages/@okta/vuepress-site/docs/guides/terraform-design-rate-limits/main/index.md, packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md, packages/@okta/vuepress-site/docs/guides/terraform-manage-end-user-experience/main/index.md, packages/@okta/vuepress-site/docs/guides/terraform-manage-external-authenticators/main/index.md, packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md
- **What's changed?**  Placeholders everywhere
- **Is this PR related to a Monolith release?**  None
=> Placeholders in Terraform docs

packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/aotp/use-flow.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/bmfaotp/use-flow.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/coobov/use-flow.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/dmfaoobov/use-flow.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/eoobsv/use-flow.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/fmfaoobsv/use-flow.md, packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/use-flow.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/use-flow.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/use-flow.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/use-flow.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/use-flow.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/configuration.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/use-flow.md
- **What's changed?** Removes placholders from Authorization > Implement by grant type/Configure Device Authz grant flow/ConfigureDirect auth grant types
=> Fix-It Days: Placeholders 4 (Brent)

packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/retrievekeys.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/go/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/go/retrievekeys.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/java/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/java/retrievekeys.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/nodejs/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/nodejs/retrievekeys.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/python/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/python/retrievekeys.md
- **What's changed?** Clarity and $ updates 
Netlify Preview Link: https://preview-4902--reverent-murdock-829d24.netlify.app/docs/guides/validate-access-tokens/dotnet/main/
=> Clarity and $ updates

packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/index.md, packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/java/createclientsecretjwt.md, packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/java/createprivatekeyjwt.md, packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/js/createclientsecretjwt.md, packages/@okta/vuepress-site/docs/guides/build-self-signed-jwt/main/js/createprivatekeyjwt.md, packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md, packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md, packages/@okta/vuepress-site/docs/guides/configure-native-sso/main/index.md, packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md, packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md, packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md, packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md, packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md, packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md, packages/@okta/vuepress-site/docs/guides/set-up-token-exchange/main/index.md
- **What's changed?** Removes placeholders from the Authorization section, part 2.
=> Fix-It Days: Placeholders 5 (Brent)

packages/@okta/vuepress-site/docs/guides/revoke-tokens/main/index.md, packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/dotnet/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/go/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/java/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/nodejs/accesstoken.md, packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/python/accesstoken.md
- **What's changed?** Removes the placeholder from the last of the guides in the Authorization section.
=> Fix-It Days: Placeholders 6 (Brent)

.github/acrolinx/global-config.edn
- **What's changed?** Placeholder work done. Putting score back to 80
=> Setting the score back to 80

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- **What's changed?** OAuth for Okta Service App FixtIt Day Clarity Update
=> OAuth for Okta Service App FixtIt Day Clarity Update

packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/examples.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/flow-diagram.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/install-sdk.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/overview.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/setup-app.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/use-flow.md
=> Auth Code with PKCE updates

packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/flow-diagram.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/install-sdk.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/overview.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/use-flow.md
- **What's changed?** client cred update
=> client cred update

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Add entries for 2024.06.1
- **Is this PR related to a Monolith release?** Yes, 2024.06.1
* [OKTA-734468](https://oktainc.atlassian.net/browse/OKTA-734468)
=> OKTA-734468 Add 2024.06.1 RN entries

packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/notifserviceadminconsole.md, packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/notifserviceadminconsole.md, packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md, packages/@okta/vuepress-site/docs/reference/api/push-providers/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Deprecates the Push Providers API content in VuePress.
* [OKTA-740804](https://oktainc.atlassian.net/browse/OKTA-740804)
=> Push Providers API: deprecate VuePress page, etc.

falsepos.txt
- **What's changed?** Adding several false positive broken URLS that have been flagged.
* n/a
=> Update false positives list

packages/@okta/vuepress-site/docs/concepts/policies/index.md
- **What's changed?** Changing name of Continuous auth evaluation to Post auth session evaluation
- **Is this PR related to a Monolith release?** 2024.07.0
* [OKTA-735460](https://oktainc.atlassian.net/browse/OKTA-735460)
=> OKTA-735460 - Update CAE content in Policies Concept

packages/@okta/vuepress-site/conductor.yml, packages/@okta/vuepress-site/docs/guides/custom-sms-messaging/main/index.md, packages/@okta/vuepress-site/docs/reference/api/factors/index.md, packages/@okta/vuepress-site/docs/reference/api/templates/index.md, packages/@okta/vuepress-site/docs/release-notes/2016/index.md, packages/@okta/vuepress-site/docs/release-notes/2020/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** deprecating templates API
* [OKTA-743964](https://oktainc.atlassian.net/browse/OKTA-743964)
=> deprecating templates API

packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Add considerations for editing AIP variables in migrated OIN apps
- **Is this PR related to a Monolith release?** No. But should be published after June 2024 (migration started at this point).
https://preview-4927--reverent-murdock-829d24.netlify.app/docs/guides/submit-oin-app/openidconnect/main/#update-integration-considerations
* [OKTA-729928](https://oktainc.atlassian.net/browse/OKTA-729928)
=> OKTA-729928 Add considerations for editing AIP variables in migrated OIN apps

.circleci/config.yml
- **What's changed?**  CircleCi workflow configuration
* [OKTA-742222](https://oktainc.atlassian.net/browse/OKTA-742222)
=> OKTA-742222 | Inclusive linting job runs with netlify preview

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding release notes to release branch
- **Is this PR related to a Monolith release?** 2024.06.2
* [OKTA-734507](https://oktainc.atlassian.net/browse/OKTA-734507)
=> Rn entry release 2024.06.2

packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md
- **What's changed?** removed reference to self-service EA
* [OKTA-728745](https://oktainc.atlassian.net/browse/OKTA-728745)
=> removing self-service EA bullet

packages/@okta/vuepress-theme-prose/components/Breadcrumb.vue
- **What's changed?**  Logic to show breadcrumb when the url contains `/-/`
* [OKTA-532916](https://oktainc.atlassian.net/browse/OKTA-532916)
=> OKTA-532916 | breadcrumbs visibility at the top of the page

packages/@okta/vuepress-site/docs/guides/enable-cors/main/index.md
- **What's changed?** Edited the Enable CORS topic to improve it's Acrolinx score. 
=> Edits on the Enable CORS topic with GPG

packages/@okta/vuepress-site/docs/reference/api/policy/index.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Adds new OIE EL expressions related to account mgmt policy.
- **Is this PR related to a Monolith release?** Yes. 2024.07.2
* [OKTA-746571](https://oktainc.atlassian.net/browse/OKTA-746571)
=> OIE Expression Language: New expressions for account mgmt policy

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Added OIE and Classic RNs
- **Is this PR related to a Monolith release?** `2024.07.0`
* [OKTA-734513 ](https://oktainc.atlassian.net/browse/OKTA-734513 )
=> OKTA-734513 -  Rn entry 2024.07.0

packages/@okta/vuepress-site/.vuepress/config.js, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** hiding amr claims doc for now
- **Is this PR related to a Monolith release?** Yes 2024.07.0
* [OKTA-738487](https://oktainc.atlassian.net/browse/OKTA-738487)
=> hide files

packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
- **What's changed?** Updated description of an Aerial org and modified API endpoints to match the API docs.
* [OKTA-746030](https://oktainc.atlassian.net/browse/OKTA-746030)
=> OKTA-746030 - Update Aerial dev guide

packages/@okta/vuepress-site/docs/concepts/iam-overview/index.md
- **What's changed?** Edited the topic to bring up its Acrolinx score 
=> Edits on the IAM overview topic

packages/@okta/vuepress-site/docs/concepts/policies/index.md, packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Removed ITP EA banners on Concept page and the Policy API reference
- **Is this PR related to a Monolith release?** `2024.07.0`
* [OKTA-747879](https://oktainc.atlassian.net/browse/OKTA-747879)
=> OKTA-747879 - Remove ITP EA banners

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Added an RN to OIE and Classic RNs for `2024.06.2` RNs
- **Is this PR related to a Monolith release?** `2024.06.2`
* [OKTA-747426](https://oktainc.atlassian.net/browse/OKTA-747426)
=> OKTA-747426 - Update to 2024.06.2 RN

packages/@okta/vuepress-theme-prose/components/HeaderBanner.vue, packages/@okta/vuepress-theme-prose/components/MobileOnThisPage.vue, packages/@okta/vuepress-theme-prose/const/index.const.js, packages/@okta/vuepress-theme-prose/enhanceApp.js, packages/@okta/vuepress-theme-prose/global-components/ApiLifecycle.vue, packages/@okta/vuepress-theme-prose/layouts/Layout.vue, packages/@okta/vuepress-theme-prose/mixins/AnchorHistory.vue
- **What's changed?**  
- Introduces changes to handle the scroll position when `<RouterLink />` is clicked, ensuring the user is taken to the correct section of the page.
- Includes a fix for the accurate calculation of the active section's visible area.
* [OKTA-744724](https://oktainc.atlassian.net/browse/OKTA-744724)
=> OKTA-744724 | Developer Doc: Scroll Position Issue

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Added release note for hotfix OKTA-747631
- **Is this PR related to a Monolith release?**  2024.07.0
* [OKTA-747631](https://oktainc.atlassian.net/browse/OKTA-747631)
=> Release note hot fix for OKTA-747631

packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  Fixed a link in the Nav Bar
* [OKTA-748328](https://oktainc.atlassian.net/browse/OKTA-748328)
=> [OKTA 748328] Nav bar fix for Group Owners API

packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md, packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md
- **What's changed?** Add migration note to published SSO integrations.
- **Is this PR related to a Monolith release?** Yes, after 2024.06.0
https://preview-4926--reverent-murdock-829d24.netlify.app/docs/guides/submit-sso-app/openidconnect/main/
---
---
---
* [OKTA-743092](https://oktainc.atlassian.net/browse/OKTA-743092)
=> OKTA-743092 Add notes regarding OIN SSO migration

packages/@okta/vuepress-site/docs/concepts/scim/index.md
- **What's changed?** Updated the doc to improve the clarity score
- **Is this PR related to a Monolith release?** no 
=> SCIM clarity fix

packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
- **What's changed?** Removes extra OIE tag
N/A
=> SIW Gen 3 guide: remove extra OIE tag

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Release notes
- **Is this PR related to a Monolith release?**  2024.07.1
* [OKTA-744003](https://oktainc.atlassian.net/browse/OKTA-744003)
=> Rn entry release 2024.07.1

packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
- **What's changed?** As per feedback, made updates to this doc: https://developer.okta.com/docs/reference/api/itp-et/ to update two event type descriptions and add a right-hand nav
* [OKTA-749502](https://oktainc.atlassian.net/browse/OKTA-749502)
=> OKTA-749502 - Update ITP event types doc

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Release docs for 2024.07.1
- **Is this PR related to a Monolith release?**  2024.07.1
* [OKTA-744003](https://oktainc.atlassian.net/browse/OKTA-744003)
=> Weekly Release 2024.07.1

packages/@okta/vuepress-site/data/event-types.json
- **What's changed?** Updated the `beta` flag to `false` to publish the following four event types: 
* workflows.user.role.group.add
* workflows.user.role.group.remove
* workflows.user.role.user.add
* workflows.user.role.user.remove
- **Is this PR related to a Monolith release?** 2024.07.1
n/
=> Event Types - set workflow events to publish

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Updated wording of blurb for OKTA-747426
- **Is this PR related to a Monolith release?**  2024.06.2
=> Blurb hotfix pt 2

packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
- **What's changed?** Added note to [Embedded SIW](https://developer.okta.com/docs/guides/embedded-siw/main/) guide to clarify which authorization server users should use. And also made some small edits to [Protect your API](https://developer.okta.com/docs/guides/protect-your-api/aspnetcore3/main/).  
* [OKTA-738065](https://oktainc.atlassian.net/browse/OKTA-738065)
=> Adding note to Embedded SIW guide

packages/@okta/vuepress-site/docs/concepts/policies/index.md
- **What's changed?** Updates the policies concept doc to include the account management policy
- **Is this PR related to a Monolith release?** Yes. 2024.07.2
* [OKTA-746992](https://oktainc.atlassian.net/browse/OKTA-746992)
=> Account management policy: concept doc update

packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Small updates to the VuePress API docs.
- **Is this PR related to a Monolith release?** Yes. 2024.07.2
* [OKTA-746715](https://oktainc.atlassian.net/browse/OKTA-746715)
=> Account management policy: VuePress Policy API updates

packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Fixing a broken link in Policy API reference
*n/a
=> Update link reference

packages/@okta/vuepress-site/docs/guides/find-your-domain/main/index.md
- **What's changed?** Edited the Find your domain page to improve its Acrolinx score
* [OKTA-751035](https://oktainc.atlassian.net/browse/OKTA-751035)
=> Edits to improve acro score

packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
- **What's changed?** Edited the Create an API token page to improve its Acrolinx score
* [OKTA-751022](https://oktainc.atlassian.net/browse/OKTA-751022)
=> Edit Create and API token page to improve Acro score

packages/@okta/vuepress-site/data/event-types.json, packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md, packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
- **What's changed?** An interim fix to update the live descriptions on the dev docs [Event Type ](https://developer.okta.com/docs/reference/api/event-types/?q=continuous)page and the [ITP Event Type](https://developer.okta.com/docs/reference/api/itp-et/) page.
* [OKTA-752964](https://oktainc.atlassian.net/browse/OKTA-752964)
=> OKTA-752964 - Updates to event types page

packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Removes a bug blurb as per the team's dev manager.
* [OKTA-754455](https://oktainc.atlassian.net/browse/OKTA-754455)
=> Remove bug blurb from 2024.07.1 release notes

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Release notes branch for 2024.07.2
- **Is this PR related to a Monolith release?** Yes. 2024.07.2
* [OKTA-744008](https://oktainc.atlassian.net/browse/OKTA-744008)
=> Release notes 2024.07.2

packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md
- **What's changed?** Auth servers concept clarity improvement
=> Auth servers concept clarity improvement

packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md
- **What's changed?** removed reference to signing in with email
* [OKTA-755562](https://oktainc.atlassian.net/browse/OKTA-755562)
=> remove sigining in with email

packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- **What's changed?** added failover information, a link to the troubleshoot section in the API content, and an example JSON response with the discussed properties
Netlify link: https://preview-4956--reverent-murdock-829d24.netlify.app/docs/guides/telephony-inline-hook/nodejs/main/#failover-to-okta-telephony-providers
* [OKTA-748316](https://oktainc.atlassian.net/browse/OKTA-748316)
=> Failover content for Telephony Inline Hook

packages/@okta/vuepress-site/archive/php/protect-your-api/index.md, packages/@okta/vuepress-site/archive/php/sign-into-web-app-redirect/index.md, packages/@okta/vuepress-site/docs/guides/archive-set-up-self-service-registration/main/index.md, packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/aspnetcore3/createendpoints.md, packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/asp-net-core-3/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md, packages/@okta/vuepress-site/docs/reference/rest/index.md
- **What's changed?** Fixed regression where inline-style was being explicitly shown at some places in dev docs
* [OKTA-750220](https://oktainc.atlassian.net/browse/OKTA-750220)
=> OKTA-750220: Fixed style regression in markdown-it-attrs plugin

packages/@okta/vuepress-site/docs/concepts/policies/index.md, packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/index.md, packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md, packages/@okta/vuepress-site/docs/reference/api/policy/index.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Release branch for 2024.07.2
- **Is this PR related to a Monolith release?** Yes - 2024.07.2
* [OKTA-744008](https://oktainc.atlassian.net/browse/OKTA-744008)
=> Release Branch -  2024.07.2

packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md, packages/@okta/vuepress-site/docs/reference/api/schemas/index.md, packages/@okta/vuepress-site/docs/reference/api/xaas/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  Deprecate identity sources on VuePress, added a missing Postman paragraph to Schemas page
Do not merge until the Redocly version of Identity Sources is published.
* [OKTA-734762](https://oktainc.atlassian.net/browse/OKTA-734762)
=> Deprecate XAAS page on Vuepress

.circleci/config.yml
- Updates semgrep task
* [OKTA-791080](https://oktainc.atlassian.net/browse/OKTA-791080)
=> Updates semgrep task

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** release notes for August monthly
- **Is this PR related to a Monolith release?** yes  2024.08.0
* [OKTA-744011](https://oktainc.atlassian.net/browse/OKTA-744011)
=> Rn entry 2024.08.0

packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
- **What's changed?** To match the new UI, replaced the "continuous access evaluation" references that appeared on the ITP Event Types page: https://developer.okta.com/docs/reference/api/itp-et/
* [OKTA-753712](https://oktainc.atlassian.net/browse/OKTA-753712)
=> OKTA-753712 - Update CAE references

packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** Fixed duplicate pages in sitemap which was resulting in duplicate results in coveo search
* [OKTA-745577](https://oktainc.atlassian.net/browse/OKTA-745577)
=> OKTA-745577: Fixed duplicate pages in sitemap

packages/@okta/vuepress-site/docs/concepts/oauth-openid/index.md
- **What's changed?** Added note to clarify recommendations about using redirect authentication or embedded.  
* [OKTA-790331](https://oktainc.atlassian.net/browse/OKTA-790331)
=> Added note to emphasise using redirect authentication.

packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
- **What's changed?** Resolving a merge conflict fix that overwrote some terminology changes; this PR address these updates. Original PR: https://github.com/okta/okta-developer-docs/pull/4983
- **Is this PR related to a Monolith release?** `2024.08.0`
* [OKTA-753712](https://oktainc.atlassian.net/browse/OKTA-753712)
=> OKTA-753712 - Address a few overwritten terminology updates

packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- **What's changed?** Update note type and removed two non-steps
* n/a
=> Minor format updates to refresh token guide

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Add RN entries for 2024.08.1
- **Is this PR related to a Monolith release?** Yes, 2024.08.1
* [OKTA-744012](https://oktainc.atlassian.net/browse/OKTA-744012)
=> OKTA-744012 RN entries for 2024.08.1

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md, packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
- **What's changed?** Added failover RL limit info to telephony hook API and inline hook concepts. Ran acrolinx checks on three topics.
* [OKTA-756271](https://oktainc.atlassian.net/browse/OKTA-756271 )
=> OKTA-756271 - Minor telephony hook updates

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** * Add RN entries for 2024.08.1
- **Is this PR related to a Monolith release?** Yes, 2024.08.1
* [OKTA-744012](https://oktainc.atlassian.net/browse/OKTA-744012)
=> OKTA-744012 Release Notes for 2024.08.1

packages/@okta/vuepress-site/docs/reference/api/event-types/index.md, packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue, scripts/event-types-to-csv.sh
- **What's changed?** Adding `changeDetails` info to Event Types and CSV
* [OKTA-754148](https://oktainc.atlassian.net/browse/OKTA-754148)
=> OKTA-754148 - Updating scripts to include changeDetails info

packages/@okta/vuepress-site/conductor.yml, packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/setup-app.md, packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md, packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md, packages/@okta/vuepress-site/docs/reference/api/apps/index.md, packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md, packages/@okta/vuepress-site/docs/release-notes/2017/index.md, packages/@okta/vuepress-site/docs/release-notes/2018/index.md, packages/@okta/vuepress-site/docs/release-notes/2020/index.md, packages/@okta/vuepress-site/docs/release-notes/2021/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** deprecation of Dynamic Client Registration
* [OKTA-792019](https://oktainc.atlassian.net/browse/OKTA-792019)
=> deprecation of Dynamic Client Registration

packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md
- **What's changed?** Updates and acrolinx
=> Updates and acrolinx

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/configure-amr-claims-mapping/main/index.md, packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- **What's changed?** Removing AMR blurb
* [OKTA-794656](https://oktainc.atlassian.net/browse/OKTA-794656)
=> Removing AMR blurb

packages/@okta/vuepress-theme-prose/custom-landings/OktaIntegrationNetwork/components/Explore.vue, packages/@okta/vuepress-theme-prose/custom-landings/OktaIntegrationNetwork/components/Features.vue
- **What's changed?** Replace "OIN Manager portal" with "OIN Wizard"
* [OKTA-794463](https://oktainc.atlassian.net/browse/OKTA-794463)
=> OKTA-794463 - OIN landing page update

packages/@okta/vuepress-site/docs/guides/saml-tracer/main/index.md
- **What's changed?**  Minor fixes to SAML tracer doc
* [OKTA-751155](https://oktainc.atlassian.net/browse/OKTA-751155)
=> Tiny changes

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Weekly OIE and Classic release note updates
- **Is this PR related to a Monolith release?** `2024.08.2`
* [OKTA-744014](https://oktainc.atlassian.net/browse/OKTA-744014)
=> OKTA-744014-Weekly release notes

packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
- **What's changed?** Minor code snippet update
* n/a
=> Minor update to code snippet

packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Updated links in the conductor file that were outdated
* [OKTA-482742](https://oktainc.atlassian.net/browse/OKTA-482742)
=> Update outdated links

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/configmid.md
- **What's changed?** Added refresh token scopes to these guides
* [OKTA-745365](https://oktainc.atlassian.net/browse/OKTA-745365)
=> OKTA-745365 - Added scopes for refresh token use to SPA guides

packages/@okta/vuepress-site/docs/guides/manage-orgs-okta-aerial/main/index.md
- **What's changed?** Added a note about consent to Aerial guide
* [OKTA-793295](https://oktainc.atlassian.net/browse/OKTA-793295)
=> OKTA-793295 - Add note to create a child org section of Aerial guide

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Release notes for 2024.08.3
- **Is this PR related to a Monolith release?** Yes, 2024.08.3
* [OKTA-744016](https://oktainc.atlassian.net/browse/OKTA-744016)
=> Rn entry 2024.08.3

packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget-deprecated-methods/main/index.md
- **What's changed?**  Updating code example in documentation which had incorrect variable names
* https://github.com/okta/okta-developer-docs/pull/5034/files
=> Recreated PR 5034

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding Release Notes for 2024.08.3
- **Is this PR related to a Monolith release?** Yes, 2024.08.3
* [OKTA-744016](https://oktainc.atlassian.net/browse/OKTA-744016)
=> Release 2024.08.3

packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Edited [Work with Okta session cookies](https://developer.okta.com/docs/guides/session-cookie/main/) to improve Acrolinx score
* [OKTA-794269](https://oktainc.atlassian.net/browse/OKTA-794269)
=> OKTA-794269 Acrolinx improvement edits 

packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md
- **What's changed?**  Deprecate Linked Objects page on Vuepress
- **Is this PR related to a Monolith release?**  possibly 2024.08.3 ? Depends on when Redocly gets published
* [OKTA-740614](https://oktainc.atlassian.net/browse/OKTA-740614)
=> [OKTA-740614] Linked Objects deprecation

packages/@okta/vuepress-theme-prose/components/Hero.vue, packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?** Added developer day timed hero banner on home page.
* [OKTA-793877](https://oktainc.atlassian.net/browse/OKTA-793877)
Preview -
=> [OKTA-793877] : Added timed hero banner for developer day

packages/@okta/vuepress-site/docs/guides/oie-upgrade-sessions-api/main/index.md, packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
- **What's changed?** Edited the [Work with Okta session cookies](https://developer.okta.com/docs/guides/session-cookie/main/) page to improve it's Acrolinx score
* [OKTA-794271](https://oktainc.atlassian.net/browse/OKTA-794271)
=> OKTA-794271 Acrolinx edits for Work with Okta Session cookies

packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- **What's changed?** undeprecate
=> Undeprecate

packages/@okta/vuepress-site/docs/reference/index.md
- **What's changed?** Updated the wording on the banner on the [Reference landing page](https://developer.okta.com/docs/reference/)
* [OKTA-744070](https://oktainc.atlassian.net/browse/OKTA-744070)
=> OKTA-744070 Reference banner update

packages/@okta/vuepress-theme-prose/components/HeaderNavItem.vue, packages/@okta/vuepress-theme-prose/mixins/SidebarItems.vue
- **What's changed?** Added API Docs button in header nav and hamburger menu in mobile view
* [OKTA-798224](https://oktainc.atlassian.net/browse/OKTA-798224)
=> OKTA-798224: Added API Docs button in header nav

packages/@okta/vuepress-theme-prose/components/Home.vue, packages/@okta/vuepress-theme-prose/components/Workforce.vue, packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?**  
1) Update text and show top banner until 30th September 5PM PT
2) Update the link "Explore reference APIs" to point to redocly
* [OKTA-798160](https://oktainc.atlassian.net/browse/OKTA-798160)
* [OKTA-798221](https://oktainc.atlassian.net/browse/OKTA-798221)
=> OKTA-798160 | OKTA-798221 | Update banner and landing page with redocly reference

packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
09-10-24 14:42 EST
https://preview-5057--reverent-murdock-829d24.netlify.app/docs/guides/terraform-enable-org-access/main/
Added section for new requirements for admin scopes
Updated other information
* [OKTA-733720-01-enable-terraform](https://oktainc.atlassian.net/browse/mds/OKTA-704299-Terraform/OKTA-733720-01-enable-terraform)
=> Updated with required admin scopes

packages/@okta/vuepress-site/docs/reference/api/groups/index.md, packages/@okta/vuepress-site/docs/reference/api/linked-objects/index.md, packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?**  Fixed postman links
* [OKTA-803106](https://oktainc.atlassian.net/browse/OKTA-803106)
=> Fixed postman links

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Fix broken links for 2024.09.11
* [OKTA-803560](https://oktainc.atlassian.net/browse/OKTA-803560)
=> OKTA-803560 Fix broken links for 2024.09.11

packages/@okta/vuepress-site/docs/reference/index.md
- **What's changed?** Small style update to banner message
=> Small edit to banner message

packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md, packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md, packages/@okta/vuepress-site/docs/reference/api/brands/index.md, packages/@okta/vuepress-site/docs/reference/api/org/index.md, packages/@okta/vuepress-site/docs/release-notes/2021/index.md, packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Deprecate Org API reference on VuePress and link out to appropriate sections in Redocly.
* [OKTA-755340](https://oktainc.atlassian.net/browse/OKTA-755340)
=> OKTA-755340 Deprecate Org API sections on VuePress

packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Fix Client Role Assignment broken link in Apps API
* [OKTA-805824](https://oktainc.atlassian.net/browse/OKTA-805824)
=> OKTA-805824 Fix Client Role Assignment broken link in Apps API

packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- **What's changed?** Commenting out content on social idp buttons in the `SignUp.vue` script
[OKTA-806218](https://oktainc.atlassian.net/browse/OKTA-806218)
=> Remove social idp buttons on signup

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?**  Release notes
- **Is this PR related to a Monolith release?**  2024.09.1
* [OKTA-794253](https://oktainc.atlassian.net/browse/OKTA-794253)
=> Rn entry release 2024.09.1

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
=> Rn entry release 2024.09.1 (#5076)

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?**  Header fix
- **Is this PR related to a Monolith release?**  2024.09.1
=> Fixed release note header

packages/@okta/vuepress-site/conductor.yml, packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md, packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md, packages/@okta/vuepress-site/docs/reference/token-hook/index.md, packages/@okta/vuepress-site/docs/release-notes/2019/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** deprecate token inline hook reference on vuepress
* [OKTA-806921](https://oktainc.atlassian.net/browse/OKTA-806921)
=> deprecate token inline hook reference on vuepress

packages/@okta/vuepress-site/conductor.yml, packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md, packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md, packages/@okta/vuepress-site/docs/release-notes/2020/index.md, packages/@okta/vuepress-site/docs/release-notes/2021/index.md, packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2022/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Deprecates the Trusted Origins API docs
* [OKTA-807264](https://oktainc.atlassian.net/browse/OKTA-807264)
=> Trusted Origins API deprecation

packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
- **What's changed?**  Some acrolinx fixes
* [OKTA-804951](https://oktainc.atlassian.net/browse/OKTA-804951)
=> OKTA-804951 Clarity for "Redirect vs embedded"

packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- **What's changed?** Improves the clarity score of the custom sign-in page guide
* [OKTA-751039](https://oktainc.atlassian.net/browse/OKTA-751039)
=> Custom sign-in page: improve clarity score

packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md, packages/@okta/vuepress-site/docs/reference/api/archive-myaccount/index.md, packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md, packages/@okta/vuepress-site/docs/reference/api/policy/index.md, packages/@okta/vuepress-site/docs/reference/api/schemas/index.md, packages/@okta/vuepress-site/docs/reference/api/user-types/index.md, packages/@okta/vuepress-site/docs/reference/api/users/index.md, packages/@okta/vuepress-site/docs/release-notes/2019/index.md, packages/@okta/vuepress-site/docs/release-notes/2020/index.md, packages/@okta/vuepress-site/docs/release-notes/2021/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js, tests/cypress/integration/tree_nav_spec.js
- **What's changed?** Deprecating the User Types API page
* [OKTA-806759](https://oktainc.atlassian.net/browse/OKTA-806759)
=> User Types API deprecation

packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-site/docs/guides/terraform-create-custom-auth-server/index.md, packages/@okta/vuepress-site/docs/guides/terraform-create-custom-auth-server/main/index.md, packages/@okta/vuepress-site/docs/guides/terraform-syntax-tips/main/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
09-19-24 18:25 Eastern 
https://preview-5075--reverent-murdock-829d24.netlify.app/docs/guides/terraform-create-custom-auth-server/main/
- Add "Create a custom authorization server", a new Terraform article
- Update "Terraform syntax tips for automation" with a change that was approved in review but didn't get committed before merging
* [OKTA-733727](https://oktainc.atlassian.net/browse/OKTA-733727)
=> Initial commit

packages/@okta/vuepress-site/conductor.yml, packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md, packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md, packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md, packages/@okta/vuepress-site/docs/reference/api/roles/index.md, packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Roles deprecation on Vuepress
- **Is this PR related to a Monolith release?**  none
* [OKTA-804327](https://oktainc.atlassian.net/browse/OKTA-804327)
=> Roles API deprecation

packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?**  Description added to examples, also added more info about schemas
* [OKTA-802677](https://oktainc.atlassian.net/browse/OKTA-802677)
=> [OKTA-802677] Updates to SCIM 2.0 with entitlements

packages/@okta/vuepress-site/conductor.yml, packages/@okta/vuepress-site/docs/guides/build-api-integration/main/index.md, packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md, packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-sso-app/index.md, packages/@okta/vuepress-site/docs/guides/submit-sso-app/main/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Update text to deprecate edit SSO in OIN Manager use case
- **Is this PR related to a Monolith release?** 2024.09.0 (no RN ticket was produced, devdoc work delayed)
* [OKTA-710607](https://oktainc.atlassian.net/browse/OKTA-710607)
=> OKTA-710607 Deprecate SSO in OIN Manager

packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
- **What's changed?** Small update to improve clarity score.
* [OKTA-751029](https://oktainc.atlassian.net/browse/OKTA-751029)
=> Embedded SIW guide - Acrolinx clarity score update

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** The blurbz
- **Is this PR related to a Monolith release?** Yes. 2024.09.2
=> RN entry release 2024.09.2

packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/aspnet/challengeintegrationsteps.md, packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/aspnet/enrollmentintegrationsteps.md, packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/index.md, packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/challengeintegrationsteps.md, packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/java/enrollmentintegrationsteps.md, packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/nodeexpress/challengeintegrationsteps.md, packages/@okta/vuepress-site/docs/guides/authenticators-google-authenticator/main/nodeexpress/enrollmentintegrationsteps.md
- **What's changed?** Makes changes to improve the Acrolinx clarity scores of all files in the guide
* [OKTA-751152](https://oktainc.atlassian.net/browse/OKTA-751152)
=> Google authenticator guide: Acrolinx clarity score

packages/@okta/vuepress-site/docs/reference/system-log-query/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** As part of the THI API migration process, moving a significant amount of existing instructional text from the VuePress [System Log API](https://developer.okta.com/docs/reference/api/system-log/) to a new guide that will appear in the reference section. 
* [OKTA-809423](https://oktainc.atlassian.net/browse/OKTA-809423)
=> OKTA-809423 - Create system log query guide

.github/CODEOWNERS
=> Adding codeowner

packages/@okta/vuepress-site/docs/reference/classic-engine/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  trying to trigger build by making a minor change
- **Is this PR related to a Monolith release?**  no
=> Made small change to trigger build

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Add 2024.09.3 release note bug
- **Is this PR related to a Monolith release?** Yes, 2024.09.3
* [OKTA-794275](https://oktainc.atlassian.net/browse/OKTA-794275)
=> OKTA-794275 Add 2024.09.3 entry

packages/@okta/vuepress-theme-prose/mixins/SidebarItems.vue
* [OKTA-813763](https://oktainc.atlassian.net/browse/OKTA-813763)
=> OKTA-813763: Reverted API Docs header change

packages/@okta/vuepress-site/docs/reference/index.md
=> Broken link

packages/@okta/vuepress-site/docs/reference/index.md
=> Removed banner from Reference overview page.

packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md, packages/@okta/vuepress-site/docs/concepts/policies/index.md, packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md, packages/@okta/vuepress-site/docs/guides/step-up-authentication/main/index.md
- **What's changed?** Changed "identity provider" to "IdP" and "OpenID Connect" to "OIDC" 
* [OKTA-813670](https://oktainc.atlassian.net/browse/OKTA-813670)
=> Add IdP and OIDC acronyms where appropriate

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Update OIN catalog use case categories to current okta.com/integrations
* [OKTA-814729](https://oktainc.atlassian.net/browse/OKTA-814729)
=> OKTA-814729 Update OIN catalog use case categories

packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
- **What's changed?**  Added a note about strings in profile for XaaS
* [OKTA-807736](https://oktainc.atlassian.net/browse/OKTA-807736)
=> [OKTA-807736] Limitations in XaaS

packages/@okta/vuepress-site/docs/concepts/scim/index.md
- **What's changed?**  Add more info about how updates work in SCIM
* [OKTA-809878](https://oktainc.atlassian.net/browse/OKTA-809878)
=> [OKTA-809878] Clarify SCIM update

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Release notes for 2024.09.3
- **Is this PR related to a Monolith release?** Yes, 2024.09.3
* [OKTA-794275](https://oktainc.atlassian.net/browse/OKTA-794275)
=> OKTA-794275 Release notes for 2024.09.3

packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
- **What's changed?** Improved the Acrolinx score for the [External IdPs page](https://developer.okta.com/docs/concepts/identity-providers/)
* [OKTA-751120](https://oktainc.atlassian.net/browse/OKTA-751120)
=> OKTA 751120 Acrolinx edits for External IdPs

packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- **What's changed?** Improved the Acrolinx score for the [Inline hooks page](https://developer.okta.com/docs/concepts/inline-hooks/)
* [OKTA-794553](https://oktainc.atlassian.net/browse/OKTA-794553)
=> OKTA 794553 - Acrolinx edit for Inline hooks

packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?**  Link fix
- **Is this PR related to a Monolith release?**  none
* [OKTA-816454](https://oktainc.atlassian.net/browse/OKTA-816454)
=> OKTA-816454 broken link

packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **Is this PR related to a Monolith release?**  none
* [OKTA-816454](https://oktainc.atlassian.net/browse/OKTA-816454)
=> Another link

packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/download-sample.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/intro.md
- Updated sample version numbers in guide to reflect current sample
* [OKTA-506229](https://oktainc.atlassian.net/browse/OKTA-506229)
=> OKTA-506229 Updated version numbers for Angular SIW sample

packages/@okta/vuepress-site/docs/guides/validate-id-tokens/main/index.md
- **What's changed?**  Acrolinx updates
* [OKTA-812814](https://oktainc.atlassian.net/browse/OKTA-812814)
=> [OKTA-812814] ID tokens

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Some acrolinx fix, some notes added, clarifying text
* [OKTA-805433](https://oktainc.atlassian.net/browse/OKTA-805433)
* [OKTA-806255](https://oktainc.atlassian.net/browse/OKTA-806255)
=> [OKTA 806255/805433] Expression language fixes

.github/CODEOWNERS
- Adds Ishan and Madhuri to code owners list
=> Adds Ishan and Madhuri

packages/@okta/vuepress-site/docs/concepts/role-assignment/index.md
- **What's changed?** Link Roles > Permissions to Redocly for one source
* [OKTA-752113](https://oktainc.atlassian.net/browse/OKTA-752113)
=> OKTA-752113 Update permissions and link out to Redocly

packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
- **What's changed?** Removed category heading and xrefs.
* [OKTA-818938](https://oktainc.atlassian.net/browse/OKTA-818938)
=> OKTA-818938 - Rate Limits overview minor update

packages/@okta/vuepress-site/docs/reference/rest/index.md
- **What's changed?** One UI update and minor formating updates to this section: https://developer.okta.com/docs/reference/rest/#get-an-access-token-and-make-a-request
*n/a
=> Very minor updates to Test APIs with Postman

packages/@okta/vuepress-site/docs/guides/dpop/main/index.md, packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/claims.md, packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/diagram.md, packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/glitch.md, packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/iat.md, packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/payload.md, packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/requestresource.md, packages/@okta/vuepress-site/docs/guides/dpop/main/nonoktaresourceserver/whatyouneed.md, packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/claims.md, packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/diagram.md, packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/iat.md, packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/payload.md, packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/requestresource.md, packages/@okta/vuepress-site/docs/guides/dpop/main/oktaresourceserver/whatyouneed.md
- **What's changed?** DPoP updates
- **Is this PR related to a Monolith release?** no 
netlify link: https://preview-5094--reverent-murdock-829d24.netlify.app/docs/guides/dpop/nonoktaresourceserver/main/
* [OKTA-798996](https://oktainc.atlassian.net/browse/OKTA-798996)
=> DPoP updates

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md
- **What's changed?** Re-adds link to RN blurb
- **Is this PR related to a Monolith release?** Yes. 2024.10.0
* [OKTA-818505](https://oktainc.atlassian.net/browse/OKTA-818505)
=> Re-add link to blurb in 2024.10.0 release notes

packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/download-sample.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/basic-sign-in.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/sign-in-form.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/sign-in-form.md
- **What's changed?** Adding `offline_access` scope to the three guides
* [OKTA-800843](https://oktainc.atlassian.net/browse/OKTA-800843)
=> OKTA-800843 - Updated embedded auth SPA guides

packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
- **What's changed?** upped the clarity score for Customize tokens groups claim
=> clarity update

packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
- **What's changed?** adding group sync to OIDC IdP
- **Is this PR related to a Monolith release?** yes 2024.10.01
* [OKTA-815335](https://oktainc.atlassian.net/browse/OKTA-815335)
=> add OIDC to group sync support

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding OIE and Classic release notes for the `2024.10.1` release
- **Is this PR related to a Monolith release?** `2024.10.1`
* [OKTA-794288](https://oktainc.atlassian.net/browse/OKTA-794288)
=> Rn entry 2024.10.1

packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
- **What's changed?**  Clarity updates for create an auth server
=> clarity updates

packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
- **What's changed?** clarity work 
=> clarity work

packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding docs and release notes for weekly release
- **Is this PR related to a Monolith release?** `2024.10.1`
* [OKTA-794288](https://oktainc.atlassian.net/browse/OKTA-794288)
=> Release notes for weekly

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/addconfigpkg.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/handlecallback.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/reqautheverything.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/reqauthspecific.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/addconfigpkg.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/testapp.md
- **What's changed?** Updated shared index file (clarity 100) and reviewed all individual language-specific files for clarity.
* [OKTA-751037](https://oktainc.atlassian.net/browse/OKTA-751037) and [OKTA-7501040](https://oktainc.atlassian.net/browse/OKTA-751040)
=> OKTA-751037 - Sign In To Spa Redirect and Angular

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Updated the formats and clarified the URL for the User grant release note for `2024.10.1`
* n/a
=> Update formatting and URL for release note

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/configmid.md
- **What's changed?** Updated scopes as per @alisaduncan PR #5162 
* n/a
=> Align scopes with samples for React and Angular

packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/prep.md, packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/see-also.md
- **What's changed?** Some words, phrases... for Acrolinx
* [OKTA-751031](https://oktainc.atlassian.net/browse/OKTA-751031)
=> OTKA-751031 build-sso-integration > saml2 Acrolinx improvements

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appatidp.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/createidpnote.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appatidp.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appatidp.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/accountlinking2.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appatidp.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- **What's changed?** Improved the Acrolinx scores for the Enterprise IdP page
* [OKTA-819058](https://oktainc.atlassian.net/browse/OKTA-819058)
=> OKTA-819058 Acrolinx edits on Enterprise IdP page

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- **What's changed?** Revert changes to headings from an [earlier PR](https://github.com/okta/okta-developer-docs/pull/5168) to avoid issues with any conductor links and links from other pages
=> Revert change to headings from earlier PR

.github/acrolinx/global-config.edn
- **What's changed?** dropping score for Brian
=> dropping score for Brian

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/addconfigpkg.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/redirectvalues.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/reqautheverything.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/reqauthspecific.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/specificlinks.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/testapp.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/useaccesstoken.md
- **What's changed?** As per Alisa's PR, update the SPA VuePress guide: https://github.com/okta/okta-developer-docs/pull/5170 
* n/a
=> Update VuePress SPA Guide

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/addconfigpkg.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/redirectvalues.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/reqautheverything.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/reqauthspecific.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/specificlinks.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/testapp.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/useaccesstoken.md
- **What's changed?** Vue quickstart updates to match sample updates.
The Vue updates became larger than expected due to toolchain changes.
=> Update Vue quickstart guide to match sample updates

.github/acrolinx/global-config.edn
- **What's changed?** putting the score back
=> putting the score back

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding Release Notes for 2024.11.0
- **Is this PR related to a Monolith release?** Yes. Release Notes 2024.11.0
* [OKTA-794280](https://oktainc.atlassian.net/browse/OKTA-794280)
=> OKTA-794280 2024.11.0 Monthly release

packages/@okta/vuepress-site/docs/concepts/scim/index.md
- **What's changed?**  Clarification to the Update section about active attribute
* [OKTA-796859](https://oktainc.atlassian.net/browse/OKTA-796859)
=> OKTA-796859 SCIM update

packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** And "Navigate to Test integrations page" in the oIN Wizard
- **Is this PR related to a Monolith release?** Yes, 2024.11.0
* [OKTA-809675](https://oktainc.atlassian.net/browse/OKTA-809675)
=> OKTA-809675 OIN Wizard - Navigate to Test integrations page

packages/@okta/vuepress-site/docs/reference/api/factors/index.md, packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** Comment out the VuePress Factors API content and update a link 
* [OKTA-828126](https://oktainc.atlassian.net/browse/OKTA-828126)
=> Hide Factors API and update one link

.github/acrolinx/global-config.edn
- **What's changed?** lowering score for Brent's PR
=> lowering score for Brent's PR

packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/redirectvalues.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/samplecode.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/android/testapp.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/addconfigpkg.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/opensignin.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/refresh.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/samplecode.md, packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/ios/testapp.md
- **What's changed?** Improves overall Acrolinx score (especially Clarity score) for mobile redirect guide.
* [OKTA-751130](https://oktainc.atlassian.net/browse/OKTA-751130)
=> Acrolinx clarity score: mobile redirect guide

.github/acrolinx/global-config.edn
- **What's changed?** raise score
=> raise score

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Add post release bugs or features
- **Is this PR related to a Monolith release?** Yes, 2024.11.0
* [OKTA-826953](https://oktainc.atlassian.net/browse/OKTA-826953)
=> Add post release bugs or features

packages/@okta/vuepress-site/copyright/index.md
- **What's changed?** Removed the link that was failing which matches all other copyright references
* [OKTA-832187 ](https://oktainc.atlassian.net/browse/OKTA-832187 )
=> OKTA-832187 - Update copyright page to remove broken link

packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md, packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?**Update OIN docs for migrated SCIM integrations
- **Is this PR related to a Monolith release?** Yes, after 2024.11.0. 2024-11-14: OK12 deployed with SCIM in OIN Wizard. 2024-11-15: OIN Ops reject new SCIM submissions.
* [OKTA-830415](https://oktainc.atlassian.net/browse/OKTA-830415)
=> OKTA-830415 Updates for migrated SCIM integrations

packages/@okta/vuepress-site/.vuepress/config.js, packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-prepare/main/index.md
- **What's changed?** Removed drop-down link to Toolkit, and removed one reference to the site.
* [OKTA-833857](https://oktainc.atlassian.net/browse/OKTA-833857)
=> OKTA-833857 - Removed link to Toolkit

scripts/setup.sh
- Recent security update for package is not compatible with platform. We've checked on CCI that we can suppress the warning and build works fine.
* [OKTA-834107](https://oktainc.atlassian.net/browse/OKTA-834107)
=> Ignores platform

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- **What's changed?** Switching steps to use the UI to assign admin roles
* [OKTA-808873](https://oktainc.atlassian.net/browse/OKTA-808873)
=> Switching steps to use the UI to assign admin roles

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Adding Release Notes for 2024.11.2
- **Is this PR related to a Monolith release?** Yes, 2024.11.2
* [OKTA-794297](https://oktainc.atlassian.net/browse/OKTA-794297)
=> RN entries 2024.11.2

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md, yarn.lock
- **What's changed?** Adding Release Notes for 2024.11.2
- **Is this PR related to a Monolith release?** Yes, 2024.11.2
* [OKTA-794297](https://oktainc.atlassian.net/browse/OKTA-794297)
=> Release 2024.11.2

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Updates the concept content of the functions section to include examples.
* [OKTA-797547](https://oktainc.atlassian.net/browse/OKTA-797547)
=> Custom email templates: add function explanation and examples

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?**  Release note entries for 2024.12.0 monthly
- **Is this PR related to a Monolith release?**  2024.12.0
* [OKTA-794282](https://oktainc.atlassian.net/browse/OKTA-794282)
=> 2024.12.0 release notes

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/afterappidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/azure/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/afterappidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/oktatookta/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/afterappidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- **What's changed?** Update automatic account linking for OIDC and SAML generic IdPs
- **Is this PR related to a Monolith release?** Yes, 2024.12.0
* [OKTA-822501](https://oktainc.atlassian.net/browse/OKTA-822501)
=> OKTA-822501 - Add account linking condition features

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Add new Use Cases field in OIN Wizard and automatic use case assignment
- **Is this PR related to a Monolith release?** Yes, 2024.12.0
* [OKTA-795656](https://oktainc.atlassian.net/browse/OKTA-795656)
=> OKTA-795656 OIN Wizard: new Use Cases field and automatic use case assignment

falsepos.txt
- **What's changed?** Cleaning up falsepos.txt file and adding two new references; removed several URLs that have been removed.
* n/a
=> Updating falsepos file

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Add SAML SP SLO not supported in OIN prerequisites > OIN SAML limitations.
* [OKTA-838336](https://oktainc.atlassian.net/browse/OKTA-838336)
=> OKTA-838336 Add SAML SP SLO not supported

packages/@okta/vuepress-theme-prose/assets/css/components/_sidebar.scss, packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_sideBar.scss
Variant of https://github.com/okta/okta-developer-docs/pull/5239
* [OKTA-842993](https://oktainc.atlassian.net/browse/OKTA-842993)
=> OKTA-842993 | Fix left TOC topic indicator in dev.okta.com - with font-weight

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/addconfigpkg.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/handlecallback.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/reqautheverything.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/reqauthspecific.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/specificlinks.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/testapp.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/useaccesstoken.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
- **What's changed?** Updates to Angular SPA Redirect Guide, as per this PR: https://github.com/okta/okta-developer-docs/pull/5237/files
* [OKTA-837257](https://oktainc.atlassian.net/browse/OKTA-837257)
=> OKTA-837257 - Updates to Angular SPA Redirect Guide

packages/@okta/vuepress-site/code/index.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/install-sdk.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/install-sdk.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/clientcreds/install-sdk.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/install-sdk.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/install-sdk.md
- **What's changed?** Updating several references to the old Languages & SDKs title
* [OKTA-844421 ](https://oktainc.atlassian.net/browse/OKTA-844421 )
=> OKTA-844421 - Update xref text

packages/@okta/vuepress-site/docs/reference/postman-collections/index.md, packages/@okta/vuepress-site/docs/reference/rest/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  Notes and updates link for the postman-collections file, remove from left-nav TOC
* [OKTA-847065](https://oktainc.atlassian.net/browse/OKTA-847065)
=> [OKTA-847065] Note to Postman Collections page

packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md, packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md, packages/@okta/vuepress-site/docs/guides/federated-claims/index.md, packages/@okta/vuepress-site/docs/guides/federated-claims/main/index.md, packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** New guide on creating entitlements and inserting into ID tokens and SAML assertions. Expression Language page update to include entitlements
- **Is this PR related to a Monolith release?** yes 2024.12.1
Netlify links: 
**Guide**: https://preview-5201--reverent-murdock-829d24.netlify.app/docs/guides/federated-claims/main/
**EL update**: https://preview-5201--reverent-murdock-829d24.netlify.app/docs/reference/okta-expression-language-in-identity-engine/
**Customize tokens returned from Okta with custom claims**: https://preview-5201--reverent-murdock-829d24.netlify.app/docs/guides/customize-tokens-returned-from-okta/main/#about-tokens-with-custom-claims
**Customize tokens returned from Okta with a groups claim**: …
=> Federated claims and entitlements

packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md
- **What's changed?** Updates to weekly release notes to Classic and OIE API
- **Is this PR related to a Monolith release?** `2024.12.1`
* [OKTA-818824](https://oktainc.atlassian.net/browse/OKTA-818824)
=> OKTA-818824 - Weekly Release Notes

.github/acrolinx/global-config.edn
- **What's changed?** Lowering score to 70 to merge React SPA Guide, PR #5263
*n/a
=> Temp score change for acrolinx

.github/acrolinx/global-config.edn
- **What's changed?** Returned acrolinx score to 80
* n/a
=> Return acrolinx score

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**Rn entry 2025.01.0 
- **Is this PR related to a Monolith release?** yes  2025.01.0
* [OKTA-844488](https://oktainc.atlassian.net/browse/OKTA-844488)
=> Rn entry 2025.01.0

packages/@okta/vuepress-site/docs/guides/submit-app-overview/index.md, packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Add notes about not using prod env for Dev orgs
* [OKTA-845930](https://oktainc.atlassian.net/browse/OKTA-845930)
=> OKTA-845930 Add notes about not using prod env for Dev orgs

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Fix broken internal link
- **Is this PR related to a Monolith release?** `2024.01.0`
* n/a
=> RNs - fix broken internal link

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Recommend ISVs to delete the test account within 30 days of being Okta Verified.
* [OKTA-851282](https://oktainc.atlassian.net/browse/OKTA-851282)
=> OKTA-851282 Update test account lifespan note for OIN

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Adding Release Notes for 2025.01.1
- **Is this PR related to a Monolith release?** Yes, 2025.01.1
* [OKTA-844510](https://oktainc.atlassian.net/browse/OKTA-844510)
=> RN entry 2025.01.1

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Adding Release Notes for 2025.01.1
- **Is this PR related to a Monolith release?** Yes, 2025.01.1
* [OKTA-844510](https://oktainc.atlassian.net/browse/OKTA-844510)
=> Release 2025.01.1

packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md, packages/@okta/vuepress-site/docs/reference/user-query/index.md
- **What's changed?**  Fix formatting and lowercase objects
* [OKTA-850793](https://oktainc.atlassian.net/browse/OKTA-850793)
=> OKTA-850793 lowercasing objects

packages/@okta/vuepress-site/docs/guides/scim-provisioning-integration-test/main/index.md
- **What's changed?** Add OIN profile sourcing note in Test a private SCIM integration
* [OKTA-852775](https://oktainc.atlassian.net/browse/OKTA-852775)
=> OKTA-852775 Add OIN profile sourcing note

packages/@okta/vuepress-site/docs/guides/create-an-api-token/main/index.md
- **What's changed?** Update to any Okta org for Create an API token topic
* [OKTA-755287](https://oktainc.atlassian.net/browse/OKTA-755287)
=> OKTA-755287 Update to any Okta org for Create an API token topic

packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- **What's changed?** Updates property name from `factors` to `factor`
* [OKTA-847904](https://oktainc.atlassian.net/browse/OKTA-847904)
=> AuthN API: Fixes factors typo

packages/@okta/vuepress-site/docs/guides/device-assurance-policies/main/index.md
- **What's changed?** Fixes a small typo
=> Device Assurance Policy API guide: typo

.circleci/config.yml
Move to new orb that has an up-to-date definition of the Semgrep job.
=> Fix semgrep jobs

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Adds campaign-specific variables to the email customizations guide
* [OKTA-817893](https://oktainc.atlassian.net/browse/OKTA-817893)
=> Email customizations: add campaign-specific variables

packages/@okta/vuepress-site/docs/release-notes/archive/index.md, packages/@okta/vuepress-site/docs/release-notes/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  Set up archive for release notes
* [OKTA-856135](https://oktainc.atlassian.net/browse/OKTA-856135)
=> [OKTA-856135] Archive

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?**  Release notes entries
- **Is this PR related to a Monolith release?**  2025.01.2
* [OKTA-844514](https://oktainc.atlassian.net/browse/OKTA-844514)
=> [OKTA-844514] 2025.01.2 Release Notes

packages/@okta/vuepress-site/copyright/index.md
- **What's changed?**  Update copyright year to 2025 
* [OKTA-859160](https://oktainc.atlassian.net/browse/OKTA-859160)
=> OKTA-859160 Copyright year

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- **What's changed?**  Added bug from OKTA-848066
- **Is this PR related to a Monolith release?**  2025.01.2
* [OKTA-844514](https://oktainc.atlassian.net/browse/OKTA-844514)
=> RN update for 2025.01.2

falsepos.txt
- **What's changed?** Addition of https://jwt.io to false positive list
* n/a
=> Update to false positives list

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- **What's changed?** remove EA tag for Account Link SAML
- **Is this PR related to a Monolith release?** Yes 2025.02.0
* [OKTA-859217](https://oktainc.atlassian.net/browse/OKTA-859217)
=> remove EA tag for Account Link SAML

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Release Note draft
- **Is this PR related to a Monolith release?** `2025.02.0`
* [OKTA-850925](https://oktainc.atlassian.net/browse/OKTA-850925)
=> OKTA-850925 - Release Note Entry 2025.02.0

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
* [OKTA-865169](https://oktainc.atlassian.net/browse/OKTA-865169)
=> Aj okta 865169 rn date

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** In the RNs, update the link for Developer Documentation updates
- **Is this PR related to a Monolith release?** `2024.02.0`
* n/a
=> Minor fix to links

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md, packages/@okta/vuepress-site/docs/release-notes/archive/index.md, packages/@okta/vuepress-site/docs/release-notes/archive/oig-changelog.md, packages/@okta/vuepress-site/docs/release-notes/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
=> Mock up of IGA Changelog

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
- **What's changed?** Fixing broken link
* n/a
=> Update IGA archive URL

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Release note entry branch
- **Is this PR related to a Monolith release?** Yes. 2025.02.1
=> Rn entry release 2025.02.1

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Devdocs release branch
- **Is this PR related to a Monolith release?** Yes. 2025.02.1
* [OKTA-850926](https://oktainc.atlassian.net/browse/OKTA-850926)
=> Release 2025.02.1

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
- **What's changed?** Updating IGA release notes to fix 404s.
* n/a
=> Revise URLs for IGA RNs

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
- **What's changed?** Fixing IGA URLs
* n/a
=> Update URLs one more time

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Updated OIN limitations for SPA 
* [OKTA- 863416](https://oktainc.atlassian.net/browse/OKTA-863416)
=> Update OIN limitations - SPA

packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Updates link
* [OKTA-871484](https://oktainc.atlassian.net/browse/OKTA-871484)
=> Expression Language for OIE: Update OAMP link

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Recreate PR #5334 (Previously approved by SME and editor)
=> Recreate PR 5334

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Add 2025.02.2 release note entries
- **Is this PR related to a Monolith release?** Yes, 2025.02.2
* [OKTA-850946](https://oktainc.atlassian.net/browse/OKTA-850946)
=> OKTA-850946 Add 2025.02.2 release note entries

packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md, yarn.lock
- **What's changed?**  Bring back a page from the dead 💀 
* [OKTA-876093](https://oktainc.atlassian.net/browse/OKTA-876093)
=> Aj okta 876093 Fix deleted page

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** 2025.02.2 Release Notes
- **Is this PR related to a Monolith release?** Yes, 2025.02.2
* [OKTA-850946](https://oktainc.atlassian.net/browse/OKTA-850946)
=> OKTA-850946 2025.02.2 Release Notes

packages/@okta/vuepress-theme-prose/components/DocsMenuItems.vue, packages/@okta/vuepress-theme-prose/components/Sidebar.vue, packages/@okta/vuepress-theme-prose/global-components/SignUp.vue, packages/@okta/vuepress-theme-prose/layouts/SignUpLayout.vue
* [OKTA-870469](https://oktainc.atlassian.net/browse/OKTA-870469)
=> OKTA-870469 | ISV Facing CORS issue on Developer Account Signup Page

packages/@okta/vuepress-site/docs/reference/rl-clientbased/index.md
- **What's changed?** Removing IDX endpoints 
* [OKTA-854553](https://oktainc.atlassian.net/browse/OKTA-854553)
=> OKTA-854553 - Update clientbased rate limiting doc

packages/@okta/vuepress-site/code/index.md
- **What's changed?** As per Alisa's forked PR: https://github.com/okta/okta-developer-docs/pull/5346
*n/a
=> AD - Update SPA quickstart links

packages/@okta/vuepress-site/code/index.md
- **What's changed?** Updates the links in this top-level site for SPA samples to match the sample links in their respective quickstarts
=> Update SPA quickstart links

packages/@okta/vuepress-site/docs/guides/app-provisioning-connection/main/index.md
- **What's changed?**  Update links to Redocly API reference and repeat examples for clarity
* [OKTA-885956](https://oktainc.atlassian.net/browse/OKTA-885956)
=> OKTA-885956 Set up an app provisioning connection - updates

packages/@okta/vuepress-site/.vuepress/config.js
=> Added HOC link

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md, yarn.lock
- **What's changed?** Adding Release Notes for 2025.03.0
- **Is this PR related to a Monolith release?** Yes. Release Notes 2025.03.0
* [OKTA-869706](https://oktainc.atlassian.net/browse/OKTA-869706)
=> Rn entry release 2025.03.0

packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- **What's changed?** Update placement of **Public client app admins** org setting in Implement OAuth for Okta with service app guide.
* [OKTA-887171](https://oktainc.atlassian.net/browse/OKTA-887171)
=> OKTA-887171 Public client app admins org setting - update placement

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md, yarn.lock
- **What's changed?** Adding Release Notes for 2025.03.0
- **Is this PR related to a Monolith release?** Yes. Release 2025.03.0 
* [OKTA-869706](https://oktainc.atlassian.net/browse/OKTA-869706)
=> OKTA-869706:Adding dev doc updates to RN entry

packages/@okta/vuepress-site/3rd_party_notices/Okta_Auth_SDK/index.md, packages/@okta/vuepress-site/3rd_party_notices/Okta_Sign-In_Widget/index.md
- **What's changed?** Updated the Okta Auth JS and SIW licenses as discussed.
* [OKTA-887213](https://oktainc.atlassian.net/browse/OKTA-887213)
=> OKTA-887213 - Update 3rd-party licenses

packages/@okta/vuepress-site/docs/reference/rl-best-practices/index.md
- **What's changed?** Revised [Request rate limit exceptions](https://developer.okta.com/docs/reference/rl-best-practices/#request-rate-limit-exceptions) section as per PM.
* [OKTA-814631](https://oktainc.atlassian.net/browse/OKTA-814631)
=> OKTA-814631 - Rate Limits Best Practices - Update request exception

packages/@okta/vuepress-site/docs/concepts/policies/index.md, packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
- **What's changed?** name update
* [OKTA-887981](https://oktainc.atlassian.net/browse/OKTA-887981)
=> Updating post auth session to session protection policy

packages/@okta/vuepress-site/docs/concepts/scim/index.md
- **What's changed?**  Clarity on SCIM server and client
* [OKTA-888144](https://oktainc.atlassian.net/browse/OKTA-888144)
=> OKTA-888144 SCIM server/client

packages/@okta/vuepress-site/docs/guides/dpop/main/index.md
- **What's changed?** fix jti and add text around replay attack
* [OKTA-876299](https://oktainc.atlassian.net/browse/OKTA-876299)
=> fix jti and add text around replay attack

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- **What's changed?** Add Release Note entries
- **Is this PR related to a Monolith release?** Yes, Release 2025.03.0
* [OKTA-887971](https://oktainc.atlassian.net/browse/OKTA-887971)
=> OKTA-887971: Add Release Note entries

packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
- **What's changed?** Explain auth code behavior with groups claim and ID tokens
* [OKTA-889003](https://oktainc.atlassian.net/browse/OKTA-889003)
=> Explain auth code behavior with groups claim and ID tokens

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** rn entry 2025.03.1
- **Is this PR related to a Monolith release?** Yes2025.03.1
* [OKTA-869709](https://oktainc.atlassian.net/browse/OKTA-869709)
=> rn entry 2025.03.1

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Release 2025.03.1
- **Is this PR related to a Monolith release?** Yes 2025.03.1
* [OKTA-869709](https://oktainc.atlassian.net/browse/OKTA-869709)
=> Release 2025.03.1

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Remove OKTA-856262 entry from 2025.03.0 Release Notes (Doc Action request)
* [OKTA-896365](https://oktainc.atlassian.net/browse/OKTA-896365)
=> Remove OKTA-856262 entry from Release Notes

packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- Adding a link and pointer towards the request body example from the telephony hook API reference
- UI and key term naming updates
* [OKTA-877160](https://oktainc.atlassian.net/browse/OKTA-877160)
=> OKTA-877160 Telephony guide update

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?**  Add release notes entries for 2025.03.2
- **Is this PR related to a Monolith release?**  2025.03.2
* [OKTA-869711](https://oktainc.atlassian.net/browse/OKTA-869711)
=> RN entries for 2025.03.2

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- **What's changed?** Feature GA blurb removed from March monthly release
- **Is this PR related to a Monolith release?** 2025.03.0 and 2025.04.0
* [OKTA-901415](https://oktainc.atlassian.net/browse/OKTA-901415)
=> OAMP GA: Remove blurb from 2025.03.0 release

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** RN entries for 2025.03.3 release
- **Is this PR related to a Monolith release?** Yes, 2025.03.3
* [OKTA-869712](https://oktainc.atlassian.net/browse/OKTA-869712)
=> RN entry 2025.03.3

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Remove OKTA-835402 from 2025.03.2 RN
* [OKTA-906465](https://oktainc.atlassian.net/browse/OKTA-906465)
=> Remove OKTA-835402 from 2025.03.2 RN - Doc action request

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Release note blurb branch
- **Is this PR related to a Monolith release?** 2025.04.0
=> Rn entry release 2025.04.0

packages/@okta/vuepress-site/docs/guides/federated-claims/main/index.md
- **What's changed?** removed EA flag
- **Is this PR related to a Monolith release?** Yes 2025.04.0
=> removed EA flag

packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- **What's changed?** Org2Org with OAuth2.0 Enabled Provisioning enhancements
- **Is this PR related to a Monolith release?** Yes, (see Account Services team: Richard Chan, Thanh-Ha) - `2025.04.0`
* [OKTA-838079](https://oktainc.atlassian.net/browse/OKTA-838079)
=> OKTA-838079 Org2Org provisioning enhancement updates

packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- **What's changed?** Adds a description of the new `useSiwGen3` variable.
- **Is this PR related to a Monolith release?** Yes. 2025.04.0
* [OKTA-898852](https://oktainc.atlassian.net/browse/OKTA-898852)
=> SIW (Gen2 and Gen3): Add description of new useSiwGen3 variable

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Add RN entry to 2025.03.3 release notes
- **Is this PR related to a Monolith release?** Yes, 2025.03.3
=> Add RN entry to 2025.03.3

packages/@okta/vuepress-site/.vuepress/config.js, packages/@okta/vuepress-theme-prose/components/Home.vue, packages/@okta/vuepress-theme-prose/components/Resources.vue, packages/@okta/vuepress-theme-prose/components/Support.vue, packages/@okta/vuepress-theme-prose/components/Workforce.vue
- **What's changed?** removing wic
Netlify link: https://preview-5381--reverent-murdock-829d24.netlify.app/
* [OKTA-904279](https://oktainc.atlassian.net/browse/OKTA-904279
=> removing wic

packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
* Update integration variable limit increase
* Remove: `Note: If you need to edit more than three variables for a published integration, contact the OIN team at [oin@okta.com](mailto:oin@okta.com).`
- **Is this PR related to a Monolith release?** Yes, 2025.04.0
* [OKTA-906911](https://oktainc.atlassian.net/browse/OKTA-906911)
=> Update integration variable limit increase

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Update Okta Browser Plugin version in OIN Wizard test requirements.
* [OKTA-883116](https://oktainc.atlassian.net/browse/OKTA-883116)
=> OKTA-883116: Update Okta Browser Plugin version

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Added weekly release notes
- **Is this PR related to a Monolith release?** `2025.04.1`
* [OKTA-898112](https://oktainc.atlassian.net/browse/OKTA-898112)
=> OKTA-898112 - Release Note entry for  2025.04.1

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
- **What's changed?**  Fix formatting in IGA RN blurb
* [OKTA-917092](https://oktainc.atlassian.net/browse/OKTA-917092)
=> OKTA-917092 Fix formatting in IGA RN blurb

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Adding release note for `2025.04.1` regarding Subscriptions API
- **Is this PR related to a Monolith release?** `2025.04.1`
* [OKTA-917819](https://oktainc.atlassian.net/browse/OKTA-917819)
=> OKTA-917819 - Release note update for `2025.04.1`

packages/@okta/vuepress-theme-prose/layouts/Layout.vue
Reference: https://okta.slack.com/archives/GLUC0B4TH/p1744384620812619
- **What's changed?**  Used `v-if` instead of `v-show` to not rendered the element
* [OKTA-917764](https://oktainc.atlassian.net/browse/OKTA-917764)
=> OKTA-917764 | remove banner from rendering

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- **What's changed?**  Typo in the date expected
- **Is this PR related to a Monolith release?**  2025.04.0
* [OKTA-919406](https://oktainc.atlassian.net/browse/OKTA-919406)
=> Date update

packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/index.md, packages/@okta/vuepress-site/docs/guides/configure-direct-auth-grants/main/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** removed grant type - it's more than just by grant type, really
=> name change

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/reqautheverything.md
- **What's changed?** Minor code and style updates
* [OKTA-849672](https://oktainc.atlassian.net/browse/OKTA-849672)
=> OKTA-849672 - Updates to Vue SPA redirect guide

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Removed note that's no longer true
* [OKTA-893383](https://oktainc.atlassian.net/browse/OKTA-893383)
=> aj-OKTA-893383

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Release Notes blurb branch
- **Is this PR related to a Monolith release?** Yes, 2025.04.3
* [OKTA-898165](https://oktainc.atlassian.net/browse/OKTA-898165)
=> Rn entry release 2025.04.3

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?**  Release Notes 2025.04.3 
- **Is this PR related to a Monolith release?** Yes, 2025.04.3
* [OKTA-898165](https://oktainc.atlassian.net/browse/OKTA-898165)
=> Release 2025.04.3

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Another phrasing change
* [OKTA-928284](https://oktainc.atlassian.net/browse/OKTA-928284)
=> Phrasing update per feedback from Susan

packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/create-app-integration.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/load-app.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/basic-sign-in.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/create-app-integration.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/load-app.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/create-app-integration.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/load-app.md
- **What's changed?** Updates based on internal feedback
* [OKTA-922083](https://oktainc.atlassian.net/browse/OKTA-922083)
=> Update sign in to SPA embedded SIW guide

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- **What's changed?** Add vuln ticket (OKTA-840719) to Release Notes 2025.04.3 
- **Is this PR related to a Monolith release?** Yes, Release 2025.04.3
* [OKTA-926593](https://oktainc.atlassian.net/browse/OKTA-926593)
=> OKTA-926593: Add vuln ticket | Release 2025.04.3

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
=> Rn entry release 2025.05.0

packages/@okta/vuepress-site/docs/reference/ssf-transmitter-sets/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** SSF Transmitter SET JWT payload examples
- **Is this PR related to a Monolith release?** Yes 2025.05.0
Netlify link: https://preview-5410--reverent-murdock-829d24.netlify.app/docs/reference/ssf-transmitter-sets/
* [OKTA-925149](https://oktainc.atlassian.net/browse/OKTA-925149)
=> SSF Transmitter SET JWT payload examples

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Added some clarifications to parameters being passed to manager assistant functions
* [OKTA-913554](https://oktainc.atlassian.net/browse/OKTA-913554)
=> OKTA-913554 manager/assistant EL functions

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
- **What's changed?** Fix April monthly IGA RN date
- **Is this PR related to a Monolith release?** Yes, April monthly
=> Update April monthly IGA RN date

packages/@okta/vuepress-site/docs/concepts/policies/index.md
=> Acrolinx tweaks to generate a build

packages/@okta/vuepress-site/docs/guides/enable-express-configuration/main/index.md, packages/@okta/vuepress-site/docs/guides/express-configuration/main/index.md
- **What's changed?** Fix minor comments.
* [OKTA-932345](https://oktainc.atlassian.net/browse/OKTA-932345)
=> OKTA-932345 | Minor fix

packages/@okta/vuepress-site/docs/guides/idv-integration/main/index.md
- **What's changed?** Removing "authorization" from a guide overview
=> Remove authorization from description

packages/@okta/vuepress-site/docs/guides/authenticators-web-authn/main/index.md
- **What's changed?** Small update to the WebAuthn integration guide. Updated UI terminology and added a link
* [OKTA-857293](https://oktainc.atlassian.net/browse/OKTA-857293)
=> OKTA-857293 WebAuthn guide update

packages/@okta/vuepress-theme-prose/components/Hero.vue, packages/@okta/vuepress-theme-prose/global-components/SignUp.vue, packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?** Adding content for banner
* [OKTA-873736](https://oktainc.atlassian.net/browse/OKTA-873736 )
=> OKTA-873736 - Adding content for banner

packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/thirdpartyoidc/policies.md, packages/@okta/vuepress-site/docs/guides/configure-claims-sharing/main/thirdpartysaml/policies.md
- **What's changed?** Security question update to claims sharing
Netlify: https://preview-5436--reverent-murdock-829d24.netlify.app/docs/guides/configure-claims-sharing/thirdpartyoidc/main/#other-authentication-policy-scenarios
* [OKTA-933730](https://oktainc.atlassian.net/browse/OKTA-933730)
=> Security question update to claims sharing

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Add 2025.05.1 RN entries
- **Is this PR related to a Monolith release?** Yes, 2025.05.1
* [OKTA-919031](https://oktainc.atlassian.net/browse/OKTA-919031)
=> OKTA-919031 2025.05.1 RN entries

.github/acrolinx/global-config.edn
- **What's changed?** return score
- **Is this PR related to a Monolith release?**no 
=> return score

packages/@okta/vuepress-site/docs/concepts/policies/index.md
- **What's changed?** Adds details about grace periods. Links to API and product docs.
- **Is this PR related to a Monolith release?** Yes. 2025.05.2
* [OKTA-850284](https://oktainc.atlassian.net/browse/OKTA-850284)
=> Grace period for authenticator enrollment policies

packages/@okta/vuepress-theme-prose/components/Hero.vue, packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?** Minor changes to banner text after launch of Integrator Free Plan orgs
* [OKTA- 892454](https://oktainc.atlassian.net/browse/OKTA- 892454)
=> OKTA-892454 - Banner updates on launch

packages/@okta/vuepress-site/.vuepress/config.js, packages/@okta/vuepress-theme-prose/global-components/SignUp.vue, packages/@okta/vuepress-theme-prose/util/attribution/attribution.js, packages/@okta/vuepress-theme-prose/util/uris.js, tests/cypress/integration/signin_spec.js
Switches to new endpoint for org creation
* [OKTA-904998](https://oktainc.atlassian.net/browse/OKTA-904998)
=> Em okta 904998 new endpoint staging

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/loginredirect.md
- **What's changed?** Returning URL to official RxJS documentation now that their site is publishing again
* [OKTA-940225](https://oktainc.atlassian.net/browse/OKTA-940225)
=> OKTA-940225 - Update URL to official rxjs documentation

packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?**  Add OneTrust and Adobe scripts.
Ref: https://docs.google.com/document/d/1yLJhDcOoobPE4YutunaNChaHAtTA8gx4tZRv8TrI47k/edit?tab=t.0#heading=h.iu53skp7cbi
* [OKTA-921280](https://oktainc.atlassian.net/browse/OKTA-921280)
=> OKTA-921280 | GTM to Adobe Tags Migration - developer.okta.com

packages/@okta/vuepress-site/docs/guides/custom-widget-migration-gen3/main/index.md
- **What's changed?** Removes node note.
=> Gen2-Gen3 migration guide: remove node pre-req note

packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md
- **What's changed?** Update to test account lifespan
* [OKTA-882892](https://oktainc.atlassian.net/browse/OKTA-882892)
=> OKTA-882892: Update to test account lifespan

falsepos.txt
- **What's changed?** Adding https://withpersona.com/ to false positive list; manually tested this list as well
* n/a
=> Add one URL to false positive list

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
Add IGA API 2025.05.1 doc action for IGA-SEPARATION-OF-DUTIES OKTA-899035
- **Is this PR related to a Monolith release?** Yes, 2025.05.1 (only merge after Redocly publish, scheduled for June 5)
* [OKTA-899035](https://oktainc.atlassian.net/browse/OKTA-899035)
=> OKTA-899035 Release 2025.05.1 IGA - Doc Action

packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
- **What's changed?** Update request body examples in the Logout request section.
* [OKTA-954411](https://oktainc.atlassian.net/browse/OKTA-954411)
=> OKTA-954411: Update request body examples

.github/acrolinx/global-config.edn
- **What's changed?** changing score bac
=> changing score back

.github/acrolinx/global-config.edn
- **What's changed?** put back header
=> put back header

packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Added user.getGroups to main EL doc
- **Is this PR related to a Monolith release?**  2025.06.0
* [OKTA-962954](https://oktainc.atlassian.net/browse/OKTA-962954)
=> [OKTA-962954] Expression Language doc updates (user.getGroups)

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?**  Updated to add user.getGroups function is GA in Preview to the June monthly RN
- **Is this PR related to a Monolith release?**  2025.06.0
* [OKTA-945229](https://oktainc.atlassian.net/browse/OKTA-945229)
=> 2025.06.0 RN hotfix

packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- **What's changed?** Added Okta Integration IdP content that was previously hidden; hid the content on OpenID Connect IdP.
- **Is this PR related to a Monolith release?** `2025.06.2`
* [OKTA-958137](https://oktainc.atlassian.net/browse/OKTA-958137)
=> OKTA-958137 - Add info on Okta Integration IdP for Org2Org guide

packages/@okta/vuepress-site/docs/guides/idv-integration/main/index.md
- **What's changed?** Remove EA tag for IDV feature. IDV_STANDARD_INTEGRATION FF is now GA Preview and going GA Prod with 7.0 release
- **Is this PR related to a Monolith release?** No, not relevant for the 7.0 release.
* [OKTA-963926](https://oktainc.atlassian.net/browse/OKTA-963926)
=> Remove EA tag for IDV feature

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?**  Add blurb for Hotfix from OKTA-963932
- **Is this PR related to a Monolith release?**  2025.06.2
=> Hotfix for 2025.06.2 release

packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/defineroute.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/loginredirect.md
- **What's changed?** Revised to include all signed commits. See: https://github.com/okta/okta-developer-docs/pull/5543 and https://github.com/okta/okta-developer-docs/pull/5497/files
n/a
=> Updating Sign user in to your web app using the redirect model (Node Express)

packages/@okta/vuepress-site/code/alternate-sign-in-sdks/index.md
- **What's changed?** Updated a broken xref to Mobile SDK
* n/a
=> Update broken link and image reference to Mobile Swift SDK

packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md, packages/@okta/vuepress-site/docs/guides/dpop/main/index.md, packages/@okta/vuepress-site/docs/guides/event-hook-filtering/main/index.md, packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md, packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/saml-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md, packages/@okta/vuepress-site/docs/guides/token-inline-hook/main/index.md, packages/@okta/vuepress-theme-prose/global-components/GlitchDeprecationNote.vue
- **What's changed?** Adding a note (as a global component) referencing the deprecation of the Glitch projects.
* [OKTA-971041](https://oktainc.atlassian.net/browse/OKTA-971041)
=> OKTA-971041 - Add Glitch deprecation note

packages/@okta/vuepress-site/archive/php/protect-your-api/index.md, packages/@okta/vuepress-site/archive/php/sign-into-web-app-redirect/index.md, packages/@okta/vuepress-site/archive/php/validate-access-tokens/index.md, packages/@okta/vuepress-site/code/dotnet/jwt-validation/index.md, packages/@okta/vuepress-site/docs/concepts/feature-lifecycle-management/index.md, packages/@okta/vuepress-site/docs/concepts/saml/index.md, packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md, packages/@okta/vuepress-site/docs/guides/add-logingov-idp/main/index.md, packages/@okta/vuepress-site/docs/guides/archive-auth-js/main/index.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/angular/guide.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/react/guide.md, packages/@okta/vuepress-site/docs/guides/archive-sign-in-to-spa-authjs/main/vue/guide.md, packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/configuration.md, packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/angular/intro.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/intro.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/intro.md, packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/sign-in-form.md, packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/main/index.md, packages/@okta/vuepress-site/docs/guides/social-login/main/index.md, packages/@okta/vuepress-site/docs/guides/terraform-create-custom-auth-server/main/index.md, packages/@okta/vuepress-site/docs/guides/terraform-manage-external-authenticators/main/index.md, packages/@okta/vuepress-site/docs/release-notes/2024-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2024/index.md, packages/@okta/vuepress-site/test_page/index.md
- **What's changed?** Reviewed repo for old API references and updated to OAS3 URLs
* [OKTA-969044](https://oktainc.atlassian.net/browse/OKTA-969044)
=> OKTA-969044 - Replaced old API reference URLs to OAS3 version

packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/index.md, packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- **What's changed?** Added meta tag to index.md
* [OKTA-971792](https://oktainc.atlassian.net/browse/OKTA-971792)
=> OKTA-971792 - Add meta tag to Index

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?**  Release notes for 2025.07.1
- **Is this PR related to a Monolith release?**  2025.07.1
* [OKTA-941860](https://oktainc.atlassian.net/browse/OKTA-941860)
=> Rn entry release 2025.07.1

packages/@okta/vuepress-site/docs/concepts/token-lifecycles/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Add token lifecycle concept
* [OKTA-946202](https://oktainc.atlassian.net/browse/OKTA-946202)
=> OKTA-946202 OAuth 2.0 token lifecycle concept for OCI

packages/@okta/vuepress-site/docs/guides/create-an-app-integration/main/OIDC/protocol-config.md
- **What's changed?** Edited to improve Acrolinx score
* [OKTA-944607](https://oktainc.atlassian.net/browse/OKTA-944607)
=> Edited to improve Acrolinx score

packages/@okta/vuepress-theme-prose/util/signupValidation.service.js
- Switches to new endpoint for email validation
- PR for testing CORS on www.okta.com staging https://github.com/okta/okta-developer-docs/pull/5566
* [OKTA-945477](https://oktainc.atlassian.net/browse/OKTA-945477)
=> Switches to new endpoint

packages/@okta/vuepress-site/.vuepress/public/img/icons/feedback.svg, packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss, packages/@okta/vuepress-theme-prose/assets/css/components/_feedback.scss, packages/@okta/vuepress-theme-prose/assets/css/components/_wrapper.scss, packages/@okta/vuepress-theme-prose/components/Feedback.vue, packages/@okta/vuepress-theme-prose/components/HeaderBanner.vue
- Added support to dismiss banner temporarily (24 hrs)
- Made feedback button smaller on mobile screens
- Added extra side padding to content so that it doesn't overlap feedback button
* [OKTA-968079](https://oktainc.atlassian.net/browse/OKTA-968079)
=> Added icon for feedback button in mobile view

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  Added and moved content for projections in ELv2 and clarified some group claims things
* [OKTA-973453](https://oktainc.atlassian.net/browse/OKTA-973453)
=> [OKTA-973453] Collection projections in ELv2

packages/@okta/vuepress-site/docs/guides/custom-well-known-uri/index.md, packages/@okta/vuepress-site/docs/guides/custom-well-known-uri/main/index.md, packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Associated domains customization guide
- **Is this PR related to a Monolith release?** Yes, 2025.07.2
* [OKTA-954434](https://oktainc.atlassian.net/browse/OKTA-954434)
=> OKTA-954434 Associated domains

packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- Updates error handling for freemium endpoint
* [OKTA-977710](https://oktainc.atlassian.net/browse/OKTA-977710)
=> Updates error handling

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
=> [2025.07.1 Release Notes]

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/asp-net-core-3/testapp.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/asp-net-core-3/whatyouneed.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/go/testapp.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/reqautheverything.md, packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/node-express/testapp.md
- **What's changed?**  Redo PR #5580 
* [OKTA-946240](https://oktainc.atlassian.net/browse/OKTA-946240)
=> Aj okta 946240 redo PR#5580

packages/@okta/vuepress-site/docs/guides/authenticators-tac-authenticator/main/index.md, packages/@okta/vuepress-site/docs/guides/custom-well-known-uri/main/index.md
- **What's changed?** Add EA lifecycle tags to two feature guides
=> Add lifecycle tags to two EA guides

packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
- **What's changed?** Update a description of the default policy rule to align with the UI
* [OKTA-953470](https://oktainc.atlassian.net/browse/OKTA-953470)
=> Update description of default policy

packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/configmid.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/redirectvalues.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/redirectvalues.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/createproject.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/getuserinfo.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/handlecallback.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/loginredirect.md, packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/vue/redirectvalues.md
- **What's changed?**  SPA/redirect doc updates
* [OKTA-978585](https://oktainc.atlassian.net/browse/OKTA-978585)
=> Aj okta 978585 spa redirect doc updates

packages/@okta/vuepress-site/docs/reference/org-defaults/index.md
- **What's changed?** Updated `Admin email` to `Sign-up email` to address ticket
* [OKTA-982306](https://oktainc.atlassian.net/browse/OKTA-982306)
=> OKTA-982306 - Updated integrator org limitations table

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Add note that clarifies how custom email templates work with super admins
* [OKTA-932568](https://oktainc.atlassian.net/browse/OKTA-932568)
=> Add note about custom email templates

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- **What's changed?** adding examples and removing ea tags
- **Is this PR related to a Monolith release?** Yes 2025.07.3
Netlify link
OIDC: https://preview-5610--reverent-murdock-829d24.netlify.app/docs/guides/add-an-external-idp/openidconnect/main/#create-an-identity-provider-in-okta
SAML: https://preview-5610--reverent-murdock-829d24.netlify.app/docs/guides/add-an-external-idp/saml2/main/#create-an-app-at-the-identity-provider
* [OKTA-983611](https://oktainc.atlassian.net/browse/OKTA-983611)
=> adding examples and removing ea tags

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md, packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Release notes for 2025.07.3
- **Is this PR related to a Monolith release?** Yes, 2025.07.3
* [OKTA-956024](https://oktainc.atlassian.net/browse/OKTA-956024)
=> Release 2025.07.3

packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md, packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md, packages/@okta/vuepress-site/docs/guides/revoke-tokens/main/index.md
- **What's changed?** Auth server concept updates for OCI
- **Is this PR related to a Monolith release?** TBD
* [OKTA-946251](https://oktainc.atlassian.net/browse/OKTA-946251)
=> OKTA-946251 Auth server concept updates for OCI

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-privileged-access/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Rn entry 2025 08.0
- **Is this PR related to a Monolith release?** yes  2025.08.0
Netlify link: https://preview-5632--reverent-murdock-829d24.netlify.app/docs/release-notes/2025/
* [OKTA-941882](https://oktainc.atlassian.net/browse/OKTA-941882)
=> Rn entry 2025 08.0

packages/@okta/vuepress-site/docs/guides/idv-integration/main/index.md
- **What's changed?** Adding new event type to IDV integration guide and other SysLog updates
- **Is this PR related to a Monolith release?** Yes, 2025.08.0
* [OKTA-988366](https://oktainc.atlassian.net/browse/OKTA-988366)
=> IDV SysLog updates

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/saml2/appidpinokta.md
- **What's changed?** sentence about having two active certs
- **Is this PR related to a Monolith release?** Yes 2025.08.0
Netlify: https://preview-5614--reverent-murdock-829d24.netlify.app/docs/guides/add-an-external-idp/saml2/main/#create-an-identity-provider-in-okta
* [OKTA-984711](https://oktainc.atlassian.net/browse/OKTA-984711)
=> sentence about having two active certs

packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/index.md, packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md, packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md, packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md, packages/@okta/vuepress-site/docs/guides/index.md, packages/@okta/vuepress-site/docs/guides/key-management/index.md, packages/@okta/vuepress-site/docs/guides/key-management/main/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- Split out client secret rotation and key management into two guides to add the new key management features for token encryption.
- Updated create a custom authorization server to point to the access token encryption information in the new key management guide.
- Updated the OAuth for Okta - service app guide to specifically call out signing keys in the key section.
- **Is this PR related to a Monolith release?** yes 2025.08.0
Netlify links:
Client secret rotation: https://preview-5588--reverent-murdock-829d24.netlify.app/docs/guides/client-secret-rotation-key/main/
Key management: https://preview-5588--reverent-murdock-829d24.netlify.app/docs/guides/key-management/main/
OAuth for Okta -- service app: https://preview-5588--reverent-murdock-829d24.netlify.app/docs/gui …
=> OIDC Token Encryption Updates to Guides

packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/index.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/test-instance.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/universal-logout-properties.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/test-instance.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/universal-logout-properties.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/universal-logout-properties.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/index.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/openidconnect/edit-links.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/openidconnect/required-app-instances.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/openidconnect/submit-checks.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/openidconnect/test-instance.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/openidconnect/test-steps.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/saml2/edit-links.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/saml2/required-app-instances.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/saml2/submit-checks.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/saml2/test-instance.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/saml2/test-steps.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/scim/edit-links.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/scim/submit-checks.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/scim/test-instance.md, packages/@okta/vuepress-site/docs/guides/update-oin-app/main/scim/test-steps.md
- **What's changed?** Create Universal Logout submission in OIN Wizard 
- **Is this PR related to a Monolith release?** 2025.08.0
* [OKTA-834704](https://oktainc.atlassian.net/browse/OKTA-834704)
=> OKTA-834704: Create Universal Logout submission in OIN Wizard

packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?**  Updated Elvis EL operator description
* [OKTA-983563](https://oktainc.atlassian.net/browse/OKTA-983563)
=> Elvis operator update

packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** fixing SIW title in nav bar
=> fixing SIW title in nav bar

packages/@okta/vuepress-site/docs/release-notes/2025-okta-privileged-access/index.md
- **What's changed?** Rotate now is EA in Production Aug 11
- **Is this PR related to a Monolith release?** Yes, 2025.08.0
* [OKTA-972687](https://oktainc.atlassian.net/browse/OKTA-972687)
=> OKTA-972687 OPA-Rotate now- is EA in Production

packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?**  Typo in navbar
=> Navbar fix

packages/@okta/vuepress-site/docs/concepts/brands/index.md, packages/@okta/vuepress-site/docs/guides/terraform-overview/main/index.md, packages/@okta/vuepress-site/docs/reference/rl-best-practices/index.md, packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2023/index.md, packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- **What's changed?** Updated minor site branding references
* [OKTA-918699](https://oktainc.atlassian.net/browse/OKTA-918699)
=> OKTA-918699 - Update site branding

packages/@okta/vuepress-site/docs/guides/request-user-consent/main/index.md
- **What's changed?** user consent updates
Netlify: https://preview-5643--reverent-murdock-829d24.netlify.app/docs/guides/request-user-consent/main/
* [OKTA-987232](https://oktainc.atlassian.net/browse/OKTA-987232)
=> user consent updates

packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/openidconnect/universal-logout-properties.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/saml2/universal-logout-properties.md, packages/@okta/vuepress-site/docs/guides/submit-oin-app/main/scim/universal-logout-properties.md
- **What's changed?** Update GTR endpoint example.
* [OKTA-1001319](https://oktainc.atlassian.net/browse/OKTA-1001319)
=> OKTA-1001319: Update GTR endpoint example

packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/main/index.md
- **What's changed?** adding note on character limit for expressions
* [OKTA-952562](https://oktainc.atlassian.net/browse/OKTA-952562)
=> adding note on character limit for expressions

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- **What's changed?**  Release notes
- **Is this PR related to a Monolith release?**  2025.08.3
* [OKTA-941901](https://oktainc.atlassian.net/browse/OKTA-941901)
=> Release notes for 2025.08.3

packages/@okta/vuepress-site/docs/guides/auth-js-redirect/main/index.md
- **What's changed?** Update [Sign users in to your SPA using redirect and Auth JS | Okta Developer](https://developer.okta.com/docs/guides/auth-js-redirect/main/#add-a-sign-out-function) to address how does the app respond when the user is signed out already.
* [OKTA-946262](https://oktainc.atlassian.net/browse/OKTA-946262)
=> OKTA-946262: Add sign-out experience

packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md, packages/@okta/vuepress-site/docs/guides/oie-upgrade-sessions-api/main/index.md
- **What's changed?** updates to oie docs about sessions
- **Is this PR related to a Monolith release?** yes 2025.08.4
Netlify
OIE Limitations: https://preview-5669--reverent-murdock-829d24.netlify.app/docs/guides/ie-limitations/main/#sessions-apis
Sessions changes: https://preview-5669--reverent-murdock-829d24.netlify.app/docs/guides/oie-upgrade-sessions-api/main/
* [OKTA-1007035](https://oktainc.atlassian.net/browse/OKTA-1007035)
=> updates to oie docs about sessions

packages/@okta/vuepress-site/docs/concepts/mfa/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Add a new concept doc that explains MFA
* [OKTA-946232](https://oktainc.atlassian.net/browse/OKTA-946232)
=> OCI MFA concept doc

packages/@okta/vuepress-site/docs/concepts/manage-user-creds/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** manage user creds
- **Is this PR related to a Monolith release?** yes2025.09.0
Netlify links: https://preview-5680--reverent-murdock-829d24.netlify.app/docs/concepts/manage-user-creds/
* [OKTA-946253](https://oktainc.atlassian.net/browse/OKTA-946253)
=> manage user creds

packages/@okta/vuepress-site/docs/concepts/sso-overview/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Fix terminology issue
- **Is this PR related to a Monolith release?**NA
* [OKTA-946275](https://oktainc.atlassian.net/browse/OKTA-946275)
=> Terminology fix

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
- **What's changed?** IGA RN entries for 2025.09.0
- **Is this PR related to a Monolith release?** Yes, 2025.09.0
=> IGA RN entries for 2025.09.0

packages/@okta/vuepress-site/docs/journeys/OCI-web-sign-in/main/index.md, packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** tryin to push a PR thru
=> tryin to push a PR thru

packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Update email template and variables for SAR
- **Is this PR related to a Monolith release?** Yes, 2025.09.0
* [OKTA-1006334](https://oktainc.atlassian.net/browse/OKTA-1006334)
=> OKTA-1006334 Update email template and variables for SAR

packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md, packages/@okta/vuepress-site/docs/guides/terraform-manage-multiple-domains/main/index.md
- **What's changed?** Removing EA references on Org2Org doc: https://developer.okta.com/docs/guides/secure-oauth-between-orgs/main/ . Also fixed two broken internal links.
- **Is this PR related to a Monolith release?** `2025.09.0`
* [OKTA-987740](https://oktainc.atlassian.net/browse/OKTA-987740)
=> OKTA-987740 - Remove EA references on Org2Org docs

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-privileged-access/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Adding RNs for OIE, Classic, IGA, OPA
- **Is this PR related to a Monolith release?** `2025.09.0`
* [OKTA-941904](https://oktainc.atlassian.net/browse/OKTA-941904)
=> OKTA-941904 - Draft monthly release notes

packages/@okta/vuepress-site/docs/guides/anything-as-a-source/index.md
- **What's changed?**  EA tags for groups and group memberships
- **Is this PR related to a Monolith release?**  2025.09.0
* [OKTA-1001521](https://oktainc.atlassian.net/browse/OKTA-1001521)
=> Added EA tags to groups and group memberships content

packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- **What's changed?** Add a section that covers the rate limits for OTPs
* [OKTA-953499](https://oktainc.atlassian.net/browse/OKTA-953499)
=> OTP rate limites

packages/@okta/vuepress-site/docs/concepts/oauth-claims/index.md, packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md, packages/@okta/vuepress-site/docs/guides/delete-all-stay-signed-in-sessions/main/index.md, packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/ios/enablesso.md
- **What's changed?** Broken internal link fixes
* [OKTA-1021366](https://oktainc.atlassian.net/browse/OKTA-1021366)
=> OKTA-1021366 - Fix broken links 709-719

packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/main/index.md, packages/@okta/vuepress-site/docs/release-notes/2019/index.md, packages/@okta/vuepress-site/docs/release-notes/2021/index.md, packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- **What's changed?** Fix broken links. lines 741-760
* [OKTA-1021382](https://oktainc.atlassian.net/browse/OKTA-1021382)
=> Fix broken links 741-760

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md, packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Added vuln ticket 
- **Is this PR related to a Monolith release?** 2025.09.1
* [OKTA-1030980](https://oktainc.atlassian.net/browse/OKTA-1030980)
=> Added vuln ticket 

packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/openidconnect/appidpinokta.md, packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- **What's changed?** For OIDC and social IdPs, add account linking **If no match is found** option description.
- **Is this PR related to a Monolith release?** Yes, 2025.09.2 (aligns with OKTA-961757 release)
* [OKTA-1023958](https://oktainc.atlassian.net/browse/OKTA-1023958)
* [OKTA-961757](https://oktainc.atlassian.net/browse/OKTA-961757)
=> OKTA-1023958 Add IdP error when JIT is disabled and account linking enabled

packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-governance/index.md
- **What's changed?** Amend RN blurb for IGA_RESOURCE_OWNERS
- **Is this PR related to a Monolith release?** yes, 2025.09.0
=> Amend RN blurb for IGA_RESOURCE_OWNERS

packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Fix two small typos
=> Fix typos in Custom domain guide

packages/@okta/vuepress-site/docs/concepts/oie-intro/index.md
* [OKTA-946230](https://oktainc.atlassian.net/browse/OKTA-946230)
=> OCI journey  task-  Okta Identity Engine overview
