okta/okta-developer-docs

- packages/@okta/vuepress-plugin-my-okta/clientRootMixin.js
- packages/@okta/vuepress-plugin-my-okta/index.js
- packages/@okta/vuepress-plugin-my-okta/package.json
- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/package.json
In this PR, there is a new package created to deal with editing the `okta-preview-domain` sections of the page to swap out for your domains based on login.okta.com.
This will only work from approved okta domains, so localhost will not provide the swap.
This code is based on the current live code through jekyll while removing jquery dependency
> Sets up a new package for the {yourOktaDomain} change 

- packages/@okta/migrate-from-jekyll/index.js
- packages/@okta/migrate-from-jekyll/utils/buildRedirects.js
- packages/@okta/vuepress-site/.vuepress/redirects.json
- packages/@okta/vuepress-site/conductor.yml
This PR addresses 404's because of missing redirects that Jekyll was doing via its magical black box.
> Creates redirects in conductor file from the redirects.json

- packages/@okta/vuepress-plugin-active-header-links/clientRootMixin.js
- packages/@okta/vuepress-plugin-active-header-links/index.js
- packages/@okta/vuepress-plugin-active-header-links/package.json
- packages/@okta/vuepress-theme-default/components/TableOfContents.vue
- packages/@okta/vuepress-theme-default/index.js
- packages/@okta/vuepress-theme-default/layouts/Layout.vue
- packages/@okta/vuepress-theme-default/package.json
This creates a new package that uses the non customizable active-header-links and tweaks it for our needs.  This also adds the functionality to handle the loading and linking within the pages to show the header below the top navigation bar.
> Creates functionality for direct linking to a hash

- packages/@okta/vuepress-plugin-active-header-links/index.js
- packages/@okta/vuepress-theme-default/components/Page.vue
- packages/@okta/vuepress-theme-default/components/TableOfContents.vue
- tests/selenium/spec/table-of-contents-spec.js
This updates the way table of contents is created. 
It uses the active header links plugin to build the headers and place them onto the `$page` object to be used. This removes a whole lot of complexity in the process and makes it function much quicker and more reliable.
> Table of Contents updates

- packages/@okta/vuepress-theme-default/assets/css/okta/pages/quickstarts.scss
Prevents long URLs in code snippets from causing this entire div to overflow
> Set max-width on QuickStart bodies

- packages/@okta/vuepress-site/code/dotnet/sample_application/index.md
- packages/@okta/vuepress-theme-default/assets/css/okta/pages/code.scss
- packages/@okta/vuepress-theme-default/components/ChangeLog.vue
- packages/@okta/vuepress-theme-default/components/Page.vue
VuePress does not seem to like the class directly on `<Content` for the build, so this is to wrap the content inside of a div
This also includes a fix for the code pages alignment
Resolves #77
Resolves #84
> Padding and alignment issues fixed

- packages/@okta/vuepress-theme-default/layouts/Guides.vue
"undefined" unexpectedly uncovered in url is understandably undesired
> Guides overview self link

- packages/@okta/vuepress-theme-default/assets/css/okta/pages/guides.scss
- packages/@okta/vuepress-theme-default/components/StackSelector.vue
- packages/@okta/vuepress-theme-default/util/frameworks.js
- packages/@okta/vuepress-theme-default/util/guides.js
* stack selector and featured guides icon sizes reduced
* stack selector selected indicator and tab/text position fixed
* featured guides now are the same size, recolored
> Guides styling

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/package.json
- yarn.lock
- Adds a dependency of `vuepress-plugin-sitemap` to generate the sitemap for docs
- Sets up the configuration options for `vuepress-plugin-sitemap` to build the sitemap during the build process of the site
* OKTA-215935
> Adds Sitemap functionality

- packages/@okta/vuepress-site/.vuepress/enhanceApp.js
- packages/@okta/vuepress-site/guides/protect-your-api/index.md
- packages/@okta/vuepress-site/guides/sign-into-mobile-app/index.md
- packages/@okta/vuepress-site/guides/sign-into-spa/index.md
- packages/@okta/vuepress-site/guides/sign-into-your-web-app/index.md
- packages/@okta/vuepress-site/guides/sign-users-out/index.md
- packages/@okta/vuepress-theme-default/components/FeaturedGuide.vue
- packages/@okta/vuepress-theme-default/components/GuideDetails.vue
- packages/@okta/vuepress-theme-default/components/GuidesNavigation.vue
- packages/@okta/vuepress-theme-default/components/StackSelector.vue
- packages/@okta/vuepress-theme-default/layouts/Guides.vue
- packages/@okta/vuepress-theme-default/util/guides.js
Updates the urls from `/guides/#sign-into-mobile/react/1` to `/guides/sign-into-mobile/react/1` for SEO purposes (a change in those parts is also forthcoming to improve SEO)
This means we lose built-in behaviors:
* everything now scrolls to the top now (to be addressed in a scrolling PR)
* links now default to loading a new page (links here are switched to use <router-link to="/link">)
On the up-side, we gain relative links between pages in guides (that will still load a new page unless we use <router-link>)
> feat(guides): Switches to using path instead of hash routes for guides

- packages/@okta/vuepress-site/reference/webfinger/index.md
- Webfinger doc examples were showing `q=...` instead of `resource=...`
* [OKTA-218920](https://oktainc.atlassian.net/browse/OKTA-218920)
@okta/idx 
@jakubvul
> Fixing webfinger query param in example

- packages/@okta/vuepress-site/reference/okta_expression_language/index.md
- **What's changed?**  Wraps response items in table in backticks.  This is necessary anytime a string has json in it.  ie. `{10, 20, 30, 40}` or `Arrays.add({10, 20, 30}, 40)`
- **Is this PR related to a Monolith release?**  NO
resolves #180
> Wrap items in backticks

- packages/@okta/vuepress-site/docs/api/resources/idps/index.md
- **What's changed?** remove the EA tag for CUSTOM_ATTRIBUTE matchType, and it is available to all IdP types;
- **Is this PR related to a Monolith release?** yes, 2019.04.0
* [OKTA-177544](https://oktainc.atlassian.net/browse/OKTA-177544)
> GA IDP_EXTENSIBLE_MATCHING_RULES

- packages/@okta/vuepress-site/docs/api/getting_started/rate-limits/index.md
Update rate limit documentation regarding OAuth2 APIs
- **Is this PR related to a Monolith release?** April major release
* [OKTA-217213](https://oktainc.atlassian.net/browse/OKTA-217213)
> Py okta 217213 new oauth2 rate limits second try

- packages/@okta/vuepress-site/reference/scim/index.md
Removed Beta flag and Beta reference for SCIM method "Create Group: POST /Groups"
The Group APIs are all now public/GA.
> Remove Beta flag and Beta reference for GA feature

- packages/@okta/vuepress-site/docs/how-to/add-user-consent-to-flow/index.md
* this is a GET request made by a browser, so drop the `curl` example including sending custom headers and the SSWS key
* rephrased text to indicate this is opened in a browser
* replaced hardcoded `state` with placeholder like `nonce` to avoid encouraging people to hardcode state value
> fix consent request example

- packages/@okta/vuepress-site/use_cases/api_access_management/index.md
- **What's changed?** The link claimed to be the iOS OIDC library but linked to the JS library instead. I updated it to the iOS library as that was the context.
* n/a
> Fixed the link to the OIDC library

- packages/@okta/vuepress-site/3rd_party_notices/index.md
- **What's changed?** Removes "edit page" link and extra empty item in list in 3rd party notices page.
* No jira yet. But can create one if needed.
**After**
**Before**
> Removes "edit page" link and extra empty item in list

- packages/@okta/vuepress-site/reference/scim/index.md
Update response startIndex in pagination example.  Request is made to `/Users?count=1&startIndex=1` but response shows `startIndex: 0`.  As SCIM uses 1-based indexing for both the request and response, the response should show `startIndex: 1`.
> Update response startIndex in pagination example

- packages/@okta/vuepress-site/use_cases/event_hooks/index.md
- **What's changed?** Edits to emphasize need for service to send HTTP response back to Okta immediately, and to note de-duplication best practice based on `data.events.uuid`.
* [OKTA-221895](https://oktainc.atlassian.net/browse/OKTA-221895)
> Edits to Event Hooks overview based on feedback

- packages/@okta/vuepress-site/docs/api/resources/oidc/index.md
- Specified that the parameter `client_id` is only applicable to Okta Org Authorization Server for the /keys endpoint
- The response examples from the .well-known endpoints in the docs are already correct, i.e. they do not include the client_id as a parameter to the jwks endpoint.
- **Is this PR related to a Monolith release?** Yes, 2019.04.2
* [OKTA-217289](https://oktainc.atlassian.net/browse/OKTA-217289)
@yuliu-okta
> Specified that the parameter `client_id` is only applicable to Okta Org Authorization Server for the /keys endpoint

- packages/@okta/vuepress-site/docs/api/resources/users/index.md
- **Update API Docs to include SHA-512 in user import** 
- **No. (The Monolith changes were already released previously, in April 2019) **
* [OKTA-222911](https://oktainc.atlassian.net/browse/OKTA-222911)
> OKTA-222911 : Update API Docs to include SHA-512 in user import

- README.md
- packages/@okta/vuepress-site/guides/sign-into-spa/create-okta-application/index.md
- packages/@okta/vuepress-theme-default/global-components/GuideLink.vue
- Adds GuideLink component (Vuepress doesn't handle relative links for pseudo-pages like Guides.  This component is a workaround for that to allow linking between guide sections while maintaining the current selected framework in the url.
- Updates README to reflect above.
- No
* [OKTA-https://oktainc.atlassian.net/browse/OKTA-224075] https://oktainc.atlassian.net/browse/OKTA-224075)
* [OKTA-https://oktainc.atlassian.net/browse/OKTA-220261] https://oktainc.atlassian.net/browse/OKTA-220261)
> Guides relative links

- packages/@okta/vuepress-theme-default/assets/css/okta/components/Button.scss
- packages/@okta/vuepress-theme-default/assets/css/okta/pages/guides.scss
- packages/@okta/vuepress-theme-default/layouts/Guides.vue
Some CSS fixes to compensate for Nim changes in Guides.
- Stack selector language icon position
- Visited button text color
- Override Vuepress outbound link icon
> Fix Nim changes to guides css

- packages/@okta/vuepress-site/docs/api/resources/authn/index.md
Related to OKTA-225188
The documentation for the usage of device fingerprinting was inaccurate. Few people complained about this. Particularly, the distinction between fingerprint and device token had to be explained more clearly and the use cases for these 2 fields. 
No
* [OKTA-225188](https://oktainc.atlassian.net/browse/OKTA-225188)
@srinivasanagandla-okta can you please review?
> Fix doc issues with the device fingeprinting uses in the authn api

- packages/@okta/vuepress-site/code/python/pysaml2/index.md
SAML guidance link has been moved and the existing link is broken. 
New link should be: https://www.okta.com/integrate/documentation/single-sign-on/
No
* no JIRA, manually found and fixed this issue.
> Fix broken link to "SAML Guidance" #2

- packages/@okta/vuepress-theme-default/assets/css/okta/pages/guides.scss
- packages/@okta/vuepress-theme-default/components/GuideDetails.vue
- Guides will now fill the available width, so switching frameworks will not cause any horizontal display changes
- No
* [OKTA-221547](https://oktainc.atlassian.net/browse/OKTA-221547)
> fix(guides): Updates Guides content to be full (avail) width

- packages/@okta/vuepress-site/use_cases/inline_hooks/registration_hook/registration_hook/index.md
- **What's changed?** There was a typo--an extra comma--in the JSON listing in the 'Sample JSON Payload of Response' section of the 'Registration Inline Hook' page.
> Removing extra comma.

- packages/@okta/vuepress-theme-default/global-components/EventTypes.vue
- **What's changed?** Filters out `beta` event types.
* [OKTA-226324](https://oktainc.atlassian.net/browse/OKTA-226324)
> OKTA-226324: Filters out beta event types.

- packages/@okta/vuepress-theme-default/README.md
- packages/@okta/vuepress-theme-default/assets/css/okta/components/Button.scss
- For buttons that open a link in a new window, changes the external icon color to be visible.
- Applies to `blue` and `red` buttons, which should be the only ones in use.
- Also tweaks theme readme to link to newly open-source Nim.
* #312
> External icons for buttons

- packages/@okta/vuepress-site/docs/api/resources/users/index.md
- **What's changed?** Acting on reader feedback that docs for finding a user's groups not findable.
* [OKTA-206894](https://oktainc.atlassian.net/browse/OKTA-206894)
> Making user groups more findable, maybe

- packages/@okta/vuepress-site/docs/api/resources/oidc/index.md
Fixed some problems as I was reviewing the OIDC API reference.
@susanharper-okta Can you give this a writer sanity check, and coordinate with the Fed team to review? Thank you!
> Make client authentication clearer

- packages/@okta/vuepress-site/docs/api/resources/users/index.md
i'm guessing previously the `-&-` resolved to `--` but now it is a single `-`
> Corrects the hash anchor in users doc

- packages/@okta/vuepress-site/use_cases/inline_hooks/registration_hook/registration_hook/index.md
`action` should have been `registration` (it's even listed in the above section)
> Correcting registration inline hook DENY example

- packages/@okta/vuepress-site/docs/api/resources/groups/index.md
- **What's changed?** The maximum limit returned by  /api/v1/groups/${groupId}/users is 1 000, not 10 000. This PR fixes the documentation to mention the correct number.
> Update limit for listing group members endpoint

- packages/@okta/vuepress-site/docs/api/resources/system_log/index.md
- **What's changed?** Adds `debugContext.debugData` callout for keys and values.
* [OKTA-221154](https://oktainc.atlassian.net/browse/OKTA-221154)
> OKTA-221154: Adds `debugContext.debugData` callout for keys and values

- packages/@okta/vuepress-site/docs/api/resources/system_log/index.md
- **What's changed?** Updates `outcome`-object values in System Log API docs.
* [OKTA-215185](https://oktainc.atlassian.net/browse/OKTA-215185)
> OKTA-215185: Updates `outcome`-object values in System Log API docs.

- packages/@okta/vuepress-site/docs/api/resources/system_log/index.md
- **What's changed?** Clarifies docs for System Log `q` param with hyphenated tokens
* [OKTA-163567](https://oktainc.atlassian.net/browse/OKTA-163567)
> OKTA-163567: Clarifies docs for System Log API `q` param with hyphenated tokens

- packages/@okta/vuepress-site/guides/sign-users-out/sign-out-of-okta/aspnet/remotesignout.md
- packages/@okta/vuepress-site/guides/sign-users-out/sign-out-of-okta/aspnetcore/remotesignout.md
* Remove unnecessary instructions for sign users out of Okta in ASP.NET Core guide.
* Minor wording change in instructions for sign users out of Okta in ASP.NET guide.
No.
* [OKTA-226308](https://oktainc.atlassian.net/browse/OKTA-226308)
> Update sign users out of Okta instructions in .NET guides

- packages/@okta/vuepress-site/docs/api/resources/zones/index.md
- Added Dynamic Zone documentation for the Network Zones Api doc
- Restructured the doc so that the Network Zone Object Reference is at the beginning of the doc
- Removed references in the doc specifying that only IP Zones are supported by the API
- Removed some superfluous attributes from json examples
- Specified that Network Zone objects  contain the auto-assigned `system` attribute, so as to not confuse admins who see this value when the API returns Network Zone objects.
* **Is this PR related to a Monolith release?** Yes. 2019.06.0
* [OKTA-111218](https://oktainc.atlassian.net/browse/OKTA-111218)
> Added Dynamic Zone Support to api doc

- packages/@okta/vuepress-site/docs/api/getting_started/rate-limits/index.md
Added High Capacity rate limits for /api/v1/users/{idOrLogin} GET which was missed out
No 
* [OKTA-227433](https://oktainc.atlassian.net/browse/OKTA-227433)
> Fixes High Capacity SKU discrepancy for /api/v1/users/{idOrLogin} GET

- packages/@okta/vuepress-site/docs/api/resources/system_log/index.md
Adds missing Logs API `AuthenticationContext.authenticationStep` docs. Also fixes the casing on the `AuthenticationContext` example.
No.
* [OKTA-163552](https://oktainc.atlassian.net/browse/OKTA-163552)
> OKTA-163552: Adds missing Logs API `AuthenticationContext.authenticationStep` docs

- packages/@okta/vuepress-theme-default/layouts/Guides.vue
- Guides without frameworks had JS console error re:appendChild if navigated to directly.  
- No
> Guides appendchild fix

- packages/@okta/vuepress-site/conductor.yml
Seeing if this will get the guide redirects working. Will do it for all the other `from` URLs if it does.
> Adding index dot html to end of guide from url

- packages/@okta/vuepress-site/conductor.yml
Reverts okta/okta-developer-docs#447
That PR didn't work, and I'd rather not confuse the issue by having a non-existent URL.
> Revert "Adding index dot html to end of guide from url"

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/next-steps/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/use-access-token/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/redirect-to-sign-in/index.md
- Updates guides content that had links in the pre-great-migration style (no /docs/)
- No
> fix(links): Update guides w/pre-migration links

- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
Added missing "s" to the "Delete Inline Hook" API Call under Request Example
Uppercase letter for: Channel Object, Config Object, AuthScheme Object.
- **Is this PR related to a Monolith release?**:
No
> Added missing "s" and capitalized letters

- packages/@okta/vuepress-site/conductor.yml
- Updates existing redirect rules where "from" ended in "/"
- Duplicates a few "from" rules without file extensions to cover the dir and file options
- Adds top-level /guides/foo/index.html redirects to /docs/guides/foo/
- No
> Patching more redirects

- packages/@okta/vuepress-site/conductor.yml
- Added redirects for paths without trailing slash (skipping release notes and guides)
- No
> Handle redirects w/o trailing slash that were failing

- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
Problem: when making a request to create a claim with filtering by groups if you follow the guide you will get a parsing validation error. 
You must change `groupFilterType` in the request to `group_filter_type`. It works then. Okta folks need to have a uniform guidance on this.
Example:
```
const formData = {
"name": "groupName",
"status": "ACTIVE",
"claimType": "RESOURCE",
"valueType": "GROUPS",
"group_filter_type": "EQUALS",
"value": groupName
}
```
> Fix the error when Okta wrongly rejects validation

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- "Response Parameters for Verify SMS Factor" and "Response Parameters for Verify Call Factor" had the wrong header level, which led to them being shown in the sidebar incorrectly.
> Fix Header Levels

- packages/@okta/vuepress-site/docs/release-notes/2019-07-2/index.md
- **What's changed?** Adding release notes entry, with beginning of content for 2019.07.2. More items might need to be added next week.
- **Is this PR related to a Monolith release?** Yes, 2019.07.2.
> Release Notes Entry for 2019.07.2 Part 1

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Removes the reference to the invalid EL expression from Linked Object function.
Removes the reference to the invalid EL expression from Linked Object function.
No
* [OKTA-238392](https://oktainc.atlassian.net/browse/OKTA-238392)
@andreyshatniy-okta
> Remove Invalid EL expression for Linked Object

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** We now allow app group deletion for app groups not used in group push mappings, so this change removes the limitation specified in the docs.
- **Is this PR related to a Monolith release?** Yes, release 2019.07.2
* [OKTA-214275](https://oktainc.atlassian.net/browse/OKTA-214275)
> Update docs to allow app group deletion

- packages/@okta/vuepress-site/code/android/index.md
AppAuth Android SDK is deprecated.
Update the reference to point to new SDK.
> Update android SDK reference.

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
1. Under the verify section in the AuthN/Factors API, just add a `token:hotp` to indicate that factor type is another factor that can be verified by simply passing a `passCode`.
2.  Add top-level index links to Enroll Custom HOTP in AuthN/Factors API
3.  In AuthN API Enrollment - state that this is not supported and link to the Factors API
4.  In Factors API Enrollment - show sample request/response for how to Enroll in Custom HOTP
For employees only i've sent a Box invite showing what the updated doc pages look like.  .  
- **Is this PR related to a Monolith release?** The changes should be in by the 2019.08.0 CF (this is major release for August)
* [OKTA-240244](https://oktainc.atlassian.net/browse/OKTA-240244)
> Add Custom HOTP factor content to the Factors and AuthN API

- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- **What's changed?** Removed the 'readOnly' column from the description of the channel object. Previously, the properties 'type' and 'version' were marked 'readOnly', but this was incorrect. Since nothing is readOnly in this object, removed the readOnly column.
* [OKTA-241061](https://oktainc.atlassian.net/browse/241061)
> Inline Hooks Management API: channel object properties not readOnly

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- **What's changed?** Adding troubleshooting section to the Inline Hooks overview, with a link to relevant system log events.
* [OKTA-238414](https://oktainc.atlassian.net/browse/OKTA-238414)
> Inline Hooks troubleshooting via System Log

- packages/@okta/vuepress-site/.vuepress/nav/codePages.js
- packages/@okta/vuepress-site/code/python/index.md
- packages/@okta/vuepress-site/docs/index.md
- packages/@okta/vuepress-theme-default/assets/css/okta/pages/docsIndex.scss
This PR adds back in the python code page which links out to the samples repo.
* [OKTA-235153](https://oktainc.atlassian.net/browse/OKTA-235153)
Updates to the css needed to allow this to show correctly
Code page rendered
> Adds python code pages

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
On https://github.com/okta/okta-signin-widget#okta-sign-in-widget we instruct users to use the latest version 3.1.0 whereas this page refers to 2.16.0
This discrepancy is causing issues with customers per an SE: https://okta.slack.com/archives/CD38NQ3SN/p1565818808106200
Definitely need a strong review on this one since I just swapped blocks of code and did not QA any of this.
On https://github.com/okta/okta-signin-widget#okta-sign-in-widget we instruct users to use the latest version 3.1.0 whereas this page refers to 2.16.0
No
> Update the version to use for SIW

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- **What's changed?** Adding information on the debugContext object to the Inline Hooks overview page.
* [OKTA-221151](https://oktainc.atlassian.net/browse/OKTA-221151)
> Inline Hooks: Adding info on debugContext object

- packages/@okta/vuepress-site/docs/release-notes/2019-08-2/index.md
- **What's changed?**  Adding release notes entry for 2019.08.2.
- **Is this PR related to a Monolith release?** Yes, 2019.08.2
> Release Notes Entry for 2019.08.2

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Removing note on limit for paginated response from the List Users with Search API.
- **Is this PR related to a Monolith release?** Yes, 2019.08.2
> User Search: Removing note on pagination limitation

- packages/@okta/vuepress-site/conductor.yml
Fixing top 404s for week of Aug 20, 2019.
/docs/api/getting_started/getting_a_token.html
/reference/okta_expression_language/index
/docs/sdk/opp/javadoc/index.html
/signin
/code/javascript/okta_sign-in_widget.html
/docs/guides/oan_guidance.html
/code/react/okta_react.html
/authentication-guide/implementing-authentication/auth-code.html
/code
/code/
/code/javascript/okta_auth_sdk.html
/authentication-guide/implementing-authentication/client-creds.html
> Fixing top 404s

- packages/@okta/vuepress-site/conductor.yml
Previous fix doesn't seem to have worked. Also found another bad redirect.
> Fixing redirect

- packages/@okta/vuepress-site/docs/reference/rate-limits/index.md
Add rate limit for OAuth2 public metadata endpoints
- **Is this PR related to a Monolith release?** Y, 2019.09.0
* [OKTA-226100](https://oktainc.atlassian.net/browse/OKTA-226100)
> Ratelimit for OAuth2 public metadata

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- The Attribute Statements object for SAML apps has an alternate form, the Group Attribute Statements object. This object has a few differences, which we now doc properly.
- This PR is not related to a release, as the changes were already released.
* [OKTA-243317](https://oktainc.atlassian.net/browse/OKTA-243317)
For more info on these SAML attributes, see [here](https://help.okta.com/en/prod/Content/Topics/Apps/Apps_App_Integration_Wizard.htm#SAMLConfigureSAML) and [here](https://help.okta.com/en/prod/Content/Topics/Apps/attribute-statements-saml.htm).
> Doc `filterValue` and `filterType` props

- packages/@okta/vuepress-site/code/nodejs/index.md
- **What's changed?**  Fixed `Node.js SDK Source` link from jsdocs to github
> Fixed link url: okta-nodejs-sdk

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- As part of 2019.10.0 release, the App Condition will be available to be used in the MFA Enroll Policy
- Also the Network condition has been available for use in MFA Enroll Policy for a long time but network condition link was missing
- 2019.10.0
How doc looks with changes in this PR
* [OKTA-231059](https://oktainc.atlassian.net/browse/OKTA-231059)
> Resolves: OKTA-231059 - add network and app condition to enroll policy

- packages/@okta/vuepress-site/conductor.yml
> Testing redirect

- packages/@okta/vuepress-theme-default/components/Code.vue
- packages/@okta/vuepress-theme-default/components/Sidebar.vue
- packages/@okta/vuepress-theme-default/global-components/Breadcrumb.vue
- Breadcrumbs when displayed on old layout were showing an odd padding, this has been fixed with scoped css and props for breadcrumb (this fix is temporary until Prose layout is built
- Sidebar was not full due to an added div, this has been fixed
> Fixes bug in sidebar and breadcrumb spacing

- packages/@okta/vuepress-site/docs/concepts/saml/index.md
SAML for Mobile Native Apps is outdated. We recommend OIDC for mobile app development now. Removing the outdated text
* [OKTA-258920](https://oktainc.atlassian.net/browse/OKTA-258920)
> Remove SAML for Mobile Native Apps

- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/test-scim-server/index.md
- packages/@okta/vuepress-site/docs/guides/build-sso-integration/integrate/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
1) Developer signup for OIN accounts still has to go through the old o.c/integrate signup until we have the OK7 correctly initialized to accept OIN accounts.
2) Nav tree entries look wrong (because they're prefixed with "OIN", and the nav tree is just using alphabetic organization, they look like they're in the wrong place. This fix puts them in the correct place alphabetically.
* [OKTA-259707](https://oktainc.atlassian.net/browse/OKTA-259707)
> Fix link to integrate sign up; fix nav tree

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- Rearrange U2F and WebAuthn factor docs for the Factors API, as they require a challenge before verification
- Also do some further clean-up and rewording per the new location
- No; this documents behavior that is already live
* [OKTA-261942](https://oktainc.atlassian.net/browse/OKTA-261942)
> Fix U2F + WebAuthn Factors API doc placement and wording

- packages/@okta/vuepress-site/docs/guides/enable-cors/overview/index.md
- **What's changed?** The CORS testing tool available on developer.okta.com does a CORS request on /api/v1/users/me endpoint. In case the user is not authenticated in the browser, a 403 error will occur and the Access-Control-Allow-Origin header will not be returned. This Doc Update adds a clarification for the tester to have an active session in Okta when testing the CORS functionality.
* OKTA-264154
> Clarification for CORS test

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** IdP Discovery is now GA, so removing mention of the Policy only existing in orgs that have the FF enabled.
> Removing mention of IdP Discovery FF

- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
- made consent parameter as optional for AS create Scope API
- 2019.12.0
* [OKTA-250368](https://oktainc.atlassian.net/browse/OKTA-250368)
> OKTA-250368: made consent parameter as optional for AS create Scope API

- scripts/update-se-drivers.sh
- Travis tests are failing as travis upgraded chrome version to 79
- This change adds support for chrome 79 driver
* [OKTA-266245](https://oktainc.atlassian.net/browse/OKTA-266245)
> Updates selenium script to accomodate chrome 79

- packages/@okta/vuepress-theme-prose/assets/css/components/_footer.scss
- packages/@okta/vuepress-theme-prose/assets/css/components/_sidebar.scss
- packages/@okta/vuepress-theme-prose/components/Sidebar.vue
TreeNav is now sticky and handles overflow scroll.
> Update Treenav to scroll with overflow

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- **What's changed?** Removing all mentions of the relayState property from text, request examples, response examples, and tables describing objects.
* [OKTA-232953](https://oktainc.atlassian.net/browse/OKTA-232953)
> Removing mentions of relayState property from authn API Reference

- packages/@okta/vuepress-site/docs/concepts/auth-overview/index.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
- **What's changed?** Basically what it says in the title. Trying to make it as obvious as possible that only Password flow and Auth Code flow without PKCE support refresh tokens. Other requests will fail.
* [OKTA-270840](https://oktainc.atlassian.net/browse/OKTA-270840)
> Making info about which flows support refresh token more prominent

- package.json
- packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
- packages/@okta/vuepress-site/quickstart-fragments/widget/default-example/index.md
- Uses the -=OKTA_REPLACE_WITH_WIDGET_VERSION=- magic replacement text to update the reference to the widget versions to always be the latest of the listed major version
- Removes an unused package.json script reference
- No
* [OKTA-270399](https://oktainc.atlassian.net/browse/OKTA-270399)
> widget link updates

- packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
Removes underline from code pages for language tabs and ctas, as well as cards for links.
> Fixes some underline on links

- packages/@okta/vuepress-site/docs/concepts/authentication/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/prepare-app/index.md
- packages/@okta/vuepress-site/docs/guides/build-sso-integration/integrate/index.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
Changed to point users to developer.okta.com sites instead of to okta.com/integrate locations.
> Correcting /integrate links

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/import-hook/index.md
- **What's changed?** Changing the name of the 'Import Inline Hook' to be 'User Import Inline Hook'. 
* [OKTA-273377](https://oktainc.atlassian.net/browse/OKTA-273377)
> Changing Name of Import Hook to User Import Hook

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- Document new sortBy and sortOrder parameters
- The parameters apply only to "List Users" queries that use `search`
- Monolith release 2020.02.0
* [OKTA-276081](https://oktainc.atlassian.net/browse/OKTA-276081)
> Document new sortBy and sortOrder parameters

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md
- update https://developer.okta.com/docs/guides/implement-oauth-for-okta/scopes/ page with newly added policies scope
- **Is this PR related to a Monolith release?** yes, 2020.02.0 (Monolith CF Jan 31)
* https://oktainc.atlassian.net/browse/OKTA-274761
@royalchan-okta 
@okta/developerdocs
> OKTA-274761 : API Doc: OAuth for /api/v1/policies

- packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
- The name of an existing user type cannot be changed
- This is tied to release 2020.02.0
* [OKTA-276302](https://oktainc.atlassian.net/browse/OKTA-276302)
> The name of a user type cannot be changed

- packages/@okta/vuepress-theme-prose/assets/css/components/_top-bar.scss
- **What's changed?** Update to add height to toggle div to fix safari issues
Resolves #954 
From left to right. Brave, Chrome, Safari, Firefox
> [Prose]: Fixes top bar height for Safari

- packages/@okta/vuepress-theme-prose/assets/css/components/_reference.scss
- **What's changed?** Fixes the img height for Safari on the reference landing pages.
Resolves #955 
TL: Brave
TR: Chrome
BL: Safari
BR: Firefox
> [Prose]: IMG Height Reference Landing

- packages/@okta/vuepress-theme-prose/assets/css/components/_breadcrumb.scss
> [Prose]: Remove extra breadcrumb padding

- packages/@okta/vuepress-theme-prose/assets/css/components/_top-bar.scss
- **What's changed?** Updates the z-index for top-bar submenu to be over search bar
resolves #986
> Force submenu to be above search

- packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
- **What's changed?** Add max width to content area to fix firefox bug
> Update max-width to fix firefox bug

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/oktatookta/appidpinokta.md
- **What's changed?** Removed trailing slash for the Issuer example present in the OIDC Identity Provider configuration as the issuer generated by Okta as authorization server does not have a trailing slash 
> Remove trailing slash for Issuer in OIDC IDP config

- packages/@okta/vuepress-theme-prose/assets/css/okta/pages/guides.scss
- packages/@okta/vuepress-theme-prose/util/frameworks.js
- Adds icons for OIDC and SAML to stack selector. These are the same icons used in the Developer and Admin Consoles.
- When stack selector names are truncated in smaller viewports, adds an ellipsis to indicate.
* [OKTA-279189](https://oktainc.atlassian.net/browse/OKTA-279189)
cc @IanHakes-okta
> Adds icons for OIDC and SAML to stack selector

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/.vuepress/scripts/addWorkerScript.js
This should prevent the mass prefetch.  There are still some prefetch items that are required, but should be limited.
This was removed during prose debugging and never added back in.
> Prevent Pre-fetch

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- **What's changed?** Changed `attem` to `attempt` in Syslog docs
> Fix typo in Syslog DatetimeFilter docs

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/authentication.json
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- Add Email factor in /authn API -- enroll, activate, send verification challenge (OTP), verify
- Enrollment / activation is new in the 2020.03.0 release.  (Verification was supported in the Early Access release but not previously included in this collection)
- 2020.03.0
* [OKTA-272973](https://oktainc.atlassian.net/browse/OKTA-272973)
> Add Email authn factor

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
Updated Okta Verify Push Verify doc for number matching challenge for high-risk requests.
No (but it should not be merged until the HOC link is live, which should be at some point on Monday. Verify with the ProdHelp team before merging)
* [OKTA-284109](https://oktainc.atlassian.net/browse/OKTA-284109)
@jakubvul-okta  @damianali-okta @okta/enterpriseauth-team @keithchin-okta @mpeng-okta
> Updated Okta Verify Push Verify api for number matching challenge

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md
Updated scopes section of the Implement OAuth for Okta giude
- Add okta.sessions.manage
- Add okta.sessions.read
- **Is this PR related to a Monolith release?** 2020.05.0
* [OKTA-286819](https://oktainc.atlassian.net/browse/OKTA-286819)
> OKTA-286819: Add Sessions API scopes to implement oauth for okta guide

- packages/@okta/vuepress-site/docs/reference/api/event-types/index.md
- packages/@okta/vuepress-site/docs/reference/api/events/index.md
- **What's changed?** As of the upcoming Monolith release, we will not be enforcing event type parity between the Events and Logs APIs. No new Events API event types will be added from here on out, while the Logs API will continue to add new event types.
* [OKTA-291221](https://oktainc.atlassian.net/browse/OKTA-291221)
* @bobtiernay-okta 
* @okta/developerdocs
> OKTA-291221: v1 event types no longer tracking v2 event types update

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** `/Groups` -> `/groups`
* Reader feedbacj
> Uppercase g where there shouldn't be

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md
Add scopes for Custom Templates and Trusted Origins APIs to implement oauth for okta guide
- Add 4 new scopes 
- okta.trustedOrigins.manage
- Add okta.trustedOrigins.read
- Add okta.templates.manage
- Add okta.templates.read
- **Is this PR related to a Monolith release?** Yes, 2020.05.0
* [OKTA-290657](https://oktainc.atlassian.net/browse/OKTA-290657)
> OKTA-290657: OAuth for Okta for Custom Templates & Trusted Origins

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- **What's changed?** Updates System Log API docs to include mention about time references
* [OKTA-296678](https://oktainc.atlassian.net/browse/OKTA-296678)
> OKTA-296678: Updates System Log API docs to include mention about time references

- packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
- packages/@okta/vuepress-site/docs/concepts/scim/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/attribute-mapping/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/next-steps/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/overview/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/prepare-api/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/prepare-app/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/test-qa/index.md
- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/test-scim-app/index.md
- packages/@okta/vuepress-site/docs/reference/scim/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
1. Clarify the difference between "App" and "Integration" in SCIM Guide
* This update changes most of the files in the SCIM guide, concept and reference topics to clarify when we mean an "integration" (an Okta thing) and and "application" (a customer's cloud application). There was a fair amount of ambiguity in the use of these terms throughout our SCIM documentation, so this set of changes aims to correct that.
2. Clarify the deletion action in SCIM applications
* In several places we discuss the DELETE operation for SCIM provisioning, but there is not a clear outline of what happens when the deletion of the user resource occurs on the Okta integration side, or on the customer's SCIM application end.
* A single set of rules has been laid out in the concepts topic, …
> Updates to SCIM guide

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/react-native/installsdk.md
As the minimum `react-native` version supported in `okta-react-native` is v0.60, the configuration guide for `react-native` under v0.60 will not be needed anymore. 
* [OKTA-292803](https://oktainc.atlassian.net/browse/OKTA-292803)
> doc: update react-native doc to only support version above 0.60 - OKTA-292803

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- **What's changed?** Improves the consistency of the `/logs` API rate limits section wrt to other pages
* [OKTA-299825](https://oktainc.atlassian.net/browse/OKTA-299825)
> OKTA-299825: Improves the consistency of the `/logs` API rate limits section wrt to other pages

- packages/@okta/vuepress-theme-prose/components/OnThisPageItem.vue
- prevent 'cannot read property offsetTop of null' from crashing page
- No
> prevent 'cannot read property offsetTop of null' from crashing page

- packages/@okta/vuepress-site/quickstart-fragments/nodejs/express-auth-code/index.md
Adding `appBaseUrl` config for express auth code guide
* [OKTA-302260](https://oktainc.atlassian.net/browse/OKTA-302260)
> fix: add missing config for nodejs express-auth-code - OKTA-302260

- packages/@okta/vuepress-site/docs/guides/sign-your-own-saml-csr/upload-the-certificate/index.md
- **What's changed?**  Removing 'Next' button from last page in 'Sign the Okta certificate with your own CA' guide.
> Removing Next button from last page in guide

- packages/@okta/vuepress-site/docs/concepts/scim/index.md
Updates the links from the SCIM concept topic to the AD and LDAP guides in h.o.c - they were not using the aliases, so when those topics were relocated, the links broke.
Nope
* [OKTA-309457](https://oktainc.atlassian.net/browse/OKTA-309457)
> Update SCIM concept topic links to h.o.c

- packages/@okta/vuepress-site/index.md
- **What's changed?** If you go to the root of the domain `localhost:8080` when you are developing, this PR adds a note about going to `/docs` instead with a link.
This will only show up during development.  `developer.okta.com/` is handled by AWS
* [OKTA-305658](https://oktainc.atlassian.net/browse/OKTA-305658)
> Update index to have link to /docs

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Add documentation for Multiple ACS URL API support for custom SAML apps.
- **Is this PR related to a Monolith release?** 2020.07.0
* [OKTA-304517](https://oktainc.atlassian.net/browse/OKTA-304517)
> Add documentation for Multiple ACS URL API support for custom SAML apps.

- packages/@okta/vuepress-site/docs/guides/set-up-event-hook/register-your-endpoint/index.md
- **What's changed?** The guide previously mentioned 'Authentication' as a typical name for the header, but 'Authorization` would be more typical, so changing to that.
> Updating recommended name for Authorization header for Event Hooks

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
Update verify push factor polling doc to include profile information
The example responses provided in the push factor polling api doc do not display the additional `profile` metadata that is returned. `profile` contains a lot of information like `username`, `deviceType`, `name`, `platform`, `version` and `keys` [[examples here](https://oktainc.atlassian.net/browse/OKTA-210969?focusedCommentId=1341314)] But since we dont want to go into too much detail in example doc, I have added only username in `profile` metadata and replaced additional details with `...`
Resolves: OKTA-210969
The example responses for verify push factor polling doc [[linked here](https://developer.okta.com/docs/reference/api/factors/#verify-a-push-factor-challenge)] do not contain the profile …
> Update verify push factor polling doc

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Adding redirect from /docs/guides/add-an-external-idp/facebook/add-okta-redirect-uri-to-idp/ to /docs/guides/add-an-external-idp/facebook/create-an-app-at-idp/
- No
> Redirect for add-okta-redirect-uri-to-idp

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/create-okta-application/index.md
There is a page change in the middle of step one
Maybe just splitting it into another step would help?
The diff looks worse than it is, the actual change is probably 50 characters
> Add missing "next" button when creating an OIDC app

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/configure-packages/springboot/configmid.md
The first step in this example was previously updated, but this step which contains the full config was never updated
> Correct invalid config in spring-boot example

- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
Update the example to use UUIDs (as are used evereywhere else) instead of emails as the unique identifier for the group PATCH operation example.
No
* [OKTA-315500](https://oktainc.atlassian.net/browse/OKTA-315500)
> Update the SCIM reference example based on user feedback

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Modified the response parameters and response example for Delete User operation in order to reflect the correct response 204 No Content instead of 202 Accepted.
> 204 response for user deletion operation

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
Group Rule has a required type `property` that is undocumented, and this PR adds that into the developer doc.
No
* [OKTA-304036](https://oktainc.atlassian.net/browse/OKTA-304036)
@jakubvul-okta @okta/eng-extensibility
> OKTA-304036: Reader Feedback: Group Rules API Missing Required Property

- packages/@okta/vuepress-site/docs/guides/build-sso-integration/before-you-begin/openidconnect/prep.md
Updates the SSO guide to clarify that for apps intended for publication in the OIN, only OIDC apps that use the Web backend and an authorization code flow.
No
* [OKTA-320981](https://oktainc.atlassian.net/browse/OKTA-320981)
> Updates OIDC instructions for OIN - Web, auth flow only

- scripts/broken-link-checker.js
- Adds github edit links to the list of link checking exceptions (these links currently exist but are not visible)
- No
The noise when validating external links
> Adds github edit to link checking exceptions

- packages/@okta/vuepress-site/code/library-versions/index.md
- okta-auth-js was listed with wrong retirement for 2.x and didn't list 4.x on the /code/library-versions/ page.
- No
* [OKTA-327605](https://oktainc.atlassian.net/browse/OKTA-327605)
> Updates auth-js versions

- packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
Added coverage to the SCIM reference guides that explain what happens when a user is created in a downstream app that has custom user attributes defined in the schema.
No
* [OKTA-328487](https://oktainc.atlassian.net/browse/OKTA-328487)
> Resolves OKTA-328487 - adding custom attributes

- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
**What's changed?** 
- Clarified that the `Referrer-Policy` is a  response header that is included.
- Removed the bullet point (kept indent under `response_mode`) to clarify the list of potential values does not include this item.
**Is this PR related to a Monolith release?** No
> Fix Referrer-Policy header explanation for OIDC response-mode

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/user-info/react/getuserinfo.md
-  Adds the `_isMounted` variable to the class-based component on the getuserinfo.md page
- Sets `_isMounted` to false when the component unmounts
- This prevents the component from calling a state update on an unmounted component
- More details can be found [here](https://devforum.okta.com/t/warning-displays-when-using-okta-docs-to-add-user-auth-to-react-app/10656)
- N/A
I don't have access to your JIRA! I'm a candidate for one of the Dev Support Engineer roles and noticed this issue when I implemented sign in on my SPA with React.
> 🐛 Updates 'Get info about user' react example

- scripts/broken-link-checker.js
- **What's changed?** removes a lot of console.logs from the link checker to clean up logs in travis
Changes:
To:
> remove console.log from many places in link checker

- packages/@okta/vuepress-site/docs/reference/password-hook/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?**  Minor doc fixes in the following files: 
http://localhost:8080/docs/reference/registration-hook/  
one misspelling
https://developer.okta.com/docs/reference/password-hook/
a few definite articles missing; missing period; and minor typo in object name
* n/a
> Updates two reference docs

- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/test-scim-app/index.md
Runscope removed the test results resulting in a 404 for this link. Temporarily removing the link and associated text until the issue can be resolved.
No
* [OKTA-332238](https://oktainc.atlassian.net/browse/OKTA-332238)
> Updates SCIM app testing instructions to remove 404 link

- packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
- Fixed problem with content nav displaying incorrectly - wrong width and horizontal scroll.  Now mobile widget "On this page" is displayed when screen width <= 1024px, not only for mobile. 
State before: 
State after:
* OKTA-331496](https://oktainc.atlassian.net/browse/OKTA-331496)
> Fixed content nav display

- packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
- packages/@okta/vuepress-theme-prose/assets/css/components/_sidebar.scss
- packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
* tree nav gets fixed width
* clicking triangle icon expands/collapses item
* line breaks are consistent between collapsed and expanded states
No
Before:
After:
* [OKTA-327765](https://oktainc.atlassian.net/browse/OKTA-327765)
> OKTA-327765: Tree nav width and arrows

- packages/@okta/vuepress-site/.vuepress/nav/codePages.js
- packages/@okta/vuepress-site/code/angular/index.md
- packages/@okta/vuepress-site/code/react/index.md
- packages/@okta/vuepress-site/code/vue/index.md
- **What's changed?** This PR fixes the left nav so it expands for Vue Guides. I also changed the order of menu items so Sign-In Widget comes before the Auth JS SDK, which seems reasonable.
Vue Guides Before:
Vue Guides After:
Left nav with Auth JS first and "Overview" instead of "Auth JS":
Left nav after:
> Fix navigation for Vue Guides 

- packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
* shrink empty tree-nav for mobile viewports
* set fixed tree-nav width for desktops only
No
* [OKTA-328009](https://oktainc.atlassian.net/browse/OKTA-328009)
> OKTA-328009: Extra space on mobile viewports

- packages/@okta/vuepress-theme-prose/components/ContentPage.vue
- packages/@okta/vuepress-theme-prose/components/OnThisPage.vue
- packages/@okta/vuepress-theme-prose/components/OnThisPageItem.vue
- packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
- packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- tests/selenium/framework/page-objects/BasePage.js
- tests/selenium/framework/shared/util.js
- tests/selenium/spec/page-content-spec.js
* add scroll correction for non-100% screen scale
* scroll page title into view on direct URL navigation w/o anchor set
* move static values out of the loop
* attach click handlers to non-heading anchors
* selenium test for scroll-to-heading
No
* [OKTA-320836](https://oktainc.atlassian.net/browse/OKTA-320836)
> OKTA-320836: In-page link target headings do not take user to the right content nav section

- packages/@okta/vuepress-site/docs/guides/find-your-domain/findorg/index.md
- **What's changed?** In the Basics guide, "Find your Okta domain" topic is updated with a note to provide an alternative way to find the Okta URL.
* [OKTA-338985](https://oktainc.atlassian.net/browse/OKTA-338985)
> Updated "Find your Okta domain" page in the Basics guide

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-theme-prose/assets/css/components/_editLink.scss
- packages/@okta/vuepress-theme-prose/assets/css/prose.scss
- packages/@okta/vuepress-theme-prose/components/PageTitle.vue
- packages/@okta/vuepress-theme-prose/layouts/Layout.vue
This change moves the 'edit link' from the PageTitle component to the Layout, as PageTitle is NOT use for every page
**NOTE:**
* Edit link is at the bottom of page
* It is only shown when screen size is bigger than a tablet 
* css is minimal, someone may want to improve it before merging
Example:
The browser URL: 
```
/docs/guides/sign-users-out/android/before-you-begin/
```
shows a link to 
```
https://github.com/okta/okta-developer-docs/edit/master/packages/@okta/vuepress-site/docs/guides/sign-users-out/android/before-you-begin//index.md
```
NFDEPLOY
> Add GitHub edit link to bottom of content pages

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
Add missing description for `expand` query param in `List groups` section.
This is what it looks like with the change:
No
* [OKTA-341635](https://oktainc.atlassian.net/browse/OKTA-341635)
> Add missing `expand` param description in list groups section.

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
Removes restrictions on System Log API SCIM filter operators.
2020.11.0
* [OKTA-338445](https://oktainc.atlassian.net/browse/OKTA-338445)
> OKTA-338445: Removes restrictions on System Log API SCIM filter operators

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/angular/reqautheverything.md
https://developer.okta.com/docs/guides/sign-into-spa/angular/require-authentication/
For Angular user should protect all routes except login callback one (with path like `login/callback` and component `OktaCallbackComponent`)
No
* [OKTA-336830](https://oktainc.atlassian.net/browse/OKTA-336830)
> Require authentication for everything > Angular - callback route should be unprotected

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/user-info/angular/getuserinfo.md
-  Change text on [Get info about the user](https://developer.okta.com/docs/guides/sign-into-spa/angular/user-info/) page:`getUser()` method returns claims object, not array (example of returned claims: [here](https://developer.okta.com/docs/reference/api/oidc/#response-example-success-5))
* [OKTA-327081](https://oktainc.atlassian.net/browse/OKTA-327081)
> Typo: getUser() method returns claims object, not array

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/entitlements/index.md
- Add the initial ASA docs, namely the sudo Entitlements documentation
> Add ASA Entitlements Documentation

- packages/@okta/vuepress-site/.vuepress/nav/main.js
- packages/@okta/vuepress-site/.vuepress/nav/reference.js
- packages/@okta/vuepress-site/docs/reference/api/asa/attributes/index.md
- Add the initial ASA docs, namely the introduction and service users.
> Add ASA Attributes

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
removed PROFILE_MASTERING feature example from “App administrator role App targets” API Doc 
https://developer.okta.com/docs/reference/api/roles/#response-example-13
* [OKTA-338565](https://oktainc.atlassian.net/browse/OKTA-338565)
> removed PROFILE_MASTERING feature example from docs

- packages/@okta/vuepress-site/docs/reference/api/user-types/index.md
- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Fix link on "full replace of an existing user" under the "Specify the User Type of a new user" section
> Fix Incorrect Link Specify User Type of a New User

- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/create-org/cli/create-org.md
- packages/@okta/vuepress-site/docs/guides/quickstart/create-org/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/create-org/website/create-org.md
- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/cli/register-app.md
- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/index.md
- packages/@okta/vuepress-site/docs/guides/quickstart/register-app/website/register-app.md
Reverts https://github.com/okta/okta-developer-docs/pull/1521 and cleans things up a bit.
- **What's changed?** Add the Okta CLI
> Add Okta CLI to QuickStart Guides

- packages/@okta/vuepress-site/docs/guides/submit-app/overview/index.md
Resolves OKTA-342532 on removing SLA text for OIN submissions
No - this goes live with the release of 2020.12.0 on production, but is not directly tied to the monolith release.
* [OKTA-342532](https://oktainc.atlassian.net/browse/OKTA-342532)
> SLA updates to OIN Guide

- packages/@okta/vuepress-site/docs/reference/password-hook/index.md
- **What's changed?** Updated Password Import Inline Hook Reference to align text with code sample. Replaced `data.credential` with `data.context.credential`
* [OKTA-353661](https://oktainc.atlassian.net/browse/OKTA-353661)
> OKTA-353661 - Password Import Inline Hook Reference Minor Update

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-serviceapp-grantscopes/index.md
- **What's changed?** Correct typo for /clients endpoint had a typo (said oauth instead of oauth2)
> Corrected typo

- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
When we made the `format` field of the `login` property modifiable (to support non-email logins), we documented it under "User Profile base subschema" but missed another place that links to there: the description of the "Update User Profile Schema property" command.  I felt that the list of allowed modifications there was getting unwieldy, so I rearranged the sentence to make it more concise.
- Description of "Update Schema" now says it can change the login format.
- Bugfix; not related to a Monolith release
* [OKTA-348953](https://oktainc.atlassian.net/browse/OKTA-348953)
> Fix omission re modifying base properties

- packages/@okta/vuepress-site/code/index.md
link needs to go to https://developer.okta.com/code/dotnet/aspnetcore/ to prevent a broken empty page
> updating .NET link

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
`status` in response will be `ACTIVE` (not `STAGED`) when `activate=true` is used in the request.
- **What's changed?** Fixed Create User with Password response example.
> Fixed Create User with Password response example

- packages/@okta/vuepress-site/docs/guides/configure-access-policy/limit-scopes-clients-can-access/index.md
- packages/@okta/vuepress-site/docs/guides/customize-authz-server/test-authz-server/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-returned-from-okta/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/request-token-claim/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-sign-jwt/index.md
- packages/@okta/vuepress-site/docs/guides/request-user-consent/verification/index.md
We've launched token.dev as a replacement for jsonwebtoken.io. We'll be configuring jsonwebtoken.io to redirect to token.dev soon, but we wanted to replace the references in the docs.
> changed all occurrences of jsonwebtoken.io to token.dev

- packages/@okta/vuepress-site/docs/concepts/identity-providers/index.md
Twitter is not listed as an option in <https://developer.okta.com/docs/concepts/social-login/>, so we probably shouldn't reference it as an example.
- **What's changed?** Replace Twitter with Apple as a social login example.
> Remove Twitter since it's not a valid social IdP

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** GROUP_API_APP_GROUP_ENHANCEMENTS, which is going GA in production next month, adds `source` and `source.id` to group objects returned from the API. In our API documentation, we currently have EA labels around those. This pull request removes the EA labels that were added in https://github.com/okta/okta-developer-docs/pull/1459. I manually tested that the documentation changes look good when built locally.
- **Is this PR related to a Monolith release?** Yes, 2021.01.0 - see [OKTA-326611](https://oktainc.atlassian.net/browse/OKTA-326611)
- @donwoods-okta @johnhuang-okta 
* [OKTA-342024](https://oktainc.atlassian.net/browse/OKTA-342024) - JIRA to add this documentation
* [OKTA-326611](https://oktainc.atlassian.net/browse/OKTA-326611) - JIRA which this documentation is …
> Remove EA labels from group `source` and `source.id` references

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/apps.json
- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
Add docs for changes/additions to Apps API endpoints. i have separated out the PR into 4 commits for easier reviewing. 
All new docs are under Apps section of docs.
Modified:
Apps > `Models` > `Application Object` > separateed `App Names and Settings` to `App Names` and `App Settings`
New sections added:
Apps > `Application Logo operations`
Apps > `Application Provisioning Connection operations`
Apps > `Application Features operations`
Apps > `Models` > `Provisioning Connection object`
Apps > `Models` > `Provisioning Connection Profile object`
Apps > `Models` > `Application Feature object` 
commit 1:
* adds `notes` to the application settings object.
* adds `autoLaunch` to application `visibility` object
---
commit 2:
* add documentation for logo upload: …
> add apps api ea docs

- packages/@okta/vuepress-theme-prose/assets/css/components/_footer.scss
- **What's changed?** Adjust spacing between social icons on mobile/tablet
* [OKTA-355567](https://oktainc.atlassian.net/browse/OKTA-355567)
> Adjust spacing between social icons on mobile/tablet

- packages/@okta/vuepress-site/signup/thank-you/index.md
- packages/@okta/vuepress-theme-prose/assets/css/components/_thankYou.scss
- packages/@okta/vuepress-theme-prose/assets/css/prose.scss
- packages/@okta/vuepress-theme-prose/global-components/Login.vue
- packages/@okta/vuepress-theme-prose/global-components/ThankYou.vue
- **What's changed?** Add a signup success page
* [OKTA-361043](https://oktainc.atlassian.net/browse/OKTA-361043)
Went without this section:
Because this exact information is already in the footer right below where it would be:
> Add a signup success page

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- /api/v1/users/{id}/lifecycle/activate can be performed on users with "DEPROVISIONED" status.
@nghadge-okta @okta/ud-core
> Fix mistake on user lifecycle update doc.

- packages/@okta/vuepress-site/.vuepress/config.js
- Change `2020` for `2021` in footer's copyright text
* [OKTA-361721](https://oktainc.atlassian.net/browse/OKTA-361721)
> Adjust copyright text

- packages/@okta/vuepress-site/pricing/index.md
- Fixed "Get more details " link in "What are the rate limits for Okta's APIs" section to match right url
- Dynamic Scale Add-On link is fixed to match right url
* [OKTA-361515](https://oktainc.atlassian.net/browse/OKTA-361515)
* [OKTA-361525](https://oktainc.atlassian.net/browse/OKTA-361525)
> Links fixed in pricing page 

- packages/@okta/vuepress-site/index.md
- **What's changed?** Seems the icon link and doc link were mixed up when rebasing, this addresses it
* [OKTA-360151](https://oktainc.atlassian.net/browse/OKTA-360151)
Before
After
> Fix mixed up link and image for android

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
attributeStatements.values is an Array of String, not a single String.
- **What's changed?** Fixed attributeStatements.values data type.
> Fixed attributeStatements.values data type

- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/use-flow/index.md
- This link leads to an anchor that does not exist. I pulled up google cache and found it used to just say, look below, so I don't think it was ever meant to be a link. Please let me know if I'm off here. (reported by Tim Lopez in #web)
No
n/a, reported by someone in #web slack channel
> Removed non-existent anchor link

- packages/@okta/vuepress-theme-prose/assets/css/components/_pricing.scss
- packages/@okta/vuepress-theme-prose/components/Pricing.vue
> Fixed checkmark styling issue on the Pricing page
> Fixed text alignment of sub note on the Pricing page 
> No
**Before:** 
**After:**
* [OKTA-362682](https://oktainc.atlassian.net/browse/OKTA-362682)
> Fixing styling issues on the Pricing page

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/add-signin-button/angular/login-redirect.md
> The Angular docs refers to a deprecated method "loginRedirect" that does not exist anymore (https://developer.okta.com/docs/guides/sign-into-spa/angular/add-signin-button/). This has now been updated to the correct method "signInWithRedirect".
> No
**Before:**
**After:**
* [OKTA-362112](https://oktainc.atlassian.net/browse/OKTA-362112)
> Updating deprecated loginRedirect method with the correct one

- packages/@okta/vuepress-site/docs/guides/protect-your-api/next-steps/go/samples.md
Current link is broken, edited to: https://github.com/okta/samples-golang
No
n/a, reported in https://okta.slack.com/archives/CM6EN4KUN/p1611627599019800
> Fixed broken link for Golang samples

- packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/session-and-persistent-sso/ios/enablesso.md
Resolves: OKTA-321310
Add a note about `Default Rule` to make sure that a user copied a custom rule' `id` for further correct requests.
No
* [OKTA-321310](https://oktainc.atlassian.net/browse/OKTA-321310)
> iOS SSO: Add a note about Default Rule

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/gather-information/index.md
- ZeroSSL offers a SHA-384 encrypted cert, which does not work for Okta, so we should not refer to it as a possible vendor for certs.
- no
n/a, surfaced from https://okta.slack.com/archives/CM6EN4KUN/p1611780594037700 and https://github.com/okta/okta-developer-docs/pull/1855
> removed reference to ZeroSSL

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app/next-steps/go/samples.md
- Fixed broken link to golang sample apps: https://github.com/okta/samples-golang (correct link)
- 
no
reported by SE:
https://okta.slack.com/archives/CM6EN4KUN/p1611786166042600
> Fixed broken link to go samples

- packages/@okta/vuepress-site/conductor.yml
- Removing /live-widget from conductor.yml so we can redirect it to the old Drupal page
* [OKTA-362883](https://oktainc.atlassian.net/browse/OKTA-362883)
> remove /live-widget from conductor.yml

- packages/@okta/vuepress-site/docs/guides/build-provisioning-integration/configure-app/index.md
- Change references to "Profile Masters", "mastering", etc., to use "Sources", "sourcing" etc.
- Also fix one tiny typo (determine -> determines).
- Verified that the link to help.okta.com can also use Sources in the URL.
- Not related to a Monolith release (Profile Sources feature and related docs are already changed).
* [OKTA-366544](https://oktainc.atlassian.net/browse/OKTA-366544)
> Update terminology to match renamed "Profile Sources" feature

- packages/@okta/vuepress-site/pricing/index.md
- Fixed missing "9" for our availability claim of four 9's: 99.99%
- no
* Reported to me by PMM (Jiong Liu)
> Fixed missing 9 for availability

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/create-service-app/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/overview/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/test-integration/index.md
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/update-default-provider/index.md
- **What's changed?** New Beta documentation to support Third-Party Risk Integration with Okta. References two new Risk APIs
- **Is this PR related to a Monolith release?** Yes, 2021.02.0
* [OKTA-345711](https://oktainc.atlassian.net/browse/OKTA-345723)
> Beta Guide: Third-Party Risk Integration

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/.vuepress/public/sitemap_index.xml
- packages/@okta/vuepress-site/.vuepress/scripts/strip-guide-parts-from-sitemap.js
> Fixing the sitemap link. Previously we were displaying the sitemap under the 'docs-sitemap' alias.
> No
* [OKTA-362166](https://oktainc.atlassian.net/browse/OKTA-362166)
**Netlify Build
https://6016f373b01495f73debdbe0--reverent-murdock-829d24.netlify.app/sitemap.xml
> Fixing sitemap link 

- packages/@okta/vuepress-site/docs/guides/build-sso-integration/specify-your-settings/openidconnect/settings.md
Added a statement to indicate that Refresh Token is not an allowed grant type for OIN app integrations.
Cleaned up a few language/terminology items.
No
* [OKTA-365891](https://oktainc.atlassian.net/browse/OKTA-365891)
> Remove refresh token as option for OIN Web apps

- packages/@okta/vuepress-site/data/event-types.json
- **What's changed?** Updated the beta flags to false in `event-types.json` to display `user.mfa.factor.suspend` and `user.mfa.factor.unsuspend`
* [OKTA-368631](https://oktainc.atlassian.net/browse/OKTA-368631)
> OKTA-368631 - Updated beta flags to false so missing Event Types display

- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-dynamic-scale/index.md
- **What's changed?** add `/login/sessionCookieRedirect` to dynamic scale and workforce license rate limit page 
- **Is this PR related to a Monolith release?**  Yes. 2021.02.2
* [OKTA-370588](https://oktainc.atlassian.net/browse/OKTA-370588)
> add /login/sessionCookieRedirect to dynamic scale and workforce license rate limit page

- packages/@okta/vuepress-site/docs/reference/rl-global-enduser/index.md
Reverts okta/okta-developer-docs#1883
This is for the March release. So, it needs to be reverted.
> Revert "added table row"

- packages/@okta/vuepress-theme-prose/global-components/EventTypes.vue
- **What's changed?** OKTA-371941: Performs event type filtering to only include documented event types.
* [OKTA-371941](https://oktainc.atlassian.net/browse/OKTA-371941)
> OKTA-371941: Performs event type filtering to only include documented event types.

- scripts/update-se-drivers.js
- Updates the selenium webdriver update script to use the more safe variant `execFileSync` instead of `execSync`
* [OKTA-367550](https://oktainc.atlassian.net/browse/OKTA-367550)
> Updates the webdriver script with execFileSync

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/add-signin-button/vue/login-redirect.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/configure-the-sdk/vue/config.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/define-callback/vue/define-route.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/handle-callback/vue/handle-callback.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/install-sdk/vue/installsdk.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/require-authentication/vue/reqauthspecific.md
Updated guide [Sign users in to your SPA](https://developer.okta.com/docs/guides/sign-into-spa/vue/define-callback/) to `@okta/okta-vue@3.x`
Affected pages:
https://developer.okta.com/docs/guides/sign-into-spa/vue/define-callback/
https://developer.okta.com/docs/guides/sign-into-spa/vue/configure-the-sdk/
https://developer.okta.com/docs/guides/sign-into-spa/vue/add-signin-button/
https://developer.okta.com/docs/guides/sign-into-spa/vue/handle-callback/
https://developer.okta.com/docs/guides/sign-into-spa/vue/require-authentication/
No
* [OKTA-358830](https://oktainc.atlassian.net/browse/OKTA-358830)
> Update 'Sign Users In' guide to @okta/okta-vue@3.x

- packages/@okta/vuepress-site/docs/guides/production-deployment/deployment-checklist/index.md
Added a bullet point calling out bulk user migration as a step for the deployment checklist, and added a blurb to ask user to check their email notification settings.
This was a request from product leadership (Grace W and Arnab):
1. Today, MFA reset emails are set to on by default. 
2. Recently, major customers (Cisco, Pinterest) have run into issues with MFA reset emails being sent to millions of customers as part of an internal migration process and are asking that these be turned off by default. These are generally CIAM use cases. 
3. However, from a workforce use case perspective, there is benefit and value to having these turned on by default as this helps drive education and adoption and 77% of our customers leave this on.
The decision is we will turn off email notifications by …
> Updating the deployment checklist for email pain point

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
* Add a new AuthType: LDAP_INTERFACE to policy api documentation
2021.03.0. (confirm with John Huang)
* OKTA-343973
> OKTA-343973: Add LDAP_INTERFACE AuthType to policy api documentation

- packages/@okta/vuepress-site/docs/reference/api/authorization-servers/index.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?**: fix incorrect value for issuer mode in developer docs: use `CUSTOM_URL` instead of `CUSTOM_URL_DOMAIN`
- **Is this PR related to a Monolith release?**: no
* [OKTA-375477](https://oktainc.atlassian.net/browse/OKTA-375477)
> fix incorrect value for issuer mode: use CUSTOM_URL instead of CUSTOM_URL_DOMAIN

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/get-refresh-token/index.md
The example did include the offline_access scope to the token end point, contradicting "The authorization code flow is unique in that the `offline_access` scope must be requested as part of the code request to the `/authorize` endpoint and not the request sent to the `/token` endpoint." testing show it should be left out of the request.
> Removed offline_access scope from example

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- The docs say when fetching a user by login, you must URL encode the request parameter. The request example shows the parameter NOT URL encoded. A customer reached out to Dev Support and was confused by this.
N/A
> URL encode request parameter

- packages/@okta/vuepress-site/docs/reference/api/oie-policy-types/index.md
Earlier all V2 policy types has a limit of 500 total for all policy types. This limit has been revised as,
per org to 5000 for App Sign On policy
and 500 for Profile Enrollment policy.
This information is being updated on developer docs.
- No
* [OKTA-369713](https://oktainc.atlassian.net/browse/OKTA-369713)
> OKTA-369713  Update doc to reflect new increases policy v2 limit

- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
The previous docs left it ambiguous what happened if no response was returned. I think this makes it clearer.
No
> Clarify behavior when no response is received by the registration hook

- packages/@okta/vuepress-site/docs/guides/implement-auth-code/use-flow/index.md
Remove extra empty `redirect_uri` query parameter from example authorize URL
> Remove redundant redirect_uri from example

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/add-signin-button/react/login-redirect.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/use-the-access-token/react/getaccesstoken.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/user-info/react/getuserinfo.md
- packages/@okta/vuepress-site/docs/guides/sign-users-out/sign-out-of-okta/react/remotesignout.md
Update React code demo to use `oktaAuth` instead of `authService` from old okra-react versions
* [OKTA-374894](https://oktainc.atlassian.net/browse/OKTA-374894)
> Updated okta-react code demo

- packages/@okta/vuepress-site/docs/reference/api-overview/index.md
- **What's changed?** Added `ne` Operator, `not` Attribute operator, and removed note about us not supporting the `ne` operator.
* [OKTA-188737 ](https://oktainc.atlassian.net/browse/OKTA-188737 )
> Updating Operators

- packages/@okta/vuepress-site/docs/guides/submit-app/submission2-specific/saml2/submit.md
Added instruction that SSO URL fields can now accept non-static URL values.
Fixed typo.
Yes. 2021.04.0
* [OKTA-380611](https://oktainc.atlassian.net/browse/OKTA-380611)
> Update SAML instructions for dynamic SSO URLs

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
Include a statement noting that the `matches` operator is available to evaluate regular expressions in Conditional Expressions section.
Add missing formatting around `=` operator.
No
> Include "matches" operator in Conditional Expressions section of Expression Language reference

- packages/@okta/vuepress-site/docs/concepts/key-rotation/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- **What's changed?** OKTA-382893 : added cache-control note in key-rotation concept and api/oidc/key endpoint
* [OKTA-382893](https://oktainc.atlassian.net/browse/OKTA-382893)
> OKTA-382893 - added cache-control note in key-rotation concept and api/oidc/key endpoint

- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/overview/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
**What's changed?** 
- Added a note in the [Registration Inline Hook API ](https://developer.okta.com/docs/reference/registration-hook/) reference page to highlight SSR must be enabled and used with SIW. Also fixed a broken code block.
- Added same note and info on SSR to [Registration Inline Hook Guide ](https://developer.okta.com/docs/guides/registration-inline-hook/nodejs/overview/)
**Is this PR related to a Monolith release?** No
* [OKTA-380150](https://oktainc.atlassian.net/browse/OKTA-380150)
> Okta-380150 Add SSR and SIW requirements for Registration Hook Guide and API Reference

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
Please see `q` parameter docs of "List users assigned to application" endpoint:
https://github.com/okta/okta-developer-docs/blob/afdc0949909ad575a837fb86343014ca5bdd5bfe/packages/%40okta/vuepress-site/docs/reference/api/apps/index.md#list-users-assigned-to-application
It clearly documents that the q parameter is used with `startsWith` matching instead of exact matching. The type of matching performed is really important to know for API users. `/api/v1/apps` endpoint treats `q` request parameter similarly to `/api/v1/apps/${applicationId}/users` endpoint and uses `startsWith` matching.
[Obvious Fix](https://developer.okta.com/cla/#what-is-considered-an-obvious-fix), CLA submitted 20200804.
> Improve list apps endpoint's q request parameter docs

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
Tested by Frank Benus (CIAM Specialist at Okta)
Added a bullitpoint in the note for primary auth-n with an activation token. The api key is optional and in case of a SPA very confusing.
> Add note on optional Authorization header

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md
- **What's changed?** Added okta.domain.manage and okta.domain.read to supported oauth2 scopes page
- **Is this PR related to a Monolith release?** Yes, 2021.05.0
* [OKTA-381286](https://oktainc.atlassian.net/browse/OKTA-381286)
> add okta.domain.manage and okta.domain.read to supported scopes page

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
Adds docs about the "co" operator and filters in the `/logs` API
- **Is this PR related to a Monolith release?**  Yes, `2021.05.0`
* [OKTA-388434](https://oktainc.atlassian.net/browse/OKTA-388434)
> OKTA-388434: Adds docs about the "co" operator and filters in the `/logs` API

- packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
- Update SAML inline hook doc to add `SessionNotOnOrAfter` support. Okta now allows clients to add `sessionLifetime` using inline hook command which will calculate `SessionNotOnOrAfter` value and return it in SAML assertion response. 
More details: [OKTA-353804](https://oktainc.atlassian.net/browse/OKTA-353804)
- **Is this PR related to a Monolith release?** Yes. Monthly Release: 2021.05.0 , Date: 4/30/2021
* [OKTA-380909](https://oktainc.atlassian.net/browse/OKTA-380909)
> Update saml inline hook doc to add SessionNotOnOrAfter support

- packages/@okta/vuepress-site/docs/reference/api/iam-roles/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
**What's changed?**
- Updated third-party admin status to be more flexible. You can update third-party status without the need of adding an admin/role, you're able to update the third-party status alone.
- Also added missing groups endpoint which covers granting third-party admin.
**Is this PR related to a Monolith release?**
- 2021.05.0
* [OKTA-381780](https://oktainc.atlassian.net/browse/OKTA-381780)
> Update Third-Party Admin Api Doc

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/scopes/index.md
- **What's changed?** Fixed a typo in the okta.domains.manage and okta.domains.read oauth2 scopes, which was released in 2021.05.0
> fix typo in the oauth2 domains scopes

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** `EXTENSIBLE_GROUP_SEARCH_API` is GA (almost) everywhere in production (and should be by the end of the week). Our API documentation has "EA" labels next to this functionality. Now that we are GA, the "EA" labels should be removed. This pull request removes the "EA" labels that were added in https://github.com/okta/okta-developer-docs/pull/1459. I manually tested that the documentation changes look good when built locally.
- **Is this PR related to a Monolith release?** Not a monolith release, but we should hold off until the rollout is complete near the end of the week.
* [OKTA-342026](https://oktainc.atlassian.net/browse/OKTA-342026)
- @chenningzhang-okta
- @okta/ud-core
> Remove EA labels from group search API documentation

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/android/installsdk.md
- packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/configure-packages/android/installsdk.md
Corrected references to ```com.okta.oidc.android:okta-oidc-androidx``` & ```com.okta.oidc.android:okta-oidc-android```. The correct artifacts are ```com.okta.android:oidc-androidx``` & ```com.okta.android:oidc-android``` respectively.
> [FIX] Incorrect Android artifacts resolves #2133

- packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
Followed guidance from: 
https://oktawiki.atlassian.net/wiki/spaces/DOC/pages/2004649380/OIE+API+Reference+Documentation+Guidance
- **What's changed?** Add new profile_reload rate limit type and also included an example event.
- **Is this PR related to a Monolith release?**  Yes, related to https://github.com/okta/okta-core/pull/52846
The 'profile_reload' type as well as  'AD agent' and 'LDAP agent' subtype are discussed and agreed with directories PM Tim and rate limit PM Joe.
* [OKTA-396500](https://oktainc.atlassian.net/browse/OKTA-396500)
> add support for profile reload rate limit type with example.

- packages/@okta/vuepress-site/code/vue/okta_vue_sign-in_widget/index.md
- Update `Auth.HandleCallback` -> `LoginCallback`
- The guide references using the `Auth.HandleCallback()` method for the component, which differs from the [v3.0.0 documentation](https://github.com/okta/okta-vue/tree/3.0#use-the-logincallback-component). This causes an error in real-time.
- Specify  org name of `okta-auth-js` by `@okta/okta-auth-js`
* No existing Jira ticket
> Fix Outdated Reference for Vue Sign In Widget Guide

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
This PR
- documents the Risk Score Conditions themselves,
- indicates that Risk Score Conditions can be used in rules for (classic) Okta Sign On Policies, and
- also indicates that Risk Score Conditions can be used in rules for the new OIE App Sign-On Policies (of type ACCESS_POLICY)
* [OKTA-386811](https://oktainc.atlassian.net/browse/OKTA-386811)
> Add doc for Risk Score Conditions

- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/teams/index.md
- **What's changed?**: Added documentation for new Server Update endpoints under the ASA section. 
- **Is this PR related to a Monolith release?**: No
* [OKTA-395544](https://oktainc.atlassian.net/browse/OKTA-395544)
> Add documentation for new ASA Server update endpoints

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** array referencing added to doc (i.e. the `[]` operator)
- **Is this PR related to a Monolith release?** 2021.05.03
* [OKTA-398045](https://oktainc.atlassian.net/browse/OKTA-398045)
> OKTA-398045: add array reference operator to developer doc

- packages/@okta/vuepress-theme-prose/components/Breadcrumb.vue
- **What's changed?**  "Show Content" is present on /reference/ page now
* [OKTA-369871](https://oktainc.atlassian.net/browse/OKTA-369871)
> Fixed issue with missing breadcrumbs "Show content" label in reference page

- packages/@okta/vuepress-theme-prose/global-components/StackSelector.vue
- packages/@okta/vuepress-theme-prose/global-components/StackSnippet.vue
`StackSelector` can now be rendered without passing `snippet` to show it without any content:
```vue
<StackSelector />
```
Added new component `StackSnippet`, which displays only a snippet of code/instructions without the selector:
```vue
// display block-level snippet
<StackSnippet snippet="snippetName" />
// display inline snippet
<StackSnippet snippet="snippetName" inline />
```
* [OKTA-397896](https://oktainc.atlassian.net/browse/OKTA-397896)
> Makes `snippet` on `StackSelector` optional, adds `StackSnippet` component

- packages/@okta/vuepress-site/docs/guides/implement-saml2/setup-app/index.md
Corrected sign in method to OIDC as that is the only way to create a native app integration in the AIW. Originally pointed out by @tohcnam in https://github.com/okta/okta-developer-docs/pull/2196
No
> Fixed sign-in method choice for SAML 2 Assertion

- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/exchange-code-token/index.md
- packages/@okta/vuepress-site/docs/guides/implement-auth-code-pkce/use-flow/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/create-sign-jwt/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/get-access-token/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
While implementing an auth flow I came across a few issues in the docs. This PR is a mix of fixes & nits.
- `/userinfo` is listed as a `GET` but the example given is a `POST`—I've updated it to `GET`
- There was a visible trailing `)` on one page
- The `/token` endpoint has a hard requirement for a `client_id`, but the page does not list that as a param.
- Minor syntax cleanup
> Minor improvements & nits

- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/android/installsdk.md
- **What's changed?** Jcenter has shutdown. The link redirects to a 404 page.
> Remove 404 jcenter link

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- **What's changed?** Minor change to the Event Hooks Concept. Removing the event property `data.events.uuid` and replacing with `eventId`.
* n/a
> Update event property for duplicate hooks

- packages/@okta/vuepress-site/docs/guides/build-custom-ui-mobile/configure-packages/android/installoktaauthsdk.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app/configure-packages/android/installsdk.md
- packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/configure-packages/android/installsdk.md
This includes the removal of our non androidx artifact, and move to maven central.
- **What's changed?**  Document latest release of okta-oidc-android.
* [OKTA-382038](https://oktainc.atlassian.net/browse/OKTA-382038)
> Document latest release of okta-oidc-android.

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
Just like "Get User" (https://github.com/okta/okta-developer-docs/blob/31deb2594c5fbaf4d60de1ddf96ee707af18f680/packages/%40okta/vuepress-site/docs/reference/api/users/index.md#get-user-with-login) accepts `login` and *login shortname* similarly these three endpoints that I changed also accept `login` and *login shortname*.
[Obvious Fix](https://developer.okta.com/cla/#what-is-considered-an-obvious-fix), CLA submitted on 20200804.
Please squash commits when merging.
> Improve users api related resources request parameters docs

- packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
- packages/@okta/vuepress-site/code/react/okta_react_sign-in_widget/index.md
- packages/@okta/vuepress-site/code/vue/okta_vue_sign-in_widget/index.md
- Name of  all `/` links in "Create Routes" section of pages which include `_sign-in_widget/` info is changed to `/ - index page`
- Links in upper part of pages where adjusted to new routes
* [OKTA-397842](https://oktainc.atlassian.net/browse/OKTA-397842)
> Renamed headings and fixed linking to avoid page autoscroll on top

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Fixed two links on the People Condition object of the [Policy API](https://developer.okta.com/docs/reference/api/policy/) reference.
* [OKTA-407204](https://oktainc.atlassian.net/browse/OKTA-407204)
> Switched links to refer to appropriate object

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/configure-idp-in-okta/index.md
Fixes an issue where a snippet split ordered list items, causing the numerics to reset.
By moving the snippet above the list it will allow the numerics to show the expected values.
> Moving note snippet above ordered list, to correct numerics

- packages/@okta/vuepress-site/docs/reference/rl-best-practices/index.md
In many systems (like Unix, Java, etc) Epoch timestamps are in Millies, this one is in seconds but the doc doesn't say that explicitly (if you look at the example it's clearly seconds). This just clarifies that.
> clarify that the UTC Epoch time is in seconds

- packages/@okta/vuepress-site/docs/reference/api/domains/index.md
- Update docs for Domains APIs
- Add two new fields (`certificateSourcetype` , `expiration`) in the response object
- Monolith release: 2021.07.0
* [OKTA-406710](https://oktainc.atlassian.net/browse/OKTA-406710)
> OKTA-406710 Update domain API docs

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
-   adding `pushStatus` attribute to /api/v1/apps API
```
"credentials": {
"scheme": "EDIT_USERNAME_AND_PASSWORD",
"userNameTemplate": {
"template": "user.login",
"type": "CUSTOM",
"pushStatus": "PUSH".  // the added attribute 
},
"revealPassword": true,
"signing": {}
},
```
- **Is this PR related to a Monolith release?** Yes, must be released along with GA of changes. Release: 2021.7.0
* OKTA-396834
> add doc for apps api GA change

- packages/@okta/vuepress-site/docs/guides/email-customization/customize-email-templates/index.md
Removing the EA flag, it is GA in prod for 2021.07.0
- SEND_TEST_EMAIL is now GA in production, so I removed the "EA" badge in this guide. 
- Yes, 2021.07.0, which hit production cells today July 13, 2021
* https://oktainc.atlassian.net/browse/OKTA-383818
> GA "Test Custom Email Templates"

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- **What's changed?** Remove the EA banner for group profiles since the feature is going GA in preview in the 2021.07.0 release. According to https://github.com/okta/okta-developer-docs/pull/1947, we only added these three EA banners when we added docs for group profiles.
- **Is this PR related to a Monolith release?** 2021.07.0
* [OKTA-409916](https://oktainc.atlassian.net/browse/OKTA-409916)
@donwoods-okta @daytonwilliams-okta @okta/ud-core
> Remove group profiles EA banner.

- packages/@okta/vuepress-site/.vuepress/config.js
NOTE: `primary_left_nav` is actually used for the top nav (and hamburger nav)
* [BD-635](https://oktainc.atlassian.net/browse/BD-635)
> Move the Dev Blog link to the top level of the menu bar

- packages/@okta/vuepress-site/.vuepress/config.js
- added full blog link https://developer.okta.com/blog/ vs /blog/
- No
* https://oktainc.atlassian.net/browse/BD-635
> Fixed incomplete blog link in header

- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Adding a release note to 2021.07.0 monthly RNs for Event Hook preview tab feature's move to GA. Re-using approved blurb from EA release with the addition of a link to the appropriate help.okta.com help page. Update documented on [Monthly Release Note wiki](https://oktawiki.atlassian.net/wiki/spaces/DOC/pages/2228921422/2021.07.0+Monthly+Release+Meeting+Notes).
- **Is this PR related to a Monolith release?** 2021.07.0
* n/a
> Update 2021.07.0 Release Notes with addition of Event Hook preview tab move to GA in Preview

- packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
Resolves OKTA-378618
- Update SCIM reference docs to clarify what happens with accounts that are suspended in Okta.
- No
* [OKTA-378618](https://oktainc.atlassian.net/browse/OKTA-378618)
> Updates SCIM references to correct 'suspended' user actions

- packages/@okta/vuepress-site/docs/reference/api-overview/index.md
- **What's changed?** Updated Link header section of the "API Design Principles" page to have 2 separate link header lines and removed references to the Events API.
* [OKTA-406097](https://oktainc.atlassian.net/browse/OKTA-406097)
> Update API Design Principles - Link header section

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/overview/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-events/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-providers/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
Related to OKTA-415576
- **What's changed?**  -- Marking an API as Early Access.
- **Is this PR related to a Monolith release?** Yes, 2021.08.0 (the feature flag is going EA in that release).
* [OKTA-415576](https://oktainc.atlassian.net/browse/OKTA-415576)
> Mark the risk providers, risk events API as EA

- packages/@okta/vuepress-site/docs/guides/custom-error-pages/overview/index.md
- packages/@okta/vuepress-site/docs/guides/customize-themes/index.md
- packages/@okta/vuepress-site/docs/guides/email-customization/before-you-begin/index.md
- packages/@okta/vuepress-site/docs/guides/style-the-widget/style-okta-hosted/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
As per https://oktainc.atlassian.net/browse/OKTA-413691, we wanted to add to our guide content to explain how to use the new Brands API to update your okta org theme (colors, icon, etc.)
I chose to add a single guide that explains all of what the Brands API can do, and then link to it from all the places where knowing about it would be useful (e.g. the guide to updating email templates, error pages, etc.)
- **Is this PR related to a Monolith release?** Yes. 2021.08.0
* [OKTA-413691](https://oktainc.atlassian.net/browse/OKTA-413691)
> adding brands api guide updates

- packages/@okta/vuepress-site/docs/guides/protect-your-api/before-you-begin/go/create-app.md
From https://developer.okta.com/docs/guides/protect-your-api/go/before-you-begin/, looks like https://github.com/okta/samples-golang/tree/develop/resource-server doesn't exist, proposing changing to https://github.com/okta/samples-golang/tree/master/resource-server.
* [OKTA-418015](https://oktainc.atlassian.net/browse/OKTA-418015)
> [OKTA-418015] Fix "Go Samples on GitHub" link in go/create-app.md

- packages/@okta/vuepress-site/docs/reference/api/asa/audits/index.md
- **What's changed?** Our style guide asks that "Request parameters", "Response parameters", "Request example", and "Response example" headings be at the h5 level. On the ASA Audits API page, the headings were at the h4 level.
* N/A - Part of onboarding Second Week Goals: "To get a commit into the okta-developer-docs" master.
> Correct format of headings in ASA Audits API

- packages/@okta/vuepress-site/conductor.yml
redirect https://developer.okta.com/signup/oie.html to https://developer.okta.com/signup/oie-preview.html
- no
* https://okta.slack.com/archives/C01AFUL7PKR/p1629766322089000
> Redirect for OIE dev orgs

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
Added missing property `status` to `Authenticator` documentation [here](https://developer.okta.com/docs/reference/api/authenticators-admin/).
> Add missing status property to Authenticators doc

- packages/@okta/vuepress-site/code/oie/index.md
- packages/@okta/vuepress-site/docs/concepts/redirect-vs-embedded/index.md
- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- packages/@okta/vuepress-site/docs/guides/ie-limitations/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-oie/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/android/projectstructure.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/android/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/android/softwarerequirements.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/projectstructure.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/softwarerequirements.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/projectstructure.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/sdkforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/android/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/java/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-cases/oie-embedded-sdk-use-case-sign-in-soc-idp/nodejs/summaryofsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-intro/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/activate-and-enable/index.md
- packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/index.md
- packages/@okta/vuepress-site/docs/guides/sampleapp-oie-redirectauth/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- packages/@okta/vuepress-site/docs/reference/rl-additional-limits/index.md
- packages/@okta/vuepress-site/docs/reference/rl-system-log-events/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- packages/@okta/vuepress-site/docs/release-notes/index.md
- packages/@okta/vuepress-site/signup/oie-preview.md
- **What's changed?** Updated docs to use one of the formal names for the two versions of our platform: Okta Identity Engine or Okta Classic Engine. We use the full formal name for the first mention on a page. Subsequent mentions on a page use the truncated versions of the names: the Identity Engine or the Classic Engine. Note the use of article ("the") with the truncated names, but not with the full names.
- **Other notes** If the front matter of a page contains mentions of these terms, I treat the front matter as a separate "page". That is, the first mention gets the formal name and subsequent mentions (in the front matter) get the truncated name. Also, the first mention of a name in a file may not be the first mention of a name on a page when Netlify renders it. I tried to ensure that …
> OKTA-425097 Proper engine naming

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
1. Profile Enrollment policy description updated.
2. App Sign On Policy description updated and HAL link is described.
3. Office365Client Condition removed - Office 365 team decided NOT to document that condition. They don’t want to support this via APIs.
4. Expression Language Condition added
5. Profile Enrollment spelling corrected.
This is OIE related changes, not related to any release.
* [OKTA-413579](https://oktainc.atlassian.net/browse/OKTA-413579)
> gborah-OKTA-413579_Minor_improvements_on_OIE_policy_types_docs

- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?** Fixing an improperly rendered link in the Registration Inline Hook API reference.
* n/a
> Fixing an improperly rendered link in Registration Inline Hook API reference

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- **What's changed?** Re-worded the [Scopes section](https://developer.okta.com/docs/guides/oie-embedded-common-download-setup-app/android/main/#scopes) to state: use the scopes included with your SDK. Detailed config of scopes deemed outside the scope, ahem, of the these use-cases.
* [OKTA-417605](https://oktainc.atlassian.net/browse/OKTA-417065)
> Update to Identity Engine common-download-setup-app file Scope configuration section

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
Removed the line implying you no longer need to configure a Trusted Origin if you add a "Login redirect URI" to an application in the admin console. This was only true in the Developer console and now you MUST add the domain to Trusted Origins for the widget to work no matter what.
- **What's changed?** Creating new PR for https://github.com/okta/okta-developer-docs/pull/2477
*n/a
> Creating new PR request for PR277

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** When the "Subscriptions" link was followed (under Reference > Core Okta API), the correct page was opened, but the tree nav didn't open to show the position of the opened article. This PR fixes that.
* Very quick fix; I didn't bother to file a ticket for this one.
> fixing subscriptions api sidebar link

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- **What's changed?** The postman collection for the policy API has been updated. This PR has updated the linked collection in the "Run in Postman" buttons on the `/docs/reference/postman-collections/` and `/docs/reference/api/policy/` pages.
* [OKTA-429944](https://oktainc.atlassian.net/browse/OKTA-429944)
> updating policy api postman collection links NFDEPLOY

- packages/@okta/vuepress-site/docs/guides/style-the-widget/style-self-hosted/index.md
- **What's changed?** We've added help for styling sign-in widget IdP buttons. This helps when admins are using an IdP we don't have a pre-styled button for.
The live dev docs page: [link](https://developer.okta.com/docs/guides/style-the-widget/style-self-hosted/)
The spike that triggered this: [link](https://oktawiki.atlassian.net/wiki/spaces/~883806289/pages/2315363996/Updating+the+sign-in+widget+for+new+IdPs+spike)
* [OKTA-429706](https://oktainc.atlassian.net/browse/OKTA-429706)
> Add help for styling sign-in widget IdP buttons

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- Add `app` and `federated` types to authenticator admin object
- @okta/developerdocs 
* [OKTA-428730](https://oktainc.atlassian.net/browse/OKTA-428730)
> Add missing authenticator types

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- Updated Brands API to reflect new feature to turn off "powered by okta" branding on sign-in page and Okta End-user dashboard
- 2021.10.0
*https://oktainc.atlassian.net/browse/OKTA-430577 and https://oktainc.atlassian.net/browse/OKTA-424736
> Brands API Reference update for removePoweredByOkta field addition

- packages/@okta/vuepress-site/docs/reference/api/risk-events/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-providers/index.md
- **What's changed?** A JIRA ticket was opened because a user couldn't find implementation on 3rd party risk provider integration, starting at the risk events api. I decided to add a link between the two to help future visitors.
* [OKTA-429931](https://oktainc.atlassian.net/browse/OKTA-429931)
> add link to 3rd party risk provider guide to risk events api reference

- packages/@okta/vuepress-site/.vuepress/scripts/findLatestWidgetVersion.js
- packages/@okta/vuepress-site/package.json
- yarn.lock
When getting the latest widget version to display in docs and live widget, we sorted the list of versions from NPM, but were sorting semver strings. When the version number has a two digit value in any place, the sorting will become out of order numerically, even though lexically the sort is accurate. (e.g. `"5.1.10"` is seen as _less than_ `"5.1.9"` from a lexical perspective, but numerically we know that it should be _greater_). Using `semver` comparators in the sort function solves this.
> Use semver comparator to sort widget versions correctly

- packages/@okta/vuepress-site/docs/reference/api/admin-notifications/index.md
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- **What's changed?** Subscriptions API has custom admin role support, added the custom role side of subscriptions API
- **Is this PR related to a Monolith release?** targeted for `2021.11.0`
* [OKTA-423325](https://oktainc.atlassian.net/browse/OKTA-423325)
@nateyocom-okta @alifatolahi-okta @susanharper-okta
> Update Subscriptions Doc for Custom Role

- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/update-default-provider/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- **What's changed?** Updated this Third-Party Risk Integration [page](https://developer.okta.com/docs/guides/third-party-risk-integration/update-default-provider/#update-the-risk-provider) that was missing a variable on the API call; updated the Hooks Best Practices guide to include an editing update (K > 100,00); a broken external link is now working correctly, not updated as per the ticket.
* [OKTA-443639](https://oktainc.atlassian.net/browse/OKTA-443639)
> Quality Update - editing update and fix to missing variable

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/index.md
- **What's changed?** In https://github.com/okta/okta-developer-docs/pull/2636, I changed the quickstart guide to a single page guide. However, I didn't set up the redirects correctly or check the possible broken links as a result. This PR fixes that.
* [OKTA-438714](https://oktainc.atlassian.net/browse/OKTA-438714)
> fixing broken links and redirects for quickstart

- packages/@okta/vuepress-site/code/dotnet/blazor/index.md
- **What's changed?** On the /code/dotnet/blazor/index.md page:
- removed chiclet (since we can't reference external sites) 
- added "Okta Management SDK for .NET" GitHub icon link to https://github.com/okta/okta-sdk-dotnet
- removed "Enable your ASP.NET application to work with Okta via OAuth 2.0/OIDC" (since this contradicts the statement in the /code/dotnet/aspnet page)
> Add Github link to okta-sdk-dotnet from the dotnet/blazor code page

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** https://github.com/okta/okta-developer-docs/pull/2638 converted https://developer.okta.com/docs/guides/sharing-cert/ to a single-page guide, but it didn't put the redirects in place correctly, or thoroughly check the source tree for broken links. This PR fixes that. 
- Redirects tested on staging server 11/15/21. Redirects work as expected. 
* [OKTA-438719](https://oktainc.atlassian.net/browse/OKTA-438719)
> fixing redirects for sharing-cert guide

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/config.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/getaccesstoken.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/getuserinfo.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/installsdk.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/login-redirect.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/angular/reqautheverything.md
- **What's changed?** Update Angular Quickstart to use correct Okta SDKs so a developer successfully creates an authenticated app. I tested using Angular v13. I think the only place where prior versions of Angular might have to make a change is where the access token is used via the HTTP call due to a change in RxJS v7. 
- **Is this PR related to a Monolith release?** I don't think so?
* No Jira ticket created (yet).
> updates to Angular quick start

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/build-sso-integration/before-you-begin/saml2/prep.md
- packages/@okta/vuepress-site/docs/guides/submit-app/overview/index.md
- packages/@okta/vuepress-site/docs/guides/updating-saml-cert/main/index.md
- **What's changed?** https://github.com/okta/okta-developer-docs/pull/2638 converted https://developer.okta.com/docs/guides/updating-saml-cert/ to a single page guide, but it didn't implement the redirects correctly or thoroughly test for broken links. This PR fixes that.
- Redirects tested on staging 11/16/21. Redirects work fine, as expected.
* [OKTA-438721](https://oktainc.atlassian.net/browse/OKTA-438721)
> fixing redirectsand internal links to updating-saml-cert guide

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/main/android/samplecode.md
- packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/main/index.md
- packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/main/ios/samplecode.md
- **What's changed?** https://github.com/okta/okta-developer-docs/pull/2651 converted https://developer.okta.com/docs/guides/unlock-mobile-app-with-biometrics/android/main/ to a single-page guide, but it didn't implement the redirects properly, or check thoroughly for broken links. This PR fixes that.
- Redirects tested on staging, 11/16/21. They all work as expected.
* [OKTA-438726](https://oktainc.atlassian.net/browse/OKTA-438726)
> fixing redirects for unlock-mobile-app-with-biometrics guide

- packages/@okta/vuepress-site/docs/guides/unlock-mobile-app-with-biometrics/main/index.md
- **What's changed?** https://github.com/okta/okta-developer-docs/pull/2752 fixed the redirects for the https://developer.okta.com/docs/guides/unlock-mobile-app-with-biometrics/android/main/, but the stack selectors and nut facts sample code still needed updating to the latest agreed guidelines. The PR fixes that.
> updating stack selectors and nut facts sample code to latest guidelines

- packages/@okta/vuepress-site/docs/guides/customize-tokens-dynamic/main/index.md
Another small bit of cleanup work arising from the single page guide conversion work.
> Removing sample code n/a from customize-tokens-dynamic guide

- packages/@okta/vuepress-site/docs/guides/customize-authz-server/main/index.md
Another small fix to get the nut facts updated to the latest agreed guidelines, this time for this customize-authz-server guide.
> Removing Sample code n/a from customize-authz-server guide nut facts

- packages/@okta/vuepress-site/docs/guides/customize-tokens-static/main/index.md
This was recently converted to a single page guide, but it needed a small tweak to update the nut facts to the latest agreed guidelines.
> Remove Sample code n/a from customize-tokens-static guide nut facts

- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/react/config.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/react/define-route.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/react/handle-callback.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa/main/react/installsdk.md
- **What's changed?** Added missing instructions to React quickstart guide so a developer successfully creates an authenticated app. I added a version qualifier to react-router because it looks like v6 no longer exports the` useRouteMatch` method that Okta react SDK expected
* No Jira ticket (yet).
> update react quickstart

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
- **What's changed?** Addition of new scopes (`okta.userTypes.manage`, `okta.userTypes.read`, `okta.profileMappings.manage`, and `okta.profileMappings.read`) to the [Implement OAuth for Okta](https://developer.okta.com/docs/guides/implement-oauth-for-okta/main/) guide.
- **Is this PR related to a Monolith release?** Yes 2021.12.0
* [OKTA-449724](https://oktainc.atlassian.net/browse/OKTA-449724)
> Addition of new scopes for the Implement OAuth for Okta Guide

- packages/@okta/vuepress-site/docs/guides/device-authorization-grant/main/index.md
- **What's changed?** We are GA'ing the flag without QR code due to security concerns. So  temporarily removing QR code from device flow docs.
- **Is this PR related to a Monolith release?** Yes  **2021.12.0**
* [OKTA-451103](https://oktainc.atlassian.net/browse/OKTA-451103)
> Temporarily remove QR code from device flow docs

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Add note to legacy EL docs - group membership group functions can only be used on Okta user, not app user.
* [OKTA-444467](https://oktainc.atlassian.net/browse/OKTA-444467)
@nghadge-okta @williamyang-okta
> Add note to legacy EL docs

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
- **What's changed?** Update Implement OAuth for Okta and Implement OAuth for Okta for Service app - with no "Overview" after nut-facts and use colon instead of mdash.
> Update Overview after nut-facts section, use colon instead of mdash for Implement OAuth for Okta

- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/main/index.md
- **What's changed?** Fix typo in /third-party-risk-integration/ anchor link.
> Fix typo in anchor reference link

- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta-bulk/main/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta-prerequisites/main/index.md
…ks to those guides
- **What's changed?** https://github.com/okta/okta-developer-docs/pull/2893 updated https://developer.okta.com/docs/guides/migrate-to-okta-password-hooks/main/ to multiple single-page guides, but it didn't add those guides to the main guides index.md file. This PR fixes that, and tweaks a few links so they can take advantage of the flexibility this brings.
> put all migrate-to-okta guides in the main guides list, and tweak links

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/deployment-checklist/index.md
- packages/@okta/vuepress-site/docs/guides/deployment-checklist/main/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-site/docs/guides/production-deployment/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** I noticed that there was one multi-page guide that had not been updated as part of the previous conversion work — https://developer.okta.com/docs/guides/production-deployment/deployment-checklist/. This PR converts that to single page, and cleans up a bunch of prose.
> convert production-deployment to single page guide

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Multiple customers have filed support cases after enabling the custom url domain after finding that they are no longer able to do local token validation for their custom OIDC integrations. These cases frequently point to a PKIX (TLS handshake) error or similar. To mitigate this, we are adding a note to https://developer.okta.com/docs/guides/custom-url-domain/main/#add-the-certificate-details advising to ensure that the intermediate/cert chain is added to Okta if any backends/resource servers will be making API calls to Okta
* [OKTA-406169](https://oktainc.atlassian.net/browse/OKTA-406169)
> add cert chain warning to custom URL article

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/index.md
- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Moves the custom email domain content to the custom Okta URL domain guide.
- **Is this PR related to a Monolith release?** nope
* [OKTA-453902](https://oktainc.atlassian.net/browse/OKTA-453902)
> TBS OKTA-453902 moves custom email domain content to custom Okta URL guide

- packages/@okta/vuepress-site/docs/guides/saml-tracer/index.md
- packages/@okta/vuepress-site/docs/guides/saml-tracer/main/index.md
- **What's changed?** Updating [SAML Testing Guide](https://developer.okta.com/docs/guides/saml-tracer/main/) from "Testing SAML with SAML Tracer" to "Test SAML app implementations with SAML Tracer" as per our style guide.
* n/a
> Update SAML testing guide heading

- packages/@okta/vuepress-site/.vuepress/public/docs/api/postman/admin-roles.json
- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
Include Custom Admin Roles API's in the admin-roles Postman collection.
Also reorganize the existing ones slightly to reduce clutter.
- **Is this PR related to a Monolith release?** Yes: 2022.01.1
* [OKTA-425507](https://oktainc.atlassian.net/browse/OKTA-425507)
> Include Custom Admin Roles API's in Postman collection

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- **What's changed?** Updates to the Inline Hooks concepts and best practices with additional information and links to concurrent inline hook rate limits
* [OKTA-443653](https://oktainc.atlassian.net/browse/OKTA-443653)
> OKTA-443653 - Updates to Inline Hook content on concurrent rate limits

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Add missing redirect to /implement-oauth-for-okta/overview
* [OKTA-454198](https://oktainc.atlassian.net/browse/OKTA-454198)
> Add redirect for /implement-oauth-for-okta/overview

- packages/@okta/vuepress-site/docs/reference/api/risk-providers/index.md
- **What's changed?** Fixes two missing commas in Risk Provider API sample cURL requests' JSON bodies
* [OKTA-459568](https://oktainc.atlassian.net/browse/OKTA-459568)
> Fix JSON body formatting in Risk Provider API cURL examples

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
Fixes assorted typos and mistakes in Administrator Roles API docs.
- **Is this PR related to a Monolith release?** **No**
* [OKTA-459727](https://oktainc.atlassian.net/browse/OKTA-459727)
> Fix assorted typos/small errors in Administrator Roles docs

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/samplecode.md
- **What's changed?** The nutrition facts sample code section on https://developer.okta.com/docs/guides/protect-your-api/springboot/main/ is inconsistent with the sample code for the other platforms — it is too long, and it feels like the cURL stuff should be moved. This PR removes the cURL example completely, and combines the Spring Initializr instructions with the first line. My rationale here is that
- it is not our responsibility to give our readers several options to create a sample app, just to teach them about using Okta technologies with their (sample) apps. The update still gives them an option that works.
- The spring boot getting started guide mentions using Spring Initializr in the first line, and the initializr app itself is pretty intuitive, so I think the new placement of …
> fix inconsistent spring boot sample code section

- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
Update /docs/reference/api/oidc/index.md to reflect that Native_SSO is no longer EA
> Update to reflect that Native_SSO is no longer EA

- packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md
- **What's changed?** Tiny change to remove a stray 'of' in the Admin Console doc I noticed while browsing the docs. The sentence doesn't make sense with it present.
> Remove stray 'of' in Admin Console doc

- packages/@okta/vuepress-site/docs/guides/index.md
- **What's changed?** Fixed three broken links on the [Guides Overview page](https://developer.okta.com/docs/guides/): Section 2: Sign users in to your single-page application; Section 2: Sign user out; Section 3 Customize tokens returned from Okta with a Groups claim.
* n/a
> Fix three broken links on Guides Overview page

- packages/@okta/vuepress-theme-prose/assets/css/base/_typography.scss
- packages/@okta/vuepress-theme-prose/assets/css/components/_pageTitle.scss
- Adjust headings to match odyssey specs
- Override `page-title`'s h1s to remain at `36px`
- Remove heading's media query (nothing relating to this in the specs Figma from Alex Cohen)
Deployed site: https://61fac2d5361d5a13f3ce0596--reverent-murdock-829d24.netlify.app/
Current site: https://developer.okta.com/docs/guides/oie-embedded-common-org-setup/aspnet/main/
* [OKTA-454123](https://oktainc.atlassian.net/browse/OKTA-454123)
Before:
After:
> Adjust headings to match odyssey specs

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Updated 4 curl calls in the following sections to use character encoding `%22` in place of `/"` to escape an apostrophe.
* [ List applications assigned to a user](https://developer.okta.com/docs/reference/api/apps/#list-applications-assigned-to-a-user)
* [ List applications assigned to a group](https://developer.okta.com/docs/reference/api/apps/#list-applications-assigned-to-a-group)
* [List apps by name](https://developer.okta.com/docs/reference/api/apps/#request-example-16)
* [List applications using a key](https://developer.okta.com/docs/reference/api/apps/#request-example-15)
All calls were tested with the new encoding character using curl and Postman, except for the **List applications using a key** call; I …
> OKTA-331115 Updated four curl examples to use character encoding

- packages/@okta/vuepress-site/docs/guides/add-an-external-idp/main/index.md
- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
- **What's changed?** On the IdP pages, we originally had the stack selectors hidden, but with the recent stack selector update they are visible again:
-  https://developer.okta.com/docs/guides/social-login/amazon/main/
- https://developer.okta.com/docs/guides/add-an-external-idp/apple/main/
We want them hidden. In https://github.com/okta/okta-developer-docs/pull/3027 we added a simple mechanism to do this, and in this PR I am adding the required frontmatter properties to do the actual hiding.
* [OKTA-467429](https://oktainc.atlassian.net/browse/OKTA-467429) — partial fix, at least.
> hide stack selectors from IdP pages

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Add OAuth 2.0 based authentication support for Provisioning Connection.
- **Is this PR related to a Monolith release?**  Yes, 2022.02.2
* OKTA-456535
> Application Provisioning Connection Profile update: add OAUTH2 support for authScheme

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/aspnetcore3/request.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/nodeexpress/request.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/request.md
Fixing a copypasta error where the `Authorization` header is missing
> *NOTE:* This is a little different than the `go` version
https://github.com/okta/okta-developer-docs/blob/oie-by-default-quickstarts/packages/%40okta/vuepress-site/docs/guides/protect-your-api/main/go/request.md
I think the `curl` version makes it more clear that this value is a header
> Cleanup invalid headers in protect-your-api

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/spring-boot/getuserinfo.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/spring-boot/samplecode.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/spring-boot/testapp.md
- **What's changed?** Fixed typos and changed `./mvnw` to `mvn` so it's platform agnostic. I believe most Java developers can translate this to `./mvnw` (for Linux / macOS) and `mvnw` (on Windows) if they want to use the Maven wrapper.
> Fix typos found in Spring Boot quickstart

- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/php/createproject.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/php/loginredirect.md
* use `public` folder since that's the PHP convention and used later down in the tutorial
* fix missing function definition in the redirect block
> minor fixes for php web app quickstart

- packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** Changing Dev docs footer banner copyright year
* n/a
> Updating copyright year from 2021 to 2022

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/interactioncode/nutrition.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/nutrition.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/nutrition.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/nutrition.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/nutrition.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/nutrition.md
- **What's changed?** Now we have moved to oie by default and the `/signup` page created OIE orgs, we should update links to the `oie-preview.html` version to just point to `/signup` (it redirects there anyway), and text references to OIE preview orgs. This PR handles that
> removing references and links to oie preview orgs

- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/react/createproject.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/python/configmid.md
- **What's changed?** Change `okta.env` to `.okta.env` and be consistent on library names for React quickstart.
> Fix .okta.env filename and cleanup Okta SDK names

- packages/@okta/vuepress-site/docs/guides/custom-error-pages/main/index.md
- **What's changed?** Fix extra `errorSummary` header and add a note for triple-braced `errorDescription` macro. This is a fix for submitted PR 3032.
* [OKTA-476236](https://oktainc.atlassian.net/browse/OKTA-476236)
* PR [3032](https://github.com/okta/okta-developer-docs/pull/3032)
> Update custom error pages with note for triple-braced errorDescription macro

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Re-add Discord, Spotify, Xero links in the TOC (left-nav) from PR 2859, 2860, 2861 that was removed from a recent merge.
> Re-add Discord, Spotify, Xero links in the TOC

- packages/@okta/vuepress-site/code/android/index.md
- packages/@okta/vuepress-site/code/angular/index.md
- packages/@okta/vuepress-site/code/dotnet/aspnet/index.md
- packages/@okta/vuepress-site/code/dotnet/aspnetcore/index.md
- packages/@okta/vuepress-site/code/dotnet/blazor/index.md
- packages/@okta/vuepress-site/code/go/index.md
- packages/@okta/vuepress-site/code/ios/index.md
- packages/@okta/vuepress-site/code/java/index.md
- packages/@okta/vuepress-site/code/java/spring/index.md
- packages/@okta/vuepress-site/code/javascript/index.md
- packages/@okta/vuepress-site/code/nodejs/index.md
- packages/@okta/vuepress-site/code/php/index.md
- packages/@okta/vuepress-site/code/python/index.md
- packages/@okta/vuepress-site/code/react-native/index.md
- packages/@okta/vuepress-site/code/react/index.md
- packages/@okta/vuepress-site/code/vue/index.md
- **What's changed?** The blog links at the bottom of the pages under https://developer.okta.com/code/ are somewhat buggy/problematic, as they also show a bunch of github links, and they don't show the pages in much of a useful order. This PR updates those to point to specific tag URLs (see https://developer.okta.com/blog/tags/). Note that I've not yet update the pages for the following, as there are a number of competing tags and it is not clear which one I should use:
- .NET and .NET Core
- Node/Node.js
- Vue/VueJS
- Note: The blog links won't work in localhost, as the build doesn't build the blog (that uses a different system). But they are correct. 
* [OKTA-476205](https://oktainc.atlassian.net/browse/OKTA-476205)
> update code blog links to tagged page URLs

- packages/@okta/vuepress-site/docs/guides/auth-js/main/index.md
- packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/react/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/vue/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/angular/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/create-app-integration.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/vue/create-app-integration.md
- **What's changed?** Update OIE-by-default embedded sign-in guides with a note about shared default authentication policy, and removed sign-on policy steps. The following guides are updated:
- /sign-in-to-spa-embedded-widget/
- /sign-in-to-spa-authjs/
- /embedded-siw/
- /auth-js/
- **Is this PR related to a Monolith release?** 2022.03.0
* [OKTA-475953](https://oktainc.atlassian.net/browse/OKTA-475953)
> OKTA-475953 - Update embedded sign-in guides with note about shared default auth policy

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- **What's changed?** Added a new bullet point to address bug concerns on encoding special characters in search. Additionally, updated 4 curl calls in the the following section to use character encoding `%22` in place of `/"` to escape an apostrophe:
- [List Users with a filter](https://developer.okta.com/docs/reference/api/users/#list-users-with-a-filter)
- [List User with a timestamp](https://developer.okta.com/docs/reference/api/users/#request-example-timestamp)
- [Search examples](https://developer.okta.com/docs/reference/api/users/#search-examples)
- [Request example for array](https://developer.okta.com/docs/reference/api/users/#request-example-for-array)
All calls were tested with the new encoding character using curl and Postman, except for the Request example for array call; I …
> OKTA-461913 Add URL encoding details and update curl examples

- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- Adding a note onto the MyAccount dev docs page, notifying readers that there is a new namespace to use and that the existing one will be deprecated.
- **Is this PR related to a Monolith release?** Yes. 2022.05.0 (subject to change)
* [OKTA-453945](https://oktainc.atlassian.net/browse/OKTA-453945)
- Adding deprecated banner to `Get Me` endpoint that won't be available in the new MyAccount namespace
> Updating dev docs for existing myAccount API

- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- **What's changed?** This `servers` is not supported in ASA /preauthorizations. Platform PR 5491 removed the `servers` parameter.
- **Is this PR related to a Monolith release?** Yes, 2022.03.2
* [OKTA-462650](https://oktainc.atlassian.net/browse/OKTA-462650)
> OKTA-462650 Set servers parameter to optional ASA /preauthorizations

- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?** Update description of behaviour of error object for inline registration hook. Update format of sample JSON response.
- **Is this PR related to a Monolith release?** Yes. 2022.03.2
- **March 14:** https://622fbae83da6a4284cc6b021--reverent-murdock-829d24.netlify.app/docs/reference/registration-hook/#error
- **March 11:** https://622bc67e4317985eeca3d2bb--reverent-murdock-829d24.netlify.app/docs/reference/registration-hook/#error
- **March 10:** https://622ab93f5798c83b1068ccd0--reverent-murdock-829d24.netlify.app/docs/reference/registration-hook/#error
- [OKTA-477959](https://oktainc.atlassian.net/browse/OKTA-477959)
> TBS OKTA-477959 Update registration hook error object

- packages/@okta/vuepress-site/docs/reference/api/asa/attributes/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/audits/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/clients/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/entitlements/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/groups/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/introduction/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/service-users/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/teams/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/users/index.md
- **What's changed?** Add pagination offset example in the ASA Intro. Add a link from the ASA Projects API (List Projects for a team operation) to the Pagination example.
* https://622fa341ea05b000a7ad43d4--reverent-murdock-829d24.netlify.app/docs/reference/api/asa/projects/#request-path-parameters
* [OKTA-459126](https://oktainc.atlassian.net/browse/OKTA-459126)
> OKTA-459126 Add pagination offset example

- packages/@okta/vuepress-site/docs/reference/okta-expression-language-in-identity-engine/index.md
- **What's changed?** Adds a note that `user.status` doesn't work with group rules.
- https://6233b93713f2c10f34d932e2--reverent-murdock-829d24.netlify.app/docs/reference/okta-expression-language-in-identity-engine/#okta-user-profile
* [OKTA-474759](https://oktainc.atlassian.net/browse/OKTA-474759)
> TBS OKTA-474759 Add user.status note to EL docs

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** Updated 5 of 6 curl calls in the the following sections of the Groups API reference to use character encoding `%22` in place of `/"` to escape a double quote character:
- [List Groups with type](https://developer.okta.com/docs/reference/api/groups/#request-example-5)
- [List Groups with Profile updated after timestamp](https://developer.okta.com/docs/reference/api/groups/#list-groups-with-profile-updated-after-timestamp)
- [List groups with MEMBERSHIP updated after timestamp](https://developer.okta.com/docs/reference/api/groups/#list-groups-with-membership-updated-after-timestamp)
- [List groups updated after timestamp](https://developer.okta.com/docs/reference/api/groups/#list-groups-updated-after-timestamp)
- [List Groups with …
> OKTA-470848 Add URL encoding to curl examples Groups API

- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-org-setup/main/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** The “Get set up to run Identity Engine sample apps“ section of “Sign users in“ is confusingly positioned, and the flow doesn't work very well. This PR aims to fix that.
- Netlify deploy available at https://6239ed9c2fc59825fe5dc1b2--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-common-org-setup/android/main/  
* [OKTA-481536](https://oktainc.atlassian.net/browse/OKTA-481536)
> reposition get set up guides

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
Update the Create User API docs to include Optional Password scenarios
YES 2022.04.0 CF, which includes EAing Optional Password
* [OKTA-462015](https://oktainc.atlassian.net/browse/OKTA-462015)
> Update the Create User API docs to include Optional Password scenarios

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Remove "Early Access" flag for OAuth 2.0-based Provisioning Connection
- **Is this PR related to a Monolith release?** 2022.04.0
* [OKTA-481557]
[OKTA-481557]: https://oktainc.atlassian.net/browse/OKTA-481557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove "Early Access" flag for OAuth 2.0-based Provisioning Connection

- packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
- These changes remove the `eventAction` field used by telephony hooks in BETA and docs the field `requestType` that was newly added by inline hooks framework
- April 2022 release 2022.04.0
* [OKTA-481120](https://oktainc.atlassian.net/browse/OKTA-481120)
> OKTA-481120: Add requestType, remove eventAction for Telephony hooks

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- Authn recovery flow `/api/v1/authn/recovery/token` can use parameter multiOptionalFactorEnroll in options like `/api/v1/authn`.
- Monthly release: 2022.04.0
- Ticket to GA FF `ENG_HONOR_MULTI_OPTIONAL_FACTOR_ENROLL` for all preview orgs: https://oktainc.atlassian.net/browse/OKTA-473102
* [OKTA-473105](https://oktainc.atlassian.net/browse/OKTA-473105)
> Edit developer doc to use multiOptionalFactorEnroll in recovery flow

- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- **What's changed?** Update the following parameters/properties in the ASA Projects API:
* `forward_traffic` (remove warning)
* `rdp_session_recording` (remove warning and add "not supported")
* `ssh_session_recording`  (remove warning)
* [OKTA-484251](https://oktainc.atlassian.net/browse/OKTA-484251)
> OKTA-484251 Remove feature flag warning in ASA Projects API 

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/flow-diagram.md
- **What's changed?** Updated Step 3 in the [Implement Authorization by Grant Type ](https://developer.okta.com/docs/guides/implement-grant-type/implicit/main/)(Implicit), which had broken link syntax.
* n/a
> Fix link syntax in Implicit Flow Grant Type Guide

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Fixed multiple spacing errors in `conductor.yml`, which broke the redirects
* n/a
> Fix spacing errors in conductor file

- packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
- **What's changed?** Originally I filed https://github.com/okta/okta-developer-docs/pull/3159 to add a note about session cookies being preferred over sessionTokens. However, we included some information about contacting your Okta rep if you wanted to reverse this behavior, but this caused a different set of problems because it was not supposed to be a general option open to all customers. This PR removes that part. 
* [OKTA-477991](https://oktainc.atlassian.net/browse/OKTA-477991)
> remove inappropriate instruction about contacting rep

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Ram from dev support informed me that the [update application policy](https://developer.okta.com/docs/reference/api/apps/#update-application-policy) feature of the `/apps` API is OIE-only. This PR marks it with an Identity Engine banner.
> mark update application policy reference as OIE-only

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
The 2 examples for checking for null and blank attributes are wrong because they use the inequality ("!=") instead of the equality ("==") operators. 
This PR fixes the two examples.
- The 2 examples for checking for null and blank attributes are wrong because they use the inequality ("!=") instead of the equality ("==") operators. 
Unsure
> Correcting 2 examples for null and blank

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** Updated two tables that referenced the group rule name parameter and description (Create a Group Rule Name and Update a Group Rule Name) to add that names can be a minimum of 1 character and a maximum of 50 characters. Tested with Admin Console and Postman.
Also deleted a redundant "Default" column in both tables.
* [OKTA-480451](https://oktainc.atlassian.net/browse/OKTA-480451)
> Updates to Groups API - MinMax length of Group Rule names

- packages/@okta/vuepress-site/docs/reference/csi-delauth-hook/index.md
Resolves: OKTA-488222
- **What's changed?** Added text to clarify the unit for two timestamp attributes for external users.
* [OKTA-488222](https://oktainc.atlassian.net/browse/OKTA-488222)
> OKTA-488222: Clarify timestamp attribute unit to be milliseconds.

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Add redirect from old migration doc(/docs/guides/migrate-to-oie/) to Napa /docs/guides/oie-upgrade-overview/ doc
* [OKTA-473009](https://oktainc.atlassian.net/browse/OKTA-473009)
> Redirect old OIE migration doc to Napa upgrade OIE overview doc

- package.json
- packages/@okta/vuepress-site/package.json
- packages/@okta/vuepress-theme-prose/package.json
- yarn.lock
This is a first pass of multiple like this. This will slowly get us back into a state where everything is on the latest version.
- axios
- semver
- include-media
- jshint
- moment
- moment-timezone
- query-string
- vue-select
* [OKTA-490911](https://oktainc.atlassian.net/browse/OKTA-490911)
> Upgrade dependencies with available patch and minor upgrades

- package.json
- packages/@okta/vuepress-site/package.json
- packages/@okta/vuepress-theme-prose/components/DocsMenuItem.vue
- packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
- yarn.lock
- **What's changed?** Upgrade dependencies to address most json-schema vuln
- Upgraded `cypress` to latest
- Upgraded `jest` to latest
- Removed `wait-on` as it wasn't being used anymore
- Removed `wait-for` as it wasn't being used anymore
- Upgraded `vuepress` and `vue`
* [OKTA-473515](https://oktainc.atlassian.net/browse/OKTA-473515)
> Upgrade dependencies to address most json-schema vuln

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Remove multiple redirect to non-inclusive filenames that no longer exist (remove redirect hops to final destination, i.e. remove **to:** "static-whitelist" entries)
* [OKTA-488933](https://oktainc.atlassian.net/browse/OKTA-488933)
> OKTA-488933 Remove non-inclusive filename hops in conductor.yml

- packages/@okta/vuepress-site/docs/guides/customize-tokens-groups-claim/main/index.md
- **What's changed?** Fix Access token code block in Customize tokens returned from Okta with a Group claims > Request a token that contains the custom claim > step 4 (tab was added)
* [OKTA-492199](https://oktainc.atlassian.net/browse/OKTA-492199)
> OKTA-492199 Fix Access token code block in Customize tokens returned ... guide

- packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- **What's changed?** There's a dummy link in the [Refresh access tokens](https://developer.okta.com/docs/guides/refresh-tokens/main/#see-also) page, which needs updating now the article is available to link to. This PR fixes that
* [OKTA-492209](https://oktainc.atlassian.net/browse/OKTA-492209)
> fix dummy link on refresh tokens guide

- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
- **What's changed?** This PR is a duplicate of PR 3232 (currently non-responsive). It removes the EA note for refresh tokens.
* PR 3232 (branch askouras:patch-10)
> Refresh Tokens for SPAs (refresh token rotation) is now GA

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- **What's changed?** Correct **`Note`** describing how system log event fields are tokenized and matched against `q` param values. 
* [OKTA-480452](https://oktainc.atlassian.net/browse/OKTA-480452)
> Correct prompt describing how system log event fields are tokenized and matched against q param values.

- packages/@okta/vuepress-site/docs/reference/api/oauth-clients/index.md
- client_name is no longer required to be unique. 
- This was removed in https://oktainc.atlassian.net/browse/OKTA-215049
- **Is this PR related to a Monolith release?** - NO
* [OKTA-477224](https://oktainc.atlassian.net/browse/OKTA-477224)
> client_name is no longer required to be unique during dynamic client registration

- packages/@okta/vuepress-site/docs/guides/social-login/main/github/noemail.md
- **What's changed?** Updated GitHub variable mappings (`appuser.id` and `idpuser.id`) variables to align with changes in OKTA-460058.
- **Is this PR related to a Monolith release?** Yes, 2022.05.0
- 
* [OKTA-490299](https://oktainc.atlassian.net/browse/OKTA-490299)
> OKTA-490299 Update Github IdP mapping variables appuser.id and idpuser.id variables

- packages/@okta/vuepress-site/docs/guides/authenticators-okta-email/main/index.md
Updated Email Factor Verification template row in matrix to show support for Magic Link and OTP
**THIS PR NEEDS TO BE PUBLISHED ON MAY 4th**
* [OKTA-491148](https://oktainc.atlassian.net/browse/OKTA-491148)
Deploy link:
https://626b4da56e25f410a0334198--reverent-murdock-829d24.netlify.app/docs/guides/authenticators-okta-email/aspnet/main/#know-which-use-cases-support-magic-link-and-otp
> Update to the Okta email authenticator guide - May 4th publish

- packages/@okta/vuepress-site/conductor.yml
- **What's changed?** Add redirect for /docs/guides/build-provisioning-integration/-/overview/. This link is coming in from https://www.okta.com/integrate/ > Start building > step 2
* [OKTA-496425](https://oktainc.atlassian.net/browse/OKTA-496425)
> OKTA-496425 Add redirect for /docs/guides/build-provisioning-integration/-/overview/

- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- **What's changed?** Updating the schemas API to include the `format` keyword in the [App User Profile Schema Property Object](https://developer.okta.com/docs/reference/api/schemas/#app-user-profile-schema-property-object) table, further description, including all format types used by the keyword, and curl request example.
* [OKTA-486203](https://oktainc.atlassian.net/browse/OKTA-486203)
> Update Schemas API to include format keyword

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** IdPs API reference page: updated Identity Provider `type` property and associated sub-structures with new social IdPs.
* May 13: https://627d7b6ecfa2be00bc06cb92--reverent-murdock-829d24.netlify.app/docs/reference/api/idps/
* May 12: https://627d53e51fcaa10fded2e42b--reverent-murdock-829d24.netlify.app/docs/reference/api/idps/
* [OKTA-493049](https://oktainc.atlassian.net/browse/OKTA-493049)
> OKTA-493049 Add new social idPs to the IdPs API

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** In the [Manager/Assistant functions](https://developer.okta.com/docs/reference/okta-expression-language/#manager-assistant-functions) section of the Okta Expression Language overview, added a bullet point that these functions are not supported for multiple AD instances.
* [OKTA-494746](https://oktainc.atlassian.net/browse/OKTA-494746)
> OKTA-494746 Update Okta Expression Language Overview for multiple AD instances

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?** Adds the new timeout error for Progressive Enrollment using Registration Inline Hooks. Tweaks the formatting of the existing content. Also, while under the hood, updates the sample requests/response in the ref doc (based on what's already published in the registration inline hook guide).
- **Is this PR related to a Monolith release?** Yes. 2022.05.3
https://6286edc0f1c2e26d8beb8ce9--reverent-murdock-829d24.netlify.app/docs/reference/registration-hook/#timeout-behavior
* [OKTA-499896](https://oktainc.atlassian.net/browse/OKTA-499896)
> TBS Add generic timeout message for Progressive Enrollment

- packages/@okta/vuepress-theme-prose/components/Home.vue
- Remove `AnnouncementBanner` instance from `home.vue`. The component remains available for future messages.
* [OKTA-499183](https://oktainc.atlassian.net/browse/OKTA-499183)
> Remove AnnouncementBanner from home page

- packages/@okta/vuepress-site/docs/guides/oie-upgrade-overview/main/index.md
- **What's changed?** Sharon from prod docs informed me that we need to update our link to the admin page for OIE upgrades seen at the top of https://developer.okta.com/docs/guides/oie-upgrade-overview/main/ to a more reliable permanent page that provides the start of this learning journey. This PR updates that link. The new admin URL to link to is https://help.okta.com/oie/en-us/Content/Topics/identity-engine/oie-upgrade-eligibility.htm
> update oie upgrade admin link

- packages/@okta/vuepress-site/docs/reference/api/asa/introduction/index.md
- **What's changed?** Add Concurrency Limits text in the Rate Limiting section for ASA Introduction
- This feature is planned for next ASA deployment (March 16, 2022). Confirm with @jayfaulkner-okta before merging.
- Update: this feature is not going out March 16 or March 22. Release TBD
* [OKTA-455468](https://oktainc.atlassian.net/browse/OKTA-455468)
> Add Concurrency Limits text in the Rate Limiting section for ASA Introduction

- packages/@okta/vuepress-site/docs/reference/api/roles/index.md
- **What's changed?** Updated [supported resources](https://developer.okta.com/docs/reference/api/roles/#supported-resources) table to add URL encoding to one REST URL.
I also have a question about the response example for this particular API. The response example ([All apps of the same type of resource](https://developer.okta.com/docs/reference/api/roles/#all-apps-of-the-same-type-as-resource)) includes a filter and escaped character in the response, but calling the API brings back only individual apps. I believe the given example is incorrect. Can you verify? 
ie: `"https://{yourOktaDomain}/api/v1/apps?filter=name+eq+\"workday\""` , I think, should look like:
`"https://{yourOktaDomain}/home/{targetAppType}/0oa1gjh63g214q0Hq0g4`
(Also, I see the property `_links.apps` but the calls I …
> OKTA-470845 Minor update to Administrator Roles API reference

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- **What's changed?** Fixed type in error responses section of the [Deactivate Device](https://developer.okta.com/docs/reference/api/devices/#deactivate-device) section. (`SUSPENEDED`)
* [OKTA-502738](https://oktainc.atlassian.net/browse/OKTA-502738)
> OKTA-502738 - Fix typo in Devices API

- packages/@okta/vuepress-site/docs/guides/social-login/main/github/noemail.md
- **What's changed?** Replace github_id with externalId for GitHub IdP based on info in OKTA-498510.
- Target release: 2022-05-31 (verify with @colekurashige-okta)
* [OKTA-499415](https://oktainc.atlassian.net/browse/OKTA-499415)
> OKTA-499415 Replace github_id with externalId for GitHub IdP

- packages/@okta/vuepress-theme-prose/components/Home.vue
- **What's changed?** Removing the out-dated widget on the developer.okta.com [home page](https://developer.okta.com/) (Scroll down to Customize your sign-in)
* as per Slack conversation of June 6, 2022
* [OKTA-479073](https://oktainc.atlassian.net/browse/OKTA-479073)
> Comment out Sign-in Widget on Home page

- packages/@okta/vuepress-site/docs/guides/authenticators-okta-verify/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-email/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-pwd-phone/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/main/index.md
Add doc messaging for device context issue
* [OKTA-505593](https://oktainc.atlassian.net/browse/OKTA-505593)
Okta Verify: https://62a2b0aa8c939049304103b2--reverent-murdock-829d24.netlify.app/docs/guides/authenticators-okta-verify/aspnet/main/
Basic sign-in flow using the password factor: https://62a2b0aa8c939049304103b2--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/aspnet/main/
Sign in with Facebook: https://62a2b0aa8c939049304103b2--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-sign-in-soc-idp/aspnet/main/
User password recovery: https://62a2b0aa8c939049304103b2--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-pwd-recovery-mfa/aspnet/main/
Self-service registration: …
> Add doc messaging for device context issue

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- **What's changed?** Updated 2 curl calls in the the following sections of the Devices reference to use character encoding %22 in place of /" to escape a double quote character:
[Usage Example Search (API Token)](https://developer.okta.com/docs/reference/api/devices/#api-token-request-3)
[Usage Example Search (Bearer token)](https://developer.okta.com/docs/reference/api/devices/#bearer-token-request-4)
See [Google testing doc](https://docs.google.com/document/d/1MxO51OAlEP6HFlGt8DbItPRkT21iu25LFKxyctRtCfw/edit?usp=sharing) for details.
* [OKTA-470847](https://oktainc.atlassian.net/browse/OKTA-470847)
> OKTA-470847 Add URL encoding to curl examples Devices API

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adds the blurbs for a few VULNs.
- **Is this PR related to a Monolith release?** Yes. 2022.06.1, but only when deployed to all prod cells.
* [OKTA-505802](https://oktainc.atlassian.net/browse/OKTA-505802)
> TBS VULN blurbs for 2022.06.1

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- Added new optional request query parameter `removeRecoveryEnrollment` to allow for the removal of a factor for use in recovery when Resetting all Factors.
- July Monthly Release - ~~2022.070~~ 2022.06.2 as per Slack convo with @susanharper-okta and @scottbermon-okta 
* [OKTA-506759](https://oktainc.atlassian.net/browse/OKTA-506759)
> Updated User Lifecycle Reset Factors to optionally support factor removal for recovery

- packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md
- packages/@okta/vuepress-theme-prose/assets/css/abstracts/_colors.scss
- packages/@okta/vuepress-theme-prose/assets/css/components/_apiLifecycle.scss
- packages/@okta/vuepress-theme-prose/global-components/ApiLifecycle.vue
- **What's changed?** This PR fixes a number of issues with the deprecated label (see https://developer.okta.com/docs/reference/releases-at-okta/#deprecation):
- The fire extinguisher icon is weird
- The color seems to be too "dangerous", and should be something like an orange
- The wording needs to be better
- The label should link directly to the deprecated section of the above linked page, not just the top of that page. 
* [OKTA-493966](https://oktainc.atlassian.net/browse/OKTA-493966)
> improving deprecated label experience

- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
- **What's changed?** Add note regarding password parameter in a SCIM Create User request to avoid confusion.
- https://62c46e20818c143b1e672212--reverent-murdock-829d24.netlify.app/docs/reference/scim/scim-20/#create-the-user
* [OKTA-413958](https://oktainc.atlassian.net/browse/OKTA-413958)
> OKTA-413958 - Add note regarding password parameter in a SCIM Create User request

- packages/@okta/vuepress-site/docs/reference/api/domains/index.md
- **What's changed?** Added 2 missing periods 
- removed n/a sections
- removed warning about EA FF
- no
none, noticed this while reading through
> missing punctuation on /domains reference

- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- **What's changed?** Removed the EA flag for trusted origins iframe embedding GA
- **Is this PR related to a Monolith release?** Yes 2022.07.0
* [OKTA-510897](https://oktainc.atlassian.net/browse/OKTA-510897)
> removing the EA flag for trusted origins iframe embedding GA

- packages/@okta/vuepress-site/docs/concepts/scim/faqs/index.md
Okta uses the `filter=displayName eq <groupName>` query param on the `/Groups` endpoint. Therefore SCIM service providers must implement this, however this is unclear with the current documentation
- **What's changed?** Clarifies documentation
> chore(SCIM docs): Clarify eq filtering support is required for groups as well

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** Added a bullet point to this section of the Groups API: [https://developer.okta.com/docs/reference/api/groups/#list-groups-with-defaults](https://developer.okta.com/docs/reference/api/groups/#list-groups-with-defaults) to address
* [OKTA-444663](https://oktainc.atlassian.net/browse/OKTA-444663)
> OKTA-444663 Update Groups API with Group Admins do not see Everyone group detail

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Remove EA banner for `pkce_required` property on apps api
https://developer.okta.com/docs/reference/api/apps/#oauth-credential-object
- **Is this PR related to a Monolith release?** yes `2022.08.0`
* [OKTA-518466](https://oktainc.atlassian.net/browse/OKTA-518466)
> Remove EA banner for pkce_required

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
Adds the attribute `uiSchemaId` to the Profile Enrollment Action Object.
The is value is generated by the back end and if present will be required when any policy update is made, otherwise a 400 will be returned.
see: https://oktawiki.atlassian.net/wiki/spaces/~60feb6dac51f3a00697babaf/pages/2510164199/Profile+Enrolment+Policy+-+Improve+API+validation?focusedCommentId=2512879955
[2022.05.0](https://oktainc.atlassian.net/issues/?jql=project%20%3D%20%22OKTA%22%20AND%20fixVersion%20%3D%20%222022.05.0%22) (https://oktainc.atlassian.net/browse/OKTA-434566)
* This enhancement is needed in order to update the OpenAPI Spec so the Management SDKs can add this attribute. …
> Add attribute uiSchemaId to the Profile Enrollment Action Object

- packages/@okta/vuepress-site/docs/guides/email-magic-links-overview/main/index.md
Add Account Unlock email template to table in EML overview guide.
2022.08.1 release
* [OKTA-521637](https://oktainc.atlassian.net/browse/OKTA-521637)
https://62ed6ff6ce17ee28e094a761--reverent-murdock-829d24.netlify.app/docs/guides/email-magic-links-overview/aspnet/main/#use-custom-email-templates
> Add Account Unlock email template to table in EML overview guide

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/index.md
Add **Password Reset By Admin template not allowed** note to the password recovery guide.
2022.08.1
* [OKTA-521731](https://oktainc.atlassian.net/browse/OKTA-521731)
https://62ed82098e5c0c3ddbe19a18--reverent-murdock-829d24.netlify.app/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/nodeexpress/main/#update-the-forgot-password-email-template
> Add Password Reset By Admin template not allowed note

- packages/@okta/vuepress-site/.vuepress/config.js
- **What's changed?** Updated the home page **Community** dropdown menu to replace "Developer Day" with "Developer Days" and the link to the latest: https://regionalevents.okta.com/DeveloperDays2022
* [OKTA-524057](https://oktainc.atlassian.net/browse/OKTA-524057)
> OKTA-524057 Updated config.js file with updated link to 2022 Developer Days

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- packages/@okta/vuepress-site/docs/concepts/monitor/index.md
- packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md
- **What's changed?** As an interim solution, removed the hard-coded links to `event-hook-eligible` Event Types from three separate locations in the guide. Outstanding Developer Platform ticket: [OKTA-525710](https://oktainc.atlassian.net/browse/OKTA-525710) to address this issue.
* n/a
> Updates to hard-coded event-hook-eligible queries

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?** Add image logo updates: SVG support and 200x200 dimension
- **Is this PR related to a Monolith release?**Yes, 2022.09.0
* [OKTA-511103](https://oktainc.atlassian.net/browse/OKTA-511103)
> OKTA-511103 Add image logo updates: SVG support and 200x200 dimension

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- packages/@okta/vuepress-site/docs/reference/api/push-providers/index.md
- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- The Devices and Push Providers API were originally using `{{api_token}}` as the variable name in the authorization header, so change it to `{{apikey}}` to keep it consistent with the existing setup docs on the [developer website](https://developer.okta.com/code/rest/#set-up-your-environment) 
- **Is this PR related to a Monolith release?**:  no
- NFDEPLOY link:  https://630d15e6cbac8f1d1422f460--reverent-murdock-829d24.netlify.app
- Postman collections list: https://630d15e6cbac8f1d1422f460--reverent-murdock-829d24.netlify.app/docs/reference/postman-collections/
- Devices API: https://630d15e6cbac8f1d1422f460--reverent-murdock-829d24.netlify.app/docs/reference/api/devices/
- Push Providers API: https://630d15e6cbac8f1d1422f460--reverent-murdock-829d24.netlify.app/docs/reference/api/push- …
> Fix devices & push providers postman collections to use {{apikey}} as the variable name

- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- added note for Postman collection that EA for `Loading Page Animation` is required to use the collection
- removed the EA notes/badges for Email Settings APIs since that is now GA
- 2022.09.0
* n/a
> early access note/update

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
The update to the navbar doesn't include the Devices SDK.
> Urgent fix: Add Devices SDK to back navbar

- packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md
- **What's changed?** Remove extra period in Release Life Cycle note.
> Fix typo in release life cycle page

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** As per Slack conversation, removed beta tag on the Weak Password Dictionary object: https://developer.okta.com/docs/reference/api/policy/#weak-password-dictionary-object
* [OKTA-510002](https://oktainc.atlassian.net/browse/OKTA-510002)
> OKTA-510002 Remove beta tag on Policy API reference

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Adding the unique expression `user.getInternalProperty("id")` to the EL guide.
* [OKTA-530768](https://oktainc.atlassian.net/browse/OKTA-530768)
> OKTA-530768 Add user attribute to EL Guide

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-new-user-activation/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- packages/@okta/vuepress-site/docs/reference/api/oidc/index.md
- packages/@okta/vuepress-site/docs/reference/api/sessions/index.md
- **What's changed?** To inspire good practices, the PAT team would like to include the “User-Agent” header reference to the API examples across the developer portal. If customers use this properly, it will help in identifying use cases and points of integrations more consistently. There is a bit of disagreement on this, so for now I've deci9ded to just add them to authn-related cURL examples and see what we think.
* [OKTA-516847](https://oktainc.atlassian.net/browse/OKTA-516847)
> add User-Agent to authn-related curl examples

- packages/@okta/vuepress-site/docs/reference/api/admin-notifications/index.md
- **What's changed?** Update Subscriptions-Role API to support bot API_ACCESS_MANAGEMENT_ADMIN instead & API_ADMIN
- **Is this PR related to a Monolith release?** Yes. 2022.10.0
[OKTA-431895](https://oktainc.atlassian.net/browse/OKTA-431895)
@williamngo-okta @rickyyang-okta @okta/dda 
0f-18a03f75bed8.png)
> OKTA-431895: Add API_ACCESS_MANAGEMENT_ADMIN to role types

- packages/@okta/vuepress-site/docs/guides/custom-widget/main/index.md
- **What's changed?** In https://developer.okta.com/docs/guides/custom-widget/main/, the `getRequestContext()` information was specific to Okta Classic, which was causing problems for OIE users. This PR aims to fix that
- **Preview URL**
- https://632dad4e22231b08272fd37f--reverent-murdock-829d24.netlify.app/docs/guides/custom-widget/main/#request-context
- https://632dad4e22231b08272fd37f--reverent-murdock-829d24.netlify.app/docs/guides/custom-widget/main/#per-application-customization
* [OKTA-535304](https://oktainc.atlassian.net/browse/OKTA-535304)
> Add OIE getRequestContext information

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Removing "self-service" from release notes for OAuth 2 for Inline Hooks feature 
- **Is this PR related to a Monolith release?** 2022.10.0
* n/a
> Removing "self-service" from release notes

- packages/@okta/vuepress-theme-prose/assets/css/components/_menuItem.scss
- **What's changed?** The small chevron image, in the developer.okta.com header, was the colour grey (or black), and was almost indistinguishable from the dark blue of the header. It appeared to throw the spacing off of the items. I've updated the CSS to use the white chevron image:
* a nit I saw while navigating
> Updated CSS to show correct image for light mode

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- packages/@okta/vuepress-site/docs/reference/import-hook/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- **What's changed?** Reviewing and updating API references as well as a few other hook docs, as per the OAuth 2.0 for inline hook feature
* [OKTA-538431](https://oktainc.atlassian.net/browse/OKTA-538431)
> OKTA-538431 Further updates to hook docs for OAuth 2 support

- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/index.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/nodejs/auth.md
- packages/@okta/vuepress-site/docs/guides/common-hook-set-up-steps/main/nodejs/scope.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/index.md
- packages/@okta/vuepress-theme-prose/global-components/RegistrationHookXref.vue
- **What's changed?** Added links to a new glitch project that works with the OAuth 2.0 for inline hooks feature.  Updated the Common Hooks guide with a mention in the existing Registration Hook guide. Also includes several UI updates and nits missed on initial release.
* [OKTA-538432](https://oktainc.atlassian.net/browse/OKTA-532432)
> OKTA-538432 - Adding xrefs for OAuth 2 for Inline Hooks

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Returned "Self-Service EA" to the OAuth 2.0 for Inline Hooks feature announcement in monthly RNs.
- **Is this PR related to a Monolith release?** 2022.10.2
* n/a
> Returned Self-Service EA to monthly release notes

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- Added a note that `loginRedirectUrl` filed has been deprecated in Identity Engine under Accessibility object for `/apps` API.  
- **Is this PR related to a Monolith release?** Yes, 2022.10.2. backend change ticket is merged in https://oktainc.atlassian.net/browse/OKTA-540515. 
- Before 
- After
* [OKTA-540517](https://oktainc.atlassian.net/browse/OKTA-540517)
> update doc that loginRedirectUrl is deprecated in Identity Engine

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/import-hook/index.md
- packages/@okta/vuepress-site/docs/reference/password-hook/index.md
- packages/@okta/vuepress-site/docs/reference/registration-hook/index.md
- packages/@okta/vuepress-site/docs/reference/saml-hook/index.md
- packages/@okta/vuepress-site/docs/reference/telephony-hook/index.md
- packages/@okta/vuepress-site/docs/reference/token-hook/index.md
- packages/@okta/vuepress-theme-prose/global-components/HookResponseSize.vue
- **What's changed?** Added the release note on Hook response size from [PR# 3175](https://github.com/okta/okta-developer-docs/pull/3715) as a Global component and used that tag for all Hook API references.
*n/a
> Add Hook response size as global component

- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- **What's changed?** Add missing UserOnDemandPeriod parameter in ASA Projects
https://6359a86c99c4633f5450a250--reverent-murdock-829d24.netlify.app/docs/reference/api/asa/projects/
* [OKTA-532542](https://oktainc.atlassian.net/browse/OKTA-532542)
> OKTA-532542 Add missing UserOnDemandPeriod parameter in ASA Projects

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/configcors.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/reqautheverything.md
- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/springboot/reqauthspecific.md
This PR replaces the `WebSecurityConfigurerAdapter` configuration in the docs with one that uses 
the `SecurityFilterChain` bean
The `SecurityFitlterChain` bean introduced in Spring Security 5.4 allows a component-based Security configuration
and is [encouraged to be used](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) instead of the `WebSecurityConfigurerAdapter`.
The configuration is compatible with Spring Boot 2.6 used throughout the docs  and will be needed anyway with the next Spring Boot version since the `WebSecurityConfigurerAdapter` is marked as [deprecated](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.html) in Spring Security …
> Replace WebSecurityConfigurerAdapter configuration with SecurityFilterChain bean

- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Adding a release note for inline hook requests sending expired access tokens
- **Is this PR related to a Monolith release?** 2022.11.1
* [OKTA-551186](https://oktainc.atlassian.net/browse/OKTA-551186)
> OKTA-551186 - Add update to 2022.11.1 release notes

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- added note to call out ability to seamlessly migrate to Okta-managed certs with no downtime by contacting support
- removed section on configuring custom domain with cloudflare - that was a stopgap before we had okta-managed certs and should not be recommended anymore
- no
* https://oktainc.atlassian.net/browse/OKTA-556756
> update for seamless migration & remove cloudflare

- packages/@okta/vuepress-site/docs/guides/social-login/main/index.md
It's an Okta-specific abbreviation, customers are not going to know what it means (I didn't know what it was without a search).
Otherwise, this term should qualified on the page:
> Application Integration Wizard (AIW)
But, IMHO it's more clear if it's removed.
> NOTE: the `/docs/guides/add-an-external-idp/azure/main/` page contains the unqualified term `AIW` too (possibly other pages)
> Remove the term "AIW" in social-login guide

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- Adding suggested information in API doc about data consistency policy and latency parameters with the query and filter string parameters that will be directed to the eventual consistent DB
Resolves: OKTA-555442
* [OKTA-555442](https://oktainc.atlassian.net/browse/OKTA-555442)
> OKTA-555442: Update List Groups API spec content on developer.okta.com

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
- Add WebAuthn's userVerification property to the verify API response in AuthN API
- Not related to a monolith release; this is rectifying a missed doc
* [OKTA-559053](https://oktainc.atlassian.net/browse/OKTA-559053)
> Add userVerification property to WebAuthn AuthN verify API

- packages/@okta/vuepress-site/code/library-versions/index.md
Updates our wording to be 6 months of support after a library is retired
> Change retiring period to 6 months

- .github/workflows/build-and-checks.js.yml
- .github/workflows/netlify-preview.js.yml
- package.json
- Implement netlify-preview action
To toggle the job, comment `/netlify preview`
This only runs when
- Within okta/okta-developer-docs
- If secrets are not available, the job will short-circuit
- Triggers on new PR comments
- Executes if PR comment is "/netlify preview"
* [OKTA-558239](https://oktainc.atlassian.net/browse/OKTA-558239)
> Implement netlify-preview action

- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
- packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md
Fix links to sample code moved from main branch to legacy branch.
**Current preview links**
Last Update: 12/20/22 15:30 GMT
Embedded Okta Sign-In Widget fundamentals:
https://63a1c4e22d0b5d084ce5f39b--reverent-murdock-829d24.netlify.app/docs/guides/archive-embedded-siw/main/#mobile-sdks
Okta Sign-In widget guide:
https://63a1c4e22d0b5d084ce5f39b--reverent-murdock-829d24.netlify.app/code/javascript/okta_sign-in_widget/#mobile-sdks
> OKTA-557217, 219: fix broken links

- packages/@okta/vuepress-site/docs/reference/api/groups/index.md
- **What's changed?** Added the `sortBy` and `sortOrder` parameters to the Groups API; re-purposed same content that was in Users API for these parameters.
- **Is this PR related to a Monolith release?** 2022.12.0
* [OKTA-508755](https://oktainc.atlassian.net/browse/OKTA-508755)
> OKTA-508755 - Groups API - Add search parameters

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/reference/api/hook-keys/index.md
- **What's changed?** The header link, Community > Developer Days, is now out-of-date; removing as per Chelsea. (Also made small syntax update to Key Mgmt API Postman reference.)
* n/a
> Remove Community > Developer Days link

- packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
Resolves: OKTA-540378
- **What's changed?** Adding more regions to AWS regions list for AWS EventBridge Log Streaming
- **Is this PR related to a Monolith release?** Yes (probably 2023.1.0)
* [OKTA-540378](https://oktainc.atlassian.net/browse/OKTA-540378)
> OKTA-540378: Updating AWS Region list for AWS EventBridge

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta/main/index.md
- **What's changed?** Removed manually maintained list of supported OAuth 2.0 scopes and pointed to the automated page in Redocly
* [OKTA-566005](https://oktainc.atlassian.net/browse/OKTA-566005)
> pointing to redocly page that is automated

- packages/@okta/vuepress-site/docs/reference/api/asa/projects/index.md
- packages/@okta/vuepress-site/docs/reference/api/asa/teams/index.md
- **What's changed?** Updated PolicySync references to reflect GA status.
- **Is this PR related to a Monolith release?** 2023.01.0
Alias URL won't be live until next HOC publish cycle. Maybe Jan 16 or 17?
* [OKTA-566414](https://oktainc.atlassian.net/browse/OKTA-566414)
> ASA -  PolicySync Cleanup

- packages/@okta/vuepress-site/docs/guides/oin-oidc-protocols/main/index.md
- **What's changed?** Remove `groups` scope from the optional scopes available for the OIN OIDC protocols guide. Another unsupported scopes note is added in PR3827 (this is a new OIN submission requirements doc with an OIN limitations section, which will list the non-supported scopes).
* [OKTA-538908](https://oktainc.atlassian.net/browse/OKTA-538908)
> OKTA-538908 Remove groups scope from the optional scopes available for OIN OIDC integration

- packages/@okta/vuepress-site/.vuepress/public/sitemap_index.xml
- packages/@okta/vuepress-site/docs/reference/api/brands/index.md
- packages/@okta/vuepress-site/docs/reference/beta-only/index.md
- packages/@okta/vuepress-site/docs/reference/index.md
- **What's changed?** Add links to Redocly for sign-in, sign-out, and error pages. Also adds the Redocly sitemap to Vuepress's sitemap index.
- **Is this PR related to a Monolith release?** Yes, ping @gormanho-okta to see if Redocly changes will go into Jan monthly
* [OKTA-508039](https://oktainc.atlassian.net/browse/OKTA-508039)
> Add links to Redocly for sign-in, sign-out, and error pages.

- packages/@okta/vuepress-site/docs/reference/api/factors/index.md
- **What's changed?** Add Note in Factors API for resend after OTP-based activate factor rate limit exceeded
- **Is this PR related to a Monolith release?** Yes 2023.01.1(vuln-after all prod cells)
* [OKTA-566108](https://oktainc.atlassian.net/browse/OKTA-566108) for corresponding RN item: OKTA-550739
> OKTA-566108 Add rate limit note for resend request in Activate factor section

- packages/@okta/vuepress-site/docs/reference/rl-dashboard/index.md
- **What's changed?** Corrected percentages on warning threshold (from 60 to 90 for workforce; 90 to 60 for CIAM)
* n/a
> Team Scotty: Correct warning threshold percentages on RL Dashboard Guide

- packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
Resolves: OKTA-573094
- **What's changed?** Updating AWS regions list for Log Streaming, removing regions that are currently not supported by Okta account
- **Is this PR related to a Monolith release?** 2023.02.0 Feb Monthly
* [OKTA-573094](https://oktainc.atlassian.net/browse/OKTA-573094)
> OKTA-573094: Removing unsupported regions

- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-providers/index.md
- **What's changed?** Deprecate Risk Providers API page and link to new Okta API reference portal (Redocly).
https://63d2d52034b93b08b9cc23fa--reverent-murdock-829d24.netlify.app/docs/reference/api/risk-providers/
* [OKTA-570767](https://oktainc.atlassian.net/browse/OKTA-570767)
> OKTA-570767 Deprecate Risk Providers API page and link to Redocly

- packages/@okta/vuepress-site/docs/guides/third-party-risk-integration/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/risk-events/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** Comment out Risk Events API page and link to Redocly. Replace internal links to Redocly
https://63f7d977c0063717884ea9a4--reverent-murdock-829d24.netlify.app/docs/reference/api/risk-events/
* [OKTA-580362](https://oktainc.atlassian.net/browse/OKTA-580362)
> OKTA-580362 Deprecate Risk Events API markdown page and link to Redocly

- packages/@okta/vuepress-site/docs/guides/ie-limitations/main/index.md
- **What's changed?** Removes an OIE limitation that was eliminated last year. See [here](https://okta.slack.com/archives/C04MY18LZLP/p1678980539780729).
Specifically, the _Target.ID value simulated for mobile phone event types_ item was changed to match the functionality of Classic.
[Netlify Preview](https://6413496f3c69df202f8d6511--reverent-murdock-829d24.netlify.app/docs/guides/ie-limitations/main/)
* [OKTA-588896](https://oktainc.atlassian.net/browse/OKTA-588896)
> Remove simulated mobile phone Target.ID Limitation for OIE

- packages/@okta/vuepress-site/docs/reference/token-hook/index.md
- **What's changed?**  Make auth_time be a reserved claim both for access token and ID token
-- -- Before 
-- -- After
- **Is this PR related to a Monolith release?**   Monolith-2023.03.2
* [OKTA-589502](https://oktainc.atlassian.net/browse/OKTA-589502)
> Make auth_time be a reserved claim both for access token and ID token

- packages/@okta/vuepress-theme-prose/assets/css/components/_card.scss
- **What's changed?** Cards on the DOC [Concepts](https://developer.okta.com/docs/concepts/) page have a weird spacing issue that causes boxes to appear at different sizes from each other.
This issue doesn't seem to impact cards on other topics within DOC.
- Topics that include the Cards element ([Search](https://github.com/search?q=repo%3Aokta%2Fokta-developer-docs%20%3Ccards%3E&type=code))
- okta-developer-docs/packages/@okta/vuepress-site/code/index.md
- okta-developer-docs/packages/@okta/vuepress-site/docs/concepts/index.md
- okta-developer-docs/packages/@okta/vuepress-site/docs/guides/quickstart/main/index.md
- okta-developer-docs/packages/@okta/vuepress-site/docs/guides/identity-providers/index.md
- okta-developer-docs/packages/@okta/vuepress-site/docs/reference/index.md
- …
> Fix <Card> height issues

- packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/android/sdksteps.md
- packages/@okta/vuepress-site/docs/guides/authenticators-custom-authenticator/main/ios/sdksteps.md
- **What's changed?** Update Access token management section to add "Add Maintenance token configuration and usage" section to custom authenticator guide (for both iOS and Android). Also add Postman collection example.
https://641c9eb002e2a006f325ff99--reverent-murdock-829d24.netlify.app/docs/guides/authenticators-custom-authenticator/android/main/
* [OKTA-591733](https://oktainc.atlassian.net/browse/OKTA-591733)
> OKTA-591733 Add maintenance token usage section to custom authenticator guide

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
Aded two missing navbar links to code/aspnet and code/blazor
* [OKTA-495057](https://oktainc.atlassian.net/browse/OKTA-495057)
> OKTA-495057 Add navbar links to code\aspnet and code\blazor

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Remove SAML config doc example links for Runscope, GitHub, Salesforce,  and Zoom in the OIN submission prerequisite doc
> Remove old SAML config doc example links in OIN submission requirements

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Removes EA tag from "Policy action with dynamic IdP routing" section.
* [OKTA-595677](https://oktainc.atlassian.net/browse/OKTA-595677)
> Remove EA tag from policy API doc

- packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-11-CRUD-Test.json
- packages/@okta/vuepress-site/.vuepress/public/standards/SCIM/SCIMFiles/Okta-SCIM-20-CRUD-Test.json
- **What's changed?** Update Okta-SCIM-11-CRUD-Test.json and Okta-SCIM-20-CRUD-Test.json files to have a stronger password value.
* [OKTA-601611](https://oktainc.atlassian.net/browse/OKTA-601611)
> OKTA-601611 Update Okta-SCIM-11-CRUD-Test.json and Okta-SCIM-20-CRUD-Test.json files

- packages/@okta/vuepress-site/docs/reference/api/devices/index.md
- **What's changed?** Adds an operation to the Device API. See [Issue 3789](https://github.com/okta/okta-developer-docs/issues/3789).
https://643f43f5fd2c2722a35aed44--reverent-murdock-829d24.netlify.app/docs/reference/api/devices/#list-all-users-for-a-device
* [OKTA-567622](https://oktainc.atlassian.net/browse/OKTA-567622)
> Add an operation to Devices API

- packages/@okta/vuepress-site/docs/guides/protect-your-api/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-authjs/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-mobile-app-redirect/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/index.md
- packages/@okta/vuepress-site/docs/guides/sign-into-web-app-redirect/main/index.md
- Added warnings to quickstarts that Okta CLI will not work unless developer edition orgs or orgs with API AM enabled are being used. 
- Also deleted a duplicate stackselector I spotted in a quickstart.
* [OKTA-516673](https://oktainc.atlassian.net/browse/OKTA-516673)
* [OKTA-441211](https://oktainc.atlassian.net/browse/OKTA-441211)
Preview at: https://645119d0e0b9430e3a28a535--reverent-murdock-829d24.netlify.app/docs/guides/sign-into-web-app-redirect/asp-net-core-3/main/
> Okta-516673: Add okta cli advisories

- packages/@okta/vuepress-site/docs/reference/api/log-streaming/index.md
- packages/@okta/vuepress-site/docs/reference/api/schemas/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- **What's changed?** Deprecate Log Streaming API on VuePress site and redirect to Redocly site
* [OKTA-602037](https://oktainc.atlassian.net/browse/OKTA-602037)
> OKTA-602037 Deprecate Log Streaming API on VuePress

- packages/@okta/vuepress-site/docs/reference/api/authenticators-admin/index.md
- **What's changed?** Authenticators Admin API > Create Authenticator endpoint needs to be put back (this was hidden from flare in okta-602753 by mistake and now it will be exposed again)
* [OKTA-604179](https://oktainc.atlassian.net/browse/OKTA-604179)
> OKTA-604179 Put back Create Authenticator from flare

- yarn.lock
- **What's changed?** Upgraded primsjs to v1.29 to support sytax highlighting for gradle code blocks.
* [OKTA-566972](https://oktainc.atlassian.net/browse/OKTA-566972)
> Upgraded prismjs to v1.29.0

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/setup-app.md
- **What's changed?** Add step for selecting application type to Implement the "SAML 2.0 Assertion" grant type. This is a doc gap identified by identity-engine-ciam channel.
https://645e4fc9ee19a40067a1f7b8--reverent-murdock-829d24.netlify.app/docs/guides/implement-grant-type/saml2assert/main/#grant-type-flow
* [OKTA-604559](https://oktainc.atlassian.net/browse/OKTA-604559)
> OKTA-604559 Add application type to SAML 2.0 Assertion grant type

- packages/@okta/vuepress-site/docs/guides/sign-in-to-spa-embedded-widget/main/react/basic-sign-in.md
- **What's changed?** Removed an h4 tag from React version of sign in to SPA embedded widget guide. Addresses concern of PR #3994 which is stuck during standard checks. This PR is already approved by @alisaduncan 
* n/a
> React - Sign in to SPA embedded widget - minor code update (3994)

- packages/@okta/vuepress-site/docs/concepts/user-profiles/index.md
- packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/mappings/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- **What's changed?** As per our ongoing Redocly migration, deprecating the [Mappings API](https://developer.okta.com/docs/reference/api/mappings/) on VuePress to point to the Redocly version: [Profile Mappings](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/ProfileMapping/).
* [OKTA-610870](https://oktainc.atlassian.net/browse/OKTA-610870)
> OKTA-610870 Mappings API deprecation

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
-- Remove the restriction that passing Context object only applies to trusted web applications (Remove the blue parts)
-- Reverse the order for context and options parameters to keep the order consistent (Reverse the red part)
-- No
* [OKTA-615259](https://oktainc.atlassian.net/browse/OKTA-615259)
> Remove the restriction that passing Context object only applies to trusted web applications

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
This reverts commit c4a96fe44070f029cc0b1ba05f755058cdaeeb41.
No
* [OKTA-615259](https://oktainc.atlassian.net/browse/OKTA-615259)
> Revert "Remove the restriction that passing Context object only applies to trusted web applications (#4177)"

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Add Password Policy changes: SSPR authenticators and constraints. This PR needs to be aligned with PR 404 in okta-oas3 repo.
- **Is this PR related to a Monolith release?** TBD (2023.06.0?)
https://643474c17272e412a24cf56d--reverent-murdock-829d24.netlify.app/docs/reference/api/policy/#password-rules-action-data
* [OKTA-596621](https://oktainc.atlassian.net/browse/OKTA-596621)
> OKTA-596621 Add SSPR primary factor and authenticator key constraints to Password Policy

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Changed the syntax for the Application User Profile section to use '$app' rather than '$appuser' in the first row of the table of the AUP section of the doc.
* [OKTA-621761](https://oktainc.atlassian.net/browse/OKTA-621761)
> Updated Application User Profile syntax for OKTA-621761.

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- **What's changed?** As per team, added a note to the Event Hook concept to only contact support for event hook calls delayed over sixty minutes
* [OKTA-620520](https://oktainc.atlassian.net/browse/OKTA-620520)
> OKTA-620520 - Event Hook update on lag

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcode/use-flow.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/authcodepkce/use-flow.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/implicit/use-flow.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/ropassword/use-flow.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/saml2assert/use-flow.md
- packages/@okta/vuepress-site/docs/guides/refresh-tokens/main/index.md
- Updated implement grant type and refresh tokens articles to use CURL calls to org server rather than custom org server.
- NOTE: Will address acrolinx scores in subsequent PR with updated images for IGT articles.
* [OKTA-443965](https://oktainc.atlassian.net/browse/OKTA-443965)
> OKTA-443965 Updated curl calls to use org auth server

- packages/@okta/vuepress-site/docs/reference/api/uischema/index.md
- **What's changed?** Updating VuePress [UI Schema API ](https://developer.okta.com/docs/reference/api/uischema/)reference to point to Redocly version of the [UI Schema API](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/UISchema/). All content from existing VuePress site migrated to Redocly platform.
* [OKTA-610874](https://oktainc.atlassian.net/browse/OKTA-610874)
> OKTA-610874 - Deprecate UI Schema API on VuePress

- packages/@okta/vuepress-plugin-qualtrics-feedback/enhanceAppFile.js
- packages/@okta/vuepress-plugin-qualtrics-feedback/index.js
- packages/@okta/vuepress-plugin-qualtrics-feedback/package.json
- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/package.json
- packages/@okta/vuepress-theme-prose/assets/css/components/_feedback.scss
- packages/@okta/vuepress-theme-prose/assets/css/prose.scss
- packages/@okta/vuepress-theme-prose/components/Feedback.vue
- packages/@okta/vuepress-theme-prose/global-components/EventHookEANote.vue
- packages/@okta/vuepress-theme-prose/global-components/EventHookEANoteProcedure.vue
- packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- tests/cypress/integration/feedback_spec.js
- tests/cypress/page-objects/MainPage.js
- yarn.lock
Refactoring the user feedback widget. Previously the widget auto-loaded the survey on each page load, as a wizard.
Now, the widget provides a link to the survey, which must be clicked in order to launch (no more passive loading).
Deploy preview instance: https://64a6fb36bb735a5c70a3248d--reverent-murdock-829d24.netlify.app/
* [OKTA-616629](https://oktainc.atlassian.net/browse/OKTA-616629)
> Refactor the feedback widget

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- yarn.lock
- **What's changed?** Adds a note about re-enrolling in the WebAuthn authenticator when a new custom domain is configured.
* [OKTA-521214](https://oktainc.atlassian.net/browse/OKTA-521214)
> Custom domain: add a WebAuthn note

- packages/@okta/vuepress-site/docs/reference/api/trusted-origins/index.md
- **What's changed?** Added filter parameters for the **List all Trusted Origins** API call, updated the **List Trusted Origins with a filter** curl example, and fixed double-quotes update from this PR( #[3884](https://github.com/okta/okta-developer-docs/pull/3884))
- **Is this PR related to a Monolith release?** 2023.07.0 (the `status` filter parameter will be fixed by this release; currently returns an error).
* [OKTA-567461](https://oktainc.atlassian.net/browse/OKTA-567461)
> OKTA-567461 - Updates to Trusted Origins API filter parameters and example

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- packages/@okta/vuepress-site/docs/reference/user-query/index.md
- **What's changed?** Explicitly state that the not operator isn't supported for filtering lists.
* [OKTA-622775](https://oktainc.atlassian.net/browse/OKTA-622775)
> Added text to state that the not operator isn't supported.

- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/mfaoob/flow-diagram.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/mfaotp/flow-diagram.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/oob/flow-diagram.md
- packages/@okta/vuepress-site/docs/guides/implement-grant-type/main/otp/flow-diagram.md
- packages/@okta/vuepress-site/docs/guides/oin-lifecycle-mgmt-overview/index.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-overview/main/index.md
- packages/@okta/vuepress-site/docs/guides/submit-app/main/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-center/directory-coexistence/lab-azure-ad/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-center/directory-coexistence/lab-generic-database/index.md
- packages/@okta/vuepress-site/docs/reference/architecture-center/directory-coexistence/lab-ldap-server/index.md
- packages/@okta/vuepress-site/docs/release-notes/index.md
- **What's changed?** We were using div="three-quarters" class in some pages, which is not correct. Turns out that the correct CSS is "three-quarter". However, this produced some huge images that were fuzzy. For these scaled images, "original" place-holder class was used which is just no class at all, with no scaling.
1. https://64b049e3f4c883396931fae1--reverent-murdock-829d24.netlify.app/docs/guides/implement-grant-type/mfaoob/main/#grant-type-flow
2. Preview that uses `three-quarter` for Direct Auth, and `<div>` for no scaling: https://64b6a2366382c60534df6ee2--reverent-murdock-829d24.netlify.app/docs/guides/implement-grant-type/mfaoob/main/#grant-type-flow
* [OKTA-627743](https://oktainc.atlassian.net/browse/OKTA-627743)
> OKTA-627743 Change image div class to appropriate classes

- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- **What's changed?** Updated the Signup page free trial term to 30 days (it incorrectly said it was 22 days) at request from Yon Xiao (PM).
* [OKTA-634186](https://oktainc.atlassian.net/browse/OKTA-634186)
> Update SignUp.vue to correct free trial access length

- packages/@okta/vuepress-site/docs/guides/policy-simulation/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Removed the EA tags from the [Policy API](https://developer.okta.com/docs/reference/api/policy/#policy-simulation-operations) and the [Test your policies with access simulations ](https://developer.okta.com/docs/guides/policy-simulation/main/)guide.
- **Is this PR related to a Monolith release?** 2023.08.0
* [OKTA-593826](https://oktainc.atlassian.net/browse/OKTA-593826)
> OKTA-593826 - Remove EA tags for access policy simulation 

- packages/@okta/vuepress-site/docs/guides/configure-ciba/main/index.md
- packages/@okta/vuepress-site/docs/guides/configure-user-scoped-account-management/main/index.md
- packages/@okta/vuepress-site/docs/guides/pwd-optional-change-email/main/react/allcontent.md
- packages/@okta/vuepress-site/docs/reference/api/archive-myaccount/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount-migration/index.md
- packages/@okta/vuepress-site/docs/reference/api/myaccount/index.md
- packages/@okta/vuepress-site/docs/release-notes/2020/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2022/index.md
- **What's changed?** Deprecates the MyAccount API docs from VuePress. 
* [OKTA-628414](https://oktainc.atlassian.net/browse/OKTA-628414)
> MyAccount API: deprecate the API docs

- packages/@okta/vuepress-site/docs/guides/implement-oauth-for-okta-serviceapp/main/index.md
- **What's changed?** Adds CLIENT_AS_PRINCIPAL content to OAuth for service app guide
- **Is this PR related to a Monolith release?** Nope. Nein.
[OKTA-630490](https://oktainc.atlassian.net/browse/OKTA-630490)
> Add CLIENT_AS_PRINCIPAL instructions to OAuth for Okta service app guide

- packages/@okta/vuepress-theme-prose/global-components/SignUp.vue
- **What's changed?** Update WIC trial URL on Sign Up page per request.
URL changed from `https://www.okta.com/free-trial` to `https://okta.com/free-trial/workforce-identity`
* [OKTA-641496](https://oktainc.atlassian.net/browse/OKTA-641496)
> Update WIC free trial link as requested

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- fix copy paste error in OEL doco
- a user might mistakenly believe that `findWorkdayUser()` returns `"Active Directory assignments"`
- N/A
> fix copy paste error in OEL doco

- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- tests/cypress/integration/api_tags_spec.js
- **What's changed?** Remove Beta flag for authenticator enrollment (OIE) and MFA (Classic) policies. Remove MFA consent object.
* [OKTA-642501](https://oktainc.atlassian.net/browse/OKTA-642501)
* [OKTA-484624](https://oktainc.atlassian.net/browse/OKTA-484624)
> OKTA-642501 Remove Beta flag for authenticator enrollment and MFA policies

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
- **What's changed?** Added 3 additional filter examples using `co` and `ew`; added a note on [core okta api operators table](https://developer.okta.com/docs/reference/core-okta-api/#operators) noting that system log api supports `co` and `ew`.
* [OKTA-638115](https://oktainc.atlassian.net/browse/OKTA-638115)
> OKTA-638115 Small updates to System Log API and core operators table

- packages/@okta/vuepress-site/docs/guides/shared-sso-android-ios/main/ios/enablesso.md
- packages/@okta/vuepress-site/docs/reference/api/policy/index.md
- **What's changed?** Updated the Policy API and one guide with details on the `maxSessionLifetimeMinutes` and `usePersistentCookie` properties being read-only for the default policy's default rule
* [OKTA-642005](https://oktainc.atlassian.net/browse/OKTA-642005)
> OKTA-642005 Global Session Policy default rule properties read-only

- packages/@okta/vuepress-site/docs/release-notes/2023-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2023/index.md
- packages/@okta/vuepress-site/docs/release-notes/index.md
- **What's changed?** Adds a note linking to a qualtrics survey.
- [RN landing page](https://6508bff9ba445e58b03ccbe1--reverent-murdock-829d24.netlify.app/docs/release-notes/)
- [OCE RNs](https://6508bff9ba445e58b03ccbe1--reverent-murdock-829d24.netlify.app/docs/release-notes/2023/)
- [OIE RNs](https://6508bff9ba445e58b03ccbe1--reverent-murdock-829d24.netlify.app/docs/release-notes/2023-okta-identity-engine/)
* [OKTA-644544](https://oktainc.atlassian.net/browse/OKTA-644544)
> Add qualtrics note to RN pages

- packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
https://65036c3b7c682f0983181ffe--reverent-murdock-829d24.netlify.app/docs/guides/terraform-enable-org-access/main/
Updated the explanation of using the OpenSSL command line in Enable Terraform access for your Okta org:
- Added CLI variations (e.g. openssl, openssl-rsa)
- Updated wording to make it clear that the generated key could be in the right format
- Updated wording on deactivating unused public keys EVERYONE -->
No
* [OKTA-640695](https://oktainc.atlassian.net/browse/OKTA-640695)
> Update info for openssl and public keys

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- This PR fixes the incorrect markdown for the attribute table for SAML 2.0 Settings object which rendered gibberish (see before and after screenshots)
> Fix SAML 2.0 Settings object formatting

- packages/@okta/vuepress-theme-prose/components/Hero.vue
- Removed mention of Dev Day from dev.okta hero banner since Dev Day concluded on October 5
* [OKTA-655687](https://oktainc.atlassian.net/browse/OKTA-655687)
> Update Hero.vue to remove mention of Dev Day since Dev Day is now over

- packages/@okta/vuepress-site/docs/reference/api/authn/index.md
Removes the `audience` param from the Authentication API. This was deprecated over two years ago, and now causes issues when included within operations. Our wording for [deprecated](https://developer.okta.com/docs/reference/releases-at-okta/#deprecation) implies it can be included, but shouldn't be. Testing indicates that including this param causes an error.
- General Acrolinx fixes: Getting that score up as high as ppssible.
- **Is this PR related to a Monolith release?** Nope, nuh-uh.
[Link](https://653970340ce2860bea9a2370--reverent-murdock-829d24.netlify.app/docs/reference/api/authn/)
* [OKTA-660403](https://oktainc.atlassian.net/browse/OKTA-660403)
> Authn API - Remove audience param

- packages/@okta/vuepress-site/docs/guides/submit-app-prereq/main/index.md
- **What's changed?** Add condition where refresh tokens aren't supported in the OIN. Currently we have a blanket statement saying integrations in OIN don't support refresh tokens. However, it's been confirmed that we support refresh tokens for the SCIM service use case.
* [OKTA-656373](https://oktainc.atlassian.net/browse/OKTA-656373)
> OKTA-656373 Add specific use case where refresh tokens aren't supported in OIN

- package.json
- yarn.lock
- update for babel package breaks local build. reverting it
* [OKTA-662011](https://oktainc.atlassian.net/browse/OKTA-662011)
> reverts babel package

- packages/@okta/vuepress-theme-prose/components/ContentPage.vue
- postpone anchors initialization till the page is loaded
currently on prod https://developer.okta.com/docs/guides/manage-orgs-okta-aerial
preview with the fix https://654d0df960340f13dbc948f5--reverent-murdock-829d24.netlify.app/docs/guides/manage-orgs-okta-aerial
* [OKTA-665369](https://oktainc.atlassian.net/browse/OKTA-665369)
> Initialize anchors when document is loaded

- packages/@okta/vuepress-theme-prose/assets/css/components/_menuItem.scss
- uses gray chevron for a white theme
preview: https://6555253523fb865ae2e82f61--reverent-murdock-829d24.netlify.app/
* [OKTA-666204](https://oktainc.atlassian.net/browse/OKTA-666204)
> Fixes chevron

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-self-reg/main/index.md
- Fed Broker mode removes the need to assign an app to everyone. Remove the middle part of the config section for self-registration guide to reflect this.
* [OKTA-506751](https://oktainc.atlassian.net/browse/OKTA-506751)
> okta-506751 Update Self-reg config steps for fed broker mode

- packages/@okta/vuepress-site/docs/reference/api/users/index.md
- packages/@okta/vuepress-site/docs/reference/user-query/index.md
- **What's changed?** Add a note that the ne operator isn't supported for Users and explain how to get the same results using a combination of lt, gt, and or operators.
* [OKTA-674903](https://oktainc.atlassian.net/browse/OKTA-674903)
> Note that the ne operator isn't supporter for Users

- packages/@okta/vuepress-theme-prose/enhanceApp.js
- Redirection for signup page happens in Amazon configuration, when the page is loaded it already has query parameters dropped from URL
* [OKTA-671204](https://oktainc.atlassian.net/browse/OKTA-671204)
> Reverting url fix

- packages/@okta/vuepress-site/docs/reference/core-okta-api/index.md
- **What's changed?** Removing reference to user-agent guide, which is now broken: https://developer.chrome.com/multidevice/user-agent on this Core Okta API page: https://developer.okta.com/docs/reference/core-okta-api/
* n/a
> Fix broken link

- packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_search.scss
- **What's changed?** This fixes checkbox color in dark theme
* [OKTA-484263](https://oktainc.atlassian.net/browse/OKTA-484263)
After fix:
> [OKTA-484263]: Fixed checkbox color in dark theme

- packages/@okta/vuepress-site/docs/reference/api/idps/index.md
- **What's changed?** added content on requiring pkce for idp
Netlify Links:
https://6580cfa5201fdd2f4268283f--reverent-murdock-829d24.netlify.app/docs/reference/api/idps/#oauth-2-0-and-openid-connect-credentials-object
https://6580cfa5201fdd2f4268283f--reverent-murdock-829d24.netlify.app/docs/reference/api/idps/#request-example
* [OKTA-678231](https://oktainc.atlassian.net/browse/OKTA-678231)
> pkce parameter

- packages/@okta/vuepress-site/docs/guides/terraform-enable-org-access/main/index.md
Jan 3, 2024 @ 3:00 EDT
https://6595bc18a5d8a20d8397ed9f--reverent-murdock-829d24.netlify.app/docs/guides/terraform-enable-org-access/main/#assign-admin-roles
Added a section on adding admin roles to the service app used by Terraform.
* [OKTA-654929](https://oktainc.atlassian.net/browse/OKTA-654929)
> Add section on securing service app with an admin role

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Updates the ToC to use relative links to Redocly. This uses relative links, so the URLs will not generate correctly on local or preview builds.
[Preview](https://65a583aacaa093242c8d5fe8--reverent-murdock-829d24.netlify.app)
* [OKTA-680608](https://oktainc.atlassian.net/browse/OKTA-680608)
> Add OPA Links to ToC

- packages/@okta/vuepress-site/docs/reference/okta-expression-language/index.md
- **What's changed?** Updated description of hasDirectoryUser() to state it returns true only when a single AD match is found; false, otherwise.
* [OKTA-633731](https://oktainc.atlassian.net/browse/OKTA-633731)
> Update hasDirectoryUser() description

- packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
- **What's changed?** Update SCIM 2.0 and 1.1: Determine if User already exists section
https://65aafac20c7751212b244e94--reverent-murdock-829d24.netlify.app/docs/reference/scim/scim-20/#determine-if-the-user-already-exists
* [OKTA-676273](https://oktainc.atlassian.net/browse/OKTA-676273)
> OKTA-676273 Update SCIM - determine if User already exists section

- packages/@okta/vuepress-theme-prose/assets/css/components/_sidebar.scss
- packages/@okta/vuepress-theme-prose/components/SidebarItem.vue
- **What's changed?**  Added sidenav border/bar to active items and its ancestors on click of the sidenav item.
* [OKTA-681884](https://oktainc.atlassian.net/browse/OKTA-681884)
> OKTA-681884: Added sidenav border to active items and its ancestors

- packages/@okta/vuepress-site/docs/reference/postman-collections/index.md
- packages/@okta/vuepress-site/docs/reference/rest/index.md
- **What's changed?** Add grant_type param for Postman OAuth instructions. Fixed broken link in Postman Collection list.
> Add grant_type param for Postman OAuth instructions

- packages/@okta/vuepress-site/docs/guides/secure-oauth-between-orgs/main/index.md
- packages/@okta/vuepress-site/docs/reference/rest/index.md
- **What's changed?** Remove SS EA note for CLIENT_AS_PRINCIPAL and update org setting note in OAuth org2org and Postman instruction topics.
- **Is this PR related to a Monolith release?** 2024.02.0 (missed)
https://65cd38b8555a083099a577f8--reverent-murdock-829d24.netlify.app/docs/guides/secure-oauth-between-orgs/main/#assign-admin-roles-to-the-oauth-2-0-service-app
https://65cd38b8555a083099a577f8--reverent-murdock-829d24.netlify.app/docs/reference/rest/#create-a-service-app-in-okta
* [OKTA-696671](https://oktainc.atlassian.net/browse/OKTA-696671)
> OKTA-696671 Update CLIENT_AS_PRINCIPAL note for org2org and Postman instructions

- packages/@okta/vuepress-theme-prose/assets/css/components/_headerNav.scss
- packages/@okta/vuepress-theme-prose/components/MobileOnThisPage.vue
- packages/@okta/vuepress-theme-prose/components/OnThisPage.vue
- packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- packages/@okta/vuepress-theme-prose/mixins/AnchorHistory.vue
1. Make one fixed header
2. "On this page" navigation should match anchors. When we scroll up on the page - active item on the right side should change to one that above the current one.
* [OKTA-699116](https://oktainc.atlassian.net/browse/OKTA-699116)
https://65de070744b78100801e7bf1--reverent-murdock-829d24.netlify.app/
1. 
2. 
https://github.com/okta/okta-developer-docs/assets/158277016/568d78db-ae75-4f2d-b478-ce8810b74afe
> [OKTA-699116] : One fixed header

- packages/@okta/vuepress-site/docs/concepts/auth-servers/index.md
- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/index.md
- **What's changed?** OAUTH2_USE_EXTERNAL_KEY_FOR_ORG_AS_ACCESS_TOKEN updates in AS concept, and Validate token guide.
- **Is this PR related to a Monolith release?** Yes, 2024.03.0
* [OKTA-694170](https://oktainc.atlassian.net/browse/OKTA-694170)
> OKTA-694170 OAUTH2-use-external-key-for-org-as-access-token

- packages/@okta/vuepress-site/docs/reference/api/apps/index.md
- **What's changed?**  Apps API: PUT /apps operation. Some of the fields are immutable in the request body, and any new value passed to that field will be ignored while updating the AppInstance. API doc should mention that these fields are immutable and any changes will be ignored. 
https://65ef58af4c20d302e83de2c9--reverent-murdock-829d24.netlify.app/docs/reference/api/apps/#update-application
* [OKTA-703301](https://oktainc.atlassian.net/browse/OKTA-703301)
> OKTA-703301 - Apps API update: add note for PUT /apps

- packages/@okta/vuepress-site/docs/concepts/multi-tenancy/index.md
Remove DAC project references from the multi-tenant solutions document
Remove DAC project references from the multi-tenant solutions document
* [OKTA-703363](https://oktainc.atlassian.net/browse/OKTA-703363)
> Remove DAC project references from the multi-tenant solutions document

- packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
- **What's changed?** Documents the workaround for the `afterRender` revert when used with SIW Gen3.
* [OKTA-686866](https://oktainc.atlassian.net/browse/OKTA-686866)
> SIW Gen3 - Document afterRender revert

- packages/@okta/vuepress-site/docs/reference/api/system-log/index.md
- **What's changed?** Adding the `changeDetails` property to the [System Log API](https://developer.okta.com/docs/reference/api/system-log/#target-object) reference.
- **Is this PR related to a Monolith release?** Yes, 2025.05.0
* [OKTA-716079](https://oktainc.atlassian.net/browse/OKTA-716079)
> OKTA-716079 - Add new target property to System Log API

- packages/@okta/vuepress-site/docs/guides/oin-universal-logout-overview/index.md
since it's not the same as the `private_key_jwt` previously linked to
> document the Universal Logout JWT

- .circleci/config.yml
- **What's changed?** This PR contains changes to send notification email to slack channel #test-circleci-notif (temporary) when the nightly job catches any broken urls in dev docs.
* [OKTA-726318](https://oktainc.atlassian.net/browse/OKTA-726318)
> OKTA-726318 - Added step to send failure email on nightly job failure

- .circleci/config.yml
- scripts/update-dev-docs-pr-cci.sh
- **What's changed?** Adds a PR comment from gh okta bot containing netlify preview URL of the changes whenever anyone triggers netlify manual job on circleci on the topic branch.
* [OKTA-726234](https://oktainc.atlassian.net/browse/OKTA-726234)
> [OKTA-726234]: Add preview link to PRs on netlify manual build

- packages/@okta/vuepress-site/docs/reference/scim/scim-11/index.md
- packages/@okta/vuepress-site/docs/reference/scim/scim-20/index.md
- **What's changed?**  SCIM reference: Add when Okta calls the GET /Groups with filtering request
https://preview-4854--reverent-murdock-829d24.netlify.app/docs/reference/scim/scim-20/#retrieve-groups
* [OKTA-520454](https://oktainc.atlassian.net/browse/OKTA-520454)
> OKTA-520454 SCIM reference update for the GET /Groups with filtering request

- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- **What's changed?** Updating number of inline hooks available per org from 50 to 100
- **Is this PR related to a Monolith release?** `2024.06.0`
* [OKTA-731717](https://oktainc.atlassian.net/browse/OKTA-731717)
> OKTA-731717 - Update number of inline hooks

- packages/@okta/vuepress-site/docs/reference/api/itp-et/index.md
- **What's changed?** Adding new event type to ITP enhanced table
- **Is this PR related to a Monolith release?**TBD
* [OKTA-727230](https://oktainc.atlassian.net/browse/OKTA-727230)
> OKTA-727230 Add new event type

- packages/@okta/vuepress-site/docs/guides/custom-email/main/index.md
- **What's changed?** Okta uses Velocity Templating Language (VTL) for email customization. VTL uses the `$` placeholder. Need to revert the changes.
> Fix-It Days: Placeholder revert on Velocity Templating Language

- packages/@okta/vuepress-theme-prose/mixins/SidebarItems.vue
- **What's changed?**  Logic for finding the active sidebar item
* [OKTA-532916](https://oktainc.atlassian.net/browse/OKTA-532916)
> OKTA-532916 | Search result links with stack selector doesn't work with left-nav

- packages/@okta/vuepress-site/docs/concepts/event-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/hooks-best-practices/index.md
- **What's changed?** Updating number of event hooks available per org from 10 to 25 on the [Event hooks](https://developer.okta.com/docs/concepts/event-hooks/) concept and [Best practices guide](https://developer.okta.com/docs/reference/hooks-best-practices/). 
- **Is this PR related to a Monolith release?** `2024.07.0`
* [OKTA-741766](https://oktainc.atlassian.net/browse/OKTA-741766)
> OKTA-745788 - Event Hook org limit update

- .circleci/config.yml
Looking at the resource usage for the build checks job, the CPU seems like it could be tuned down, and while RAM does at one point spike between 1/3 to just below 1/2 usage of 16 GB on XLarge, the job itself seems to set a Node limit of roughly 4GB, far below the 8GB which is on a Large resource class. So thought it would be wise to try to see if we can tune this down for improved resource usage.
Same seems to apply to nightly, so made that change too.
Sample run from a recent mainline build:
https://app.circleci.com/pipelines/github/okta/okta-developer-docs/3586/workflows/23e11945-8f10-4cb5-bb2b-cc49f254eb81/jobs/7256/steps
* n/a
> chore(ci): Reduce resource class size of two pipeline jobs

- packages/@okta/vuepress-theme-prose/assets/css/components/_search.scss
- **What's changed?**  CSS to fix text being cut off
* [OKTA-745531](https://oktainc.atlassian.net/browse/OKTA-745531)
> OKTA-745531 | Filter text are clipped off

- .circleci/config.yml
- package.json
- yarn.lock
This PR provides a number of enhancements to the CI/CD pipeline in the repo.
* Implement Yarn dependency caching.
* Currently, each Yarn install step seems to take roughly 35 seconds.
* By caching the dependencies into CircleCI, and restoring them, the restore + install collecitvely seems to take on average 21 seconds. 
* This is *unscientifically* a 40% reduction in that step. 😉
* Practically, it just shaves a little over 10 seconds of a job which takes ~10 minutes.
* Use CircleCI Test features.
*  The Cypress reporter for JUnit was added, as well as the pipeline collecting those values.
* CircleCI will now be able to calculate test metrics, and more easily raise their values/results into the UI.
* Overtime, this'll allow the project to make use of features like automated flaky test …
> chore(ci): Yarn caching enhancements and pipeline tweaks

- packages/@okta/vuepress-theme-prose/assets/css/abstracts/_colors.scss
- packages/@okta/vuepress-theme-prose/assets/css/components/_content.scss
- **What's changed?** Did a workaround to hide extra underline in external links. This is a bug on vuepress side as evident on their docs as well. Since we enter content in md and that gets converted into html by vuepress automatically, there is no way for us to directly change the html of the external link icon on our website to remove the extra underline. Hence, a workaround is needed to fix this.
* [OKTA-744028](https://oktainc.atlassian.net/browse/OKTA-744028)
> OKTA-744028: Removed extra underline from external links

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Okta now supports TLS certs and keys of 2048, 3072, and 4096 bits
- **Is this PR related to a Monolith release?** Yes. 2024.08.0
* [OKTA-746721](https://oktainc.atlassian.net/browse/OKTA-746721)
> Custom domains: update TLS cert and key info

- packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?** Added timed top banner for okta developer day
* [OKTA-793877](https://oktainc.atlassian.net/browse/OKTA-793877)
> Added Okta Developer Day event timed banner

- packages/@okta/vuepress-theme-prose/assets/css/components/_hero.scss
- packages/@okta/vuepress-theme-prose/components/Hero.vue
- packages/@okta/vuepress-theme-prose/layouts/Layout.vue
- **What's changed?** Hero banner is not appearing on production due to some v-if issue. This issue is not happening on local or on preview build - https://preview-5047--reverent-murdock-829d24.netlify.app/.
* [OKTA-793877](https://oktainc.atlassian.net/browse/OKTA-793877)
> [OKTA-793877]: Fixed hero banner

- packages/@okta/vuepress-site/code/library-versions/index.md
- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/concepts/okta-organizations/index.md
- packages/@okta/vuepress-site/docs/reference/releases-at-okta/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- packages/@okta/vuepress-theme-prose/global-components/ApiLifecycle.vue
- **What's changed?** Deprecating the [Release lifecycles page](https://developer.okta.com/docs/reference/releases-at-okta/) on dev.okta.com. The old page now redirects to the new site and all links are updated to point to the page on the new site.
* [OKTA-743108](https://oktainc.atlassian.net/browse/OKTA-743108)
> OKTA-743108 Deprecate Release lifecycle page

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/guides/event-hook-hookdeck/main/index.md
- packages/@okta/vuepress-site/docs/guides/event-hook-implementation/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/event-hooks/index.md
- packages/@okta/vuepress-site/docs/release-notes/2019/index.md
- packages/@okta/vuepress-site/docs/release-notes/2021/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Deprecated the [Event Hooks Mgmt API](https://developer.okta.com/docs/reference/api/event-hooks/) to point to the [OAS3 version](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/EventHook/#tag/EventHook).
* [OKTA-727513](https://oktainc.atlassian.net/browse/OKTA-727513)
> OKTA-727513 - Deprecate Event Hooks Mgmt API on VuePress

- packages/@okta/vuepress-site/conductor.yml
- packages/@okta/vuepress-site/docs/concepts/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/guides/archive-registration-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/migrate-to-okta-password-hooks/main/index.md
- packages/@okta/vuepress-site/docs/guides/password-import-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/guides/registration-inline-hook/main/nodejs/apisetup.md
- packages/@okta/vuepress-site/docs/guides/telephony-inline-hook/main/index.md
- packages/@okta/vuepress-site/docs/reference/api/hook-keys/index.md
- packages/@okta/vuepress-site/docs/reference/api/inline-hooks/index.md
- packages/@okta/vuepress-site/docs/reference/import-hook/index.md
- packages/@okta/vuepress-site/docs/reference/password-hook/index.md
- packages/@okta/vuepress-site/docs/release-notes/2019/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Deprecating the existing [Inline Hooks Management API](https://developer.okta.com/docs/reference/api/inline-hooks/) on VuePress to now point to the latest version on [OAS3](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/InlineHook/).
* [OKTA-806715](https://oktainc.atlassian.net/browse/OKTA-806715)
> OKTA-806715 - Deprecate Inline Hooks Mgmt API on vuepress

- packages/@okta/vuepress-site/code/angular/okta_angular_sign-in_widget/index.md
- packages/@okta/vuepress-site/code/javascript/okta_sign-in_widget/index.md
- packages/@okta/vuepress-site/docs/guides/archive-embedded-siw/main/index.md
- packages/@okta/vuepress-site/docs/guides/embedded-siw/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/aspnet/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/go/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/java/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-common-download-setup-app/main/nodejs/widgetforyourapp.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/aspnet/siw.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/main/nodeexpress/siw.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/aspnet/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/go/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/java/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-widget-use-case-load/main/nodejs/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-upgrade-sign-in-widget/main/index.md
- **What's changed?** Added a variable which fetches the latest version of the Sign-in Widget. Added to places in docs which explicitly mention the latest version. 
* [OKTA-476264](https://oktainc.atlassian.net/browse/OKTA-476264)
> OKTA-476264 Adding SIW variable

- packages/@okta/vuepress-theme-prose/util/coveo/endpoint.js
- catches error in token processing
I've copied broken_coveo token to a preview site, after refreshing the page script handled error and reset token to a valid value
* [OKTA-820519](https://oktainc.atlassian.net/browse/OKTA-820519)
> Catches errors

- packages/@okta/vuepress-site/docs/guides/session-cookie/main/index.md
- **What's changed?** Changed the `id_token` response parameter from a query to a fragment
* [OKTA-405221](https://oktainc.atlassian.net/browse/OKTA-405221)
> OKTA-405221 Fixed incorrect parameter in response sample

- packages/@okta/vuepress-site/.vuepress/config.js
- packages/@okta/vuepress-site/docs/concepts/index.md
- **What's changed?**  We currently set the canonical URL for every page in `.vuepress/config.js`. However, Vuepress also allows setting the canonical URL directly within each page's frontmatter block. Since the canonical URL can be managed at the page level, it's redundant to override it globally in config.js. This change updates the global override in config.js.
* [OKTA-821460](https://oktainc.atlassian.net/browse/OKTA-821460)
> OKTA-821460 | Improvement for canonical urls

- packages/@okta/vuepress-theme-prose/assets/css/components/_button.scss
- packages/@okta/vuepress-theme-prose/assets/css/themes/dark/_button.scss
- **What's changed?**  Override span's css to fix text clipping
* [OKTA-794747](https://oktainc.atlassian.net/browse/OKTA-794747)
> OKTA-794747 | CSS issue on Dev Docs

- .circleci/config.yml
- package.json
- yarn.lock
- **What's changed?**  Fixed fsevents vulnerability, upgraded fsevents package to 2.3.3
* [OKTA-824463](https://oktainc.atlassian.net/browse/OKTA-824463)
> OKTA-824463: Fixed fsevents vulnerability  

- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/aspnet/pwdoptionalusecase.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/go/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/index.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/ios/integrationsteps.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/java/pwdoptionalusecase.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/getuserprofile.md
- packages/@okta/vuepress-site/docs/guides/oie-embedded-sdk-use-case-basic-sign-in/main/nodejs/pwdoptionalusecase.md
- **What's changed?** Fixed an issue with a note where two notes were nested together
* [OKTA-837437](https://oktainc.atlassian.net/browse/OKTA-837437)
> OKTA-837437 Fix formatting issue with notes

- falsepos.txt
- **What's changed?** Added back the URL: `https://www.w3.org/Security/wiki/Same_Origin_Policy/`, which is incorrectly flagged by the broken link checker script.
* n/a
> Add back a URL mistakenly removed from falsepos.txt file

- packages/@okta/vuepress-site/docs/concepts/policies/index.md
- **What's changed?** Adds device assurance policies to the policies concept doc.
* [OKTA-843906](https://oktainc.atlassian.net/browse/OKTA-843906)
> Device assurance policy: update policies concept doc

- packages/@okta/vuepress-site/docs/guides/client-secret-rotation-key/main/index.md
- **What's changed?** Removed extraneous backslash from request path
See: https://developer.okta.com/docs/guides/client-secret-rotation-key/main/ , third bullet of What you need
As per: https://github.com/okta/okta-developer-docs/pull/5270
* https://github.com/okta/okta-developer-docs/pull/5270
> Client secret rotation and key mgmt - typo fix

- packages/@okta/vuepress-site/docs/guides/custom-widget-gen3/main/index.md
- **What's changed?** As per @askouras and [PR#5282](https://github.com/okta/okta-developer-docs/pull/5282/files), updates to [Style the Sign-In Widget (third generation) guide](https://developer.okta.com/docs/guides/custom-widget-gen3/main/).
Corrected code sample for MutationObserver method to replace references to the non-existent 'context' with the existing 'ctx'
* n/a
> Update Style the Sign-In Widget (third generation) Guide

- packages/@okta/vuepress-site/docs/guides/device-assurance-policies/index.md
- packages/@okta/vuepress-site/docs/guides/device-assurance-policies/main/index.md
- packages/@okta/vuepress-site/docs/guides/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adds a device assurance policies API guide
* [OKTA-825476](https://oktainc.atlassian.net/browse/OKTA-825476)
> Device assurance policies guide

- packages/@okta/vuepress-site/docs/guides/build-sso-integration/main/saml2/prep.md
- **What's changed?** Updated groups claim information for SAML
- **Is this PR related to a Monolith release?** Yes 2025.02.0
Netlify link: https://preview-5299--reverent-murdock-829d24.netlify.app/docs/guides/build-sso-integration/saml2/main/#gather-saml-attributes
* [OKTA-793467](https://oktainc.atlassian.net/browse/OKTA-793467)
> Groups claim update for SAML

- packages/@okta/vuepress-site/docs/release-notes/2025-okta-identity-engine/index.md
- packages/@okta/vuepress-site/docs/release-notes/2025/index.md
- **What's changed?** Removing the Risk Event and Providers deprecation notice in OIE and Classic RNs.
- **Is this PR related to a Monolith release?** `2025.02.0`
* [OKTA-866047](https://oktainc.atlassian.net/browse/OKTA-866047)
> OKTA-866047 - Doc action RN removal

- packages/@okta/vuepress-site/docs/guides/social-login/main/google/appatidp.md
- **What's changed?** Update deprecated Google documentation link in the Social Login page based on customer feedback.
* [OKTA-636257](https://oktainc.atlassian.net/browse/OKTA-636257)
> OKTA-636257 - Update deprecated Google documentation link in the Social Login page

- packages/@okta/vuepress-site/docs/guides/custom-url-domain/main/index.md
- **What's changed?** Removes some mentions of SPF in the custom email domain guide. Adds link to use your own email provider doc.
* [OKTA-869591](https://oktainc.atlassian.net/browse/OKTA-869591)
> Custom email domain guide: remove SPF mentions

- packages/@okta/vuepress-site/docs/guides/configure-signon-policy/main/index.md
- **What's changed?** Update the Policies API to remove the note that says the Maximum Okta global session lifetime of the default global session policy rule is read-only.
- **Is this PR related to a Monolith release?** Yes, 2025.03.0
* [OKTA-882801](https://oktainc.atlassian.net/browse/OKTA-882801)
> Remove note about GSP default rule

- packages/@okta/vuepress-site/docs/concepts/policies/index.md
- packages/@okta/vuepress-site/docs/guides/okta-account-management-policy/main/index.md
- yarn.lock
- **What's changed?** Removes mentions of device probing from OAMP doc
* [OKTA-825647](https://oktainc.atlassian.net/browse/OKTA-825647)
> OAMP - remove device probe mentions

- packages/@okta/vuepress-site/docs/guides/scim-with-entitlements/main/index.md
- **What's changed?** Remove the reference to Okta Developer Edition org as Entitlements are associated with Okta Identity Governance which cannot be enabled in a dev org. Updated based on the Support ticket. 
* [OKTA-921857](https://oktainc.atlassian.net/browse/OKTA-921857)
> OKTA-921857| Updated based on Support ticket - Remove dev org reference

- packages/@okta/vuepress-site/docs/reference/org-defaults/index.md
- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- **What's changed?** Adding reference documentation for new org type
* [OKTA-912701](https://oktainc.atlassian.net/browse/OKTA-912701)
> OKTA-912701 - Add reference doc for org configs

- packages/@okta/vuepress-site/docs/guides/sign-into-spa-redirect/main/angular/loginredirect.md
- **What's changed?** Link to RxJS Observable is down; updated to https://rxjs-dev.firebaseapp.com/guide/observable in this guide: https://developer.okta.com/docs/guides/sign-into-spa-redirect/angular/main/#redirect-to-the-sign-in-page
* [OKTA-940225](https://oktainc.atlassian.net/browse/OKTA-940225)
> OKTA-940225 - Update broken link

- packages/@okta/vuepress-site/docs/guides/validate-access-tokens/main/java/accesstoken.md
- **What's changed?** Adds a note describing how best to use the Okta JWT Verifier for Java library.
* [OKTA-694703](https://oktainc.atlassian.net/browse/OKTA-694703)
> Validate access tokens (Java): add note about verifier limitations

- packages/@okta/vuepress-site/.vuepress/scripts/build-guides-info.js
- packages/@okta/vuepress-theme-prose/util/contentBuilder.js
- making all framework names lower case, so that they are alphabetically ignoring capital non capital characters.
broken:
- https://developer.okta.com/docs/guides/create-an-app-integration/SCIM/main/
- https://developer.okta.com/docs/guides/enable-express-configuration/SCIM/main/
fixed:
- Netlify link does not work because it is transforms url to lowercaes
- Staging link does not work because of the issue on artifactor
- adding screens from local preview
* [OKTA-1011046](https://oktainc.atlassian.net/browse/OKTA-1011046)
> makes all names lowercase

- packages/@okta/vuepress-theme-prose/const/navbar.const.js
- packages/@okta/vuepress-theme-prose/util/contentBuilder.js
- fixing breadcrumbs by correcting topic path in navbar constants
- fixing default framework.
- Needed to lower case SCIM to correctly find it in frameworks map.
- Simply taking first framework from alphabetically sorted list. I'm not sure why `.reduce` call was needed there.
* [OKTA-1011936](https://oktainc.atlassian.net/browse/OKTA-1011936)
> Fixes framework
